<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Week 7 Disease Mapping III | EPI 563: Spatial Epidemiology, Fall 2021</title>
<meta name="author" content="Michael Kramer">
<meta name="description" content="7.1 Getting Ready  7.1.1 Learning objectives  TABLE 2.1: Learning objectives by weekly module After this module you should be able to…Discuss the meaning and interpretation of basic functions of...">
<meta name="generator" content="bookdown 0.23 with bs4_book()">
<meta property="og:title" content="Week 7 Disease Mapping III | EPI 563: Spatial Epidemiology, Fall 2021">
<meta property="og:type" content="book">
<meta property="og:description" content="7.1 Getting Ready  7.1.1 Learning objectives  TABLE 2.1: Learning objectives by weekly module After this module you should be able to…Discuss the meaning and interpretation of basic functions of...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Week 7 Disease Mapping III | EPI 563: Spatial Epidemiology, Fall 2021">
<meta name="twitter:description" content="7.1 Getting Ready  7.1.1 Learning objectives  TABLE 2.1: Learning objectives by weekly module After this module you should be able to…Discuss the meaning and interpretation of basic functions of...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.10/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EPI 563: Spatial Epidemiology, Fall 2021</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">How to use this eBook</a></li>
<li><a class="" href="download-ebook.html"><span class="header-section-number">1</span> Download eBook</a></li>
<li class="book-part">Getting ready…</li>
<li><a class="" href="software-installation.html">Software installation</a></li>
<li><a class="" href="installing-packages-for-this-course.html">Installing packages for this course</a></li>
<li class="book-part">Weekly Modules</li>
<li><a class="" href="locating-spatial-epidemiology.html"><span class="header-section-number">2</span> Locating Spatial Epidemiology</a></li>
<li><a class="" href="cartography-for-epidemiology-i.html"><span class="header-section-number">3</span> Cartography for Epidemiology I</a></li>
<li><a class="" href="cartography-for-epidemiology-ii.html"><span class="header-section-number">4</span> Cartography for Epidemiology II</a></li>
<li><a class="" href="disease-mapping-i.html"><span class="header-section-number">5</span> Disease Mapping I</a></li>
<li><a class="" href="disease-mapping-ii.html"><span class="header-section-number">6</span> Disease Mapping II</a></li>
<li><a class="active" href="disease-mapping-iii.html"><span class="header-section-number">7</span> Disease Mapping III</a></li>
<li><a class="" href="disease-mapping-iv.html"><span class="header-section-number">8</span> Disease Mapping IV</a></li>
<li><a class="" href="spatial-structure-and-clustering-i.html"><span class="header-section-number">9</span> Spatial Structure and Clustering I</a></li>
<li><a class="" href="spatial-structure-and-clustering-ii.html"><span class="header-section-number">10</span> Spatial Structure and Clustering II</a></li>
<li><a class="" href="spatreg1.html"><span class="header-section-number">11</span> Spatial Regression I</a></li>
<li><a class="" href="spatial-regression-ii.html"><span class="header-section-number">12</span> Spatial Regression II</a></li>
<li><a class="" href="spatial-regression-iii.html"><span class="header-section-number">13</span> Spatial Regression III</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="reproducibility-and-projects-in-r.html"><span class="header-section-number">14</span> Reproducibility and Projects in R</a></li>
<li><a class="" href="introduction-to-r-notebooks.html"><span class="header-section-number">15</span> Introduction to R Notebooks</a></li>
<li><a class="" href="formatting-markdown-and-notebooks.html"><span class="header-section-number">16</span> Formatting Markdown and Notebooks</a></li>
<li><a class="" href="sf-overview.html"><span class="header-section-number">17</span> Tips for working with sf data class</a></li>
<li><a class="" href="dplyr.html"><span class="header-section-number">18</span> Tips for using dplyr</a></li>
<li><a class="" href="intro-tmap.html"><span class="header-section-number">19</span> Tips for using tmap</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/mkram01/EPI563-SpatialEPI">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="disease-mapping-iii" class="section level1" number="7">
<h1>
<span class="header-section-number">Week 7</span> Disease Mapping III<a class="anchor" aria-label="anchor" href="#disease-mapping-iii"><i class="fas fa-link"></i></a>
</h1>
<div id="getting-ready-4" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> Getting Ready<a class="anchor" aria-label="anchor" href="#getting-ready-4"><i class="fas fa-link"></i></a>
</h2>
<div id="learning-objectives-5" class="section level3" number="7.1.1">
<h3>
<span class="header-section-number">7.1.1</span> Learning objectives<a class="anchor" aria-label="anchor" href="#learning-objectives-5"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 100%; margin-left: auto; margin-right: auto;  " id="learning-ob">
<caption style="caption-side: top; text-align: center;">
<span id="tab:learning-ob">TABLE 2.1: </span> Learning objectives by weekly module</caption>
<col>
<tr><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(204, 204, 204); font-weight: bold;">After this module you should be able to…</th></tr>
<tr><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Discuss the meaning and interpretation of basic functions of spatial point processes including intensity, stationarity, heterogeneity</td></tr>
<tr><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(230, 230, 230); font-weight: normal;">Produce spatially smoothed estimates of epidemiologic parameters using kernel density estimators for point and polygon data</td></tr>
</table></div>
</div>
<div id="additional-resources-5" class="section level3" number="7.1.2">
<h3>
<span class="header-section-number">7.1.2</span> Additional Resources<a class="anchor" aria-label="anchor" href="#additional-resources-5"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li><a href="https://training.fws.gov/courses/references/tutorials/geospatial/CSP7304/documents/PointPatterTutorial.pdf">Adrian Baddeley tutorial on analysis spatial point processes</a></li>
<li>Hazelton. Kernel Smoothing Methods. Chapter 10, Handbook of Spatial Epidemiology. <em>Posted on Canvas</em>
</li>
</ul>
</div>
<div id="important-vocabulary-5" class="section level3" number="7.1.3">
<h3>
<span class="header-section-number">7.1.3</span> Important Vocabulary<a class="anchor" aria-label="anchor" href="#important-vocabulary-5"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-2">
<caption style="caption-side: top; text-align: center;">
<span id="tab:unnamed-chunk-2">TABLE 2.2: </span> Vocabulary for Week 6</caption>
<col>
<col>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Term</span></th>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Definition</span></th>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Bandwidth</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A measure of the width or spatial extent of a two-dimensional kernel density estimator. The bandwidth is the key to controlling how much smoothing occurs, with larger bandwidths producing more smooth surfaces, and smaller bandwidths producing less smooth surfaces</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Bandwidth, adaptive</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">An adaptive bandwith means the width or search radius of the spatial kernel density estimator varies or adapts through space, usually to maintain a constant number of points within the window. The result is that in areas with few points there is more smoothing, whereas in areas with many points there is more granularity</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Bandwidth, fixed</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A fixed bandwidth means the width or search radius of the spatial kernel density estimator is constant (fixed) for the full study region</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Geographic-weighting</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">A method for calculating summary weighted statistics by relying on a kernel density estimator to describe the weights in local summaries.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Homogenous Poisson Point Process</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A spatial statistical assumption that the count of events in an arbitrarily small area is distributed Poisson with mean lambda for all regions</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Inhomogenous Poisson Point Process</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">A spatial statistical assumption that the count of events in an arbitrarily small area is distributed Poisson with mean lambda that varies through space as a function of the underlying population at risk. This is true for most spatial epidemiology.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Kernel density estimator</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A non-parametric way to estimate the probability distribution function of a random variable. In spatial (e.g. 2-d) kernel density estimation, it is a way to describe the spatially continuous variation in the intensity of events (points).</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial density</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">A standardized metric of spatial intensity. Related to a probability density function, it is a proportionate indicator of how much of the total events occur in a specific region. In kernel density estimation, the density surface integrates (or sums) to 1 across a study region.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial intensity</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A measure of the ratio of events at specific points to a unit of area. Spatial intensity describes the spatially continuous surface of event occurrence. In kernel density estimation, a spatial intensity surface integrates (or sums) to the sample size across a study region.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Stationarity vs non-stationarity</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Many statistics assume that the parameter, estimate, or property is constant across sub-units. For example if we take the average height of a population, under stationarity we would assume that average applies equally to sub-populations. In contrast, non-stationarity implies the parameter, estimate, or property varies across sub-groups. In spatial analysis stationarity is an assumption of homogeneity, and non-stationarity allows for heterogeneity.</td>
</tr>
</table></div>
</div>
</div>
<div id="spatial-thinking-in-epidemiology-4" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Spatial Thinking in Epidemiology<a class="anchor" aria-label="anchor" href="#spatial-thinking-in-epidemiology-4"><i class="fas fa-link"></i></a>
</h2>
<div id="revisiting-spatial-point-processes" class="section level3" number="7.2.1">
<h3>
<span class="header-section-number">7.2.1</span> Revisiting spatial point processes<a class="anchor" aria-label="anchor" href="#revisiting-spatial-point-processes"><i class="fas fa-link"></i></a>
</h3>
<p>People exist in places, but they are not uniformly nor randomly distributed. More live in cities; fewer live in rural area. But conditional on <em>where</em> people actually live or work or play, under a null expectation we could treat the occurrence of health events (e.g. disease, death, behaviors) as random variables, and leverage the tools of statistics to characterize when occurrence is what we would expect versus when it is something unusual.</p>
<p>In spatial analysis, we treat health events as random events among individuals located in space. Thus, conditional on where people are, we might assume (again, under the null hypothesis) that the occurrence of events is generated according to the assumed probability distribution. The utility of the <em>Poisson Point Process</em> becomes apparent when we see that we could divide a region into very small sub-regions and count the number of events within each, assuming that count follows a Poisson distribution.</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="images/quadrat.png" alt="Poisson point process"><p class="caption">
FIGURE 3.1: Poisson point process
</p>
</div>
<p>In the above figure, we quantify the <em>spatial intensity</em> of events by calculating <span class="math inline">\(\lambda = \frac{n}{area}\)</span>. Thus, all of our statistical analysis to date is premised on this idea that the spatial location of points can be interpreted through the lens of a <em>Poisson</em> probability distribution.</p>
<p>But what if we could calculate the <em>spatial intensity</em> more continuously, without the constraint of a specific parametric distribution, and without using the possibly arbitrary boundaries and zoning schemes of areal geographic units such as census tracts, zip codes, or counties?</p>
<p><em>Spatial point process</em> analysis focuses on characterizing patterns derived directly from the location of the points themselves, without arbitrary aggregation. The study of <em>point process analysis</em> is broad, but we will focus on one particularly flexible strategy this week: <strong>kernel density estimation</strong> (KDE). Kernel density estimation has several features making it useful for spatial epidemiology including:</p>
<ul>
<li>It is non-parametric, meaning it does not rely on a specific probability distribution (e.g. Poisson, negative binomial)</li>
<li>It provides an alternative means for characterizing <em>local neighbors</em>. The strategy of the KDE estimators is most similar to <em>inverse distance weighting</em>
</li>
<li>It can be used as a primary tool, or can be an intermediate step for creating <em>spatial weights</em>, as we will see in <em>geographically weighted regression</em>
</li>
<li>While it is really designed for analyzing <em>points</em>, we can use it on areal/polygon data as well.</li>
</ul>
</div>
<div id="what-is-a-kernel-density-estimator" class="section level3" number="7.2.2">
<h3>
<span class="header-section-number">7.2.2</span> What is a kernel density estimator?<a class="anchor" aria-label="anchor" href="#what-is-a-kernel-density-estimator"><i class="fas fa-link"></i></a>
</h3>
<p>A <em>kernel</em> is a function (e.g. mathematically described ‘<em>shape</em>’) that is iteratively centered over each point of data. For example, a Gaussian kernel means there is a Gaussian bell-shaped curve centered over each point; the width of the curve is defined by a parameter, <span class="math inline">\(h\)</span>, which stands for the <em>bandwidth</em>.</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="images/kde2.png" alt="Kernel density estimator"><p class="caption">
FIGURE 3.2: Kernel density estimator
</p>
</div>
<p>To estimate the <em>spatial intensity</em> of points, <span class="math inline">\(\hat{\lambda}\)</span>, we can sum up the area under all of the kernels to estimate an overall <em>kernel density</em> at each location. This <em>kernel density estimate</em> essentially reports a spatially continuous summary of the <em>local intensity</em> of events.</p>
<p>The result is that we can summarize a study region with spatially-referenced point data using a <em>spatially continuous intensity surface</em>. The analyst decides on how <em>smooth</em> or <em>bumpy</em> the surface should be by increasing or decreasing the value of the bandwidth parameter, <span class="math inline">\(h\)</span>. As we will see below, the decision about bandwidth could be made subjectively (e.g. to produce a visually appealing surface), or by minimizing error or through cross-validation.</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="images/kde3.jpg" alt="Kernel density smoothing"><p class="caption">
FIGURE 3.3: Kernel density smoothing
</p>
</div>
</div>
<div id="spatial-heterogeneity-versus-spatial-non-stationarity" class="section level3" number="7.2.3">
<h3>
<span class="header-section-number">7.2.3</span> Spatial heterogeneity versus Spatial non-stationarity<a class="anchor" aria-label="anchor" href="#spatial-heterogeneity-versus-spatial-non-stationarity"><i class="fas fa-link"></i></a>
</h3>
<p>By now you are familiar with the concept of <em>spatial heterogeneity</em> as being the phenomenon where local estimates of intensity, risk, or rate are different in at least some locations from the <em>global</em> estimates across the entire region. If all local rates were statistically similar to the global rate then we could say the process is <em>spatially homogeneous</em>, and not likely of much interest from a <em>spatial</em> or <em>cartographic</em> perspective.</p>
<p>In the vocabulary for Disease Mapping 1, we first introduced the terms ‘<em>stationarity</em>’ versus ‘<em>non-stationarity</em>’ which referred to a closely related idea. A <em>stationary process</em> is one where the estimate of a statistic (e.g. an intensity, density, risk, rate, but also a correlation or regression coefficient) is not dependent on location within the region. In other words, the estimate of the statistic is invariant to choice of local area within the global study region. In contrast, <em>spatial non-stationarity</em> is present when the estimate of the statistic is <em>dependent on</em> the location at which the measures are made.</p>
<div class="rmdnote">
<p><strong>Distinguishing heterogeneity from non-stationarity</strong></p>
<p>These two concepts are clearly similar. One way to unpack the subtle differences is to think about two kinds of <em>spatial heterogeneity</em>:</p>
<ol style="list-style-type: decimal">
<li>Areal units (e.g. counties) have different values of the parameter of interest (e.g. disease rate), but the high-rate counties and low-rate counties are randomly distributed. In other words we would conclude there was heterogeneity even if we randomly mixed up the exact location of the counties.</li>
<li>Area units have different values, but the values tend to be clustered in space such that the high-rate counties are near one another, and the low-rate counties are near one another. Thus the value of a given county is <em>dependent on</em> the spatial location.</li>
</ol>
<p>This discussion of <em>spatial heterogeneity</em> and <em>spatial non-stationarity</em> will be relevant in discussion of the spatially varying statistics in the second part of the Spatial Analysis module this week, but will be especially relevant when we begin to discuss <em>spatial clustering</em> and <em>spatial regression</em>.</p>
</div>
</div>
<div id="limitations-in-kernel-density-estimation" class="section level3" number="7.2.4">
<h3>
<span class="header-section-number">7.2.4</span> Limitations in kernel density estimation<a class="anchor" aria-label="anchor" href="#limitations-in-kernel-density-estimation"><i class="fas fa-link"></i></a>
</h3>
<p>There are several features of real data that can limit the accurate estimation of a <em>true</em> underlying spatial intensity surface. Here are a few:</p>
<ul>
<li>
<strong>Study region and edge effects</strong>: In almost any situation, the data available in a given dataset represents only a subset of the universe of points and events of interest. We can only carry out KDE on available data, and if there are boundaries to where data is collected (e.g. only within a given state boundary), then the intensity of points near boundaries may be mis-estimated due to missing data. Several of the statistical smoothers below have options to incorporate adjustments for these <em>edge effects</em>.</li>
<li>
<strong>Determining bandwidth</strong>: The choice of the kernel bandwidth is perhaps the most influential decision driving how the final results appear. While occasionally there may be theoretical grounds for <em>a priori</em> specification of bandwidth, often the decision is one of <em>subjective analyst choice</em> (typically not ideal) or of statistical optimization. In the sections below there is discussion of <em>fixed</em> versus <em>adaptive</em> bandwidths, as well as some algorithms for selecting values or at least upper or lower bounds.</li>
</ul>
</div>
<div id="uses-for-kernel-density-estimation-kde-in-spatial-epidemiology" class="section level3" number="7.2.5">
<h3>
<span class="header-section-number">7.2.5</span> Uses for kernel density estimation (KDE) in spatial epidemiology<a class="anchor" aria-label="anchor" href="#uses-for-kernel-density-estimation-kde-in-spatial-epidemiology"><i class="fas fa-link"></i></a>
</h3>
<p>Because kernel density estimation is the only method we will learn this semester for working with <em>point data</em>, it should be clear that this is one major application. However, more generally, KDE has broad applications. Here are some examples of when you might think about using kernel density estimates:</p>
<ul>
<li>For producing spatially continuous (typically <em>raster</em>) surfaces representing disease risk. This is the application most consistent with disease mapping, where the purpose is to describe spatial heterogeneity in disease <em>intensity</em> or risk.</li>
<li>For summarizing point-referenced resources (e.g. retail food outlets; health care clinics; toxic emitters; etc) as an <em>exposure surface</em>. This strategy is an alternative to calculating custom distances between each event point and every other resource or exposure. Instead, the kernel density surface summarizes the <em>average exposure</em> to all resources at any given point in space.</li>
<li>For smoothing and summarizing data measured at an areal or polygon unit. While KDE is optimized for point data, it is possible to extend it to smoothing any data (exposure, covariate, or health outcome) measured or reported at an ecologic areal unit.</li>
<li>Building on the extension of KDE to polygons, we can summarize social or economic <em>exposure surfaces</em>. This is a useful way to extend socio-economic-cultural measures that might be available at census geography to represent them as not only contained within specific boundaries, but as being explicitly spatially situated.</li>
</ul>
<div class="rmdcaution">
<p><strong>Distinguishing point intensity from risk intensity</strong></p>
<p>The material above emphasizes the interest in the <em>intensity of points</em> per unit area. But what does a <em>point</em> represent epidemiologically? Usually it represents the location of an observation, but it it not automatically clear whether the observation is an <em>event of interest</em> (e.g. illness, death, etc), or whether it is a <em>person at risk</em> (e.g. a sampled or observed participant who may or may not experience the event).</p>
<p>For most epidemiologic purposes we care about the <em>ratio of events to population at risk</em>. We can translate that idea into kernel density surfaces by estimating <strong>two kernel density estimates</strong>: one for the intensity of events (e.g. deaths) per unit area, and the second for the intensity of persons at risk for death per unit area. We can then take the <em>ratio of two kernel density estimates</em> to produce a <strong>risk surface</strong>.</p>
<p>This will be illustrated in the following sections.</p>
</div>
<p>In the next section, we introduce two different uses of kernel density estimation:</p>
<ol style="list-style-type: decimal">
<li>First is the intensity estimation of spatial point processes consistent with the description above.</li>
<li>Second, we illustrate the use of kernel density estimators to create <em>weights</em> for <em>geographically-weighted summary statistics</em>, including the spatially varying mean risk or rate. This strategy can be applied to either <em>points</em> or to <em>polygons</em>.</li>
</ol>
</div>
<div id="guide-to-the-rest-of-this-section" class="section level3" number="7.2.6">
<h3>
<span class="header-section-number">7.2.6</span> Guide to the rest of this section…<a class="anchor" aria-label="anchor" href="#guide-to-the-rest-of-this-section"><i class="fas fa-link"></i></a>
</h3>
<div class="rmdtip">
<p>There is a lot of content contained in this module. It is worth highlighting some broad distinctions to help you navigate.</p>
<p><strong>The first section</strong> focuses on tools using the <code>sparr</code> and <code>spatstat</code> packages to create kernel density estimates from <em>point data</em>. This includes:</p>
<ul>
<li>Creating <code>ppp</code> objects for <em>planar point processes</em>
</li>
<li>Creating <code>owin</code> objects to define study regions</li>
<li>Discussion of several different strategies for selecting a <em>kernel bandwidth</em> which dictates smoothing</li>
<li>Creation of kernel density surfaces of single point processes</li>
<li>Creation of kernel density <em>relative risk</em> surfaces contrasting the ratio of numerator to denominator intensity</li>
<li>Visualizing the output in several ways.</li>
</ul>
<p><strong>The second section</strong> introduces a seemingly quite distinct strategy for incorporating kernel density estimators into spatial epidemiology. It introduces tools for calculating <em>geographically weighted summary statistics</em> to characterize spatial heterogeneity. These tools use kernel density estimators to geographically weight observations, and can be applied to <em>points</em> or <em>polygons</em>.</p>
</div>
<div class="rmdnote">
<p><strong>NOTE</strong>:</p>
<p>For most modules this semester, the <em>Spatial Analysis</em> section of the eBook uses examples to introduce analytic approaches, and then the in-class Lab uses different data to practice.</p>
<p>Because of the ‘<em>newness</em>’ of kernel density estimators, and the large volume of information, the following material in the eBook is <em>very closely aligned</em> with what we will practice in Lab.</p>
<p>I recommend you read through this content before the lab, then work through the lab itself, then refer back to the eBook as you have questions.</p>
</div>
</div>
</div>
<div id="spatial-analysis-in-epidemiology-kernel-estimation-of-point-processes" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> Spatial Analysis in Epidemiology: Kernel estimation of point processes<a class="anchor" aria-label="anchor" href="#spatial-analysis-in-epidemiology-kernel-estimation-of-point-processes"><i class="fas fa-link"></i></a>
</h2>
<p>This section has three specific objectives:</p>
<ol style="list-style-type: decimal">
<li>Introduce a new spatial data class in <code>R</code>, <code>ppp</code>, which is necessary for executing the kernel estimation functions</li>
<li>Introduce kernel density estimation of spatial point processes, including selection of fixed bandwidths, and use of adaptive bandwidths</li>
<li>Introduce spatial <em>relative risk surfaces</em>, including estimation of tolerance contours</li>
</ol>
<div id="preparing-packages-and-data" class="section level3" number="7.3.1">
<h3>
<span class="header-section-number">7.3.1</span> Preparing packages and data<a class="anchor" aria-label="anchor" href="#preparing-packages-and-data"><i class="fas fa-link"></i></a>
</h3>
<p>There are several new packages that will be required for this work:</p>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>,  <span class="co"># for general data management</span>
               <span class="va">sp</span>,         <span class="co"># for handling legacy spatial data classes</span>
               <span class="va">sf</span>,         <span class="co"># for handling sf data class</span>
               <span class="va">tmap</span>,       <span class="co"># for mapping</span>
               <span class="va">spatstat</span>,   <span class="co"># A package with tools that underly the sparr package</span>
               <span class="va">sparr</span>,      <span class="co"># A package for estimating spatial intensity and relative risk</span>
               <span class="va">maptools</span>,   <span class="co"># This has a helper function for working with ppp class data</span>
               <span class="va">raster</span><span class="op">)</span>     <span class="co"># The outputs of these KDE functions will be raster. This package gives us tools for working with rasters</span></code></pre></div>
<div class="rmdnote">
<p><strong><code>sp</code> Data class</strong></p>
<p>In addition to those new packages, we will also need the <code>sp</code> package. Recall that we have only worked with <code>sf</code> class data up until now, although we learned that <code>sp</code> was the <em>older format</em> for spatial data in <code>R</code>. Some packages and functions (including <code>sparr</code> and <code>spatstat</code>) have not incorporated compatibility with <code>sf</code> data, so we will need to convert some particular objects from <code>sf</code> to <code>sp</code> before moving forward.</p>
</div>
<p>The data used in this example, and in the lab, concerns the exact <span class="math inline">\(x,y\)</span> residential location of all births in Dekalb and Fulton county, including indication of infants who subsequently died within the first year of life.</p>
<blockquote>
<p>NOTE: These data are simulated based on approximate patterns. This is <strong>not a representation of actual birth event data</strong>.</p>
</blockquote>
<p>The spatial point location for births and infant deaths are in two separate files. In addition a polygon file providing the outline for Dekalb and Fulton counties is provided to describe the <em>study window</em>.</p>
<div class="sourceCode" id="cb107"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># This is points for births in Dekalb/Fulton county</span>
<span class="va">b_point</span> <span class="op">&lt;-</span> <span class="fu">st_read</span><span class="op">(</span><span class="st">'birth_points.gpkg'</span><span class="op">)</span>

<span class="co"># This is points for deaths in Dekalb/Fulton county</span>
<span class="va">d_point</span> <span class="op">&lt;-</span> <span class="fu">st_read</span><span class="op">(</span><span class="st">'death_points.gpkg'</span><span class="op">)</span> 

<span class="co"># This is an outline of Dekalb/Fulton county to be used as a study 'window'</span>
<span class="va">county</span> <span class="op">&lt;-</span> <span class="fu">st_read</span><span class="op">(</span><span class="st">'DekalbFultonWindow.gpkg'</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">as</span><span class="op">(</span><span class="st">'Spatial'</span><span class="op">)</span></code></pre></div>
<p>In the code above, note the us of the function <code><a href="https://r-spatial.github.io/sf/reference/coerce-methods.html">as('Spatial')</a></code> for the object <code>county</code>. This is a conversion step, translating the <code>sf</code> object to an object of class <code>sp</code>. It is only necessary in this particular case for the polygon file representing the <em>study window</em> because the functions the create that window expect data of class <code>sp</code>. In contrast we can extract the coordinates from an <code>sf</code> point object, without a need to convert to <code>sp</code> first.</p>
</div>
<div id="introducing-a-new-spatial-data-class-ppp" class="section level3" number="7.3.2">
<h3>
<span class="header-section-number">7.3.2</span> Introducing a new spatial data class: <code>ppp</code><a class="anchor" aria-label="anchor" href="#introducing-a-new-spatial-data-class-ppp"><i class="fas fa-link"></i></a>
</h3>
<p>Much of the statistical methods for spatial point process actually developed out of <em>ecology</em>, and the methods are only merging with the other spatial analysis and spatial epidemiology fields in recent years. One consequence of this history, is that the early developers of these methods in <code>R</code> defined their own spatial data classes, and in this case the class is called <code>ppp</code> for point pattern data in a two-dimensional plane.</p>
<p>To create a <code>ppp</code> data object we need, at a minimum, two things:</p>
<ol style="list-style-type: decimal">
<li>A matrix of <span class="math inline">\(x,y\)</span> coordinates for event points</li>
<li>A definition for the <em>spatial window</em> or study region.</li>
</ol>
<p>This <em>window</em> is necessary because nearly any data set is a sub-sample of the universe of possible <em>points</em>, and analysis of point processes requires appreciation for the <em>bounds of sampling</em> or observation.</p>
<p>We define the window formally in <code>R</code> as an object of class <code>owin</code>, and it can be a rectangular bounding box (e.g. the outline of the available data), or a customized polygon. We will use the outline of Dekalb &amp; Fulton counties as the customized <em>spatial window</em> for the observation of births and infant deaths.</p>
<div class="rmdnote">
<p><strong>Note</strong>:
The function below to create the <code>owin</code> object only works on <code>sp</code> class <code>SpatialPolygons</code>. That is why we converted the polygon file to class <code>sp</code> when we imported (above).</p>
</div>
<p>You can see from the summary and the plot what this <code>owin</code> object looks like.</p>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">county_owin</span> <span class="op">&lt;-</span> <span class="fu">maptools</span><span class="fu">::</span><span class="fu"><a href="http://maptools.r-forge.r-project.org/reference/as.owin.html">as.owin.SpatialPolygons</a></span><span class="op">(</span><span class="va">county</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">county_owin</span><span class="op">)</span></code></pre></div>
<pre><code>## Window: polygonal boundary
## single connected closed polygon with 698 vertices
## enclosing rectangle: [1026366.3, 1098719.2] x [1220671, 1302019.3] units
##                      (72350 x 81350 units)
## Window area = 2086320000 square units
## Fraction of frame area: 0.354</code></pre>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">county_owin</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-9-1.png" width="672"></div>
</div>
<div id="creating-the-ppp-objects" class="section level3" number="7.3.3">
<h3>
<span class="header-section-number">7.3.3</span> Creating the <code>ppp</code> objects<a class="anchor" aria-label="anchor" href="#creating-the-ppp-objects"><i class="fas fa-link"></i></a>
</h3>
<p>Now we will use the function <code>ppp()</code> to create objects of class <code>ppp</code> for each of the <em>spatial point</em> files, <code>b_point</code> (representing locations of all births, the denominator for infant mortality), and <code>d_point</code> (representing locations of all deaths, the numerator for infant mortality). Doing so requires definition of the <em>study window</em> defined above as the object name <code>county_owin</code> of class <code>owin</code>.</p>
<p>Again, the study window delineates what is <em>in</em> versus <em>out</em> of the study area demarcates <em>edges</em> of the study region. You can look at the help documentation for the function <code>ppp()</code> to see the arguments. Note that because the function requires specification of the <span class="math inline">\(x,y\)</span> locations as two separate vectors, we extract the coordinate values from our <code>sf</code> object using <code><a href="https://r-spatial.github.io/sf/reference/st_coordinates.html">st_coordinates()</a></code>.</p>
<div class="rmdnote">
<p><strong>Why two <code>ppp</code> objects?</strong></p>
<p>Recall that estimation of a spatial point process is agnostic to whether the point (or person) had the event (e.g. death) or not (e.g. live birth who lived past 1 year). To represent the ratio of deaths to all live births (e.g. the infant mortality rate), we need to estimate <strong>two kernel density surfaces</strong>, and then take the ratio.</p>
</div>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Create the birth ppp object</span>
<span class="va">b_ppp</span> <span class="op">&lt;-</span> <span class="fu">ppp</span><span class="op">(</span>x <span class="op">=</span> <span class="fu">st_coordinates</span><span class="op">(</span><span class="va">b_point</span><span class="op">)</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, 
             y <span class="op">=</span> <span class="fu">st_coordinates</span><span class="op">(</span><span class="va">b_point</span><span class="op">)</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>,
             window <span class="op">=</span> <span class="va">county_owin</span><span class="op">)</span>

<span class="co"># Create the death ppp object</span>
<span class="va">d_ppp</span> <span class="op">&lt;-</span> <span class="fu">ppp</span><span class="op">(</span>x <span class="op">=</span> <span class="fu">st_coordinates</span><span class="op">(</span><span class="va">d_point</span><span class="op">)</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, 
             y <span class="op">=</span> <span class="fu">st_coordinates</span><span class="op">(</span><span class="va">d_point</span><span class="op">)</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>,
             window <span class="op">=</span> <span class="va">county_owin</span><span class="op">)</span></code></pre></div>
<p>As you might expect, there are built-in methods (from the <code>spatstat</code> package) to summarize and plot <code>ppp</code> objects.</p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">d_ppp</span><span class="op">)</span></code></pre></div>
<pre><code>## Planar point pattern:  701 points
## Average intensity 3.359978e-07 points per square unit
## 
## Coordinates are given to 2 decimal places
## i.e. rounded to the nearest multiple of 0.01 units
## 
## Window: polygonal boundary
## single connected closed polygon with 698 vertices
## enclosing rectangle: [1026366.3, 1098719.2] x [1220671, 1302019.3] units
##                      (72350 x 81350 units)
## Window area = 2086320000 square units
## Fraction of frame area: 0.354</code></pre>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">d_ppp</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-11-1.png" width="672"></div>
<p>The summary includes information about the overall <em>spatial intensity</em> (e.g. events per unit area), as well as the number of points, and the observational window. The plot for <code>d_ppp</code> should look just like a plot of <code>d_point</code> as they both contain the same information. Of note, if you repeat the above code for all of the birth events, <code>b_point</code>, the plot will be less readable because there are over 94,000 births as compared with only 705 deaths!</p>
</div>
<div id="bandwidth-selection" class="section level3" number="7.3.4">
<h3>
<span class="header-section-number">7.3.4</span> Bandwidth selection<a class="anchor" aria-label="anchor" href="#bandwidth-selection"><i class="fas fa-link"></i></a>
</h3>
<p>As discussed above, and in lecture, the kernel density estimation requires the analyst to specify a <em>kernel function</em> (e.g. a Gaussian kernel, or a quartic bi-weight kernel), and a <em>kernel bandwidth</em>.</p>
<p>Of the two, the bandwidth is substantially more impactful on results than choice of kernel function.</p>
<p>As a reminder, the <em>bandwidth</em> (sometimes indicated by variable <span class="math inline">\(h\)</span>) describes the <em>width</em> or <em>radius</em> of the kernel function, and as a result dictates how <em>smooth</em> the resulting intensity surface will be. A small bandwidth will produce a bumpier or rougher surface, whereas a larger bandwidth will result in more smoothing.</p>
<div class="rmdnote">
<p><strong>Bandwidth measures proximity or closeness</strong></p>
<p>Conceptually you might notice a similarity between what the <em>bandwidth</em> does for spatial analysis to what the definition of <em>spatial neighbors</em> does. In each case it is a kind of ‘<em>local</em>’ inclusion of data for analysis, within a broader <em>global</em> study region.</p>
<p>Bandwidth defines which sets of points will be considered <em>close</em> and which are not.</p>
</div>
<p>There are two general kinds of bandwidth settings:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Fixed bandwidths:</strong> A single value of <span class="math inline">\(h\)</span> designates that the width of the kernel (and thus the resulting smoothness of the estimated intensity surface) is the same for the entire study region. Fixed bandwidths are commonly used, and sensible for a study region with relatively homogeneous population at risk. However choosing a single value can be challenging in practice when the density of points varies substantially across the study region, as could be the case when your study region includes a range from very urban to very rural.</li>
<li>
<strong>Adaptive bandwidths:</strong> As the name implies, this approach changes or <em>adapts</em> the size of the kernel density bandwidth according to the density of points (data) in differing sub-areas of the overall study region. The result is relatively more smoothing (larger bandwidth) in areas with sparse point data, and relatively less smoothing (smaller bandwidth) in areas with more point density.</li>
</ol>
<div id="fixed-bandwidth-methods" class="section level4" number="7.3.4.1">
<h4>
<span class="header-section-number">7.3.4.1</span> Fixed bandwidth methods<a class="anchor" aria-label="anchor" href="#fixed-bandwidth-methods"><i class="fas fa-link"></i></a>
</h4>
<p>If you prefer a <em>fixed bandwidth</em>, the first challenge is choosing what it should be. One option for selecting a <em>fixed bandwidth</em> is to incorporate theory or prior knowledge about the process of interest. For instance, if you are trying to understand whether the prevalence of diabetes is related to local food environment in an urban area, you might want a bandwidth which helps illuminate differences in diabetes <em>intensity</em> at a scale consistent with the food environment. For instance a bandwidth of <em>1-mile</em> might be more reasonable in urban areas than one of <em>50-miles</em>, as the latter would likely smooth away all of the local variation of interest.</p>
<p>However, it is not uncommon that theory or prior knowledge are insufficient to make a clear choice, or that data sparsity mandates an alternate approach driven by concern for stable estimates.</p>
<p>The package <code>sparr</code> has several functions designed to use primarily statistical optimization for estimating an <em>‘optimum’</em> bandwidth. We will introduce two commonly used statistical bandwidth selection optimizers:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Cross-validation:</strong> this approach divides the data into subsets, using one subset to choose a bandwidth, and comparing the performance on other subsets. The goal is to find a value that works <em>‘best’</em> (e.g. optimize a statistical parameter across multiple iterations). The approach is computationally intensive for large datasets. As discussed in note below, cross-validation can result in <em>too small</em> bandwidth estimation.</li>
<li>
<strong>Over-smoothing:</strong> this is an alternate approach that aims to identify the maximum amount of smoothing necessary for minimizing statistical error. By definition it is a <em>maximum</em> value rather than an <em>ideal</em> or <em>optimal</em> value, but can be useful in setting bounds.</li>
</ol>
<div class="rmdnote">
<p>The <code>sparr</code> package provides three <em>cross-validation</em> approaches to estimation:</p>
<ul>
<li>
<code>LCSV.density</code> (least squares cross validated);</li>
<li>
<code>LIK.density</code> (likelihood cross-validated);</li>
<li>
<code>SLIK.adapt</code> (described as an experimental likelihood cross-validation for adaptive).</li>
</ul>
<p>Each is ‘optimizing’ a different thing. The <code>LSCV.density</code> minimizes an unbiased estimate of the mean integrated squared error (MISE) whereas <code>LIK.density</code> maximizes cross-validated leave-one-out average of the log-likelihood of the density estimate.</p>
<p>If you look at the help documentation for these you will see (near the bottom) a prominent warning message. It reports that “<em>CV for bandwidth selection is notoriously unstable in practice and has a tendency to produced rather small bandwidths…</em>”</p>
</div>
</div>
<div id="cross-validation-with-lik.density" class="section level4" number="7.3.4.2">
<h4>
<span class="header-section-number">7.3.4.2</span> Cross-validation with <code>LIK.density()</code><a class="anchor" aria-label="anchor" href="#cross-validation-with-lik.density"><i class="fas fa-link"></i></a>
</h4>
<p><code>LIK.density()</code> uses likelihood estimation of cross-validation optimal bandwidth. For the <em>death</em> dataset, <code>d_ppp</code>, it runs in just a few seconds. However it took &gt; 5 minutes to produce a value on the much larger <em>births</em> dataset, <code>b_ppp</code>. This code lets you try it to see what it produces:</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">h_LIK_d</span> <span class="op">&lt;-</span> <span class="fu">LIK.density</span><span class="op">(</span><span class="va">d_ppp</span><span class="op">)</span></code></pre></div>
<pre><code>## Searching for optimal h in [27.463186212964, 12058.8149770359]...Done.</code></pre>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">h_LIK_d</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1613.661</code></pre>
<p>If you examine the object returned (<code>h_LIK_d</code>), you’ll see it is just a single number. This is the value of <span class="math inline">\(h\)</span>, or the optimized bandwidth. It is, in other words, the radius of the 2-dimensional kernel density function in the units of the data, which is <em>meters</em> in this case (e.g. the original data were <em>Albers Equal Area</em> projected). So this means that the optimum kernel will have a radius of just over 1.5 kilometers.</p>
</div>
<div id="oversmoothing-algorithm-with-function-os" class="section level4" number="7.3.4.3">
<h4>
<span class="header-section-number">7.3.4.3</span> Oversmoothing algorithm with function <code>OS()</code><a class="anchor" aria-label="anchor" href="#oversmoothing-algorithm-with-function-os"><i class="fas fa-link"></i></a>
</h4>
<p>This approach is much less computationally intense, and thus feasible for both of our spatial point processes (e.g. both numerator deaths, and denominator births). As we will see below, we can use the value returned from <code>OS()</code> as a <em>pilot value</em> for <em>adaptive bandwidth</em> estimation. In other words it provides a kind of reference or starting point for the adaptation process.</p>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">h_os_d</span> <span class="op">&lt;-</span> <span class="fu">OS</span><span class="op">(</span><span class="va">d_ppp</span><span class="op">)</span>
<span class="va">h_os_b</span> <span class="op">&lt;-</span> <span class="fu">OS</span><span class="op">(</span><span class="va">b_ppp</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">h_os_d</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 4257.798</code></pre>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">h_os_b</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1897.371</code></pre>
<p>Note that the <em>birth</em> data have a smaller optimal bandwidth (<code>h_os_b</code>) because there are more points. More points means more information is available for more granular smoothing, whereas the relatively more sparse <em>death</em> data have a larger over smoothing bandwidth (<code>h_os_d</code>).</p>
</div>
<div id="selecting-a-common-bandwidth-for-both-numerator-and-denominator" class="section level4" number="7.3.4.4">
<h4>
<span class="header-section-number">7.3.4.4</span> Selecting a common bandwidth for both numerator and denominator<a class="anchor" aria-label="anchor" href="#selecting-a-common-bandwidth-for-both-numerator-and-denominator"><i class="fas fa-link"></i></a>
</h4>
<p>One challenge in bandwidth selection is that we typically have two related spatial point processes (e.g. the numerator, death events; and the denominator, birth events). Therefore we don’t want only a single KDE, but instead we will need to consider a numerator representing the spatial intensity of deaths, and a denominator representing the spatial intensity of all live births at risk. This raises the question of whether there should be a <em>common bandwidth for both</em>, or whether <em>each should be optimized separately</em>.</p>
<p>While there may be only minor differences in the <em>absolute intensity</em> under different bandwidths in a single point process, taking the ratio of two intensity surfaces can exaggerate small differences to be quite large. There are functions for estimating a single, joint, optimum for the bandwidth. The function <code>LSCV.risk()</code> does just what the <code>LIK.density()</code> above did, but with <em>two spatial point processes</em>. The code example is below, but like the previous example, the cross-validation approach to the birth data set takes an excessive amount of time (at least for this exercise).</p>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#h_LSCV_risk &lt;- LSCV.risk(d_ppp, b_ppp)</span></code></pre></div>
</div>
<div id="adaptive-bandwidth-methods" class="section level4" number="7.3.4.5">
<h4>
<span class="header-section-number">7.3.4.5</span> Adaptive bandwidth methods<a class="anchor" aria-label="anchor" href="#adaptive-bandwidth-methods"><i class="fas fa-link"></i></a>
</h4>
<p>Adaptive methods are specified <em>at the time of kernel density estimation</em>. While the bandwidth is not constant, but instead <em>adaptive</em>, we usually still need to specify a <em>pilot bandwidth</em>, which is a reference point from which adaptive modification occurs. As mentioned above, the <em>over-smoothing</em> approach from <code>OS()</code> can be used as a pilot value.</p>
</div>
</div>
<div id="estimating-kernel-density-surfaces" class="section level3" number="7.3.5">
<h3>
<span class="header-section-number">7.3.5</span> Estimating Kernel Density surfaces<a class="anchor" aria-label="anchor" href="#estimating-kernel-density-surfaces"><i class="fas fa-link"></i></a>
</h3>
<p>We now turn to the actual estimation of kernel density approximations of the underlying <em>spatial intensity</em> of disease. The approach in this lab is to first illustrate how to estimate separate densities for each point process (e.g. of <em>deaths</em> and of <em>births</em>), and then to demonstrate two strategies for creating <em>spatial relative risk surfaces</em>, which is generally the target output for spatial epidemiologists.</p>
<p>Of note, this discussion will demonstrate use of both <em>fixed</em> and <em>adaptive</em> bandwidths. In general adaptive bandwidths may be the most practical approach <em>in the absence of theoretical or empirical preference</em> otherwise. However there are instances where <em>fixed bandwidths</em> (either theoretically informed, or as derived from CV or over-smoothing algorithms) are desired, and thus seeing both in action is useful.</p>
<div id="bivariate.density-for-kde-of-single-point-process" class="section level4" number="7.3.5.1">
<h4>
<span class="header-section-number">7.3.5.1</span> <code>bivariate.density()</code> for KDE of single point process<a class="anchor" aria-label="anchor" href="#bivariate.density-for-kde-of-single-point-process"><i class="fas fa-link"></i></a>
</h4>
<p>There are actually several <code>R</code> packages that accomplish kernel density estimation, but one that is particularly useful for spatial epidemiology (where the kernel density estimator must be 2-dimensional and we frequently take the ratio of two densities) is the <code>sparr</code> package, which stands for <em>Spatial and Spatiotemporal Relative Risk</em>.</p>
<p>The <code>sparr</code> function <code>bivariate.density()</code> is a flexible and useful tool for carrying out KDE with either <em>fixed</em> or <em>adaptive</em> bandwidths. There are many arguments for <code>bivariate.density()</code> (see help documentation), but here are several worth specifically highlighting.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="16%">
<col width="83%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong><code>pp</code></strong></td>
<td>This first argument expects a <em>single</em> point process object of class <code>ppp</code>. We will use either <code>d_ppp</code> or <code>b_ppp</code>
</td>
</tr>
<tr class="even">
<td><strong><code>h0</code></strong></td>
<td>This argument specifies the <em>global fixed</em> bandwidth, if desired. This could be a theoretically-informed value (i.e. 2000 meters), or derived from an optimization algorithm (e.g. see above)</td>
</tr>
<tr class="odd">
<td><strong><code>hp</code></strong></td>
<td>If conducting <em>adaptive bandwidth</em> estimation, a single <em>pilot bandwidth</em> is still required, and this is where to specify it.</td>
</tr>
<tr class="even">
<td><strong><code>adapt</code></strong></td>
<td>This logical argument is <code>FALSE</code> by default, but set to <code>TRUE</code> if you want adaptive bandwidth estimation</td>
</tr>
<tr class="odd">
<td><strong><code>edge</code></strong></td>
<td>Because a given dataset is invariably a subset of the real world, there are likely <em>edges</em> where there is an artificially abrupt cessation of information. The result is a potentially biased intensity estimation at the study region edges. However there are correction factors. We will choose the <code>edge = 'diggle'</code> specification here</td>
</tr>
<tr class="even">
<td><strong><code>intensity</code></strong></td>
<td>By default, <code>intensity = FALSE</code> which means that by default <code>bivariate.density()</code> produces a <em>density surface</em>. If you want an <em>intensity surface</em>, set <code>intensity = TRUE</code>. (See note below)</td>
</tr>
</tbody>
</table></div>
<div class="rmdnote">
<p><strong>Intensity versus Density</strong></p>
<p>Up until now we have used the words <strong>intensity</strong> and <strong>density</strong> as if they are synonymous for point process parameter, but that is not exactly accurate.</p>
<p><strong>Intensity</strong> is the <em>average number of points per unit area</em>. The <strong>density</strong> is proportionate to the <em>intensity</em>, but scaled so that all values in the study region <em>sum to 1</em>. In other words a <strong>density surface</strong> is a proper probability density function (PDF).</p>
<p>A map of the two will look identical <em>except for the scale or legend</em>.</p>
</div>
</div>
<div id="fixed-bandwidth-kde-with-bivariate.density" class="section level4" number="7.3.5.2">
<h4>
<span class="header-section-number">7.3.5.2</span> Fixed bandwidth KDE with <code>bivariate.density()</code><a class="anchor" aria-label="anchor" href="#fixed-bandwidth-kde-with-bivariate.density"><i class="fas fa-link"></i></a>
</h4>
<p>First, let’s try a basic version that uses the <em>over-smooth</em> estimate for each point process.</p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">death_kde</span> <span class="op">&lt;-</span> <span class="fu">bivariate.density</span><span class="op">(</span>pp <span class="op">=</span> <span class="va">d_ppp</span>, h0 <span class="op">=</span> <span class="va">h_os_d</span>, edge <span class="op">=</span> <span class="st">'diggle'</span><span class="op">)</span>
<span class="va">birth_kde</span> <span class="op">&lt;-</span> <span class="fu">bivariate.density</span><span class="op">(</span>pp <span class="op">=</span> <span class="va">b_ppp</span>, h0 <span class="op">=</span> <span class="va">h_os_b</span>, edge <span class="op">=</span> <span class="st">'diggle'</span><span class="op">)</span></code></pre></div>
<p>You can explore the objects produced by the function call. For instance, they are <code>list</code> objects, with named sub-elements:</p>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">birth_kde</span><span class="op">)</span></code></pre></div>
<pre><code>## Bivariate Kernel Density/Intensity Estimate
## 
## Bandwidth
##   Fixed smoothing with h0 = 1897.371 units (to 4 d.p.)
## 
## No. of observations
##   94373 
## 
## Spatial bound
##   Type: polygonal
##   2D enclosure: [1026366, 1098719] x [1220671, 1302019]
## 
## Evaluation
##   128 x 128 rectangular grid
##   5808 grid cells out of 16384 fall inside study region
##   Density/intensity range [6.313906e-14, 1.585466e-09]</code></pre>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">birth_kde</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "z"         "h0"        "hp"        "h"         "him"       "q"        
## [7] "gamma"     "geometric" "pp"</code></pre>
<p>There is also some plotting functionality built into the <code>sparr</code> package that allows us to quickly visualize the resulting density plot.</p>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="co"># Plots in 1 row with 2 columns</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">birth_kde</span>, main <span class="op">=</span> <span class="st">'Birth density'</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">death_kde</span>, main <span class="op">=</span> <span class="st">'Death density'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-17-1.png" width="672"></div>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>  <span class="co"># Reset plotting space to be 1 row, 1 column</span></code></pre></div>
</div>
<div id="adaptive-bandwidth-kde-with-bivariate.density" class="section level4" number="7.3.5.3">
<h4>
<span class="header-section-number">7.3.5.3</span> Adaptive bandwidth KDE with <code>bivariate.density()</code><a class="anchor" aria-label="anchor" href="#adaptive-bandwidth-kde-with-bivariate.density"><i class="fas fa-link"></i></a>
</h4>
<p>As discussed above, an alternative to a single <em>fixed bandwidth</em>, is implementation of an algorithm that changes (<em>adapts</em>) the bandwidth across the study region in response to the density or sparseness of the data. This approach still requires specification of a <em>global</em> bandwidth, and the adaptation is a multiplier making the global smaller or larger as needed.</p>
<p>In this code we use the argument <code>h0 = xxx</code> to specify a <em>pilot bandwidth</em>. Because <em>adaptive bandwidth KDE</em> requires adjustment across the study region, you will notice that these functions take longer than the <em>fixed bandwidth</em> above, especially the large birth point process.</p>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">death_kde_adapt</span> <span class="op">&lt;-</span> <span class="fu">bivariate.density</span><span class="op">(</span><span class="va">d_ppp</span>, 
                                     h0 <span class="op">=</span> <span class="va">h_os_d</span>, 
                                     edge <span class="op">=</span> <span class="st">'diggle'</span>, 
                                     adapt <span class="op">=</span> <span class="cn">TRUE</span>,
                                     verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">birth_kde_adapt</span> <span class="op">&lt;-</span> <span class="fu">bivariate.density</span><span class="op">(</span><span class="va">b_ppp</span>, 
                                     h0 <span class="op">=</span> <span class="va">h_os_b</span>, 
                                     edge <span class="op">=</span> <span class="st">'diggle'</span>,
                                     adapt <span class="op">=</span> <span class="cn">TRUE</span>,
                                     verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">birth_kde_adapt</span>, main <span class="op">=</span> <span class="st">'Birth density\n(adaptive h)'</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">death_kde_adapt</span>, main <span class="op">=</span> <span class="st">'Death density\n(adaptive h)'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-20-1.png" width="672"></div>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="rmdnote">
<p><strong>Why are adaptive maps so similar to fixed bandwidth?</strong></p>
<p>The plots of the <em>intensity</em> from the <em>adaptive bandwidth</em> point processes do not look very different from those of the *fixed bandwidth processes. The reason is because the units of measurement (intensity) are so small that differences are not readily apparent.</p>
<p>However the differences become more apparent when we take the <em>ratio of the two surfaces</em>, which we will do below.</p>
</div>
</div>
<div id="plotting-kde-estimates-with-tmap" class="section level4" number="7.3.5.4">
<h4>
<span class="header-section-number">7.3.5.4</span> Plotting KDE estimates with <code>tmap</code><a class="anchor" aria-label="anchor" href="#plotting-kde-estimates-with-tmap"><i class="fas fa-link"></i></a>
</h4>
<p>It is handy that the <code>sparr</code> package has some built-in plotting functionality to quickly visualize the results. However you may want to have more control over the plotting, for instance in <code>tmap</code> or even in <code>ggplot2</code>.</p>
<p>If you recall the named elements in the <code>list</code> object returned by <code>bivariate.density()</code>, the first is called <code>z</code>, and this is the density surface itself.</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">birth_kde</span><span class="op">$</span><span class="va">z</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "im"</code></pre>
<p>The class of this object is <code>im</code> for <em>image</em>. However for almost any spatial plotting or operation outside of <code>sparr</code> and <code>spatstat</code>, we want this data in the <code>raster</code> class rather than this <code>im</code> format (fundamentally the data <em>is</em> a raster model, but the data structure in <code>R</code> is not quite the same as the data structure of class <code>raster</code>). We can convert <code>im</code> to <code>raster</code> class like this:</p>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">death_kde_raster</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="op">(</span><span class="va">death_kde_adapt</span><span class="op">$</span><span class="va">z</span>,
                           crs <span class="op">=</span> <span class="st">"+init=epsg:5070"</span><span class="op">)</span>
<span class="va">birth_kde_raster</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="op">(</span><span class="va">birth_kde_adapt</span><span class="op">$</span><span class="va">z</span>,
                           crs <span class="op">=</span> <span class="st">"+init=epsg:5070"</span><span class="op">)</span></code></pre></div>
<p>Notice in the code above the specification of <code>crs = "+init=epsg:5070"</code>. The <code>im</code> object lost all information about the original <em>coordinate reference system</em> (CRS) or <em>projection</em>. However, we need our raster object to have this CRS information to plot properly in <code>tmap</code>. We know that the original point data were <em>projected</em> in <em>Albers Equal Area</em>, specifically with <em>EPSG code</em> of 5070. So we re-define that when creating the rasters above.</p>
<p>Now we can plot these in <code>tmap</code>:</p>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Create map of death surface</span>
<span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">death_kde_raster</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">'BuPu'</span>,
            style <span class="op">=</span> <span class="st">'quantile'</span>,
            n <span class="op">=</span> <span class="fl">9</span>,
            title <span class="op">=</span> <span class="st">'Death density'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">county</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>scientific <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Create map of birth surface</span>
<span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">birth_kde_raster</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">'BuPu'</span>,
            style <span class="op">=</span> <span class="st">'quantile'</span>,
            n <span class="op">=</span> <span class="fl">9</span>,
            title <span class="op">=</span> <span class="st">'Birth density'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">county</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>scientific <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span>

<span class="co"># plot 2-panel arrangment</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">m1</span>, <span class="va">m2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-23-1.png" width="672"></div>
<div class="rmdtip">
<p><strong>Why do the maps look pixely?</strong></p>
<p>There are two reasons contributing to this.</p>
<ol style="list-style-type: decimal">
<li><p>First, the code above specified the colors in quantiles in order to get a range despite possibly skewed values. But you could try re-plotting the above plots setting <code>style = 'cont'</code> for <em>continuous</em> color palette, and comment out the <code>n=9</code>. You will see that this produces a much <em>smoother</em> looking plot. The difference between the plots with <code>style = 'cont'</code> and <code>style = 'quantile'</code> is the gradation of color in the intermediate levels of intensity.</p></li>
<li><p>Another reason for the pixelation is because the original call to <code>bivariate.density()</code> used the default output resolution of 128 x 128 grid cells. This was done for computational efficiency. However, note that if you want a higher-resolution surface (e.g. for publication, presentation), you can increase by specifying <code>resolution =</code> in the creation of the KDE surface in the original call to <code>bivariate.density()</code>.</p></li>
</ol>
</div>
</div>
</div>
<div id="creating-relative-risk-surface-manually" class="section level3" number="7.3.6">
<h3>
<span class="header-section-number">7.3.6</span> Creating relative risk surface manually<a class="anchor" aria-label="anchor" href="#creating-relative-risk-surface-manually"><i class="fas fa-link"></i></a>
</h3>
<p>Up until now, we have only created the KDE surface for the <em>death</em> and <em>birth</em> points separately. But for epidemiology, we rarely care about numerator and denominator separately! So how do we put these two together into a more informative disease map?</p>
<p><em>Raster algebra</em> is a term for arithmetic and algebraic manipulation of raster grids. Recall that a <em>raster</em> data set is simply a array of numbers. The numbered value of each grid-point represents the mean density or intensity of points per unit-area, and is mapped as color to make the plot.</p>
<p>Because it is simply a matrix of numbers, we can take two rasters of the same resolution and study area and add, subtract, multiply, log-transform, or otherwise operate on them arithmetically.</p>
<p>For instance to manually create <em>spatial relative risk surface</em> we simply take the ratio of two <em>KDE density surfaces</em>. The result is a relative measure akin to the SMR: it quantifies the relative deviation of each area from an overall average value. So values below 1 are areas with <em>lower than average risk</em>, meaning that the intensity of <em>deaths</em> is less than the intensity of <em>live births</em>, and values above 1 have <em>higher than average risk</em> (the intensity of <em>deaths</em> is greater than the intensity of <em>live births</em>).</p>
<div class="rmdcaution">
<p><strong>Intensity vs Density matters for taking a ratio</strong></p>
<p>For interpreting the <em>ratio of two kernel surfaces</em> take care to distinguish between the <strong>spatial intensity</strong> (number of point events per unit area; the value integrates or sums to the total number of points across the study region) versus the <strong>spatial density</strong> (probability of a point event occurring at this location, conditional on total number of points; integrates to 1 across the study region). The distinction is important.</p>
<p>The default output of <code>bivariate.density()</code> function is a <em>spatial density surface</em>. The ratio of two density (probability) surfaces will take the value of 1.0 when the probability of a death at that location is proportionate to the probability of a birth at that location.</p>
<p>In contrast the ratio of two <em>intensity surfaces</em> is interpreted as an absolute measure (e.g. risk, rate, prevalence) ranging from zero to 1. If you choose <code>intensity = TRUE</code> when specifying the <code>bivariate.density()</code> function you will get the intensity rather than (default) density surface.</p>
</div>
<p>In the <code>tmap</code> call I <em>flipped</em> the color ramp by using the negative sign in front of the name of the ramp. I also specified a continuous style rather than discrete (e.g. <code>quantile</code>), and specified some legend breaks.</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Create risk surface as ratio of death density to birth density</span>
<span class="va">risk</span> <span class="op">&lt;-</span> <span class="va">death_kde_raster</span> <span class="op">/</span> <span class="va">birth_kde_raster</span>

<span class="co"># Map it...</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">risk</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">'-RdYlGn'</span>,
            style <span class="op">=</span> <span class="st">'cont'</span>,
            breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>, <span class="fl">0.6</span>, <span class="fl">0.9</span>,   <span class="fl">1.1</span>, <span class="fl">2</span>, <span class="fl">4.9</span><span class="op">)</span>,
            title <span class="op">=</span> <span class="st">'IMR SMR'</span><span class="op">)</span>  <span class="op">+</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">county</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-24-1.png" width="672"></div>
<p>Now we can more clearly see regions of <em>higher risk</em> and <em>lower risk</em> of infant mortality!</p>
</div>
<div id="creating-relative-risk-surface-with-risk-function" class="section level3" number="7.3.7">
<h3>
<span class="header-section-number">7.3.7</span> Creating relative risk surface with <code>risk()</code> function<a class="anchor" aria-label="anchor" href="#creating-relative-risk-surface-with-risk-function"><i class="fas fa-link"></i></a>
</h3>
<p>The preceding <em>manual</em> approach created two separate kernel density surfaces, and then manually relied on raster algebra to create the spatial relative risk surface. This is useful to know because you may use KDE in other setting where you only work with a single spatial point process (e.g. imagine that instead of estimating disease intensity, you wish to estimate an <em>exposure</em> density surface).</p>
<p>However, the <code>sparr</code> package provides a shortcut for estimation of spatial relative risk surfaces in the function <code>risk()</code>. It takes a numerator and denominator <code>ppp</code> object as arguments and calculates the spatial relative risk surface automatically.</p>
<p>As a demonstration of comparing four pre-defined (possibly theoretically informed, or possibly arbitrary), fixed bandwidths for the purposes of data exploration, below we estimate four distinct spatial relative risk surfaces, as well as one adaptive KDE. In each case notice the first two arguments are the numerator and denominator <code>ppp</code> object. The next argument is a pre-specified fixed bandwidth (e.g. 1000, 2000, 4000, and 8000 meters).</p>
<p>This function also illustrates another <em>feature</em> which allows us to quantify statistical precision by creating <em>tolerance contours</em>. Tolerance contours are simply lines which encircle regions that are statistically significant beyond a given threshold. The argument <code>tolerate = T</code> tells the function to estimate <em>asymptotic</em> p-values testing the null hypothesis that the local relative risk of death is equal across the study region.</p>
<p>By default, the function estimates the <em>log relative risk</em>, which is a helpful reminder that the <em>relative risk</em> is asymmetric. However, we understand ratio measures, and will be careful to plot the results appropriately. For that reason, I set <code>log = FALSE</code>, although obviously you could omit that and keep everything on the <code>log</code> scale.</p>
<p><strong>NOTE:</strong> The <em>fixed bandwidth</em> <code>risk()</code> functions will run quickly, but once again, the <em>adaptive bandwidth</em> is more computationally intensive, and will take longer.</p>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">imr1000</span> <span class="op">&lt;-</span> <span class="fu">risk</span><span class="op">(</span><span class="va">d_ppp</span>, <span class="va">b_ppp</span>, h0 <span class="op">=</span> <span class="fl">1000</span>, 
            tolerate <span class="op">=</span> <span class="cn">T</span>,
            verbose <span class="op">=</span> <span class="cn">F</span>, 
            log <span class="op">=</span> <span class="cn">F</span>,
            edge <span class="op">=</span> <span class="st">'diggle'</span><span class="op">)</span>

<span class="va">imr2000</span> <span class="op">&lt;-</span> <span class="fu">risk</span><span class="op">(</span><span class="va">d_ppp</span>, <span class="va">b_ppp</span>, h0 <span class="op">=</span> <span class="fl">2000</span>, 
            tolerate <span class="op">=</span> <span class="cn">T</span>,
            log <span class="op">=</span> <span class="cn">F</span>,
            edge <span class="op">=</span> <span class="st">'diggle'</span>,
            verbose <span class="op">=</span> <span class="cn">F</span><span class="op">)</span>

<span class="va">imr4000</span> <span class="op">&lt;-</span> <span class="fu">risk</span><span class="op">(</span><span class="va">d_ppp</span>, <span class="va">b_ppp</span>, h0 <span class="op">=</span> <span class="fl">4000</span>, 
            tolerate <span class="op">=</span> <span class="cn">T</span>,
            log <span class="op">=</span> <span class="cn">F</span>,
            edge <span class="op">=</span> <span class="st">'diggle'</span>,
            verbose <span class="op">=</span> <span class="cn">F</span><span class="op">)</span>

<span class="va">imr8000</span> <span class="op">&lt;-</span> <span class="fu">risk</span><span class="op">(</span><span class="va">d_ppp</span>, <span class="va">b_ppp</span>, h0 <span class="op">=</span> <span class="fl">8000</span>, 
            tolerate <span class="op">=</span> <span class="cn">T</span>,
            log <span class="op">=</span> <span class="cn">F</span>,
            edge <span class="op">=</span> <span class="st">'diggle'</span>,
            verbose <span class="op">=</span> <span class="cn">F</span><span class="op">)</span>

<span class="va">imradapt</span> <span class="op">&lt;-</span> <span class="fu">risk</span><span class="op">(</span><span class="va">d_ppp</span>, <span class="va">b_ppp</span>, 
                 h0 <span class="op">=</span> <span class="va">h_os_d</span>, 
                 adapt <span class="op">=</span> <span class="cn">T</span>, 
                 tolerate <span class="op">=</span> <span class="cn">T</span>,
                 log <span class="op">=</span> <span class="cn">F</span>,
                 edge <span class="op">=</span> <span class="st">'diggle'</span>,
                 verbose <span class="op">=</span> <span class="cn">F</span><span class="op">)</span></code></pre></div>
<p>Examine the contents of one of these objects. The summary show us the range of the estimated risk, the resolution of the evaluation grid, and the number of points evaluated.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">imr1000</span><span class="op">)</span></code></pre></div>
<pre><code>## Log-Relative Risk Function.
## 
## Estimated risk range [-8.216873e-14, 11.05946]
## 
## --Numerator (case) density--
## Bivariate Kernel Density/Intensity Estimate
## 
## Bandwidth
##   Fixed smoothing with h0 = 1000 units (to 4 d.p.)
## 
## No. of observations
##   701 
## 
## Spatial bound
##   Type: polygonal
##   2D enclosure: [1026366, 1098719] x [1220671, 1302019]
## 
## Evaluation
##   128 x 128 rectangular grid
##   5808 grid cells out of 16384 fall inside study region
##   Density/intensity range [-1.82875e-25, 2.78467e-09]
## 
## --Denominator (control) density--
## Bivariate Kernel Density/Intensity Estimate
## 
## Bandwidth
##   Fixed smoothing with h0 = 1000 units (to 4 d.p.)
## 
## No. of observations
##   94373 
## 
## Spatial bound
##   Type: polygonal
##   2D enclosure: [1026366, 1098719] x [1220671, 1302019]
## 
## Evaluation
##   128 x 128 rectangular grid
##   5808 grid cells out of 16384 fall inside study region
##   Density/intensity range [2.143127e-16, 2.383589e-09]</code></pre>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">imr1000</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "rr" "f"  "g"  "P"</code></pre>
<div class="rmdcaution">
<p><strong>NOTICE</strong></p>
<p>You can see that the range of the estimated risk is <span class="math inline">\([-8.216873e-14, 11.05946]\)</span>. The lower bound is in practical terms zero (e.g. it is very, very small), but counter-intuitively it is also <em>negative</em>! How could we estimated <em>negative risk</em>? The answer seems to be related to the Diggle edge correction. For example if you substitute <code>edge = 'uniform'</code> the anomaly goes away. This is likely because edge correction (which in the big picture is a valuable strategy) reweights regions and may result in specific location estimates that become negative.</p>
</div>
<p>Once again, we can use built-in plotting functionality from <code>sparr</code> to produce maps of the <em>spatial relative risk surface</em> and the tolerance contours. (NOTE: the default legend works best for <em>log relative risk</em>, but doesn’t behave well for the <em>relative risk</em> because it treats the distance from 0 to 1 as the same as the distance from 1 to 2, or 4 to 5).</p>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="co"># adjust the plotting margins</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>   <span class="co"># Plot 3 rows and 2 columns</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">imr1000</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">imr2000</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">imr4000</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">imr8000</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">imradapt</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>  <span class="co"># reset the plot space to 1 row, 1 col</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-28-1.png" width="672"></div>
<p>While the code above plots these side-by-side, you might find it easier to plot them one at a time and zoom in closer.</p>
<div class="rmdnote">
<p><strong>Things to notice in above plots</strong>:</p>
<ol style="list-style-type: decimal">
<li>Notice the contour lines for <span class="math inline">\(p&lt;0.05\)</span>.<br>
</li>
<li>Notice how the risk surface becomes smoother as the fixed bandwidth transitions from <span class="math inline">\(1km\)</span> to <span class="math inline">\(8km\)</span>.</li>
<li>Finally, notice how the <em>adaptive</em> bandwidth is consistent with the other maps, but seems to balance the detail between the 2000 meter and 4000 meter definitions.</li>
</ol>
</div>
</div>
<div id="using-functions-to-map-rr-with-tmap" class="section level3" number="7.3.8">
<h3>
<span class="header-section-number">7.3.8</span> Using functions to map RR with <code>tmap</code><a class="anchor" aria-label="anchor" href="#using-functions-to-map-rr-with-tmap"><i class="fas fa-link"></i></a>
</h3>
<p>When we begin plotting several maps, the conversion from the <code>im</code> to <code>raster</code> and the code for producing map panels can feel cumbersome. While the following section is not required, it is a demonstration of how you can write simple custom functions in <code>R</code> to speed up repetitive tasks.</p>
<p>A function in <code>R</code> is like a macro in SAS; it is simply a set of instructions that accepts <em>arguments</em> (inputs), carries out some action on those inputs, and then <em>returns</em> some output. Thus, it helps automate cumbersome tasks so you can do them repeatedly and efficiently.</p>
<p>Below is a function that accepts a single <em>argument</em>, labeled simply <code>x</code> here. The expectation is that <code>x</code> should be the output from one of the preceding calls to the <code>risk()</code> function.</p>
<p>Notice how the function first extracts the spatial relative risk surface (e.g. <code>x$rr</code>), and then assigns the appropriate projection (it got stripped off some where along the way).</p>
<p>Then the function extracts the <em>probability map</em> which is the set of pixel-specific p-values. The <code>rasterToContour()</code> function takes this raster and creates contour lines with the specified levels corresponding to a 95% tolerance contour. Finally, the use of the <code><a href="https://rdrr.io/r/base/function.html">return()</a></code> tells what should be returned when the function is called.</p>
<p>Once you write a function, it need only be loaded once in a given session; afterwords you can <em>call</em> it by using <code>prepRaster(x = my_risk_object)</code>.</p>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">### --- prepRaster() function --- ###</span>
<span class="va">prepRaster</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span>
  <span class="va">rr</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="va">rr</span>,
               crs <span class="op">=</span> <span class="st">"+init=epsg:5070"</span><span class="op">)</span>

  <span class="va">p_raster</span> <span class="op">&lt;-</span> <span class="fu">raster</span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="va">P</span>,
               crs <span class="op">=</span> <span class="st">"+init=epsg:5070"</span><span class="op">)</span>
  <span class="va">plines</span> <span class="op">&lt;-</span> <span class="fu">rasterToContour</span><span class="op">(</span><span class="va">p_raster</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>,  <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span>
  
  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>rr<span class="op">=</span><span class="va">rr</span>,plines<span class="op">=</span><span class="va">plines</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span> <span class="co">## END prepRaster() ##</span></code></pre></div>
<p>While we’re on a roll, we could also write a function for producing a <code>tmap</code> panel:</p>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">### --- make_map() function to create panel maps --- ###</span>
<span class="va">make_map</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">bw</span><span class="op">)</span><span class="op">{</span>
  <span class="va">mtitle</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">'IMR - '</span>, <span class="va">bw</span>, <span class="st">' smooth'</span>, sep <span class="op">=</span> <span class="st">''</span><span class="op">)</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="va">rr</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">'-RdYlGn'</span>,
            style <span class="op">=</span> <span class="st">'cont'</span>,
            breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>, <span class="fl">0.6</span>, <span class="fl">0.9</span>,   <span class="fl">1.1</span>, <span class="fl">2</span>, <span class="fl">4.9</span><span class="op">)</span>,
            midpoint <span class="op">=</span> <span class="cn">NA</span>,
            title <span class="op">=</span> <span class="st">'IMR SMR'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">x</span><span class="op">$</span><span class="va">plines</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_lines.html">tm_lines</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">'level'</span>,
           legend.col.show <span class="op">=</span> <span class="cn">F</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>main.title <span class="op">=</span> <span class="va">mtitle</span>,
            legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> 
<span class="op">}</span> <span class="co">## END make_map() function ##</span></code></pre></div>
<p>The result of this work is that we can easily (and more compactly), map the four fixed-bandwidth spatial relative risk surfaces.</p>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># First convert to raster and extract p-value contours</span>
<span class="va">rr_1000</span> <span class="op">&lt;-</span> <span class="fu">prepRaster</span><span class="op">(</span><span class="va">imr1000</span><span class="op">)</span>
<span class="va">rr_2000</span> <span class="op">&lt;-</span> <span class="fu">prepRaster</span><span class="op">(</span><span class="va">imr2000</span><span class="op">)</span>
<span class="va">rr_4000</span> <span class="op">&lt;-</span> <span class="fu">prepRaster</span><span class="op">(</span><span class="va">imr4000</span><span class="op">)</span>
<span class="va">rr_8000</span> <span class="op">&lt;-</span> <span class="fu">prepRaster</span><span class="op">(</span><span class="va">imr8000</span><span class="op">)</span>
<span class="va">rr_adapt</span> <span class="op">&lt;-</span> <span class="fu">prepRaster</span><span class="op">(</span><span class="va">imradapt</span><span class="op">)</span>

<span class="co"># Then produce map panels</span>
<span class="va">m1000</span> <span class="op">&lt;-</span> <span class="fu">make_map</span><span class="op">(</span><span class="va">rr_1000</span>, <span class="st">'1 km'</span><span class="op">)</span>
<span class="va">m2000</span> <span class="op">&lt;-</span> <span class="fu">make_map</span><span class="op">(</span><span class="va">rr_2000</span>, <span class="st">'2 km'</span><span class="op">)</span>
<span class="va">m4000</span> <span class="op">&lt;-</span> <span class="fu">make_map</span><span class="op">(</span><span class="va">rr_4000</span>, <span class="st">'4 km'</span><span class="op">)</span>
<span class="va">m8000</span> <span class="op">&lt;-</span> <span class="fu">make_map</span><span class="op">(</span><span class="va">rr_8000</span>, <span class="st">'8 km'</span><span class="op">)</span>
<span class="va">mapadapt</span> <span class="op">&lt;-</span> <span class="fu">make_map</span><span class="op">(</span><span class="va">rr_adapt</span>, <span class="st">'adaptive'</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">m1000</span>, <span class="va">m2000</span>, <span class="va">m4000</span>, <span class="va">m8000</span>,<span class="va">mapadapt</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-31-1.png" width="672"></div>
</div>
</div>
<div id="gwss" class="section level2" number="7.4">
<h2>
<span class="header-section-number">7.4</span> Spatial Analysis in Epidemiology: Kernel estimation of areal data<a class="anchor" aria-label="anchor" href="#gwss"><i class="fas fa-link"></i></a>
</h2>
<p>In the preceding section we saw how to use KDE for estimating a smooth <em>spatial intensity surface</em> from a spatial point process. In this section we introduce <em>geographically-weighted</em> statistics that are extendable to areal units and not only points. There were three key features about the use of KDE from the preceding section that we will expand on here:</p>
<ol style="list-style-type: decimal">
<li>
<em>KDE are not only for points</em> - while the whole notion of the kernel density estimation process is indeed connected to the <span class="math inline">\(x,y\)</span> point location, this does not mean we cannot take advantage of the non-parametric smoothing for other kinds of data, such as polygons. Typically the centroid (geometric center) of a polygon is used as the stand-in for point when KDE is done with polygons.</li>
<li>
<em>KDE is not only for binary values</em> - a spatial point process is by definition the description of the location of discrete points representing a discrete state. For instance in section above, we visualized the spatial intensity surface of infant deaths, and separately the surface of live births. But what if we want to measure a <em>continuous value</em> rather than a discrete, binary state at spatial locations? The mechanics of KDE can still be helpful!</li>
<li>
<em>KDE is a kind of spatial weighting procedure</em> - this was true in Part A as well…the <em>spatial intensity</em> is essentially the spatially-weighted number of points surrounding an index location divided by the area under the kernel function. In this lab the primary use of the kernel function is to produce weights for calculating weighted-statistics including <em>mean</em>, <em>median</em>, etc of any quantity that is measured.</li>
</ol>
<p>To accomplish these extensions we will use functions in the package <code>GWmodel</code> (e.g. <em>geographically weighted models</em>) that are very useful for exploratory spatial data analysis. The main function used here, <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code>, stands for <em>geographically weighted summary statistics</em>, and uses the non-parametric spatial weighting of a kernel density function to compute <em>locally varying descriptive statistics</em> such as the <em>mean</em>, <em>median</em>, <em>standard deviation</em>, <em>correlation</em>, and more. And while it certainly works for data represented as <span class="math inline">\(x,y\)</span> points, it can also work for polygon data.</p>
<p>What this means is that the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> function can be useful for exploring spatial heterogeneity as a form of <em>local spatial non-stationarity</em>. Recall that <em>spatial stationarity</em> is the notion that a statistical parameter is <em>global</em> or <em>constant</em> across space?</p>
<p>We previously encountered <em>stationarity</em> as the opposite of <em>spatial heterogeneity</em>. In that context we were referring to the <em>risk</em> or <em>prevalence</em> of health states. But <strong>any statistic</strong> can be <em>stationary</em> (constant) or <em>non-stationary</em> (spatially varying).</p>
<p>The objective of this section is to extend our understanding of the utility of <em>kernel density functions</em> beyond simply computing <em>intensity</em> or <em>density</em> surfaces to seeing them as a tool for creating <em>spatially local weights</em> for any statistical function. We will use the same study region (Fulton and Dekalb counties), but now will be looking at several socio-contextual <em>covariates</em> derived from the American Community Survey to be considered along with the infant mortality rate produced above.</p>
<p>This section focuses primarily on the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> function to accomplish the following tasks:</p>
<ul>
<li>Estimate a statistically-optimal <em>fixed bandwidth</em> and explore <em>adaptive bandwidths</em> for use with the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> function</li>
<li>Calculate local, spatially-weighted <em>mean</em>, <em>median</em>, <em>SD</em>, and <em>IQR</em> for four census-tract level continuous measures using kernel density functions</li>
<li>Using Monte Carlo simulation to produces significance contours on our estimates of local, spatially-weighted summary statistics</li>
<li>Calculate local, spatially-weighted <em>bivariate statistics</em> summarizing how the correlations (Pearson and Spearman) of pairs of variables varies through space</li>
</ul>
<div id="packages-and-data" class="section level3" number="7.4.1">
<h3>
<span class="header-section-number">7.4.1</span> Packages and data<a class="anchor" aria-label="anchor" href="#packages-and-data"><i class="fas fa-link"></i></a>
</h3>
<p>The new package introduced here is <code>GWmodel</code>, but several other familiar packages will also be useful:</p>
<div class="sourceCode" id="cb148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># For data piping and manipulationlibrary(GWmodel)   # Has the function gwss() </span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span>        <span class="co"># For import of sf data</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/edzer/sp/">sp</a></span><span class="op">)</span>        <span class="co"># For conversion to sp, required for GWmodel</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mtennekes/tmap">tmap</a></span><span class="op">)</span>      <span class="co"># For mapping</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://gwr.nuim.ie/">GWmodel</a></span><span class="op">)</span>   <span class="co"># Geographically weighted statistics</span></code></pre></div>
<p>The methods introduced in this section will work for either <em>spatial points</em> or <em>spatial polygons</em>. However for this example we will demonstrate their use specifically for <em>spatial polygons</em>, and more specifically polygons representing the census tracts in Fulton and Dekalb counties. This dataset has 345 census tract polygons (4 tracts were deleted due to missing values), and summarizes five summary measures of each tract:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="33%">
<col width="66%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>GEOID</code></td>
<td>Unique ID for each census tract unit</td>
</tr>
<tr class="even">
<td><code>pctNOHS</code></td>
<td>% of adults over 25 without a high school diploma or GED</td>
</tr>
<tr class="odd">
<td><code>pctPOV</code></td>
<td>% of the population living below the federal poverty line</td>
</tr>
<tr class="even">
<td><code>ICE_INCOME_all</code></td>
<td>Index of Concentration at the Extremes, which is an index of the concentration of poverty and affluence. It ranges from -1 (concentrated poverty) to +1 (concentrated affluence), with values near zero having equal income distribution</td>
</tr>
<tr class="odd">
<td><code>pctMOVE</code></td>
<td>% of households who moved in the past 12 months</td>
</tr>
<tr class="even">
<td><code>pctOWNDER_OCC</code></td>
<td>% of households occupied by owners (e.g. rather than renters)</td>
</tr>
</tbody>
</table></div>
<p>First, we read in the <code>gpkg</code> data as an <code>sf</code> object, and then convert it to <code>sp</code> for use with <code>GWmodel</code>. As with the <code>sparr</code> package, <code>GWmodel</code> is not yet fully <code>sf</code> compliant so we are forced to use <code>sp</code> data classes. This will likely change at some point in the future.</p>
<div class="sourceCode" id="cb149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># This is Dekalb/Fulton census tracts</span>
<span class="va">atl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">'Fulton-Dekalb-covariates.gpkg'</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/coerce-methods.html">as</a></span><span class="op">(</span><span class="st">'Spatial'</span><span class="op">)</span> <span class="co"># convert to sp class</span></code></pre></div>
<div id="mapping-the-observed-values" class="section level4" number="7.4.1.1">
<h4>
<span class="header-section-number">7.4.1.1</span> Mapping the observed values<a class="anchor" aria-label="anchor" href="#mapping-the-observed-values"><i class="fas fa-link"></i></a>
</h4>
<p>To understand the new data, consider using <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, or other exploratory functions, as well as producing some simple maps to see the spatial distribution of these variables. <em>Recall that the <code>tmap</code> package works for both <code>sf</code> and <code>sp</code> data!</em> This means that we can map the object in the <em>‘usual manner’</em> even though we converted it to <code>sp</code>.</p>
<div class="sourceCode" id="cb150"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># First map the 4 variables that are %</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctNOHS'</span>, <span class="st">'pctPOV'</span>, <span class="st">'pctMOVE'</span>, <span class="st">'pctOWNER_OCC'</span><span class="op">)</span>,
          style <span class="op">=</span> <span class="st">'quantile'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-35-1.png" width="672"></div>
<p>The <em>Index of Concentration at the Extremes (ICE)</em> ranges from -1 to +1. A value of <span class="math inline">\(-1\)</span> occurs where everyone in the tract is poor; a value of <span class="math inline">\(+1\)</span> occurs in tracts where everyone is affluent; a value of <span class="math inline">\(0\)</span> suggests that either there is a balance of affluence and poverty, or alternatively that everyone is ‘<em>middle income</em>.’ Therefore it makes sense to map it separately because it will inevitably need a <em>divergent</em> color ramp.</p>
<div class="sourceCode" id="cb151"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'ICE_INCOME_all'</span>,
          style <span class="op">=</span> <span class="st">'quantile'</span>,
          palette <span class="op">=</span> <span class="st">'div'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-36-1.png" width="672"></div>
</div>
<div id="why-are-we-using-kde-on-these-data" class="section level4" number="7.4.1.2">
<h4>
<span class="header-section-number">7.4.1.2</span> Why are we using KDE on these data?<a class="anchor" aria-label="anchor" href="#why-are-we-using-kde-on-these-data"><i class="fas fa-link"></i></a>
</h4>
<p>There could be at least two general reasons you might think to use a spatial smoothing approach such as KDE for continuous data such as these:</p>
<ol style="list-style-type: decimal">
<li>You believe the estimates at each for each spatial unit (polygons in this case, but could be points) are statistically unstable, and you believe that averaging them with their neighbors will produce a more reliable estimate of the parameter of interest; or</li>
<li>You are interested in identifying spatial patterns or trends that are possibly <em>larger scale</em> than the data units themselves. For instance you might be looking for regions of the city where there is apparent clustering of poverty, home ownership, or residential instability. In other words you suspect that people are not only exposed to values within the boundaries of their tracts, but also to nearby environments.</li>
</ol>
</div>
</div>
<div id="what-bandwidth-for-kernel-density-estimates" class="section level3" number="7.4.2">
<h3>
<span class="header-section-number">7.4.2</span> What bandwidth for kernel density estimates?<a class="anchor" aria-label="anchor" href="#what-bandwidth-for-kernel-density-estimates"><i class="fas fa-link"></i></a>
</h3>
<p>Recall that the decision about the <em>bandwidth</em> of the kernel density function is one of the most influential to in using KDE for spatial epidemiology. The reason is because the <em>bandwidth</em> defines the <em>smoothness</em> or <em>bumpiness</em> of the statistical estimation, and different choices can produce dramatically different results.</p>
<p>Once again, we might have theoretically important criteria for selecting a bandwidth, or we could use a statistical optimization approach. In <code>GWmodel</code> the function <code><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwss.average.html">bw.gwss.average()</a></code> is used for estimating the <em>‘optimal’</em> bandwidth for estimating the spatially varying <em>mean</em> or <em>median</em> using cross-validation. There is no specific function for other statistics (e.g. the <em>SD</em>, <em>IQR</em>, or <em>correlation coefficients</em>). Because the spatial structure might be different for each variable, we can evaluate all variables:</p>
<div class="sourceCode" id="cb152"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Fixed bandwidth selection</span>
<span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwss.average.html">bw.gwss.average</a></span><span class="op">(</span><span class="va">atl</span>, vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV'</span>, <span class="st">'pctPOV'</span>, <span class="st">'pctMOVE'</span>, 
                              <span class="st">'pctOWNER_OCC'</span>, <span class="st">'ICE_INCOME_all'</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##                   pctPOV   pctPOV  pctMOVE pctOWNER_OCC ICE_INCOME_all
## Local Mean bw   58801.33 58801.33 58801.33     65740.07       65740.07
## Local Median bw 65740.07 65740.07 58801.33     70028.45       65353.39</code></pre>
<p>These numbers are in the units of the map, which are meters. This suggests that the we need a pretty large fixed bandwidth (between 58 and 70 km!), at least to minimize the error as determined from the cross-validation approach.</p>
<div class="rmdnote">
<p><strong>Adaptive bandwidth in <code>GWmodel</code></strong></p>
<p>Adaptive bandwidth in <code>GWmodel</code> works a little differently from how it did in the <code>sparr</code> package. When we choose <code>adaptive = TRUE</code> what is returned is not a distance in the units of the map (e.g. meters) but instead is <em>a number of nearest neighbors</em> that defines how large or small the kernel function <em>adapts</em>.</p>
<p>This is important conceptually for what <em>adaptation</em> means: in <code>GWmodel</code> the unit of analysis is the census tract, not the individual person. So a census tract with 10 people and a census tract with 10,000 are assumed to have the same amount of information.</p>
</div>
<div class="sourceCode" id="cb154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Adapative bandwidth selection</span>
<span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwss.average.html">bw.gwss.average</a></span><span class="op">(</span><span class="va">atl</span>, vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV'</span>, <span class="st">'pctNOHS'</span>, <span class="st">'pctMOVE'</span>, 
                              <span class="st">'pctOWNER_OCC'</span>, <span class="st">'ICE_INCOME_all'</span><span class="op">)</span>,
                adaptive <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></code></pre></div>
<pre><code>##                 pctPOV pctNOHS pctMOVE pctOWNER_OCC ICE_INCOME_all
## Local Mean bw      315     268     297          337            333
## Local Median bw    297     297     315          326            315</code></pre>
<pre><code>##                 pctPOV pctNOHS pctMOVE pctOWNER_OCC ICE_INCOME_all
## Local Mean bw      315     268     297          337            333
## Local Median bw    297     297     315          326            315</code></pre>
<p>Again, we see the same story that the CV approach suggests a very large bandwidth. There are only 345 areal units in this dataset, and this suggests that <em>nearly all of them</em> should be included in the kernel. That would produce very little spatial variation. While the idea of a statistical optimization approach is appealing, as we discussed above, the CV methods is known to be imperfect.</p>
<p>For now we will use a more common-sense approach. It would seem that we might balance local information and spatial variation by including no more than 10% of the data in any single kernel density estimation location. So we could choose to use <span class="math inline">\(n=35\)</span> neighbors as the definition of our <em>adaptive bandwidth</em>. Note that you could alter this number to see how the results vary.</p>
</div>
<div id="geographically-weighted-summary-statistics-gwss" class="section level3" number="7.4.3">
<h3>
<span class="header-section-number">7.4.3</span> Geographically weighted summary statistics: <code>gwss()</code><a class="anchor" aria-label="anchor" href="#geographically-weighted-summary-statistics-gwss"><i class="fas fa-link"></i></a>
</h3>
<p>To more fully describe and explore our <em>‘raw’</em> data, we want to summarize it by smoothing out extremes, and looking for broad spatial trends in the values. Finding a <em>local average value</em> can be done using either a <em>mean</em> or <em>median</em> to quantify <em>central tendency</em>. Obviously, if the distribution of the data within local regions is relatively normally distributed (or at least symmetric), the <em>mean</em> and <em>median</em> will be similar. But if the data are quite skewed, we might prefer the <em>median</em> as a summary measures.</p>
<p>Similarly, knowing whether (or how much) local measures are <em>alike</em> or <em>different</em> is informative. Once again we could choose a statistic that works well to describe variation for normally-distributed (or symmetric) data (e.g. the <em>standard deviation</em>), or one that performs well with non-normal or skewed data (e.g. the <em>inter-quartile range</em>). Finding <em>large values</em> of either the <em>SD</em> or <em>IQR</em> would suggest substantial <em>local heterogeneity</em> or difference in the target measure, whereas small values would suggest that local areas are relatively similar.</p>
<p>The <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> function actually estimates more than just those listed above, but for now we will only focus on those measures.</p>
<p>To calculate the <em>geographically-weighted summary statistics</em> using <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> we need to provide a dataset, a single variable (or vector of multiple variables), a decision about using <em>fixed</em> or <em>adaptive</em> bandwidth, and finally a specification of <code>bw</code> or bandwidth itself. And once again, the value you enter for <code>bw</code> depends on whether you select <code>adaptive = T</code> or not.</p>
<p>If <em>fixed</em> bandwidth, the value you enter is a number in the units of the map (e.g. <em>meters</em> in our case). But if you are requesting an <em>adaptive</em> bandwidth, the value for <code>bw</code> is not in <em>meters</em>, but is actually a number or <em>count</em> of how many nearest neighbors should minimally be included in the kernel density estimation at each location. As discussed above, I will use <span class="math inline">\(n=35\)</span> as an adaptive definition of neighbors. This will result in each summary estimation including approximately 10% of the total data. Because we would like what are called <em>robust</em> statistics (e.g. the <em>median</em> and <em>IQR</em> which are robust to skewed or non-normal data), we also must specify the argument <code>quantile = T</code>.</p>
<div class="sourceCode" id="cb157"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">atl.ss</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss</a></span><span class="op">(</span><span class="va">atl</span>, vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV'</span>, <span class="st">'pctNOHS'</span>, <span class="st">'pctMOVE'</span>, <span class="st">'pctOWNER_OCC'</span>,
                             <span class="st">'ICE_INCOME_all'</span><span class="op">)</span>,
               adaptive <span class="op">=</span> <span class="cn">T</span>,
               bw <span class="op">=</span> <span class="fl">35</span>,
               quantile <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></code></pre></div>
<p>Perhaps unintuitively, the way to get a summary of the result is not the usual <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>, but instead to type <code><a href="https://rdrr.io/r/base/print.html">print(atl.ss)</a></code>. When you do so you will see A LOT of results. We will focus for the moment on just the results at the very top (local mean; local SD) and at the very bottom (local median; local IQR) of the output.</p>
<div class="sourceCode" id="cb158"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">)</span></code></pre></div>
<pre><code>##    ***********************************************************************
##    *                       Package   GWmodel                             *
##    ***********************************************************************
## 
##    ***********************Calibration information*************************
## 
##    Local summary statistics calculated for variables:
##     pctPOV pctNOHS pctMOVE pctOWNER_OCC ICE_INCOME_all
##    Number of summary points: 345
##    Kernel function: bisquare 
##    Summary points: the same locations as observations are used.
##    Adaptive bandwidth: 35 (number of nearest neighbours)
##    Distance metric: Euclidean distance metric is used.
## 
##    ************************Local Summary Statistics:**********************
##    Summary information for Local means:
##                           Min.   1st Qu.    Median   3rd Qu.   Max.
##    pctPOV_LM          0.050645  0.119765  0.180836  0.270868 0.3947
##    pctNOHS_LM         0.011338  0.031796  0.051985  0.079042 0.1369
##    pctMOVE_LM         0.129222  0.166627  0.185688  0.215939 0.3356
##    pctOWNER_OCC_LM    0.214225  0.421030  0.486894  0.568339 0.7545
##    ICE_INCOME_all_LM -0.363659 -0.161687 -0.010174  0.180475 0.3921
##    Summary information for local standard deviation :
##                           Min.  1st Qu.   Median  3rd Qu.   Max.
##    pctPOV_LSD         0.030466 0.080964 0.095033 0.122989 0.2000
##    pctNOHS_LSD        0.013018 0.027740 0.038529 0.055891 0.1512
##    pctMOVE_LSD        0.043404 0.062143 0.070973 0.085519 0.1594
##    pctOWNER_OCC_LSD   0.128460 0.171147 0.193042 0.236043 0.3127
##    ICE_INCOME_all_LSD 0.098726 0.153791 0.186239 0.214184 0.2949
##    Summary information for local variance :
##                              Min.    1st Qu.     Median    3rd Qu.   Max.
##    pctPOV_LVar         0.00092817 0.00655511 0.00903123 0.01512619 0.0400
##    pctNOHS_LVar        0.00016947 0.00076952 0.00148449 0.00312385 0.0229
##    pctMOVE_LVar        0.00188388 0.00386175 0.00503717 0.00731354 0.0254
##    pctOWNER_OCC_LVar   0.01650192 0.02929137 0.03726506 0.05571613 0.0978
##    ICE_INCOME_all_LVar 0.00974689 0.02365154 0.03468479 0.04587486 0.0870
##    Summary information for Local skewness:
##                            Min.  1st Qu.   Median  3rd Qu.   Max.
##    pctPOV_LSKe         -0.60296  0.40145  0.88760  1.50706 4.5718
##    pctNOHS_LSKe        -0.26353  0.80588  1.38779  2.41449 7.7612
##    pctMOVE_LSKe        -0.43164  0.27893  0.58307  0.97433 2.6409
##    pctOWNER_OCC_LSKe   -1.21089 -0.41080 -0.10531  0.17408 1.1014
##    ICE_INCOME_all_LSKe -1.03050 -0.18046  0.17660  0.55386 1.8477
##    Summary information for localized coefficient of variation:
##                             Min.    1st Qu.     Median    3rd Qu.    Max.
##    pctPOV_LCV            0.21281    0.41550    0.57740    0.73493  1.1784
##    pctNOHS_LCV           0.31989    0.49239    0.85060    1.30476  2.2432
##    pctMOVE_LCV           0.23460    0.35345    0.38736    0.42998  0.6638
##    pctOWNER_OCC_LCV      0.20111    0.35046    0.42753    0.51556  0.7493
##    ICE_INCOME_all_LCV -127.78594   -1.02921   -0.35211    1.03900 94.7817
##    Summary information for localized Covariance and Correlation between these variables:
##                                                     Min.      1st Qu.
##    Cov_pctPOV.pctNOHS                       -0.002293092  0.000901241
##    Cov_pctPOV.pctMOVE                       -0.002989390  0.000907888
##    Cov_pctPOV.pctOWNER_OCC                  -0.039119689 -0.020228990
##    Cov_pctPOV.ICE_INCOME_all                -0.054587425 -0.021777955
##    Cov_pctNOHS.pctMOVE                      -0.006067192  0.000036009
##    Cov_pctNOHS.pctOWNER_OCC                 -0.028576009 -0.005198261
##    Cov_pctNOHS.ICE_INCOME_all               -0.027722207 -0.005410855
##    Cov_pctMOVE.pctOWNER_OCC                 -0.026758619 -0.012236511
##    Cov_pctMOVE.ICE_INCOME_all               -0.017867269 -0.008467689
##    Cov_pctOWNER_OCC.ICE_INCOME_all           0.007196400  0.020528232
##    Corr_pctPOV.pctNOHS                      -0.317000144  0.330201284
##    Corr_pctPOV.pctMOVE                      -0.331272313  0.157747220
##    Corr_pctPOV.pctOWNER_OCC                 -0.926032270 -0.768233160
##    Corr_pctPOV.ICE_INCOME_all               -0.921214422 -0.855191644
##    Corr_pctNOHS.pctMOVE                     -0.555196633  0.009497939
##    Corr_pctNOHS.pctOWNER_OCC                -0.742254592 -0.495928778
##    Corr_pctNOHS.ICE_INCOME_all              -0.793477505 -0.545592647
##    Corr_pctMOVE.pctOWNER_OCC                -0.891153190 -0.746883164
##    Corr_pctMOVE.ICE_INCOME_all              -0.817237195 -0.594811585
##    Corr_pctOWNER_OCC.ICE_INCOME_all          0.476114554  0.736449688
##    Spearman_rho_pctPOV.pctNOHS              -0.313709999  0.399932352
##    Spearman_rho_pctPOV.pctMOVE              -0.338963728  0.215510831
##    Spearman_rho_pctPOV.pctOWNER_OCC         -0.932742660 -0.772363010
##    Spearman_rho_pctPOV.ICE_INCOME_all       -0.945687048 -0.876406885
##    Spearman_rho_pctNOHS.pctMOVE             -0.407210551  0.057271829
##    Spearman_rho_pctNOHS.pctOWNER_OCC        -0.828797842 -0.551819264
##    Spearman_rho_pctNOHS.ICE_INCOME_all      -0.840537241 -0.647642983
##    Spearman_rho_pctMOVE.pctOWNER_OCC        -0.885112112 -0.731419517
##    Spearman_rho_pctMOVE.ICE_INCOME_all      -0.832992937 -0.560002101
##    Spearman_rho_pctOWNER_OCC.ICE_INCOME_all  0.454870395  0.712341847
##                                                   Median      3rd Qu.    Max.
##    Cov_pctPOV.pctNOHS                        0.001807506  0.003304389  0.0180
##    Cov_pctPOV.pctMOVE                        0.002229805  0.004467243  0.0099
##    Cov_pctPOV.pctOWNER_OCC                  -0.014516859 -0.009563665 -0.0016
##    Cov_pctPOV.ICE_INCOME_all                -0.014606879 -0.009577934 -0.0023
##    Cov_pctNOHS.pctMOVE                       0.000331801  0.000748402  0.0038
##    Cov_pctNOHS.pctOWNER_OCC                 -0.002496901 -0.001218701  0.0065
##    Cov_pctNOHS.ICE_INCOME_all               -0.002789993 -0.001573582  0.0039
##    Cov_pctMOVE.pctOWNER_OCC                 -0.008392739 -0.005565503  0.0056
##    Cov_pctMOVE.ICE_INCOME_all               -0.005403826 -0.002219461  0.0149
##    Cov_pctOWNER_OCC.ICE_INCOME_all           0.031021243  0.044464726  0.0689
##    Corr_pctPOV.pctNOHS                       0.528380318  0.709155971  0.9313
##    Corr_pctPOV.pctMOVE                       0.336717286  0.519424037  0.7694
##    Corr_pctPOV.pctOWNER_OCC                 -0.701980159 -0.604820576 -0.3121
##    Corr_pctPOV.ICE_INCOME_all               -0.805848933 -0.738051250 -0.2913
##    Corr_pctNOHS.pctMOVE                      0.134766298  0.300808384  0.6833
##    Corr_pctNOHS.pctOWNER_OCC                -0.380222665 -0.228294821  0.4213
##    Corr_pctNOHS.ICE_INCOME_all              -0.446961901 -0.323081384  0.3913
##    Corr_pctMOVE.pctOWNER_OCC                -0.613431373 -0.433099806  0.2776
##    Corr_pctMOVE.ICE_INCOME_all              -0.458003819 -0.189021343  0.5593
##    Corr_pctOWNER_OCC.ICE_INCOME_all          0.813864246  0.868133644  0.9618
##    Spearman_rho_pctPOV.pctNOHS               0.556988603  0.704535569  0.9311
##    Spearman_rho_pctPOV.pctMOVE               0.374243796  0.529475103  0.7608
##    Spearman_rho_pctPOV.pctOWNER_OCC         -0.699827624 -0.621225648 -0.3108
##    Spearman_rho_pctPOV.ICE_INCOME_all       -0.839312766 -0.774693178 -0.3117
##    Spearman_rho_pctNOHS.pctMOVE              0.174120074  0.303105444  0.5853
##    Spearman_rho_pctNOHS.pctOWNER_OCC        -0.428396144 -0.245467087  0.2446
##    Spearman_rho_pctNOHS.ICE_INCOME_all      -0.524973642 -0.381356579  0.1699
##    Spearman_rho_pctMOVE.pctOWNER_OCC        -0.619497465 -0.450139874  0.3082
##    Spearman_rho_pctMOVE.ICE_INCOME_all      -0.428406930 -0.173601402  0.4005
##    Spearman_rho_pctOWNER_OCC.ICE_INCOME_all  0.797280146  0.852406288  0.9477
##    Summary information for Local median:
##                               Min.   1st Qu.    Median   3rd Qu.   Max.
##    pctPOV_Median          0.042468  0.090310  0.161004  0.251916 0.3919
##    pctNOHS_Median         0.003663  0.014632  0.042506  0.068828 0.1053
##    pctMOVE_Median         0.095830  0.158633  0.186185  0.201781 0.3108
##    pctOWNER_OCC_Median    0.191905  0.391960  0.490220  0.602281 0.8389
##    ICE_INCOME_all_Median -0.384111 -0.195011 -0.023930  0.170068 0.3830
##    Summary information for Interquartile range:
##                            Min.   1st Qu.    Median   3rd Qu.   Max.
##    pctPOV_IQR         0.0272517 0.0846864 0.1150697 0.1709975 0.3370
##    pctNOHS_IQR        0.0071992 0.0233457 0.0362078 0.0567798 0.1961
##    pctMOVE_IQR        0.0492332 0.0777156 0.0943680 0.1143242 0.2195
##    pctOWNER_OCC_IQR   0.0695205 0.2406716 0.2930468 0.3634722 0.6663
##    ICE_INCOME_all_IQR 0.0741381 0.1853240 0.2307883 0.2932845 0.5597
##    Summary information for Quantile imbalance:
##                            Min.    1st Qu.     Median    3rd Qu.   Max.
##    pctPOV_QI         -0.8423900 -0.3575769 -0.1613870  0.0836692 0.7498
##    pctNOHS_QI        -0.9376945 -0.5163889 -0.2601448  0.0084147 0.4966
##    pctMOVE_QI        -0.7152669 -0.2848576 -0.0713806  0.1454639 0.7001
##    pctOWNER_OCC_QI   -0.7647186 -0.1424103  0.0614975  0.2285407 0.7302
##    ICE_INCOME_all_QI -0.8670434 -0.2368184 -0.0310687  0.1636269 0.8803
## 
##    ************************************************************************</code></pre>
<p>What the summary gives you is information for the range of <em>smoothed</em> values for each statistic, and for each variable. Notice, for example the <em>names</em> of the variables. All of the estimates of the <em>geographically weighted mean</em> end with <code>_LM</code> which stands for <em>local mean</em>. Similarly the estimates of <em>geographically weighted standard deviation</em> end with <code>_LSD</code> for <em>local SD</em>.</p>
<div id="mapping-gwss-results" class="section level4" number="7.4.3.1">
<h4>
<span class="header-section-number">7.4.3.1</span> Mapping <code>gwss</code> results<a class="anchor" aria-label="anchor" href="#mapping-gwss-results"><i class="fas fa-link"></i></a>
</h4>
<p>How do we <strong>see</strong> the results? Try looking at our result:</p>
<div class="sourceCode" id="cb160"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "SDF"      "vars"     "kernel"   "adaptive" "bw"       "p"       
##  [7] "theta"    "longlat"  "DM.given" "sp.given" "quantile"</code></pre>
<div class="sourceCode" id="cb162"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">)</span></code></pre></div>
<pre><code>##          Length Class                    Mode     
## SDF      345    SpatialPolygonsDataFrame S4       
## vars       5    -none-                   character
## kernel     1    -none-                   character
## adaptive   1    -none-                   logical  
## bw         1    -none-                   numeric  
## p          1    -none-                   numeric  
## theta      1    -none-                   numeric  
## longlat    1    -none-                   logical  
## DM.given   1    -none-                   logical  
## sp.given   1    -none-                   logical  
## quantile   1    -none-                   logical</code></pre>
<p>There are many <em>sub-objects</em> within the main result object. But the first one, always called <code>SDF</code> has class <code>SpatialPolygonsDataFrame</code>. The is basically the <code>sp</code> version of a polygon spatial file. If you examine it more closely (e.g. try <code>summary(atl.ss$SDF))</code> to see what happens) you will see that it has the information we need to make maps (e.g. it is a spatial object with attribute data).</p>
<p>First, let’s map <em>geographically-weighted median</em> value for each of the statistics:</p>
<div class="sourceCode" id="cb164"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Map geographically-weighted Median</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV_Median'</span>, <span class="st">'pctNOHS_Median'</span>, <span class="st">'pctMOVE_Median'</span>, <span class="st">'pctOWNER_OCC_Median'</span><span class="op">)</span>,
          style <span class="op">=</span> <span class="st">'quantile'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-45-1.png" width="672"></div>
<p>And we can also examine the local variation or diversity in values by mapping the <em>geographically-weighted IQR</em></p>
<div class="sourceCode" id="cb165"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Map geographically-weighted IQR</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV_IQR'</span>, <span class="st">'pctNOHS_IQR'</span>, <span class="st">'pctMOVE_IQR'</span>, <span class="st">'pctOWNER_OCC_IQR'</span><span class="op">)</span>,
          style <span class="op">=</span> <span class="st">'quantile'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-46-1.png" width="672"></div>
<p>Remember, places with <em>higher IQR</em> have <em>larger local differences</em> in the values. Are the places of high variability similar to, or different from, the places with high median values?</p>
<p>You can now repeat the above code for the <code>ICE_INCOME_all</code> variable, and also repeat all variables looking at the <em>mean</em> and <em>SD</em> rather than the <em>median</em> and <em>IQR</em>. Is there evidence that the <em>local mean</em> and <em>local median</em> are different?</p>
</div>
</div>
<div id="calculating-pseudo-p-values-for-smoothed-estimates" class="section level3" number="7.4.4">
<h3>
<span class="header-section-number">7.4.4</span> Calculating pseudo p-values for smoothed estimates<a class="anchor" aria-label="anchor" href="#calculating-pseudo-p-values-for-smoothed-estimates"><i class="fas fa-link"></i></a>
</h3>
<p>The motivation for much of disease mapping is the detection of <em>spatial heterogeneity</em> and <em>spatial dependence</em> in epidemiologic data. <em>Spatial heterogeneity</em> in a statistical parameter means that values are <em>truly different</em> in some locations compared to others. <em>Spatial dependence</em> in a random variable means that the values in one location tend to be more correlated with values in nearby locations than with values in distant locations.</p>
<p>A related idea is that of <em>spatial stationarity</em> which implies that the value for a summary of data (e.g. the <em>spatially-local mean</em>) is location independent. In other words if you divided your study region into 10 equal-sized sub-regions, the <em>mean</em> value would be approximately the same in each. In contrast, <em>spatial non-stationarity</em> means that the local summaries are location-dependent. For example the estimate of the <em>spatially local mean</em> could be different in one sub-region compared to another.</p>
<p>Note that <em>spatial non-stationarity</em> implies both <strong>heterogeneity</strong> in the parameter of interest (values are not the same everywhere) <strong>and spatial dependence</strong> of the observations (near values are more correlated than distant values). If there were only <em>heterogeneity</em>, but not <em>dependence</em> we would expect, on average, that local summaries of statistics would still be <em>stationary</em>.</p>
<p>We can restate some of the above definitions in the form of testable hypotheses to evaluate in our disease mapping analysis. First note that in this example we have multiple candidate <em>random variables</em> (e.g. <code>pctPOV</code>, <code>pctMOVE</code>, <code>ICE_INCOME_all</code>, …), as well as multiple candidate statistical parameters (e.g. the <em>mean</em>, <em>median</em>, <em>SD</em>, <em>IQR</em>, …). To hone in on the questions at hand, let us assume we are interested in describing the <em>mean</em> value of the random variable <code>pctPOV</code>. The use of kernel density functions applied to spatial data are particularly well suited for testing of <em>spatial stationarity</em> versus <em>spatial non-stationarity</em> of statistic parameters.</p>
<p>As noted above, the question about <em>spatial stationarity</em> hinges largely on the presence of <em>spatial dependence</em> versus <em>spatial independence</em> of observed values. Therefore, under a <em>null hypothesis</em>, <span class="math inline">\(H_0:\)</span>, we might posit that the observed values of <code>pctPOV</code> are independent of one another, and therefore any <em>spatially local mean</em> estimate of <code>pctPOV</code> would be location independent (e.g. the summary in one location would, on average, be the same as the summary in another location). The <em>alternative hypothesis</em>, <span class="math inline">\(H_A:\)</span>, is that the values of <code>pctPOV</code> are <em>spatially dependent</em> and therefore any <em>spatially local mean</em> estimate of <code>pctPOV</code> could be location dependent (e.g. not equal to a single <em>global</em> value, nor to every other location-specif value).</p>
<p>How can we test this hypothesis? As we have seen previously, hypothesis testing with spatial data is made more challenging by the complex structure of the data, and difficulty making plausible assumptions under conventional statistical rules.</p>
<p>One effective empirical solution to the complexity is to carry out <em>Monte Carlo permutation testing</em> of the null hypothesis. The idea with permutation testing, is that we can empirically simulate what we believe the data would look like under the <em>null distribution</em>. Then we can compare our <em>observed</em> data to the simulated <em>null distribution</em> to describe how unusual our observations were, given what would have been expected due to chance alone.</p>
<p>Permutation testing is particularly well-suited to questions about <em>spatial independence</em> versus <em>spatial dependence</em>, because it is not hard to conceive of what it means to have data values independent of one another. For example, imagine that our random variable, <code>pctPOV</code> has been measured on 345 units, as it has here. Under the <em>null hypothesis</em> of spatial independence, the geographic location of the measures is irrelevant. For example if we took the exact same vector of <span class="math inline">\(n=345\)</span> values of <code>pctPOV</code> and randomly changed their geographic location, it should not matter because we assume, under the null, that geographic location is irrelevant. If we were to randomly reassign the vector of <span class="math inline">\(n=345\)</span> values of <code>pctPOV</code> to different locations many, many times we would begin to see a <em>distribution of arrangements under the null hypothesis</em>, e.g. spatial independence.</p>
<div class="rmdnote">
<p><strong>What is permutation testing doing?</strong></p>
<ul>
<li>First, the measure of interest in this case is the geographically-weighted average of a variable, say <code>pctPOV</code>. So each region will have its own <em>spatially weighted average</em> calculated as the weighted average of it’s own neighbors (as defined by the kernel).</li>
<li>Under the null, we assume that the value of an individual region’s <code>pctPOV</code> is independent of the value of the value in its neighbors. Therefore, the permutations are an empirical way to approximate this null assumption by randomly re-assigning the known values to different geographic locations.</li>
<li>Each time we randomly reassign a set of locations, we repeat the process of creating the geographically weighted average of the variable, e.g. <code>pctPOV</code>. After doing this a lot of times, we have a distribution of what the geographically weighted <code>pctPOV</code> for each individual region would look like if the null (spatial independence) were true.</li>
<li>We can then compare our <em>single observed realization</em> of the geographically-weighted <code>pctPov</code> in each region to the long list of hypothetical values (under the null) to see how typical or unusual our observed data are. Essentially the pseudo p-value is just the rank-ordered percentile of the observed data in relation to the range of values under the null.</li>
<li>The number of random permutations guides the precision of our eventual pseudo-p-value. Our p-value could theoretically be smaller if we have more null permutations. For instance if we compare <span class="math inline">\(n=1\)</span> observed realization of the data with <span class="math inline">\(n=99\)</span> null permutations the very most extreme statement we could make is that our data is more extreme at <span class="math inline">\(p = \frac{1}{100} = 0.01\)</span> level. In contrast if we had <span class="math inline">\(n=1\)</span> observed realizations and <span class="math inline">\(n=999\)</span> random permutations under the null the most extreme our data could be is <span class="math inline">\(p = \frac{1}{1000} = 0.001\)</span>.</li>
</ul>
</div>
<p>This is what the function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.montecarlo.html">gwss.montecarlo()</a></code> does. In the specific context of the <em>geographically weighted summary statistics</em>, the function follows a 3-step process:</p>
<ol style="list-style-type: decimal">
<li>First it will randomly reassign the location of variables of interest <span class="math inline">\(n\)</span> times (where <span class="math inline">\(n\)</span> specified by user, but typically reasonably large)</li>
<li>Second, for each random permutation of the random variable (e.g. <code>pctPOV</code>), the summary statistic (e.g. the <em>spatially-weighted local mean</em> of <code>pctPOV</code>) is calculated.<br>
</li>
<li>Finally, the <em>observed</em> results (e.g. the <em>spatially-weighted mean</em> of <code>pctPOV</code> calculated using our original <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code>) is compared to the <em>null distribution</em>. If we calculated <span class="math inline">\(n=999\)</span> random permutations, then we would have <span class="math inline">\(n=1000\)</span> versions of the summarized statistic, including the observed. The <em>pseudo p-value</em> is calculated as the number of times for each spatial unit that the <em>observed</em> value is <em>more extreme</em> than what would be expected under the null. For example if we defined <em>extreme</em> as being something that happens fewer than 5% of the time by random chance alone, then we might classify our observed value as <em>extreme</em> (and thus <em>significant</em>) if our observed value was either less than the lower 2.5% of the null values, or greater than the upper 97.5% of the null values.</li>
</ol>
<p>It might sound like a lot of things are happening. Mechanically it is a relatively straightforward procedure, but it can be time consuming, particularly when you have a lot of permutations of the null. Here we carry out the Monte Carlo permutation test for geographically-weighted statistics on a single variable, <code>pctPOV</code>. Most of the arguments are familiar, but we now must specify how many permutations or <em>simulations</em> we wish by using the arguments <code>nsim =</code>. On my computer, it took less than 1 minute to run with <span class="math inline">\(n=499\)</span> permutations. Note that because we request <span class="math inline">\(n=499\)</span> simulations, when combined with our <em>observed</em> data, there will be <span class="math inline">\(n=500\)</span> total values of the <em>spatially-weighted mean</em> value of <code>pctPOV</code> to compare.</p>
<div class="sourceCode" id="cb166"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p.val</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwss.montecarlo.html">gwss.montecarlo</a></span><span class="op">(</span><span class="va">atl</span>, vars <span class="op">=</span> <span class="st">'pctPOV'</span>, 
                         adaptive <span class="op">=</span> <span class="cn">T</span>,
                         bw <span class="op">=</span> <span class="fl">35</span>,
                         nsim <span class="op">=</span> <span class="fl">499</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">p.val</span><span class="op">)</span></code></pre></div>
<p>You can now examine the result. First you might find that what is returned is of class <code>matrix</code>. You will notice that there are columns for all 5 of the primary summary statistics estimated by <code>gwss</code></p>
<ul>
<li>
<code>_LM</code> which is the <em>local mean</em>
</li>
<li>
<code>_LSD</code> which is the <em>local standard deviation</em>
</li>
<li>
<code>_LVar</code> which is the <em>local variance</em>
</li>
<li>
<code>_LSKe</code> which is the <em>local skewness</em>
</li>
<li>
<code>_LCV</code> which is the <em>local coefficient of variation</em>
</li>
</ul>
<p>The numbers in each column are values that range from 0 to 1. These numbers are <em>percentiles</em> reflecting the <em>rank</em> location of the single <em>spatially weighted local mean</em> of <code>pctPOV</code> from the <em>observed</em> data as compared to the <span class="math inline">\(n=499\)</span> versions where spatial location was randomly assigned.</p>
<p>To calculate a 2-side pseudo p-value at the conventional 0.05 threshold, we would be interested in which census tracts the <em>observed</em> data were either in the very lowest 2.5% or the very highest 2.5% of the null distribution. In other words we could ask which census tracts were observed to have a spatially-weighted local mean value that is <em>extreme</em> as compared to what would happen by chance alone.</p>
<div class="rmdnote">
<p><strong>NOTE</strong>:</p>
<p>The percentile values come from a specific set of randomly distributed simulations. Repeating the procedure could produce <em>slightly</em> different values from what is printed above simply due to random variation. But based on the <em>Central Limit Theorem</em>, we believe that as the number of the simulations grows larger, the more consistent the results will be.</p>
</div>
<p>However the result returned in the object <code>p.val</code> is not easy to use just as it is. How could we convert it into something we could map? Below, we can test which census tracts were <em>extreme</em> under the above definition, and then make a new spatial object that includes only <em>significant</em> tracts.</p>
<div class="sourceCode" id="cb167"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># First, create TRUE/FALSE vectors testing whether column 1 (pctPOV_LM) is extreme</span>
<span class="co"># I am using 2 significance levels: 90% and 95%</span>
<span class="va">sig95</span> <span class="op">&lt;-</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">0.025</span> <span class="op">|</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0.975</span>
<span class="va">sig90</span> <span class="op">&lt;-</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="op">|</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0.95</span>

<span class="co"># Second create a spatial object that ONLY contains significant tracts</span>
<span class="va">atl.sig95</span> <span class="op">&lt;-</span> <span class="va">atl</span><span class="op">[</span><span class="va">sig95</span>, <span class="op">]</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate</a></span><span class="op">(</span>dissolve <span class="op">=</span> <span class="cn">T</span>, FUN <span class="op">=</span> <span class="va">length</span><span class="op">)</span> <span class="co"># this is sp code to merge adjacent tracts</span>

<span class="va">atl.sig90</span> <span class="op">&lt;-</span> <span class="va">atl</span><span class="op">[</span><span class="va">sig90</span>, <span class="op">]</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate</a></span><span class="op">(</span>dissolve <span class="op">=</span> <span class="cn">T</span>, FUN <span class="op">=</span> <span class="va">length</span><span class="op">)</span></code></pre></div>
<div class="rmdtip">
<p>In the code above we use the <code>sp</code> function <code><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate()</a></code> in a similar way we might use the <code>dplyr</code> function <code>group_by()</code> with <code>sf</code> class data: to merge or dissolve adjacent polygons that share a value. In this case we are merging census tracts that have p-values below a certain threshold in order to create a bold outline on the map.</p>
<p>The <code><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate()</a></code> function requires an action or function (<code>FUN</code>) to be applied to the groups of tracts being merged together. We do not care about the output of the function, but just need to put something in. Somewhat arbitrarily I choose the function <code>length</code> because it works well for both numeric and character data. However, we will not pay attention to the value returned; instead we only care about the shape of the resulting polygon.</p>
</div>
<p>Now we can use the results from above to create a map summarizing our evidence in relation to the <em>null hypothesis</em> that the <em>geographically-weighted mean</em> value of <code>pctPOV</code> is <em>stationary</em>, against the <em>alternative hypothesis</em> that at least some locations have significantly more extreme local values than expected under the null.</p>
<div class="sourceCode" id="cb168"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'pctPOV_LM'</span>, 
          style <span class="op">=</span> <span class="st">'quantile'</span>,
          title <span class="op">=</span> <span class="st">'Local Average % Poverty'</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.sig90</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> 
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.sig95</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span><span class="st">'red'</span><span class="op">)</span> <span class="op">+</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">'line'</span>,
              labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'p &lt; 0.05'</span>, <span class="st">'p &lt; 0.10'</span><span class="op">)</span>,
              col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'red'</span>, <span class="st">'blue'</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-50-1.png" width="672"></div>
<p>What we see is that the visual inspection of the <em>geographically-weighted mean</em> of <code>pctPOV</code> suggests that there is a great deal of <em>spatial heterogeneity</em> and apparent <em>spatial non-stationarity</em>. However, the permutation test suggests that only a few regions in far North Fulton and in West Atlanta have values that are more extreme than we might expect under an assumption of spatial independence.</p>
<div class="rmdcaution">
<p><strong>NOTE</strong>:</p>
<p>It is important to remember the hypothesis we were testing! This is not a test of whether the poverty rate is zero, nor a test of whether the poverty rate is different in some specific census tracts compared to others.</p>
<p>Instead, this is specifically a test of whether there is <em>spatial dependence</em> in the data that would give rise to unexpectedly extreme local measures under the assumptions of the KDE with specified neighbors.</p>
</div>
</div>
<div id="estimating-geographically-weighted-bivariate-statistics" class="section level3" number="7.4.5">
<h3>
<span class="header-section-number">7.4.5</span> Estimating geographically-weighted bivariate statistics<a class="anchor" aria-label="anchor" href="#estimating-geographically-weighted-bivariate-statistics"><i class="fas fa-link"></i></a>
</h3>
<p>The final bits of information we will examine from the <em>geographically-weighted summary statistics</em> function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> are the bivariate correlations and covariances. Any time two or more variables are supplied to the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> function, it will automatically calculate the correlation coefficients (both Pearson and Spearman), as well as measures of covariance, for every pair of variables.</p>
<p>Up until now, we have seen how the KDE function can produce a smoothed estimate of the local <em>mean</em>, <em>median</em>, <em>SD</em>, etc. But it can also show whether any correlation between pairs of variables is <em>spatially stationary</em> (the same everywhere), or <em>spatially non-stationary</em> (varies by location).</p>
<div class="sourceCode" id="cb169"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Spearman_rho_pctPOV.pctNOHS'</span>,
            <span class="st">'Spearman_rho_pctPOV.pctMOVE'</span>,
            <span class="st">'Spearman_rho_pctPOV.ICE_INCOME_all'</span><span class="op">)</span>,
          style <span class="op">=</span> <span class="st">'quantile'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-51-1.png" width="672"></div>
<p>Two things are illustrated by these maps.</p>
<ol style="list-style-type: decimal">
<li>First, it appears that the magnitude of correlation among these pairs of variables is larger in some areas and smaller in others.</li>
<li>The second, is that the spatial patterns of correlation between <code>pctPOV</code> and two other variables are distinct. In other words the areas where correlation is relatively stronger or weaker are not the same.</li>
</ol>
<p>We might once again ask whether these differences are more extreme than we might expect under a null hypothesis of <em>spatial independence</em> and <em>spatial stationarity</em>.</p>
<p>Previously we only conducted the <em>Monte Carlo permutation test</em> on a single variable, <code>pctPOV</code>. But if we provide two or more variables to the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.montecarlo.html">gwss.montecarlo()</a></code> function, we will get pseudo p-values for both univariate and bivariate statistics. <strong>NOTE</strong> this takes more time because there is more work for the computer to do. The code below took a little over 1-minute on my computer.</p>
<div class="sourceCode" id="cb170"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p.val</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwss.montecarlo.html">gwss.montecarlo</a></span><span class="op">(</span><span class="va">atl</span>, vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'pctPOV'</span>, <span class="st">'pctMOVE'</span><span class="op">)</span>, 
                         adaptive <span class="op">=</span> <span class="cn">T</span>,
                         bw <span class="op">=</span> <span class="fl">35</span>,
                         nsim <span class="op">=</span> <span class="fl">499</span><span class="op">)</span></code></pre></div>
<p>You can use <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> or <code><a href="https://rdrr.io/r/base/dimnames.html">dimnames()</a></code> to figure out which column you want. We want to get the permutation p-value for <code>Spearman_rho_pctPOV.pctMOVE</code>, which is in the 13th column of the matrix.</p>
<div class="sourceCode" id="cb171"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># First, create TRUE/FALSE vectors testing whether column 1 (pctPOV_LM) is extreme</span>
<span class="co"># I am using 2 significance levels: 90% and 95%</span>
<span class="va">sig95</span> <span class="op">&lt;-</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">13</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">0.025</span> <span class="op">|</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">13</span><span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0.975</span>
<span class="va">sig90</span> <span class="op">&lt;-</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">13</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="op">|</span> <span class="va">p.val</span><span class="op">[</span>, <span class="fl">13</span><span class="op">]</span> <span class="op">&gt;</span> <span class="fl">0.95</span>

<span class="co"># Second create a spatial object that ONLY contains significant tracts</span>
<span class="va">atl.sig95</span> <span class="op">&lt;-</span> <span class="va">atl</span><span class="op">[</span><span class="va">sig95</span>, <span class="op">]</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate</a></span><span class="op">(</span>dissolve <span class="op">=</span> <span class="cn">T</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span> 

<span class="va">atl.sig90</span> <span class="op">&lt;-</span> <span class="va">atl</span><span class="op">[</span><span class="va">sig90</span>, <span class="op">]</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/aggregate.sf.html">aggregate</a></span><span class="op">(</span>disolve <span class="op">=</span> <span class="cn">T</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span></code></pre></div>
<p>Now we can map the correlation between <code>pctPOV</code> and <code>pctMOVE</code> along with the significance test.</p>
<div class="sourceCode" id="cb172"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.ss</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'Spearman_rho_pctPOV.pctMOVE'</span>, 
          style <span class="op">=</span> <span class="st">'quantile'</span>,
          title <span class="op">=</span> <span class="st">'Local correlation Poverty\n&amp; Residential instability'</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.sig90</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span> 
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl.sig95</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>lwd <span class="op">=</span> <span class="fl">2</span>, col <span class="op">=</span><span class="st">'red'</span><span class="op">)</span> <span class="op">+</span>
<span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">'line'</span>,
              labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'p &lt; 0.05'</span>, <span class="st">'p &lt; 0.10'</span><span class="op">)</span>,
              col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'red'</span>, <span class="st">'blue'</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-disease-mapping-3_files/figure-html/unnamed-chunk-54-1.png" width="672"></div>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="disease-mapping-ii.html"><span class="header-section-number">6</span> Disease Mapping II</a></div>
<div class="next"><a href="disease-mapping-iv.html"><span class="header-section-number">8</span> Disease Mapping IV</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#disease-mapping-iii"><span class="header-section-number">7</span> Disease Mapping III</a></li>
<li>
<a class="nav-link" href="#getting-ready-4"><span class="header-section-number">7.1</span> Getting Ready</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#learning-objectives-5"><span class="header-section-number">7.1.1</span> Learning objectives</a></li>
<li><a class="nav-link" href="#additional-resources-5"><span class="header-section-number">7.1.2</span> Additional Resources</a></li>
<li><a class="nav-link" href="#important-vocabulary-5"><span class="header-section-number">7.1.3</span> Important Vocabulary</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#spatial-thinking-in-epidemiology-4"><span class="header-section-number">7.2</span> Spatial Thinking in Epidemiology</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#revisiting-spatial-point-processes"><span class="header-section-number">7.2.1</span> Revisiting spatial point processes</a></li>
<li><a class="nav-link" href="#what-is-a-kernel-density-estimator"><span class="header-section-number">7.2.2</span> What is a kernel density estimator?</a></li>
<li><a class="nav-link" href="#spatial-heterogeneity-versus-spatial-non-stationarity"><span class="header-section-number">7.2.3</span> Spatial heterogeneity versus Spatial non-stationarity</a></li>
<li><a class="nav-link" href="#limitations-in-kernel-density-estimation"><span class="header-section-number">7.2.4</span> Limitations in kernel density estimation</a></li>
<li><a class="nav-link" href="#uses-for-kernel-density-estimation-kde-in-spatial-epidemiology"><span class="header-section-number">7.2.5</span> Uses for kernel density estimation (KDE) in spatial epidemiology</a></li>
<li><a class="nav-link" href="#guide-to-the-rest-of-this-section"><span class="header-section-number">7.2.6</span> Guide to the rest of this section…</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#spatial-analysis-in-epidemiology-kernel-estimation-of-point-processes"><span class="header-section-number">7.3</span> Spatial Analysis in Epidemiology: Kernel estimation of point processes</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#preparing-packages-and-data"><span class="header-section-number">7.3.1</span> Preparing packages and data</a></li>
<li><a class="nav-link" href="#introducing-a-new-spatial-data-class-ppp"><span class="header-section-number">7.3.2</span> Introducing a new spatial data class: ppp</a></li>
<li><a class="nav-link" href="#creating-the-ppp-objects"><span class="header-section-number">7.3.3</span> Creating the ppp objects</a></li>
<li><a class="nav-link" href="#bandwidth-selection"><span class="header-section-number">7.3.4</span> Bandwidth selection</a></li>
<li><a class="nav-link" href="#estimating-kernel-density-surfaces"><span class="header-section-number">7.3.5</span> Estimating Kernel Density surfaces</a></li>
<li><a class="nav-link" href="#creating-relative-risk-surface-manually"><span class="header-section-number">7.3.6</span> Creating relative risk surface manually</a></li>
<li><a class="nav-link" href="#creating-relative-risk-surface-with-risk-function"><span class="header-section-number">7.3.7</span> Creating relative risk surface with risk() function</a></li>
<li><a class="nav-link" href="#using-functions-to-map-rr-with-tmap"><span class="header-section-number">7.3.8</span> Using functions to map RR with tmap</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#gwss"><span class="header-section-number">7.4</span> Spatial Analysis in Epidemiology: Kernel estimation of areal data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#packages-and-data"><span class="header-section-number">7.4.1</span> Packages and data</a></li>
<li><a class="nav-link" href="#what-bandwidth-for-kernel-density-estimates"><span class="header-section-number">7.4.2</span> What bandwidth for kernel density estimates?</a></li>
<li><a class="nav-link" href="#geographically-weighted-summary-statistics-gwss"><span class="header-section-number">7.4.3</span> Geographically weighted summary statistics: gwss()</a></li>
<li><a class="nav-link" href="#calculating-pseudo-p-values-for-smoothed-estimates"><span class="header-section-number">7.4.4</span> Calculating pseudo p-values for smoothed estimates</a></li>
<li><a class="nav-link" href="#estimating-geographically-weighted-bivariate-statistics"><span class="header-section-number">7.4.5</span> Estimating geographically-weighted bivariate statistics</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/mkram01/EPI563-SpatialEPI/blob/master/06-disease-mapping-3.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/mkram01/EPI563-SpatialEPI/edit/master/06-disease-mapping-3.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EPI 563: Spatial Epidemiology, Fall 2021</strong>" was written by Michael Kramer. It was last built on Last updated: 2021-10-25.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
