<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Week 17 Tips for using dplyr | EPI 563: Spatial Epidemiology, Fall 2023</title>
<meta name="author" content="Michael Kramer">
<meta name="description" content="Here are a few handy resources with more detail on wrangling with dplyr and tidyr: dplyr overview Data transformation with dplyr cheat sheet Epidemiologists R Handbook - tidy data As is the case...">
<meta name="generator" content="bookdown 0.35 with bs4_book()">
<meta property="og:title" content="Week 17 Tips for using dplyr | EPI 563: Spatial Epidemiology, Fall 2023">
<meta property="og:type" content="book">
<meta property="og:description" content="Here are a few handy resources with more detail on wrangling with dplyr and tidyr: dplyr overview Data transformation with dplyr cheat sheet Epidemiologists R Handbook - tidy data As is the case...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Week 17 Tips for using dplyr | EPI 563: Spatial Epidemiology, Fall 2023">
<meta name="twitter:description" content="Here are a few handy resources with more detail on wrangling with dplyr and tidyr: dplyr overview Data transformation with dplyr cheat sheet Epidemiologists R Handbook - tidy data As is the case...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.1/transition.js"></script><script src="libs/bs3compat-0.5.1/tabs.js"></script><script src="libs/bs3compat-0.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EPI 563: Spatial Epidemiology, Fall 2023</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">How to use this eBook</a></li>
<li><a class="" href="download-ebook.html">Download eBook</a></li>
<li class="book-part">Getting ready…</li>
<li><a class="" href="software-installation.html">Software installation</a></li>
<li><a class="" href="installing-packages-for-this-course.html">Installing packages for this course</a></li>
<li class="book-part">Weekly Modules</li>
<li><a class="" href="locating-spatial-epidemiology.html"><span class="header-section-number">1</span> Locating Spatial Epidemiology</a></li>
<li><a class="" href="cartography-for-epidemiology-i.html"><span class="header-section-number">2</span> Cartography for Epidemiology I</a></li>
<li><a class="" href="cartography-for-epidemiology-ii-spatial-ethics.html"><span class="header-section-number">3</span> Cartography for Epidemiology II: Spatial Ethics</a></li>
<li><a class="" href="disease-mapping-i-aspatial-empirical-bayes.html"><span class="header-section-number">4</span> Disease Mapping I: Aspatial Empirical Bayes</a></li>
<li><a class="" href="disease-mapping-ii-spatial-empirical-bayes.html"><span class="header-section-number">5</span> Disease Mapping II: Spatial Empirical Bayes</a></li>
<li><a class="" href="disease-mapping-iii-introduction-to-fully-bayesian-mapping.html"><span class="header-section-number">6</span> Disease Mapping III: Introduction to Fully Bayesian mapping</a></li>
<li><a class="" href="disease-mapping-iv-kernel-density-estimation.html"><span class="header-section-number">7</span> Disease Mapping IV: Kernel Density Estimation</a></li>
<li><a class="" href="spatial-structure-and-clustering-i-morans-i-and-lisa.html"><span class="header-section-number">8</span> Spatial Structure and Clustering I: Moran’s I and LISA</a></li>
<li><a class="" href="spatial-structure-and-clustering-ii-spatial-scan-statistics.html"><span class="header-section-number">9</span> Spatial Structure and Clustering II: Spatial scan statistics</a></li>
<li><a class="" href="spatreg1.html"><span class="header-section-number">10</span> Spatial Regression I: Spatializing aspatial regression residuals</a></li>
<li><a class="" href="spatial-regression-ii-spatial-econometric-regression.html"><span class="header-section-number">11</span> Spatial Regression II: Spatial econometric regression</a></li>
<li><a class="" href="spatial-regression-iii-geographically-weighted-regression.html"><span class="header-section-number">12</span> Spatial Regression III: Geographically Weighted Regression</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="reproducibility-and-projects-in-r.html"><span class="header-section-number">13</span> Reproducibility and Projects in R</a></li>
<li><a class="" href="introduction-to-r-notebooks.html"><span class="header-section-number">14</span> Introduction to R Notebooks</a></li>
<li><a class="" href="formatting-markdown-and-notebooks.html"><span class="header-section-number">15</span> Formatting Markdown and Notebooks</a></li>
<li><a class="" href="sf-overview.html"><span class="header-section-number">16</span> Tips for working with sf data class</a></li>
<li><a class="active" href="dplyr.html"><span class="header-section-number">17</span> Tips for using dplyr</a></li>
<li><a class="" href="intro-tmap.html"><span class="header-section-number">18</span> Tips for using tmap</a></li>
<li><a class="" href="kde-extract.html"><span class="header-section-number">19</span> Using kernel density estimates to quantify an exposure for Spatial Epi</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/mkram01/EPI563-SpatialEPI">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="dplyr" class="section level1" number="17">
<h1>
<span class="header-section-number">Week 17</span> Tips for using <code>dplyr</code><a class="anchor" aria-label="anchor" href="#dplyr"><i class="fas fa-link"></i></a>
</h1>
<p>Here are a few handy resources with more detail on wrangling with <code>dplyr</code> and <code>tidyr</code>:</p>
<ul>
<li><a href="https://dplyr.tidyverse.org/"><code>dplyr</code> overview</a></li>
<li><a href="https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">Data transformation with <code>dplyr</code> cheat sheet</a></li>
<li><a href="https://epirhandbook.com/transition-to-r.html?q=tidy#tidy-data">Epidemiologists R Handbook - <code>tidy</code> data</a></li>
</ul>
<p>As is the case in many software packages, there is always more than one way to get something done in <code>R</code>! Base-R tools can accomplish all kinds of tasks, but sometimes they are cumbersome and inefficient.</p>
<p>Because most of our use of <code>R</code> as epidemiologists is focused on the tools of <em>data science</em>, you might find the diverse and continually evolving <code>tidyverse</code> a great toolbox to explore. Originated by Hadley Wickham (founder of RStudio), the packages constituting the <code>tidyverse</code> are now contributed by lots of different people. What they have in common is an interest in handling data in <strong>tidy</strong> ways. <a href="https://r4ds.had.co.nz/">R for Data Science</a> is an authoritative guide to <em>tidy</em> data, and many of the tools constituting the <code>tidyverse</code> including <code>ggplot2</code>, <code>dplyr</code> and more.</p>
<p>This appendix is a very brief introduction to the <code>dplyr</code> package which is a set of data manipulation functions. In other words it is the epidemiologists’ go-to package for data manipulation, recoding, and preparation in <code>R</code>.</p>
<p>There are two high-level observations about how we will use <code>dplyr</code> this semester:</p>
<ol style="list-style-type: decimal">
<li>
<code>dplyr</code> functions can be thought of as <strong>verbs</strong>. That means each one is a tool to <em>act on</em> your data, producing a change. So your question is <em>“what do I want to change?”</em>
</li>
<li>Functions in <code>dplyr</code> (and in many other parts of the <code>tidyverse</code> for that matter) can be stand alone code. Or alternatively they can be <em>chained together in a sequence</em>. This chaining (called <em>piping</em> because the tool to connect or chain steps is called a pipe and looks like this: <code>%&gt;%</code>) can make your code both easier for humans to read, and also helps run a sequence of steps more efficiently.</li>
</ol>
<p>For the examples below, I will use the Georgia motor vehicle crash mortality dataset where the unit of observation (e.g. the content of one row of data) is a Georgia county, and the columns are variable names. This dataset is also explicitly <em>spatial</em> meaning that it includes geography information regarding the boundaries of each county, contained with the <code>geom</code> column, as is typical for <code>sf</code> class data in <code>R</code>.</p>
<p>Here is what the first few rows of the dataset looks like (minus the <code>geom</code> column):</p>
<pre><code>## Reading layer `ga_mvc' from data source 
##   `/Users/MKRAM02/Library/CloudStorage/OneDrive-EmoryUniversity/EPI563-Spatial Epi/SpatialEpi-2021/DATA/GA_MVC/ga_mvc.gpkg' 
##   using driver `GPKG'
## Simple feature collection with 159 features and 17 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -85.60516 ymin: 30.35785 xmax: -80.83973 ymax: 35.00066
## Geodetic CRS:  WGS 84</code></pre>
<pre><code>##   GEOID                     NAME   variable estimate          County
## 1 13001  Appling County, Georgia B00001_001     1504  Appling County
## 2 13003 Atkinson County, Georgia B00001_001      875 Atkinson County
## 3 13005    Bacon County, Georgia B00001_001      945    Bacon County
## 4 13007    Baker County, Georgia B00001_001      390    Baker County
## 5 13009  Baldwin County, Georgia B00001_001     2943  Baldwin County
## 6 13011    Banks County, Georgia B00001_001     1767    Banks County
##   MVCDEATHS_05 MVCDEATHS_14 MVCDEATH_17 TPOP_05 TPOP_14 TPOP_17
## 1            4            4          10   17769   18540   18521
## 2            5            1           3    8096    8223    8342
## 3            7            5           0   10552   11281   11319
## 4            1            1           1    3967    3255    3200
## 5            6            8          13   46304   45909   44906
## 6            4            8           6   16683   18295   18634
##   NCHS_RURAL_CODE_2013    nchs_code     rural MVCRATE_05 MVCRATE_14 MVCRATE_17
## 1                    6     Non-core     Rural   22.51111   21.57497   53.99276
## 2                    6     Non-core     Rural   61.75889   12.16101   35.96260
## 3                    6     Non-core     Rural   66.33813   44.32231    0.00000
## 4                    4  Small metro non-Rural   25.20797   30.72197   31.25000
## 5                    5 Micropolitan non-Rural   12.95784   17.42578   28.94936
## 6                    6     Non-core     Rural   23.97650   43.72779   32.19921</code></pre>
<div id="select" class="section level2" number="17.1">
<h2>
<span class="header-section-number">17.1</span> <code>select()</code><a class="anchor" aria-label="anchor" href="#select"><i class="fas fa-link"></i></a>
</h2>
<p>The first <em>verb</em> of <code>dplyr</code> is called <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> and it is useful when you want to remove or <em>select</em> specific columns/variables. For instance, as mentioned this dataset has 17 attribute columns plus the <code>geom</code> column. But perhaps we only need three variables, and we decided it would be easier to exclude the unneeded variables? Then we can <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> those we want (or inversely we can select those we <strong>don’t want</strong>).</p>
<p>There are three useful tips on using <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> with spatial data:</p>
<ol style="list-style-type: decimal">
<li>To select variables <em>to keep</em> simply list them (e.g. <code>select(data, var1, var2, var3)</code>)</li>
<li>If it is easier to only <em>omit</em> specific variables (e.g. perhaps you have 100 variables and you only want to drop 3), place a negative sign before the name (e.g. <code>select(data, -var5, -var6)</code>).</li>
<li>Finally, something specific to working with <code>sf</code> spatial data is that the geometry column (typically named <code>geom</code> or <code>geometry</code>) is <strong>sticky</strong>. That means that it’s hard to get rid of it. That’s actually a good thing. You usually want the geometry to <strong>stick</strong> with the attribute data. But occasionally you might want to convert you <em>spatial</em> <code>sf</code> data object into an <em>aspatial</em> <code>data.frame</code>. To do this you must first set the geometry to be null like this: <code>aspatial.df &lt;- st_set_geometry(spatial.df, NULL)</code>. <a href="sf-overview.html#sf-overview">See additional info here</a>.</li>
</ol>
<p>Let’s do that with the motor vehicle crash data.</p>
<div class="sourceCode" id="cb380"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># First we read in the dataset, which is stored as a geopackage</span></span>
<span><span class="va">mvc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">'GA_MVC/ga_mvc.gpkg'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Look at column names</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">mvc</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># For this example we do not want the geom column because it is too big to view</span></span>
<span><span class="va">mvc2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="va">mvc</span>, <span class="cn">NULL</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creating a new object with only 4 attributes</span></span>
<span><span class="va">mvc2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">mvc2</span>, <span class="va">GEOID</span>, <span class="va">NAME</span>, <span class="va">rural</span>, <span class="va">MVCRATE_05</span>, <span class="va">MVCRATE_17</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># look at column names</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">mvc2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "GEOID"                "NAME"                 "variable"            
##  [4] "estimate"             "County"               "MVCDEATHS_05"        
##  [7] "MVCDEATHS_14"         "MVCDEATH_17"          "TPOP_05"             
## [10] "TPOP_14"              "TPOP_17"              "NCHS_RURAL_CODE_2013"
## [13] "nchs_code"            "rural"                "MVCRATE_05"          
## [16] "MVCRATE_14"           "MVCRATE_17"           "geom"</code></pre>
<pre><code>## [1] "GEOID"      "NAME"       "rural"      "MVCRATE_05" "MVCRATE_17"</code></pre>
</div>
<div id="mutate" class="section level2" number="17.2">
<h2>
<span class="header-section-number">17.2</span> <code>mutate()</code><a class="anchor" aria-label="anchor" href="#mutate"><i class="fas fa-link"></i></a>
</h2>
<p>Another frequently needed <em>verb</em> is called <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> and as you might guess it <em>changes</em> your data. Specifically <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> is a function for creating a new variable, possibly as a recode of an older variable. The <code>mvc</code> data object has 159 rows (one each for n=159 counties).</p>
<p>Let’s imagine that we wanted to create a map that illustrated the magnitude of the <strong>change</strong> in the rate of death from motor vehicle crashes between 2005 and 2017. To do this we want to create two new variables that we will name <code>delta_mr_abs</code> (the <em>absolute</em> difference in rates) and <code>delta_mr_rel</code> (the <em>relative</em> diference in rates).</p>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Now we make a new object called mvc2</span></span>
<span><span class="va">mvc3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">mvc2</span>, </span>
<span>               delta_mr_abs <span class="op">=</span> <span class="va">MVCRATE_05</span> <span class="op">-</span> <span class="va">MVCRATE_17</span>,</span>
<span>               delta_mr_rel <span class="op">=</span> <span class="va">MVCRATE_05</span> <span class="op">/</span> <span class="va">MVCRATE_17</span><span class="op">)</span></span></code></pre></div>
<p>If you look at the help documentation for <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> you’ll see that the first argument is the input dataset, in this case <code>mvc</code>. Then anywhere from one to a zillion different <em>‘recode’</em> steps can be included inside the parentheses, each separated by a comma. Above, we created two new variables, one representing the <em>absolute</em> and the other representing the <em>relative</em> difference in rates between the two years.</p>
<p>We can look at the first few rows of selected columns to see the new variables:</p>
<div class="sourceCode" id="cb384"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mvc3</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   GEOID                     NAME     rural MVCRATE_05 MVCRATE_17 delta_mr_abs
## 1 13001  Appling County, Georgia     Rural   22.51111   53.99276   -31.481650
## 2 13003 Atkinson County, Georgia     Rural   61.75889   35.96260    25.796294
## 3 13005    Bacon County, Georgia     Rural   66.33813    0.00000    66.338135
## 4 13007    Baker County, Georgia non-Rural   25.20797   31.25000    -6.042034
## 5 13009  Baldwin County, Georgia non-Rural   12.95784   28.94936   -15.991517
## 6 13011    Banks County, Georgia     Rural   23.97650   32.19921    -8.222703
##   delta_mr_rel
## 1    0.4169284
## 2    1.7173090
## 3          Inf
## 4    0.8066549
## 5    0.4476038
## 6    0.7446303</code></pre>
</div>
<div id="filter" class="section level2" number="17.3">
<h2>
<span class="header-section-number">17.3</span> <code>filter()</code><a class="anchor" aria-label="anchor" href="#filter"><i class="fas fa-link"></i></a>
</h2>
<p>While <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> above was about choosing which <strong>columns</strong> you keep or drop, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> is about choosing which <strong>rows</strong> you keep or drop. If you are more familiar with SAS, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> does what an <code>if</code> or <code>where</code> statement might do.</p>
<p>Imagine we wanted to only map the <em>urban counties</em>, and omit the rural counties. We could do this be defining a filtering rule. A rule is any logical statement (e.g. a relationship that can be tested in the data and return <code>TRUE</code> or <code>FALSE</code>).</p>
<p>Here we create a new dataset, <code>mvc4</code> that is created from <code>mvc3</code> but is restricted only to <code>non-Rural</code> counties:</p>
<div class="sourceCode" id="cb386"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">mvc3</span>, <span class="va">rural</span> <span class="op">==</span> <span class="st">'non-Rural'</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">mvc3</span><span class="op">)</span> <span class="co"># dimensions (rows, columns) of the mvc3 object</span></span></code></pre></div>
<pre><code>## [1] 159   7</code></pre>
<div class="sourceCode" id="cb388"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">mvc4</span><span class="op">)</span> <span class="co"># dimensions (rows, columns) of the restricted mvc4 object</span></span></code></pre></div>
<pre><code>## [1] 102   7</code></pre>
<p>As you can see the original object (<code>mvc3</code>) had 159 rows, while the <em>filtered</em> object (<code>mvc4</code>) has only 102, reflecting the number of non-Rural counties in Georgia.</p>
<div class="rmdnote">
<p>Although the example above used only <em>one</em> filtering rule (e.g. keep only rows where <code>rural == 'non-Rural'</code>), you could construct a complex filter by including several different logical tests within the <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> function, each separated by a comma. For instance you could filter for non-rural counties with a population above 100,000 and in a specified region of the state, assuming you had variables indicating each of those values.</p>
</div>
</div>
<div id="arrange" class="section level2" number="17.4">
<h2>
<span class="header-section-number">17.4</span> <code>arrange()</code><a class="anchor" aria-label="anchor" href="#arrange"><i class="fas fa-link"></i></a>
</h2>
<p>Occasionally you might want to sort a dataset, perhaps to find the lowest or highest values of a variable, or to group like values together. Sorting with <code>dplyr</code> uses the <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> verb. By default, data is <em>arranged</em> in ascending order (either numerical or alphabetical for character variables), but you can also choose descending order as below:</p>
<div class="sourceCode" id="cb390"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">mvc3</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">MVCRATE_17</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mvc5</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   GEOID                     NAME     rural MVCRATE_05 MVCRATE_17 delta_mr_abs
## 1 13307  Webster County, Georgia     Rural   38.81988  115.16315    -76.34327
## 2 13269   Taylor County, Georgia     Rural   22.57336   73.69197    -51.11860
## 3 13165  Jenkins County, Georgia     Rural   47.00353   57.03205    -10.02853
## 4 13001  Appling County, Georgia     Rural   22.51111   53.99276    -31.48165
## 5 13087  Decatur County, Georgia non-Rural   18.17455   52.40305    -34.22851
## 6 13191 McIntosh County, Georgia non-Rural   16.11863   49.62427    -33.50564
##   delta_mr_rel
## 1    0.3370859
## 2    0.3063205
## 3    0.8241598
## 4    0.4169284
## 5    0.3468223
## 6    0.3248135</code></pre>
</div>
<div id="pipe-operator" class="section level2" number="17.5">
<h2>
<span class="header-section-number">17.5</span> <code>%&gt;%</code> Pipe operator<a class="anchor" aria-label="anchor" href="#pipe-operator"><i class="fas fa-link"></i></a>
</h2>
<p>Everything we’ve done up until now has been one step at a time, and we created five different datasets to avoid overwriting our original. But one source of coding efficiency in <code>R</code> comes from the careful <em>chaining</em> or <em>piping</em> together of multiple steps.</p>
<p>While every verb above required an <em>input dataset</em> as the first argument, when we chain steps, the functions take the <em>output</em> of the previous step as the <em>input</em> for the current step. For example this code chunk does everything we did above in one step:</p>
<div class="sourceCode" id="cb392"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc6</span> <span class="op">&lt;-</span> <span class="va">mvc</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>                             <span class="co"># remove geom column</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">NAME</span>, <span class="va">rural</span>, <span class="va">MVCRATE_05</span>, <span class="va">MVCRATE_17</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="co"># select target variables</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>delta_mr_abs <span class="op">=</span> <span class="va">MVCRATE_05</span> <span class="op">-</span> <span class="va">MVCRATE_17</span>,        <span class="co"># recode variables</span></span>
<span>        delta_mr_rel <span class="op">=</span> <span class="va">MVCRATE_05</span> <span class="op">/</span> <span class="va">MVCRATE_17</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rural</span> <span class="op">==</span> <span class="st">'non-Rural'</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>                      <span class="co"># filter (restrict) rows</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">MVCRATE_17</span><span class="op">)</span><span class="op">)</span>                             <span class="co"># sort by MVCRATE_17</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">mvc6</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 102   7</code></pre>
<div class="sourceCode" id="cb394"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mvc6</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   GEOID                      NAME     rural MVCRATE_05 MVCRATE_17 delta_mr_abs
## 1 13087   Decatur County, Georgia non-Rural   18.17455   52.40305   -34.228506
## 2 13191  McIntosh County, Georgia non-Rural   16.11863   49.62427   -33.505640
## 3 13033     Burke County, Georgia non-Rural   34.87510   39.96093    -5.085824
## 4 13189  McDuffie County, Georgia non-Rural   18.67501   37.21276   -18.537756
## 5 13055 Chattooga County, Georgia non-Rural   11.76194   36.33428   -24.572337
## 6 13227   Pickens County, Georgia non-Rural   29.32874   34.82335    -5.494612
##   delta_mr_rel
## 1    0.3468223
## 2    0.3248135
## 3    0.8727301
## 4    0.5018442
## 5    0.3237147
## 6    0.8422147</code></pre>
<p>In practice, it takes some experience to write a whole chain of steps that do what you want. I often go iteratively, adding one step at a time and checking that each step is doing what I expected.</p>
</div>
<div id="group_by-and-summarise" class="section level2" number="17.6">
<h2>
<span class="header-section-number">17.6</span> <code>group_by()</code> and <code>summarise()</code><a class="anchor" aria-label="anchor" href="#group_by-and-summarise"><i class="fas fa-link"></i></a>
</h2>
<p>A <code>dplyr</code> verb that can be incredibly important for spatial epidemiology is the combination of <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> with <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>. These two are used to aggregate and summarize data. For instance if you had data arranged with individual persons as the unit of analysis (e.g. 1 person = 1 row of data), but you wanted to aggregate them so you got counts per census tract, you could use <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> to arrange the rows into groups defined by census tract, and then use <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to do some calculation (e.g. count, mean, sum, etc) separately for each group.</p>
<p>In fact, you can enter multiple variables into the <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> argument and the result is the cross-classification of grouping. For example, imagine you had COVID-19 line listing data where each row is a single person, and rows include age (<code>young</code> or <code>old</code>) as well as county of residence. If you enter <code>group_by(county, age)</code> the data will be stratified by age within county. If you then used <code>summarise(count = n())</code>, you would get a count of individual cases in each age group and in each county. You could use this to make a map of the density of young and old cases by county.</p>
<p>An important feature of <code>sf</code> data objects when operated on by <code>dplyr</code> verbs, is that there is built in functionality to handle geography/geometry data. So for instance, imagine we wanted to create a map where we aggregated all of the <em>rural counties</em> and separately all of the <em>non-rural counties</em>.</p>
<div class="sourceCode" id="cb396"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc7</span> <span class="op">&lt;-</span> <span class="va">mvc</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">rural</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>avg_mr_17 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">MVCRATE_17</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mvc7</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   rural     avg_mr_17
## * &lt;chr&gt;         &lt;dbl&gt;
## 1 Rural          29.2
## 2 non-Rural      18.8</code></pre>
<p>As you can see (and as you might have predicted), the aggregation changed our dataset from 159 rows to 2 rows: one row for rural and one for non-rural. Let’s see what it did to the spatial data by first mapping the original data, and then mapping the aggregated data. Read <a href="intro-tmap.html#qtm">more about <code>qtm()</code></a>) and other <code>tmap</code> functions.</p>
<div class="sourceCode" id="cb398"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Using the qtm() function from tmap to create map of original data</span></span>
<span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/qtm.html">qtm</a></span><span class="op">(</span><span class="va">mvc</span>, <span class="st">'MVCRATE_17'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Using the qtm() function from tmap package to create a map</span></span>
<span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/qtm.html">qtm</a></span><span class="op">(</span><span class="va">mvc7</span>, <span class="st">'avg_mr_17'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">m1</span>, <span class="va">m2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="55-intro-dplyr_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<div class="rmdtip">
<p>As with other <code>dplyr</code> verbs (e.g. <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>), you are not constrained to using <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> with only a single variable. Returning to the example with individual observations nested within census tracts, you could use <code>new_data &lt;- individ_data %&gt;% group_by(gender, year, tract)</code> to create a file that has a row of data for each unique stratum of gender * year * census tract.</p>
</div>
<div class="rmdnote">
<p>You may see a <em>message</em> in the <code>R</code> console when you run <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> followed by <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> that says something like <code>summarise() ungrouping output override with .groups argument</code>. What this is telling you is that <code>R</code> automatically <em>ungrouped</em> your data. More specifically it removed grouping by the <em>last <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> variable, to avoid unintended consequences from persistent grouping. If you <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> two or more variables it </em>only drops the last grouping*, so other grouping may persist. All grouping can be removed by adding <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup()</a></code> after the <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code>.</p>
</div>
</div>
<div id="join" class="section level2" number="17.7">
<h2>
<span class="header-section-number">17.7</span> <code>join()</code><a class="anchor" aria-label="anchor" href="#join"><i class="fas fa-link"></i></a>
</h2>
<p>Merging data is so common in epidemiology, but also prone to so many unintended consequences that it is important to pay attention to the options for successful merges or ‘<em>table joins</em>’ as they are called in the parlance of relational databases.</p>
<p>Because of the challenges with getting the desired output from a merge or <code>join()</code>, <code>dplyr</code> has a set of verbs including: <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join()</a></code> and more. Here is documentation of the <a href="https://dplyr.tidyverse.org/reference/join.html">many ways to join!</a></p>
<p>A join is simply a way to merge two tables when they have some common key or ID variable. For our purposes in this class I want to focus on several key features of joining that are important for spatial analysis.</p>
<p>For this explanation we will work with two separate files: an <em>aspatial <code>data.frame</code></em> with the motor vehicle crash data called <code>mvc.df</code>; and a <code>sf</code> object of all U.S. counties, called <code>us</code>. The unit of analysis in each is the county, there is a common ID or key variable in the county FIPS code (named <code>GEOID</code>), but they have a different number of rows:</p>
<div class="sourceCode" id="cb399"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">mvc.df</span><span class="op">)</span>  <span class="co"># this is dimensions for the aspatial attribute data</span></span></code></pre></div>
<pre><code>## [1] 159  17</code></pre>
<div class="sourceCode" id="cb401"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">us</span><span class="op">)</span>      <span class="co"># this is dimensions for the spatial county polygon sf data</span></span></code></pre></div>
<pre><code>## [1] 3221   13</code></pre>
<p>As expected, the <code>mvc.df</code> has the <span class="math inline">\(n=159\)</span> counties that makeup Georgia. However the spatial/geography information has <span class="math inline">\(n=3220\)</span> rows, corresponding to the number of U.S. counties and territories.</p>
<p>First, the difference between the <code>xxxx_join()</code> is how the two tables relate to one another. For most purposes a <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> or <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code> will do the trick. Here is the difference: a <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> <strong>starts with</strong> the first object and joins it to the second. In contrast the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code> <strong>starts with</strong> the second object and joins it to the first. What does that mean?</p>
<div class="sourceCode" id="cb403"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># left join, starting with mvc.df as the first object, us as the second</span></span>
<span><span class="va">test.left</span> <span class="op">&lt;-</span> <span class="va">mvc.df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">us</span>, by <span class="op">=</span> <span class="st">'GEOID'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">test.left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 159  29</code></pre>
<div class="sourceCode" id="cb405"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">test.left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "data.frame"</code></pre>
<div class="sourceCode" id="cb407"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># right join, starting with mvc.df as the first object</span></span>
<span><span class="va">test.right</span> <span class="op">&lt;-</span> <span class="va">us</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">mvc.df</span>, by <span class="op">=</span> <span class="st">'GEOID'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">test.right</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 3221   29</code></pre>
<div class="sourceCode" id="cb409"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">test.right</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "sf"         "data.frame"</code></pre>
<p><strong>What did we learn?</strong></p>
<ul>
<li>The number of rows in the output dataset is dictated by two things:</li>
<li>the order the objects are written (e.g. in this case <code>mvc.df</code> was always <em>first</em> and <code>us</code> was always <em>second</em>, contained within the <code>join()</code>)</li>
<li>the direction of the join. In a <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> the merge <em>begins with</em> <code>mvc.df</code>, which limits the output to only 159 rows. In contrast with <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code> the merge <em>begins with</em> <code>us</code>, which limits the output to 3220 rows.</li>
<li>The class of the output data depends on which object was <em>first</em>. Notice that in the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code>, because we started with an aspatial <code>data.frame</code>, the output is also an aspatial <code>data.frame</code> (although the <code>geom</code> column <strong>is now incorporated</strong>!). In contrast with the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code> which put the <code>sf</code> object <code>us</code> first, the class was <code>sf</code>.</li>
</ul>
<p>This means that when merging or joining you should think about whether you want <em>all of the rows</em> of data to go to the output, or only some; and think about whether (or how) you can make the <code>sf</code> object be first.</p>
<p>In the scenario above, we only want <span class="math inline">\(n=159\)</span> rows, and thus want to exclude all of the non-Georgia counties. That means we must have <code>mvc.df</code> first. Therefore, we could <em>force</em> the object to be of class <code>sf</code> like this (<a href="sf-overview.html#st-as-sf">also see info here</a>):</p>
<div class="sourceCode" id="cb411"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">test.left</span> <span class="op">&lt;-</span> <span class="va">mvc.df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">us</span>, by <span class="op">=</span> <span class="st">'GEOID'</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">test.left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 159  29</code></pre>
<div class="sourceCode" id="cb413"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">test.left</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "sf"         "data.frame"</code></pre>
<p><strong>Joining when Key/ID variables have different names</strong></p>
<p>Sometimes we have a common variable, such as the county FIPS code, but the variable names are different. For example in the code below, the column storing the unique county ID for the <code>mvc.df</code> is named <code>GEOID</code>. However the column in the <code>sf</code> object <code>us</code> that stores the unique county ID is named <code>FIPS</code>. It is still possible to use the <code>join()</code> verbs by relating them (inside a <code><a href="https://rdrr.io/r/base/c.html">c()</a></code> concatenation) in the order in which the datasets are introduced.</p>
<div class="sourceCode" id="cb415"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># if us had the FIPS code stored in the column named 'FIPS'</span></span>
<span><span class="va">test.left</span> <span class="op">&lt;-</span> <span class="va">mvc.df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">us</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'GEOID'</span> <span class="op">=</span> <span class="st">'FIPS'</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="pivot_" class="section level2" number="17.8">
<h2>
<span class="header-section-number">17.8</span> Reshaping (transposing) data<a class="anchor" aria-label="anchor" href="#pivot_"><i class="fas fa-link"></i></a>
</h2>
<p>There are numerous other intermediate to advanced data manipulation options available in <code>dplyr</code> and the <code>tidyverse</code>, but most are outside of the scope of this course. One final verb that represents a more sophisticated kind of data change, is however useful in preparing spatial data. That is the tools to <strong>transpose</strong> or <strong>reshape</strong> a rectangular dataset from <em>wide</em> to <em>long</em> or vice versa. Transposing is useful when, for example, you have a column with a disease rate for each of several years (these data are <em>wide</em>), but you want a dataset where a single column contains the rate and a separate column indicates the year (these data are <em>long</em>). <a href="https://tidyr.tidyverse.org/articles/pivot.html">This article introduces the notion of <em>pivoting</em> data</a>; you can also review <a href="https://r4ds.had.co.nz/tidy-data.html#pivoting">this section in R for Data Science</a></p>
<p>Two related verbs help pivot <code>tidy</code> data one direction or the other:</p>
<div id="pivot_longer-for-going-from-wide-to-long" class="section level3" number="17.8.1">
<h3>
<span class="header-section-number">17.8.1</span> <code>pivot_longer()</code> for going from wide to long<a class="anchor" aria-label="anchor" href="#pivot_longer-for-going-from-wide-to-long"><i class="fas fa-link"></i></a>
</h3>
<p>Reviewing the article linked in the previous paragraph (or searching the help documentation) will give you more detail. But as an example we will look at how to take our current <code>mvc</code> dataset, which contains the motor vehicle crash mortality rate for each county from three different years (2005, 2014, 2017) as separate columns (e.g. it is <em>wide</em>):</p>
<div class="sourceCode" id="cb416"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># this code shows the first 6 rows (the head) of the relevant variables</span></span>
<span><span class="va">mvc</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">NAME</span>, <span class="va">MVCRATE_05</span>, <span class="va">MVCRATE_14</span>, <span class="va">MVCRATE_17</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   GEOID                     NAME MVCRATE_05 MVCRATE_14 MVCRATE_17
## 1 13001  Appling County, Georgia   22.51111   21.57497   53.99276
## 2 13003 Atkinson County, Georgia   61.75889   12.16101   35.96260
## 3 13005    Bacon County, Georgia   66.33813   44.32231    0.00000
## 4 13007    Baker County, Georgia   25.20797   30.72197   31.25000
## 5 13009  Baldwin County, Georgia   12.95784   17.42578   28.94936
## 6 13011    Banks County, Georgia   23.97650   43.72779   32.19921</code></pre>
<p>For mapping a time-series it is often beneficial to have the data <strong>long</strong>, which is to say we want the data with a single column for <code>mvc_rate</code> and a separate column for <code>year</code>, and then we can choose to create a map for each subset (defined by year) of the data.</p>
<div class="sourceCode" id="cb418"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc_long</span> <span class="op">&lt;-</span> <span class="va">mvc</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">GEOID</span>, <span class="va">NAME</span>, <span class="va">MVCRATE_05</span>, <span class="va">MVCRATE_14</span>, <span class="va">MVCRATE_17</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"MVCRATE"</span><span class="op">)</span>,</span>
<span>               names_to <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">".value"</span>, <span class="st">"year"</span><span class="op">)</span>,</span>
<span>               values_to <span class="op">=</span> <span class="st">"mvc_rate"</span>,</span>
<span>               names_sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>year <span class="op">=</span> <span class="fl">2000</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">year</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>First let’s look at the results, and then I’ll walk through each of the steps in the code chunk above:</p>
<div class="sourceCode" id="cb419"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc_long</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   GEOID NAME                      year MVCRATE
##   &lt;chr&gt; &lt;chr&gt;                    &lt;dbl&gt;   &lt;dbl&gt;
## 1 13001 Appling County, Georgia   2005    22.5
## 2 13001 Appling County, Georgia   2014    21.6
## 3 13001 Appling County, Georgia   2017    54.0
## 4 13003 Atkinson County, Georgia  2005    61.8
## 5 13003 Atkinson County, Georgia  2014    12.2
## 6 13003 Atkinson County, Georgia  2017    36.0</code></pre>
<p>As you can see, we now have <strong>3 rows</strong> for Appling County (GEOID 13001): one for each of the three years, with different <code>MVCRATE</code> in each. That is a <em>long</em> dataset. So how did that code work? Here is a step-by-step of what that code chunk did:</p>
<ol style="list-style-type: decimal">
<li>The first step was to create a new object, <code>mvc_long</code> that will be the outcome of all of the steps piped together. The input to the pipe is the original dataset, <code>mvc</code>.</li>
<li>The use of <code><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble()</a></code> is a current work around to an annoying <em>‘feature’</em> of the <code>pivot_*</code> functions and that is that they don’t play well with <code>sf</code> data classes. So when we use <code><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble()</a></code> we are essentially removing the class designation, (making it a <code>tibble</code> which is a tidy object); importantly this is <em>different from</em> <code>st_set_geometry(NULL)</code> which actually omits the geometry column (e.g. <a href="#sf_overview">see additional detail here</a>).</li>
<li>I used <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> to pull out only the variables of interest, although you could leave other variables if desired.</li>
<li>
<code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> can be called in several ways. The way I call it here, I first specified <strong>which columns to pivot</strong> by defining the <code>cols =</code> argument to be all variables that <em>start with</em> the phrase <code>MVCRATE</code>. <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with()</a></code> is another utility function in <code>dplyr</code>. So this step told <code>R</code> that the columns I wanted changed were the three called <code>MVCRATE_05</code>, <code>MVCRATE_12</code> and <code>MVCRATE_17</code>
</li>
<li>The <code>names_to =</code> argument defines the column name <em>in the new dataset</em> that will delineate between the three variables (e.g. <code>MVCRATE_05</code>, etc). In our case we wanted the value to be the <strong>year</strong> not the word <code>MVCRATE_12</code>. To accomplish this we had to do some extra work:</li>
</ol>
<ul>
<li>First, note that we used the option <code>names_sep = '_'</code>. That is another utility function that says we want to break a string into parts wherever a designated separated (e.g. the underscore, <code>_</code>) occurs. So this will take the column name <code>MVCRATE_05</code> and break it at the underscore to return two parts: <code>MVCRATE</code> and <code>05</code>.</li>
<li>Because breaking it into two would produce <em>two answers</em>, we had to make <em>two variable names</em> in the <code>names_to =</code> to hold them. Thus <code>names_to = c(".value", "year")</code>. In other words the column labeled <code>.variable</code> will hold the value <code>MVCRATE</code> and the column <code>year</code> will hold the value <code>05</code>
</li>
<li>
<code>'.value'</code> is actually a special value in this instance. It is a way of designating that the first part was essentially <em>junk</em>. As such it will automatically be discarded.</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>
<code>values_to = 'mvcrate'</code>. This is where we define the name in the <em>new dataset</em> that will hold the actual value (e.g. the MVC mortality rate itself.)</li>
<li>The <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> step is just a way to take the year fragment (e.g. <code>05</code>, <code>12</code>, <code>17</code>) and make it into calendar years by first making it numeric, and then simply adding 2000.</li>
<li>The final step, <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code> is because all of the manipulations above actually removed the objects designation as class <code>sf</code>. Importantly, it DID NOT remove the <code>geom</code> column, but the object is not recognized (e.g. by <code>tmap</code>) as a spatial object. So <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code> simply declares that it is in fact <code>sf</code>.</li>
</ol>
<p>The best way to wrap your head around this is to start trying to reshape or transpose data you have on hand. You may need to look for additional help or examples online, but with time it will become more intuitive.</p>
<p>To see <em>why</em> you might have gone through all of that work, we will use the <code><a href="https://rdrr.io/pkg/tmap/man/tm_facets.html">tm_facets()</a></code> (read more about<a href="intro-tmap.html#tmap-facet"><code>tmap_facets()</code> here</a>).</p>
<div class="sourceCode" id="cb421"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">mvc_long</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'MVCRATE'</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_facets.html">tm_facets</a></span><span class="op">(</span>by <span class="op">=</span> <span class="st">'year'</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="55-intro-dplyr_files/figure-html/unnamed-chunk-20-1.png" width="672"></div>
</div>
<div id="pivot_wider" class="section level3" number="17.8.2">
<h3>
<span class="header-section-number">17.8.2</span> <code>pivot_wider()</code><a class="anchor" aria-label="anchor" href="#pivot_wider"><i class="fas fa-link"></i></a>
</h3>
<p>Of course it is also possible to go the other way, from long to wide. This often is easier. Here is some code to return to our original shape:</p>
<div class="sourceCode" id="cb422"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc_wide</span> <span class="op">&lt;-</span> <span class="va">mvc_long</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>my_var <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'MVCRATE '</span>, <span class="va">year</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">year</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span>names_from <span class="op">=</span> <span class="va">my_var</span>,</span>
<span>              values_from <span class="op">=</span> <span class="va">MVCRATE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Take a look at the output:</p>
<div class="sourceCode" id="cb423"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mvc_wide</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_set_geometry</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   GEOID NAME                     `MVCRATE 2005` `MVCRATE 2014` `MVCRATE 2017`
##   &lt;chr&gt; &lt;chr&gt;                             &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1 13001 Appling County, Georgia            22.5           21.6           54.0
## 2 13003 Atkinson County, Georgia           61.8           12.2           36.0
## 3 13005 Bacon County, Georgia              66.3           44.3            0  
## 4 13007 Baker County, Georgia              25.2           30.7           31.2
## 5 13009 Baldwin County, Georgia            13.0           17.4           28.9
## 6 13011 Banks County, Georgia              24.0           43.7           32.2</code></pre>
<p>It appears that we have returned to <em>1 row per county</em>. So what were all of those steps?</p>
<ol style="list-style-type: decimal">
<li>Once again, we start by removing the class designation <code>sf</code> but calling <code><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble()</a></code>
</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> is called to re-create a variable that will become the column names.</li>
<li>We no longer need the old <code>year</code> variable so I omit it with <code>select(-year)</code>
</li>
<li>Finally the <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code> call has arguments defining which <em>current</em> variable contains the informatino that will be the <em>new</em> column name (<code>names_from =</code>) and which <em>current</em> variable contains the information that will population the cells within that column (<code>values_from =</code>).</li>
</ol>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="sf-overview.html"><span class="header-section-number">16</span> Tips for working with sf data class</a></div>
<div class="next"><a href="intro-tmap.html"><span class="header-section-number">18</span> Tips for using tmap</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#dplyr"><span class="header-section-number">17</span> Tips for using dplyr</a></li>
<li><a class="nav-link" href="#select"><span class="header-section-number">17.1</span> select()</a></li>
<li><a class="nav-link" href="#mutate"><span class="header-section-number">17.2</span> mutate()</a></li>
<li><a class="nav-link" href="#filter"><span class="header-section-number">17.3</span> filter()</a></li>
<li><a class="nav-link" href="#arrange"><span class="header-section-number">17.4</span> arrange()</a></li>
<li><a class="nav-link" href="#pipe-operator"><span class="header-section-number">17.5</span> %&gt;% Pipe operator</a></li>
<li><a class="nav-link" href="#group_by-and-summarise"><span class="header-section-number">17.6</span> group_by() and summarise()</a></li>
<li><a class="nav-link" href="#join"><span class="header-section-number">17.7</span> join()</a></li>
<li>
<a class="nav-link" href="#pivot_"><span class="header-section-number">17.8</span> Reshaping (transposing) data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#pivot_longer-for-going-from-wide-to-long"><span class="header-section-number">17.8.1</span> pivot_longer() for going from wide to long</a></li>
<li><a class="nav-link" href="#pivot_wider"><span class="header-section-number">17.8.2</span> pivot_wider()</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/mkram01/EPI563-SpatialEPI/blob/master/55-intro-dplyr.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/mkram01/EPI563-SpatialEPI/edit/master/55-intro-dplyr.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EPI 563: Spatial Epidemiology, Fall 2023</strong>" was written by Michael Kramer. It was last built on Last updated: 2023-08-14.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
