<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Week 12 Spatial Regression III: Geographically Weighted Regression | EPI 563: Spatial Epidemiology, Fall 2022</title>
<meta name="author" content="Michael Kramer">
<meta name="description" content="12.1 Getting Ready  12.1.1 Learning objectives  TABLE 1.1: Learning objectives by weekly module After this module you should be able to…Explain and relate spatial non-stationarity to epidemiologic...">
<meta name="generator" content="bookdown 0.28 with bs4_book()">
<meta property="og:title" content="Week 12 Spatial Regression III: Geographically Weighted Regression | EPI 563: Spatial Epidemiology, Fall 2022">
<meta property="og:type" content="book">
<meta property="og:description" content="12.1 Getting Ready  12.1.1 Learning objectives  TABLE 1.1: Learning objectives by weekly module After this module you should be able to…Explain and relate spatial non-stationarity to epidemiologic...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Week 12 Spatial Regression III: Geographically Weighted Regression | EPI 563: Spatial Epidemiology, Fall 2022">
<meta name="twitter:description" content="12.1 Getting Ready  12.1.1 Learning objectives  TABLE 1.1: Learning objectives by weekly module After this module you should be able to…Explain and relate spatial non-stationarity to epidemiologic...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">EPI 563: Spatial Epidemiology, Fall 2022</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">How to use this eBook</a></li>
<li><a class="" href="download-ebook.html">Download eBook</a></li>
<li class="book-part">Getting ready…</li>
<li><a class="" href="software-installation.html">Software installation</a></li>
<li><a class="" href="installing-packages-for-this-course.html">Installing packages for this course</a></li>
<li class="book-part">Weekly Modules</li>
<li><a class="" href="locating-spatial-epidemiology.html"><span class="header-section-number">1</span> Locating Spatial Epidemiology</a></li>
<li><a class="" href="cartography-for-epidemiology-i.html"><span class="header-section-number">2</span> Cartography for Epidemiology I</a></li>
<li><a class="" href="cartography-for-epidemiology-ii-spatial-ethics.html"><span class="header-section-number">3</span> Cartography for Epidemiology II: Spatial Ethics</a></li>
<li><a class="" href="disease-mapping-i-aspatial-empirical-bayes.html"><span class="header-section-number">4</span> Disease Mapping I: Aspatial Empirical Bayes</a></li>
<li><a class="" href="disease-mapping-ii-spatial-empirical-bayes.html"><span class="header-section-number">5</span> Disease Mapping II: Spatial Empirical Bayes</a></li>
<li><a class="" href="disease-mapping-iii-introduction-to-fully-bayesian-mapping.html"><span class="header-section-number">6</span> Disease Mapping III: Introduction to Fully Bayesian mapping</a></li>
<li><a class="" href="disease-mapping-iv-kernel-density-estimation.html"><span class="header-section-number">7</span> Disease Mapping IV: Kernel Density Estimation</a></li>
<li><a class="" href="spatial-structure-and-clustering-i-morans-i-and-lisa.html"><span class="header-section-number">8</span> Spatial Structure and Clustering I: Moran’s I and LISA</a></li>
<li><a class="" href="spatial-structure-and-clustering-ii-spatial-scan-statistics.html"><span class="header-section-number">9</span> Spatial Structure and Clustering II: Spatial scan statistics</a></li>
<li><a class="" href="spatreg1.html"><span class="header-section-number">10</span> Spatial Regression I: Spatializing aspatial regression residuals</a></li>
<li><a class="" href="spatial-regression-ii-spatial-econometric-regression.html"><span class="header-section-number">11</span> Spatial Regression II: Spatial econometric regression</a></li>
<li><a class="active" href="spatial-regression-iii-geographically-weighted-regression.html"><span class="header-section-number">12</span> Spatial Regression III: Geographically Weighted Regression</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="reproducibility-and-projects-in-r.html"><span class="header-section-number">13</span> Reproducibility and Projects in R</a></li>
<li><a class="" href="introduction-to-r-notebooks.html"><span class="header-section-number">14</span> Introduction to R Notebooks</a></li>
<li><a class="" href="formatting-markdown-and-notebooks.html"><span class="header-section-number">15</span> Formatting Markdown and Notebooks</a></li>
<li><a class="" href="sf-overview.html"><span class="header-section-number">16</span> Tips for working with sf data class</a></li>
<li><a class="" href="dplyr.html"><span class="header-section-number">17</span> Tips for using dplyr</a></li>
<li><a class="" href="intro-tmap.html"><span class="header-section-number">18</span> Tips for using tmap</a></li>
<li class="book-part">Weekly Lab Handouts</li>
<li><a class="" href="week-0-getting-oriented-to-r-with-spatial.html"><span class="header-section-number">20</span> Week 0: Getting oriented to R with spatial</a></li>
<li><a class="" href="week-1-introduction-to-spatial-data-and-mapping.html"><span class="header-section-number">21</span> Week 1: Introduction to spatial data and mapping</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/mkram01/EPI563-SpatialEPI">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="spatial-regression-iii-geographically-weighted-regression" class="section level1" number="12">
<h1>
<span class="header-section-number">Week 12</span> Spatial Regression III: Geographically Weighted Regression<a class="anchor" aria-label="anchor" href="#spatial-regression-iii-geographically-weighted-regression"><i class="fas fa-link"></i></a>
</h1>
<div id="getting-ready-10" class="section level2" number="12.1">
<h2>
<span class="header-section-number">12.1</span> Getting Ready<a class="anchor" aria-label="anchor" href="#getting-ready-10"><i class="fas fa-link"></i></a>
</h2>
<div id="learning-objectives-11" class="section level3" number="12.1.1">
<h3>
<span class="header-section-number">12.1.1</span> Learning objectives<a class="anchor" aria-label="anchor" href="#learning-objectives-11"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 100%; margin-left: auto; margin-right: auto;  " id="learning-ob">
<caption style="caption-side: top; text-align: center;">
<span id="tab:learning-ob">TABLE 1.1: </span> Learning objectives by weekly module</caption>
<col>
<tr><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(204, 204, 204); font-weight: bold;">After this module you should be able to…</th></tr>
<tr><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Explain and relate spatial non-stationarity to epidemiologic concepts of heterogeneity</td></tr>
<tr><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(230, 230, 230); font-weight: normal;">Use geographically weighted regression to produce and interpret epidemiologic parameters from point and polygon data</td></tr>
</table></div>
</div>
<div id="important-vocabulary-11" class="section level3" number="12.1.2">
<h3>
<span class="header-section-number">12.1.2</span> Important Vocabulary<a class="anchor" aria-label="anchor" href="#important-vocabulary-11"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-2">
<caption style="caption-side: top; text-align: center;">
<span id="tab:unnamed-chunk-2">TABLE 1.2: </span> Vocabulary for Week 12</caption>
<col>
<col>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Term</span></th>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Definition</span></th>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Data generating process</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">The true underlying causal structure that gives rise to (generates) the data from which you sampled. The data generating process is not typically known. We use models to try to emulate or approximate the data generating process.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial Durbin model</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Spatial econometric model in which sptaially lagged summary of neighbors values of the *covariates* and of the *outcome*. Spatially lagged covariates suggest exposure in neighboring places affects outcome in index location.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial Econometrics</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A sub-field of statistics bridging econometrics and spatial analysis, wherein theoretical properties, dependencies, and interactions of spatially referenced data are analyzed in a regression framework.</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial error model</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Spatial econometric model in which unmeasured or unobserved spatially clustered predictors of the outcome produce residual autocorrelation in regression model residuals that is not accounted for by the main effects of measured covariates</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial lag model</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">Spatial econometric model in which a spatially lagged sumary of neighbors values of the dependent (outcome) variable is included on the right-hand side of the model. This pattern theoretically suggests a diffusion or contagion process of the *outcome*</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatially lagged variable</td>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">The weighted sum or weighted average of the neighboring values for that variable. The variable could be a spatially lagged outcome or spatially lagged covariate/predictor</td>
</tr>
</table></div>
</div>
</div>
<div id="spatial-thinking-in-epidemiology-9" class="section level2" number="12.2">
<h2>
<span class="header-section-number">12.2</span> Spatial Thinking in Epidemiology<a class="anchor" aria-label="anchor" href="#spatial-thinking-in-epidemiology-9"><i class="fas fa-link"></i></a>
</h2>
<div id="non-stationarity-and-spatially-varying-relationships" class="section level3" number="12.2.1">
<h3>
<span class="header-section-number">12.2.1</span> Non-stationarity and spatially varying relationships<a class="anchor" aria-label="anchor" href="#non-stationarity-and-spatially-varying-relationships"><i class="fas fa-link"></i></a>
</h3>
<p>The latter half of the course has focused on how to estimate, describe, and test for epidemiologically relevant <em>spatial structure</em> or <em>spatial heterogeneity</em> in population health data. Briefly these have been the topics covered following the introductory Epidemiologic Cartography module:</p>
<ol style="list-style-type: decimal">
<li>
<strong>Disease mapping of spatial heterogeneity</strong> to describe epidemiologically meaningful patterns of disease over space, possibly even in the presence of sparse data that reduces certainty and precision of estimates. The tools of disease mapping focused on stabilizing and smoothing parameter estimates, possibly in formal testing for statistical deviation from expectations, and contrasting local rates to global rates (e.g. SMRs).</li>
<li>
<strong>Global and local spatial auto correlation</strong> as ways to describe the tendency for univariate data (e.g. health outcomes) to be spatially dependent. These tests described the degree to which (and in the case of <em>local tests</em>, the location <em>where</em>) outcomes clustered in space. Spatial auto correlation is a fundamental characteristic of spatial structure, and thus very useful in exploring and describing data. Importantly, testing for spatial auto correlation does not explain <strong>why</strong> population events are spatially dependent or clustered.</li>
<li>
<strong>Spatial scan statistics</strong> were a class of tests designed as an alternative (or complementary) tool for testing for the presence of spatially-clustered health events. While spatial auto correlation tested explicitly for spatial-dependence between locations, spatial scan statistics tested for statistically unusual extreme rates or risks of disease within arbitrarily small/large search windows. In that way spatial scan statistics describe spatial structure through the lens of <em>spatial homogeneity (constant risk) or heterogeneity</em>. However, spatial scan statistics share with spatial auto correlation statistics the lack of explanatory insight as to <em>how</em> or <em>why</em> disease intensity varies in space.</li>
<li>
<strong>Spatial auto correlation tests of aspatial regression residuals</strong> was the first step towards describing spatial structure as a function of <em>multi-dimensional</em> (multiple variable) predictors. By fitting multivariable regression models that could include predictors that might <em>explain</em> the reason for spatial structure, this approach began the intersection of multivariable regression with spatial structure. This approach to <em>spatializing aspatial regression</em> is a useful exploratory or diagnostic step, which could result in insight to understand why or how spatial structure is generated. However, often residual spatial auto correlation in residuals exists after inclusion of important measured variables, and the question remains: <em>What produces residual dependence?</em>
</li>
</ol>
<p><em>This brings us to geographically weighted statistics</em>. While the order of topics covered above is written in a somewhat hierarchical or linear-sequential manner (each step follows and expands on the preceding), the course of analysis is not always this way. In particular, geographically weighted statistics are not the culmination of all spatial analysis to date, but instead represent an alternative way to view the <em>data generating process</em>.</p>
<div class="rmdnote">
<p>The <strong>data generating process</strong> ideally refers to the the biological, social, and ecologic mechanisms and processes that collectively give rise to or <em>generate</em> the data we observed.</p>
<p>We often use statistical models to approximate what we believe is the underlying process that generated data. To the extent that we correctly describe the data generating process that gave rise to the data, we can most efficiently (and validly) carry out analysis on the observed data.</p>
</div>
</div>
<div id="introducing-geographically-weighted-regression" class="section level3" number="12.2.2">
<h3>
<span class="header-section-number">12.2.2</span> Introducing geographically weighted regression<a class="anchor" aria-label="anchor" href="#introducing-geographically-weighted-regression"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Stationarity</strong> is the assumption that a statistic or parameter estimate is, on average, constant or homogeneous across samples. By extension, <strong>spatial stationarity</strong> is the assumption that a statistic for a given study region is constant regardless of the spatial location.</p>
<p>Examples of <strong>spatial non-stationarity</strong> were previously introduced with <em>geographically weighted summary statistics</em> (e.g. in <a href="disease-mapping-iv-kernel-density-estimation.html#gwss">Disease Mapping 3</a>), and more generally with the idea of spatially heterogeneous mean intensity of disease, as was tested with the spatial scan statistic or Poisson tests of excess risk. This notion that some places have <em>higher</em> and some places have <em>lower</em> risk or rates suggests that a single global statistic (e.g. the overall risk or rate) is not adequate for describing the health of the population; instead a set of local statistics are needed.</p>
<p>Spatially non-stationary disease intensity (e.g. spatial heterogeneity) is an example of <strong>first order spatial variation</strong>. In this context, ‘<em>first order</em>’ refers to the first statistical moment which is the mean expected value. So <em>first order spatial variation</em> is a variation in the mean disease rate.</p>
<p>But we may also be interested in <strong>second order spatial variation</strong>, which refers not to the mean, but to the <em>covariance</em> among variables. Therefore, second order spatial processes reflect an interest in whether <em>relationships</em> among variables are constant (global; stationary) or heterogeneous (local; non-stationary).</p>
<p><em>Geographically weighted</em> <strong>regression</strong> (GWR) is the natural extension to <em>geographically weights</em> <strong>summary statistics</strong> when we wish to go from single variable mean intensity (first order process) to describe multivariable covariance patterns (second order process) in space. GWR is quite simply multivariable regression carried out iteratively with restrictions to specific geographic sub-sets of the entire study region, with an interest in estimating not just a single set of regression coefficients, <span class="math inline">\(\beta\)</span>, but instead a set of coefficients with one for each geographic sub-region (e.g. <span class="math inline">\(\beta_{x,y}\)</span>}).</p>
<p>Just as we had tools for statistically testing whether the spatial intensity (e.g. rate, prevalence) of disease was homogeneous versus heterogeneous, we can similarly use statistical tests to compare the fit of the <em>global</em> (stationary) regression model to the fit of the <em>local</em> (non-stationary) model. If there is evidence of better fit, even after penalty for multiple comparisons, then we can proceed with interpreting results from the GWR.</p>
<p>Geographically weighted regression is therefore a powerful tool for further characterizing or understanding the data generating process. It provides insight into spatial relationships by:</p>
<ol style="list-style-type: lower-alpha">
<li>permitting local analysis of multivariable relationships; and</li>
<li>statistically testing whether a single global model fits the data better or worse than an ensemble of local models, even after penalizing for multiple comparison.</li>
</ol>
<p>While this tool represents a significant step forward in our ability as spatial epidemiologists to understand spatial variation in population health – even accounting for confounding and heterogeneity of effects – the methods have several well-described limitations that collectively lead us to treat GWR as an <em>exploratory</em> tool:</p>
<ul>
<li>
<strong>Local multi-collinearity</strong>: Regression with highly colinear (highly correlated) predictor variables can produce statistically unstable regression coefficients due to variance inflation. In a single global dataset there may be sufficient distinction among variables to avoid this problem. However – because covariates may be spatially clustered – it is common that collinearity is a greater problem when restricting to specific spatial sub-regions. Thus, GWR estimates could suffer from variance inflation and instability of beta coefficients.</li>
<li>
<strong>Multiple comparison</strong>: The analytic strategy of GWR is to re-fit a regression model multiple times, once for each sub-region in a study area. This quite reasonably raises concerns for multiple comparisons, particularly if statistical hypothesis tests are being conducted.</li>
<li>
<strong>Model overfitting</strong>: A known concern in regression modeling is that coefficients can be biased when the model begins to describe the ‘<em>random error</em>’ rather than the underlying relationships, reducing the generalizability of coefficients. This can occur from including too many covariates for a given number of observations. Therefore the process of restricting the geographic region for model fitting in GWR can lead to local overfitting.</li>
<li>
<strong>Local sensitivity to outliers</strong>: In global regression, we are aware that it is possible for single extreme observations to have undue influence on the estimation of regression coefficient. In linear regression, residual diagnostics focus on influence statistics to diagnose this problem. With GWR, the refitting of a model in multiple subsets of the data increases the risk that at least some of the local fits will be unduly influenced by outlier observations.</li>
<li>
<strong>Bandwidth selection</strong>: Just as we discussed when introducing kernel density estimation in Disease Mapping, a key driver of results when using kernel density functions to smooth or weight data is the bandwidth. Bandwidth is the radius of the kernel search area. In GWR, the kernel bandwidth defines how many observations (and with what weight) will be included in each local regression. A larger bandwidth will include more of the total data, but will limit the amount of spatial variation in coefficients. In contrast a smaller bandwidth will include less data in each fit but maximize the possible identification of local spatial variation.</li>
</ul>
</div>
<div id="making-epidemiologic-meaning-of-spatially-varying-coefficients" class="section level3" number="12.2.3">
<h3>
<span class="header-section-number">12.2.3</span> Making epidemiologic meaning of spatially varying coefficients<a class="anchor" aria-label="anchor" href="#making-epidemiologic-meaning-of-spatially-varying-coefficients"><i class="fas fa-link"></i></a>
</h3>
<p>Although <em>spatial heterogeneity</em> has been a theme throughout this course, it may not be obvious what exactly heterogeneity in regression coefficients means or tells us as epidemiologists. One analogy – and to be clear it is only an imperfect analogy and not an exact correspondence – is to conceive of <em>spatially varying regression coefficients</em> as akin to <em>statistical interaction</em> in non-spatial models.</p>
<p>In epidemiology, a powerful and important concept for describing causal effects of exposures or interventions on health outcomes, is that of <em>effect measure modification</em>. This is the idea that the causal effect of an exposure on the outcome is not homogeneous (e.g. constant; stationary), but instead varies or <em>depends on</em> the value of a second covariate (e.g. is heterogeneous or non-stationary). An example of effect measure modification in non-spatial epidemiology would be if the magnitude of the causal effect of a drug treatment for preventing death in a given disease was larger in women as compared to men.</p>
<p>While it is common for analysts of epidemiologic data to incorporate <em>interaction terms</em> in multivariable regression in an effort to identify and estimate effect measure modification, it is important to recall that statistical interaction is not always (or perhaps is rarely) equivalent to causal effect measure modification. However, statistical interactions are tests for the idea of heterogeneity or variation in the magnitude (e.g. on an additive or multiplicative scale depending on the model being fit) of relationship or association between predictor and outcome.</p>
<p>Therefore, interpreting the spatially varying coefficients from a geographically weighted regression could be seen to be similar as interpreting the heterogeneous correlation evidenced by a statistical interaction in a non-spatial model: it describes <em>where</em> and <em>to what degree</em> the association between exposure and outcome differs or varies.</p>
<p>If the model identified a causal data generating process, statistical interaction could indicate the presence of a form of <em>spatial effect measure modification</em>, or identification of how something about <em>location</em> modifies the relationship between exposure and outcome.</p>
</div>
<div id="distinguishing-variation-in-prevalence-from-variation-in-correlation" class="section level3" number="12.2.4">
<h3>
<span class="header-section-number">12.2.4</span> Distinguishing variation in <strong>prevalence</strong> from variation in <strong>correlation</strong><a class="anchor" aria-label="anchor" href="#distinguishing-variation-in-prevalence-from-variation-in-correlation"><i class="fas fa-link"></i></a>
</h3>
<p>One final conceptual challenge in interpreting spatially varying coefficients (and for interpreting statistical interactions in general) is to be clear about the role of spatially varying covariate <em>prevalence</em> as compared to the role of spatially varying <em>correlation</em> of covariate with outcome.</p>
<p>The GWR describes geographic regions where the magnitude of association between predictor/covariate and outcome is larger or smaller. However, that should not be confused with the overall prevalence of the predictor in those areas.</p>
<p>For example, examine the maps below illustrating the <em>prevalence</em> of smoking and poor physical health in Atlanta census tracts (predictors or exposures; top two panels) as compared to the <em>strength of association</em> between each covariate and the outcome, poor mental health (bottom two panels).</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="images/gwr-prevalence.png" alt="GWR: Prevalence vs. Correlation"><p class="caption">
FIGURE 2.1: GWR: Prevalence vs. Correlation
</p>
</div>
<p>The interpretation of regression coefficients in the bottom two maps is “<em>the change in <span class="math inline">\(Y\)</span> for each one-unit change in <span class="math inline">\(X\)</span></em>’. Therefore, what we see is that the prevalence of poor mental health increases more for every 1-unit increase in smoking prevalence in the southern part of the map as compared with the northern. On the other hand the prevalence of poor mental health increases more for every 1-unit increase in prevalence of poor physical health in census tracts in the northern part of the map.</p>
<p>However, when combined with the prevalence information, we can see that meaning of ‘<em>one-unit change in <span class="math inline">\(x\)</span></em>’ should be put in the context of the variation in the covariates themselves. While the magnitude of association between poor physical health and poor mental health appears strongest in the north, those census tracts actually have quite low prevalence of poor physical health.</p>
<p>The point of this illustration is to consider whether your interest is in relative variation in magnitude of association (e.g. interaction or non-stationarity in the <em>association</em>), or the population impact which itself is related to baseline prevalence. Either could be relevant, but considering both prevalence and correlation/association provides more context.</p>
</div>
</div>
<div id="spatial-analysis-in-epidemiology-7" class="section level2" number="12.3">
<h2>
<span class="header-section-number">12.3</span> Spatial Analysis in Epidemiology<a class="anchor" aria-label="anchor" href="#spatial-analysis-in-epidemiology-7"><i class="fas fa-link"></i></a>
</h2>
<div id="estimating-geogrpahically-weighted-regression-models" class="section level3" number="12.3.1">
<h3>
<span class="header-section-number">12.3.1</span> Estimating geogrpahically weighted regression models<a class="anchor" aria-label="anchor" href="#estimating-geogrpahically-weighted-regression-models"><i class="fas fa-link"></i></a>
</h3>
<div id="packages-and-data-1" class="section level4" number="12.3.1.1">
<h4>
<span class="header-section-number">12.3.1.1</span> Packages and Data<a class="anchor" aria-label="anchor" href="#packages-and-data-1"><i class="fas fa-link"></i></a>
</h4>
<p>There are at least four packages that provide functions for geographically weighted regression: <code>McSpatial</code>, <code>gwrr</code>, <code>spgwr</code>, and <code>GWModel</code>. We will be using the latter package, <code>GWModel</code> as it has much of the functionality of others, with additional diagnostic and model form capabilities.</p>
<div class="sourceCode" id="cb326"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span>,   <span class="co"># For data workflow</span></span>
<span>               <span class="va">sf</span>,          <span class="co"># For managing spatial data class sf</span></span>
<span>               <span class="va">sp</span>,          <span class="co"># For managing spatial data class sp</span></span>
<span>               <span class="va">GWmodel</span>,     <span class="co"># For geographically-weighted statistics</span></span>
<span>               <span class="va">raster</span>,      <span class="co"># For converting spatial grid to raster in final section</span></span>
<span>               <span class="va">tmap</span><span class="op">)</span>        <span class="co"># For mapping results</span></span></code></pre></div>
<p>The example in this tutorial uses data from the <a href="https://www.cdc.gov/places/index.html">CDC PLACES project</a>. These data were developed in collaboration with Robert Wood Johnson Foundation and CDC in an effort to increase availability of small-area health data. Briefly, the project uses data from each state’s Behavioral Risk Factor Surveillance System (BRFSS) survey to estimate small area (census tract) prevalence of a limited set of BRFSS indicators. The estimation process employed by CDC to create the dataset uses restricted-access geocodes, as well as some model-interpolation assumptions.</p>
<p>The data are only available for more urbanized locations. I have included exposure measures from other public-use data sets as indicated in the Data Dictionary below.</p>
<p>These data are at the geographic level of <em>census tracts</em> (although 500-cities actually estimates down to the census block group). The values for each measure (e.g. poor mental health, smoking, etc) are tract-specific <strong>prevalence</strong>. In other words these are purely <em>ecologic</em> data, and thus all regression below is <em>ecologic analysis</em>. While this has been true for most exercises this semester, it is particularly important to keep this fact in mind as we begin conducting multivariable regression.</p>
<div class="sourceCode" id="cb327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">atl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">'BRFSS_Atl.gpkg'</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># na.omit() drops 2 tracts with missing variables</span></span></code></pre></div>
</div>
<div id="brfss-data" class="section level4" number="12.3.1.2">
<h4>
<span class="header-section-number">12.3.1.2</span> Data Dictionary<a class="anchor" aria-label="anchor" href="#brfss-data"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="20%">
<col width="32%">
<col width="47%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Source</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>FIPS</code></td>
<td>Census tract ID</td>
<td></td>
</tr>
<tr class="even">
<td><code>PopulationCount</code></td>
<td>Count of tract pop</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="odd">
<td><code>INSURANCE</code></td>
<td>Prevalence uninsured (18+)</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="even">
<td><code>SMOKING</code></td>
<td>Prevalence current smoking (18+)</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="odd">
<td><code>MENTALHLTH</code></td>
<td>Prevalence poor mental health &gt; 14 days (18+)m</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="even">
<td><code>MentalHlthCOUNT</code></td>
<td>(Estimated) count of poor mental health &gt;14 days</td>
<td>Calculated from 500-cities, BRFSS</td>
</tr>
<tr class="odd">
<td><code>PHYSHLTH</code></td>
<td>Prevalence poor physical health &gt; 14 days (18+)</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="even">
<td><code>ParkProximity_std</code></td>
<td>Distance to nearest park (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="odd">
<td><code>Vacancy_std</code></td>
<td>Prevalence vacant housing (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="even">
<td><code>HealthAccess_std</code></td>
<td># Health facilities within 2-miles (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="odd">
<td><code>Foreclosure_std</code></td>
<td>Prevalence foreclosure, 2010 (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="even">
<td><code>Poverty_std</code></td>
<td>Poverty rate (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="odd">
<td><code>PovertyRate</code></td>
<td>Poverty rate (%)</td>
<td>USDA Food Access Research Atlas</td>
</tr>
<tr class="even">
<td><code>MedianFamilyIncome</code></td>
<td>Median Income in tract ($)</td>
<td>USDA Food Access Research Atlas</td>
</tr>
<tr class="odd">
<td><code>PctSeniors</code></td>
<td>Ratio of seniors (65+) to total population (%)</td>
<td>USDA Food Access Research Atlas</td>
</tr>
<tr class="even">
<td><code>InstabilityStress</code></td>
<td>Summed z-score from Foreclosure &amp; Vacancy</td>
<td>Derived from Opportunity Index</td>
</tr>
<tr class="odd">
<td><code>geometry</code></td>
<td>Census tract polygon geom</td>
<td>US Census bureau</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="preparing-for-using-gwmodel" class="section level3" number="12.3.2">
<h3>
<span class="header-section-number">12.3.2</span> Preparing for using <code>GWModel</code><a class="anchor" aria-label="anchor" href="#preparing-for-using-gwmodel"><i class="fas fa-link"></i></a>
</h3>
<div class="rmdtip">
<p>Please note that you have already been introduced to the <code>GWModel</code> package through the use of <a href="disease-mapping-iv-kernel-density-estimation.html#gwss">geographically weighted summary statistics</a> in Disease Mapping 3. You might revisit that section (and the Part B lab from Disease Mapping 3), for a review of using kernel density weighting to produce locally smoothed <em>mean intensity</em> and <em>correlation</em> statistics.</p>
</div>
<p>The <code>GWModel</code> package has not been updated to accommodate <code>sf</code> class spatial data in R yet. For that reason, it is necessary for us to convert the <code>sf</code> data to the <code>sp</code> class. Furthermore, the way the kernel density estimator evaluates which regions <em>are</em> versus <em>are not</em> in the ‘<em>local</em>’ region is by using a matrix of the distances between the centroid of every pair of census tracts (e.g. this is simply a different way of defining neighbors than what we used from the <code>spdep</code> package).</p>
<p>While each function in <code>GWModel</code> can calculate this distance matrix <em>on the fly</em>, because it will be needed so many times, it can be computationally efficient to calculate this <em>distance matrix</em> only once, and then simply provide the matrix to each function that needs it.</p>
<p>This code creates a <code>sp</code> object, then a large matrix that is <span class="math inline">\(185 X 185\)</span>, with each cell representing the Euclidean distance between pairs of tract centroids.</p>
<div class="sourceCode" id="cb328"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create a copy of data in the 'sp' format for use in some functions</span></span>
<span><span class="va">atl.sp</span> <span class="op">&lt;-</span> <span class="va">atl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/methods/as.html">as</a></span><span class="op">(</span><span class="st">'Spatial'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create distance matrix from centroids</span></span>
<span><span class="va">atl.DM</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gw.dist.html">gw.dist</a></span><span class="op">(</span>dp.locat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sp/man/coordinates.html">coordinates</a></span><span class="op">(</span><span class="va">atl.sp</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="rmdtip">
<p>By default, the distance is calculated between every pair of observations. In the default case a kernel density function is centered over <em>every single observation</em>. However, if you were analyzing a much larger dataset (e.g. thousands of points), this would be computationally inefficient and if points were close together might not add much new information.</p>
<p>It is therefore possible to pre-define locations at which the kernel function will be centered to adequately cover the region in a more efficient manner. These points are often defined along a grid (e.g. every 1000 meters, for example), and define a subset of locations at which to fit the kernel.</p>
<p>There is an illustration of this approach in the final section of this tutorial, and please note that this adaptation would be useful in many settings. However, for the immediate purposes we will accept the default behavior.</p>
</div>
</div>
<div id="defining-local-optimizing-kernel-bandwidths" class="section level3" number="12.3.3">
<h3>
<span class="header-section-number">12.3.3</span> Defining local: optimizing kernel bandwidths<a class="anchor" aria-label="anchor" href="#defining-local-optimizing-kernel-bandwidths"><i class="fas fa-link"></i></a>
</h3>
<p>Remember how we considered alternative definitions of <em>local</em> using kernel density estimates by changing the bandwidth of the kernel function? Recall the bandwidth is the radius of the search window, and the kernel is typically a bell-shaped curve (e.g. Gaussian or bi-square or similar).</p>
<p>The <code>GWModel</code> package has many functions for using cross-validation (or AIC) to find an optimal (defined as best fitting) bandwidth for a given dataset. Unfortunately the <em>best fit</em> completely depends on the statistic being estimated. For that reason we may need to find a different bandwidth for each statistical test.</p>
<p>Just as with previous applications of kernel density functions, we can choose from a <em>fixed</em> or an <em>adaptive</em> bandwidth. <em>Fixed bandwidth</em> refers to a single kernel density radius to use in all parts of the study region. In contrast, <em>adaptive bandwidth</em> is a strategy to allow the radius to be adjusted to maintain a consistent amount of information, irrespective of changes in the population or area.</p>
<p>In the case of <code>GWModel</code>, fixed bandwidths are defined in terms of the linear units of the map (e.g. meters in this case). In contrast adaptive bandwidths are defined by the number of units; therefore the kernel grows or shrinks in order to maintain a constant number of units ‘<em>under</em>’ the kernel function.</p>
<p>In <a href="disease-mapping-iv-kernel-density-estimation.html#gwss">Disease Mapping 3</a>, we used the function <code><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwss.average.html">bw.gwss.average()</a></code> to find an optimal bandwidth that was specific to calculation of geographically weighted summary statistics. However, the optimal bandwidth can be different for each statistic of interest, and therefore the procedure for finding an optima for <em>geographically weighted regression</em> is different.</p>
<p>The function <code><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwr.html">bw.gwr()</a></code> uses cross-validation to find optimum bandwidth for a geographically weighted <em>regression</em> rather than <em>summary statistics</em>.</p>
<div class="sourceCode" id="cb329"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">h.fixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwr.html">bw.gwr</a></span><span class="op">(</span><span class="va">MENTALHLTH</span> <span class="op">~</span> <span class="va">SMOKING</span> <span class="op">+</span> <span class="va">PHYSHLTH</span>, </span>
<span>             data <span class="op">=</span> <span class="va">atl.sp</span>, </span>
<span>             dMat <span class="op">=</span> <span class="va">atl.DM</span><span class="op">)</span></span>
<span></span>
<span><span class="va">h.adapt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/bw.gwr.html">bw.gwr</a></span><span class="op">(</span><span class="va">MENTALHLTH</span> <span class="op">~</span> <span class="va">SMOKING</span> <span class="op">+</span> <span class="va">PHYSHLTH</span>, </span>
<span>             data <span class="op">=</span> <span class="va">atl.sp</span>, </span>
<span>             adaptive <span class="op">=</span> <span class="cn">T</span>,</span>
<span>             dMat <span class="op">=</span> <span class="va">atl.DM</span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb330"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">h.fixed</span></span></code></pre></div>
<pre><code>## [1] 12082.4</code></pre>
<div class="sourceCode" id="cb332"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">h.adapt</span></span></code></pre></div>
<pre><code>## [1] 59</code></pre>
<p>The optimal bandwidth <em>for this specific regression model</em> is either a fixed radius of 12082 meters, or else an adaptive bandwidth that always maintains 59 census tracts within the local region, regardless of their relative size (e.g. this is akin to k-nearest neighbors).</p>
</div>
<div id="geographically-weighted-regression" class="section level3" number="12.3.4">
<h3>
<span class="header-section-number">12.3.4</span> Geographically weighted regression<a class="anchor" aria-label="anchor" href="#geographically-weighted-regression"><i class="fas fa-link"></i></a>
</h3>
<p><code>GWModel</code> offers a wide range of modeling tools including geographically weighted linear regression, Poisson regression, binomial regression, and even local fitting options including adjustment for local heteroscedasticity, and local ridge regression which is robust to collinearity.</p>
<p>Because our outcome, <code>MENTALHLTH</code> is continuous and relatively normally distributed, basic linear geographically weighted regression will work.</p>
<p>The fitting of <em>basic</em> (meaning linear) GWR models is via the function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.basic.html">gwr.basic()</a></code>. Just as there are many functions in <code>GWModel</code> that begin with <code>bw.x</code> for estimating bandwidths, there are many functions that begins with <code>gwr.x</code> for fitting a variety of models. Look at the help documentation.</p>
<div class="sourceCode" id="cb334"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwr.basic.html">gwr.basic</a></span><span class="op">(</span><span class="va">MENTALHLTH</span> <span class="op">~</span> <span class="va">SMOKING</span> <span class="op">+</span> <span class="va">PHYSHLTH</span>, </span>
<span>             data <span class="op">=</span> <span class="va">atl.sp</span>, </span>
<span>             bw <span class="op">=</span> <span class="va">h.adapt</span>,</span>
<span>             adaptive <span class="op">=</span> <span class="cn">T</span>,</span>
<span>             dMat <span class="op">=</span> <span class="va">atl.DM</span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb335"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    ***********************************************************************
##    *                       Package   GWmodel                             *
##    ***********************************************************************
##    Program starts at: 2022-09-04 21:45:02 
##    Call:
##    gwr.basic(formula = MENTALHLTH ~ SMOKING + PHYSHLTH, data = atl.sp, 
##     bw = h.adapt, adaptive = T, dMat = atl.DM)
## 
##    Dependent (y) variable:  MENTALHLTH
##    Independent variables:  SMOKING PHYSHLTH
##    Number of data points: 185
##    ***********************************************************************
##    *                    Results of Global Regression                     *
##    ***********************************************************************
## 
##    Call:
##     lm(formula = formula, data = data)
## 
##    Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4988 -0.9689 -0.1638  0.6708  5.7530 
## 
##    Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
##    (Intercept)  3.13908    0.28497  11.015  &lt; 2e-16 ***
##    SMOKING      0.16286    0.02830   5.754 3.64e-08 ***
##    PHYSHLTH     0.50325    0.04137  12.166  &lt; 2e-16 ***
## 
##    ---Significance stars
##    Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
##    Residual standard error: 1.451 on 182 degrees of freedom
##    Multiple R-squared: 0.8523
##    Adjusted R-squared: 0.8507 
##    F-statistic: 525.1 on 2 and 182 DF,  p-value: &lt; 2.2e-16 
##    ***Extra Diagnostic information
##    Residual sum of squares: 383.1576
##    Sigma(hat): 1.446982
##    AIC:  667.704
##    AICc:  667.9262
##    BIC:  516.4669
##    ***********************************************************************
##    *          Results of Geographically Weighted Regression              *
##    ***********************************************************************
## 
##    *********************Model calibration information*********************
##    Kernel function: bisquare 
##    Adaptive bandwidth: 59 (number of nearest neighbours)
##    Regression points: the same locations as observations are used.
##    Distance metric: A distance matrix is specified for this model calibration.
## 
##    ****************Summary of GWR coefficient estimates:******************
##                    Min.    1st Qu.     Median    3rd Qu.   Max.
##    Intercept -1.4633747 -0.0771617  3.0706879  3.9759400 8.0903
##    SMOKING   -0.0074907  0.0599293  0.1369631  0.3200178 0.6134
##    PHYSHLTH  -0.1574946  0.1773786  0.5613934  0.9628009 1.1627
##    ************************Diagnostic information*************************
##    Number of data points: 185 
##    Effective number of parameters (2trace(S) - trace(S'S)): 27.10305 
##    Effective degrees of freedom (n-2trace(S) + trace(S'S)): 157.8969 
##    AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 568.6092 
##    AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 540.1906 
##    BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 441.6136 
##    Residual sum of squares: 179.7807 
##    R-square value:  0.9307003 
##    Adjusted R-square value:  0.9187292 
## 
##    ***********************************************************************
##    Program stops at: 2022-09-04 21:45:02</code></pre>
<p>This procedure produces a lot of output! Examine the output above, and review some of the key points of interest:</p>
<ol style="list-style-type: decimal">
<li>An initial test for the presence of significant non-stationarity is evidence that the (much more complex) GWR fits better than the simpler global model. Do this by checking whether the <em>local</em> (GWR) model fits better than the <em>global</em> (aspatial) model by comparing the AICc from the global model at the top of the output to the AICc from the GWR at the bottom. The AICc is a fit statistics that penalizes for additional parameters, including the many parameters being estimated by repeating the model many times. Therefore we only find evidence of non-stationarity when the AICc for the GWR is <strong>smaller than</strong> then AICc for the global model (typically a difference in AICc of 3 or greater is sufficient to say the local model fits better). In this case the GWR fits much better than the global, suggesting significant non-stationarity in the relationships in this model.</li>
<li>Next compare the magnitude of the regression coefficients in the global fit (top) to the <em>range of coefficients</em> in the GWR (lower portion of output). Which variables appear to <em>vary</em> the most? Using the interquartile comparison (e.g. comparing Q1 to Q3 of the range of coefficients), the absolute difference is greatest for <code>PHYSHLTH</code>, although <code>SMOKING</code> also has substantial variation.</li>
<li>Look at the variance explained as summarized by the adjusted <span class="math inline">\(R^2\)</span> value. Both the global and the GWR models explain a great deal of variance, but the GWR has a higher <span class="math inline">\(R^2\)</span> of 0.93.</li>
</ol>
</div>
<div id="checking-local-multi-collinearity" class="section level3" number="12.3.5">
<h3>
<span class="header-section-number">12.3.5</span> Checking local multi-collinearity<a class="anchor" aria-label="anchor" href="#checking-local-multi-collinearity"><i class="fas fa-link"></i></a>
</h3>
<p>While collinearity is a possible concern in any regression model, its importance in GWR is heightened by the fact that the model is re-fit in geographic subsets of the data where variables would be anticipated to have higher correlation than in the study region at large (e.g. like things tends to be near like things). Multicollinearity can lead to variance inflation which may produce statistically unreliable (imprecise) estimates.</p>
<p>We can first carry out collinearity diagnostics on the model results, and then if we find evidence for concerning multicollinearity we could either alter the model (remove culprit covariates) or consider fitting model forms robust to collinearity including <em>local ridge regression</em> available via the function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.lcr.html">gwr.lcr()</a></code>.</p>
<p>For now we will begin with diagnostics. The function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.collin.diagno.html">gwr.collin.diagno()</a></code> returns the Condition Number and Variance Inflation Factor (VIF) from the model fit above.</p>
<div class="sourceCode" id="cb337"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">collin</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwr.collin.diagno.html">gwr.collin.diagno</a></span><span class="op">(</span><span class="va">MENTALHLTH</span> <span class="op">~</span> <span class="va">SMOKING</span> <span class="op">+</span> <span class="va">PHYSHLTH</span>,</span>
<span>                            data <span class="op">=</span> <span class="va">atl.sp</span>,</span>
<span>                            adaptive <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                            dMat <span class="op">=</span> <span class="va">atl.DM</span>,</span>
<span>                            bw <span class="op">=</span> <span class="va">h.adapt</span><span class="op">)</span></span></code></pre></div>
<p>There is neither a <code><a href="https://rdrr.io/r/base/print.html">print()</a></code> nor a <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function for the output of this function. However to see the output summarized as a spatial object we can look at the names of <code>collin$SDF</code>:</p>
<div class="sourceCode" id="cb338"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">collin</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "SMOKING_VIF"             "PHYSHLTH_VIF"           
## [3] "local_CN"                "Intercept_VDP"          
## [5] "SMOKING_VDP"             "PHYSHLTH_VDP"           
## [7] "Corr_Intercept.SMOKING"  "Corr_Intercept.PHYSHLTH"
## [9] "Corr_SMOKING.PHYSHLTH"</code></pre>
<p>You will see that there is an overall Condition Number (<code>local_CN</code>), as well as Variance Inflation Factors (VIF) and Variance Decomposition Proportions (VDP) for each variable. In evaluating for concerning collinearity, we can map these values to understand whether (and if so, <em>where</em>) there is evidence of collinearity.</p>
<p>For instance we might start looking at the local Condition Number; a rule of thumb suggests that a value over 30 is evidence of important multicollinearity.</p>
<div class="sourceCode" id="cb340"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">collin</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'local_CN'</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'fixed'</span>,</span>
<span>          breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">15</span>,<span class="fl">25</span>,<span class="fl">30</span>,<span class="fl">35</span><span class="op">)</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">'-PRGn'</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> </span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-14-1.png" width="672"></div>
<p>It looks like only a portion of southwest Atlanta have concerning CN’s. Now we can look at the VIF for variables to see which are culprits (and where).</p>
<div class="sourceCode" id="cb341"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">collin</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'SMOKING_VIF'</span>, <span class="st">'PHYSHLTH_VIF'</span><span class="op">)</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'fixed'</span>,</span>
<span>          breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">'-PRGn'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> </span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-15-1.png" width="672"></div>
<p>From this we can see that no places have VIF for any variable above 4; this reduces our concern about meaningful local variance inflation from this model. We could continue to explore diagnostics, but for now this is satisfactory finding.</p>
</div>
<div id="adjusting-for-multiple-comparisons" class="section level3" number="12.3.6">
<h3>
<span class="header-section-number">12.3.6</span> Adjusting for multiple comparisons<a class="anchor" aria-label="anchor" href="#adjusting-for-multiple-comparisons"><i class="fas fa-link"></i></a>
</h3>
<p>First, let’s look more closely at the output of our call to <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.basic.html">gwr.basic()</a></code> above. Specifically, let’s look at the names of the <code>m$SDF</code> portion of the output.</p>
<div class="sourceCode" id="cb342"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "Intercept"     "SMOKING"       "PHYSHLTH"      "y"            
##  [5] "yhat"          "residual"      "CV_Score"      "Stud_residual"
##  [9] "Intercept_SE"  "SMOKING_SE"    "PHYSHLTH_SE"   "Intercept_TV" 
## [13] "SMOKING_TV"    "PHYSHLTH_TV"   "Local_R2"</code></pre>
<p>Not surprisingly, we see there are values for the estimate of the local intercept, and the regression coefficients for each predictor. But in addition there is a standard error for each coefficient, as well as a t-value test statistic which relates to its significance. This is simply the local version of all the information from the global regression output above, but it provides the information necessary to determine whether each covariate is <em>statistically significantly</em> associated with the outcome, should that be of interest.</p>
<p>However, the presence of these local test statistics of significance highlight another critique of GWR, which is the repetition of tests across the study region. While repeating tests centered on each county in turn do not reflect fully independent tests (there is a lot of the same information in each new <em>window</em> of the kernel), there is clearly some concern about making inference (for example via tests of statistical significance) when multiple testing has occurred.</p>
<p>However we can adjust the test statistic to account for multiple comparison using the function <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.t.adjust.html">gwr.t.adjust()</a></code>. This function takes a <code>gwrm.Obj</code> object which is the output of the <code><a href="https://rdrr.io/pkg/GWmodel/man/gwr.basic.html">gwr.basic()</a></code> function as its input, and returns a set of p-values adjusted for multiple comparisons in different ways.</p>
<div class="sourceCode" id="cb344"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t.adj</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwr.t.adjust.html">gwr.t.adjust</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code></pre></div>
<p>The function calculates adjusted p-values under four alternative schemes. One is the familiar <em>Bonferroni</em> adjustment, which is almost surely too conservative, because it assumes that every test location was a completely independent sample (which by definition of GWR is false). The other approaches are various versions of False Discovery Rate algorithms which try to assess the degree of <em>dependence</em> between tests to determine how the <em>effective number</em> of tests conducted (e.g. the equivalent of the number of unique, independent tests after accounting for overlapping information). Any could work, but at least one review suggest the <em>Benjamini-Yekutieli</em> method is a good middle ground.</p>
<p>If you look at the results returned by the function above you will see that adjusted p-values are provided for each method with the <em>Benjamini-Yekutieli</em> indicated by the *_by* suffix.</p>
<div class="sourceCode" id="cb345"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">t.adj</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] "Intercept_t"    "SMOKING_t"      "PHYSHLTH_t"     "Intercept_p"   
##  [5] "SMOKING_p"      "PHYSHLTH_p"     "Intercept_p_by" "SMOKING_p_by"  
##  [9] "PHYSHLTH_p_by"  "Intercept_p_fb" "SMOKING_p_fb"   "PHYSHLTH_p_fb" 
## [13] "Intercept_p_bo" "SMOKING_p_bo"   "PHYSHLTH_p_bo"  "Intercept_p_bh"
## [17] "SMOKING_p_bh"   "PHYSHLTH_p_bh"</code></pre>
</div>
<div id="visualizing-model-inference" class="section level3" number="12.3.7">
<h3>
<span class="header-section-number">12.3.7</span> Visualizing model inference<a class="anchor" aria-label="anchor" href="#visualizing-model-inference"><i class="fas fa-link"></i></a>
</h3>
<p>Finally, we are ready to visualize the results of our GWR model. There are many ways to visualize the significance of each parameter. Here is one approach. In the code chunk below I do the following things:</p>
<ol style="list-style-type: decimal">
<li>Convert from <code>sp</code> to <code>sf</code> so that I can take advantage of the data manipulation for <code>sf</code> objects using <code>dplyr()</code> verbs and pipes.</li>
<li>Recode the adjusted p-value for each coefficient (e.g. <code>Intercept</code>, <code>SMOKING</code>, and <code>PHYSHLTH</code>) to indicate counties where the respective coefficient p-value is &lt;0.05, naming the resulting variable <code>pval</code>
</li>
<li>Group counties by whether their covariate coefficient <em>is</em> or <em>is not</em> statistically significant by grouping on variable <code>pval</code>
</li>
<li>Use the <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> function to aggregate the 185 census tracts into either significant or not.</li>
<li>Finally, use <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> to exclude the non-significant regions. Note we are not removing the actual coefficients used for the choropleth map! Instead we are just selecting for the outlines of census tracts that are <em>statistically significant</em> adjusting for multiple comparisons.</li>
</ol>
<div class="sourceCode" id="cb347"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create a spatial object delineating statistically significant INTERCEPT coefficients</span></span>
<span><span class="va">intercept.p</span> <span class="op">&lt;-</span> <span class="va">t.adj</span><span class="op">$</span><span class="va">SDF</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pval <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">SMOKING_p_by</span> <span class="op">&lt;</span><span class="fl">0.05</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">pval</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">pval</span> <span class="op">==</span><span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span></span>
<span></span>
<span><span class="co"># Create a spatial object delineating statistically significant SMOKING coefficients</span></span>
<span><span class="va">smoke.p</span> <span class="op">&lt;-</span> <span class="va">t.adj</span><span class="op">$</span><span class="va">SDF</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pval <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">Intercept_p_by</span> <span class="op">&lt;</span><span class="fl">0.05</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">pval</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">pval</span> <span class="op">==</span><span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># Create a spatial object delineating statistically significant PHYHLTH coefficients</span></span>
<span><span class="va">physhlth.p</span> <span class="op">&lt;-</span> <span class="va">t.adj</span><span class="op">$</span><span class="va">SDF</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pval <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">PHYSHLTH_p_by</span> <span class="op">&lt;</span><span class="fl">0.05</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">pval</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>count <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">pval</span> <span class="op">==</span><span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<p>With this complete, we can now map the geographically weighted regression coefficient (along with adjusted test of significance) for the association of <code>SMOKING</code>, conditional on other variables, with <code>MENTALHLTH</code>. The <code>tmap</code> code below should be relatively familiar at this point, with the exception of a couple additions:</p>
<ul>
<li>I use the function <code><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend()</a></code> to manually specify that I want the legend to include red lines labeled as ‘p-value &lt; 0.05’.</li>
<li>In <code>R</code> there are different ways to get Greek letters and other symbols in plots. In <code>tmap</code> the only one I have found to work is the use of <em>Unicode</em> values. These are unique codes for every possible symbol. If you Google ‘unicode Greek letters’ you will find lists. In the <code>smoke.coefficients</code> map below I specify the title of the legend to be <code>\u03B2</code> which is the value specific to a Greek <span class="math inline">\(\beta\)</span>.</li>
</ul>
<div class="sourceCode" id="cb348"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Map of observed prevalence of smoking</span></span>
<span><span class="va">smoke.prev</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">atl</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'SMOKING'</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'quantile'</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">'BuPu'</span>,</span>
<span>          title <span class="op">=</span> <span class="st">'%'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">'Prevalence of smoking'</span>,</span>
<span>          legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Map for spatially varying SMOKING coefficients</span></span>
<span><span class="va">smoke.coefficients</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'SMOKING'</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'quantile'</span>,</span>
<span>          title <span class="op">=</span> <span class="st">'\u03B2'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">smoke.p</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">'red'</span>, </span>
<span>             lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">'Coefficients for SMOKING'</span>,</span>
<span>          legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">'line'</span>,</span>
<span>              labels <span class="op">=</span> <span class="st">'p-value &lt; 0.05'</span>,</span>
<span>              col <span class="op">=</span> <span class="st">'red'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">smoke.prev</span>, <span class="va">smoke.coefficients</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-20-1.png" width="672"></div>
<p>This map demonstrates several things about the relationship between local prevalence of smoking and prevalence of poor mental health (the outcome) at the census tract level.</p>
<ol style="list-style-type: decimal">
<li>First, as a reminder, we have the map of the observed prevalence (a predictor of poor mental health) in the left hand map. Smoking prevalence is higher in South Atlanta.</li>
<li>It is evident that the strength of the relationship between smoking and poor mental health is not stationary, but instead quite non-stationary or location-dependent. We see this evidenced by the fact that the coefficient ranges in the right-hand panel from essentially zero (e.g. in the north) to 0.6 in the southwest.</li>
<li>Finally, while the global model suggested smoking was a statistically significant predictor of poor mental health, it appears from the right-hand map that this is only true in <em>part of the study area</em>. In other words, smoking <em>is not significantly</em> associated with poor mental health in regions outside of the zone delineated by the red line.</li>
</ol>
<p>We can examine all three coefficients together like this:</p>
<div class="sourceCode" id="cb349"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Map for spatially varying intercepts</span></span>
<span><span class="va">int.coefficients</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'Intercept'</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'quantile'</span>,</span>
<span>          title <span class="op">=</span> <span class="st">'\u03B2'</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">'OrRd'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">intercept.p</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">'red'</span>, </span>
<span>             lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">'Intercepts'</span>,</span>
<span>          legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">'line'</span>,</span>
<span>              labels <span class="op">=</span> <span class="st">'p-value &lt; 0.05'</span>,</span>
<span>              col <span class="op">=</span> <span class="st">'red'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Map for spatially varying PHYSHLTH coefficients</span></span>
<span><span class="va">physhlth.coefficients</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_fill</a></span><span class="op">(</span><span class="st">'PHYSHLTH'</span>,</span>
<span>          style <span class="op">=</span> <span class="st">'quantile'</span>,</span>
<span>          title <span class="op">=</span> <span class="st">'\u03B2'</span>,</span>
<span>          palette <span class="op">=</span> <span class="st">'YlGnBu'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">physhlth.p</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_polygons.html">tm_borders</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">'red'</span>, </span>
<span>             lwd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_layout.html">tm_layout</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">'Coefficients for PHYSHLTH'</span>,</span>
<span>          legend.format <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_add_legend.html">tm_add_legend</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">'line'</span>,</span>
<span>              labels <span class="op">=</span> <span class="st">'p-value &lt; 0.05'</span>,</span>
<span>              col <span class="op">=</span> <span class="st">'red'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">int.coefficients</span>, <span class="va">smoke.coefficients</span>, <span class="va">physhlth.coefficients</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-21-1.png" width="672"></div>
</div>
<div id="extensions" class="section level3" number="12.3.8">
<h3>
<span class="header-section-number">12.3.8</span> Extensions<a class="anchor" aria-label="anchor" href="#extensions"><i class="fas fa-link"></i></a>
</h3>
<p>Unlike some other tools we’ve learned in this class, GWR is quite widely adaptable to a variety of situations. For example it is possible to conduct GWR analysis on <em>points</em> or <em>polygons</em>, and while we demonstrated linear regression, we could also use <em>Poisson</em> or <em>Binomial</em> regression.</p>
<p>As an example, if you had individual level outcome data and associated exposures (individual or contextual) linked to street-level geocodes (e.g. points) you could carry out spatial logistic regression, estimating the spatially-varying association between predictors and outcome.</p>
<p>Alternatively if you had aggregated count data as might be common with the surveillance-type data we relied on in Disease Mapping, you could use Poisson to estimate rates rather than rely on linear regression.</p>
</div>
<div id="data-models" class="section level3" number="12.3.9">
<h3>
<span class="header-section-number">12.3.9</span> Data models<a class="anchor" aria-label="anchor" href="#data-models"><i class="fas fa-link"></i></a>
</h3>
<p>One final option that could be useful is using gridded points to pre-specify the evaluation location for each kernel density estimation. Recall that by default, all of the preceding procedures place the kernel estimator over every single feature (each census tract polygon centroid in our case). However it could be more efficient to describe a regular grid of points that covers the whole region. This could be computationally efficient if for example the number of grid points was smaller than the number of features (observations). Note that the pre-specified evaluation points don’t change the data; instead they change <strong>where</strong> the kernel window is centered for estimation.</p>
<div class="rmdtip">
<p>This strategy described below could be generalized to any time you wanted to return a <em>raster surface</em> from kernel density smoothing (e.g. using <code><a href="https://rdrr.io/pkg/GWmodel/man/gwss.html">gwss()</a></code> or <code>gwr.xx()</code> models) of points or polygons. In otherwords using gridded evaluation points converts the answer from polygon/point to raster surface.</p>
</div>
<p>Here is an approach that follows these steps:</p>
<ol style="list-style-type: decimal">
<li>Extract the <em>bounding box</em> or <em>spatial extent</em> of the original data. This is the min and max <span class="math inline">\(x,y\)</span> coordinate locations of the <code>obesity</code> spatial object.</li>
<li>Define a spatial resolution of the grid points. Below I have specified <span class="math inline">\(1000\)</span> meters or 1 km. This is how far between each evaluation point.</li>
<li>Define the dimensions of the grid that would cover the spatial extent of the data using the specified resolution. This is how many rows or columns are needed (at the specified resolution) to cover the target area.</li>
<li>Finally, create a <code>SpatialGrid</code> object in <code>sp</code> with the target dimensions.</li>
</ol>
<div class="sourceCode" id="cb350"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sp/man/bbox.html">bbox</a></span><span class="op">(</span><span class="va">atl.sp</span><span class="op">)</span></span>
<span><span class="va">res</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span><span class="va">c.dim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">ceiling</a></span><span class="op">(</span><span class="op">(</span><span class="va">bb</span><span class="op">[</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="va">bb</span><span class="op">[</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="va">res</span><span class="op">)</span>,</span>
<span>           <span class="fu"><a href="https://rdrr.io/r/base/Round.html">ceiling</a></span><span class="op">(</span><span class="op">(</span><span class="va">bb</span><span class="op">[</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="va">bb</span><span class="op">[</span><span class="fl">2</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="op">/</span> <span class="va">res</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">grd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/sp/man/SpatialGrid.html">SpatialGrid</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/sp/man/SpatialGrid.html">GridTopology</a></span><span class="op">(</span>cellcentre.offset <span class="op">=</span> <span class="va">bb</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, </span>
<span>                                cellsize <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">res</span>,<span class="va">res</span><span class="op">)</span>, </span>
<span>                                cells.dim <span class="op">=</span> <span class="va">c.dim</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>When we plot the grid over the original data you can visualize how the evaluation points (the grid points) represent the region. Each grid is a single location where the GWR model will be centered. In this case we clearly have more evaluation points than the number of census tracts. In that way this strategy <em>is not actually</em> saving computational time, but instead is simply a step towards producing a raster surface of GWR results.</p>
<div class="sourceCode" id="cb351"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">grd</span>, col <span class="op">=</span> <span class="st">'red'</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">atl.sp</span>, add <span class="op">=</span> <span class="cn">T</span>, col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="st">'navyblue'</span>,alpha.f<span class="op">=</span><span class="fl">0.3</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-23-1.png" width="672"></div>
<p>Next, we recalculate the distance matrix. Recall that originally it was describing the distance between each pair of county centroids (to inform the weights derived from kernel density functions). Now, we combine information about <em>where each census tract is</em> (for weighting, described as <em>data</em> point, or <code>dp.locat</code>), with <em>where each evaluation point is</em> (for locating the kernel itself, described as <em>regression</em> points, or <code>rp.locat</code>).</p>
<div class="sourceCode" id="cb352"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">atl.DM2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gw.dist.html">gw.dist</a></span><span class="op">(</span>dp.locat<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/sp/man/coordinates.html">coordinates</a></span><span class="op">(</span><span class="va">atl.sp</span><span class="op">)</span>,</span>
<span>              rp.locat<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/sp/man/coordinates.html">coordinates</a></span><span class="op">(</span><span class="va">grd</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Finally, we can refit the original model, now using the <code>SpatialGrid</code> as a definition of the model calibration points, rather than assuming the default which is that each region in the <code>SpatialPolygons</code> represents a calibration or model-fitting location.</p>
<div class="sourceCode" id="cb353"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Refit model at specified gridded points</span></span>
<span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/GWmodel/man/gwr.basic.html">gwr.basic</a></span><span class="op">(</span><span class="va">MENTALHLTH</span> <span class="op">~</span> <span class="va">SMOKING</span> <span class="op">+</span> <span class="va">PHYSHLTH</span>, </span>
<span>                data <span class="op">=</span> <span class="va">atl.sp</span>,</span>
<span>                dMat <span class="op">=</span> <span class="va">atl.DM2</span>, </span>
<span>                regression.points <span class="op">=</span> <span class="va">grd</span>,</span>
<span>                bw <span class="op">=</span> <span class="va">h.adapt</span>,</span>
<span>                adaptive <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span></code></pre></div>
<p>To make visualizing easier we can convert the output of this model (which is a <code>SpatialPixelDataFrame</code>) to a raster object. Typically a <code>raster</code> object in <code>R</code> only has a single attribute (e.g. one statistic or variable with pixel values representing the local value of that statistic).</p>
<p>However, in this case we want to convert the pixel values for both of the coefficients plus the intercept. To do that we create what is called a <em>raster brick</em>, which is just a stack of rasters. Because the grid has coverage well outside the bounds of the study region, we can also <em>mask</em> (e.g. trim or crop) the raster to only show results for areas we have data.</p>
<div class="sourceCode" id="cb354"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create brick and crop it to the county data</span></span>
<span><span class="va">m2.raster</span> <span class="op">&lt;-</span> <span class="fu">brick</span><span class="op">(</span><span class="va">m2</span><span class="op">$</span><span class="va">SDF</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">mask</span><span class="op">(</span><span class="va">atl</span><span class="op">)</span></span></code></pre></div>
<p>To visualize the results:</p>
<div class="sourceCode" id="cb355"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">raster.int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m2.raster</span><span class="op">$</span><span class="va">Intercept</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span><span class="st">'Intercept'</span>,</span>
<span>            style <span class="op">=</span> <span class="st">'cont'</span>,</span>
<span>            palette <span class="op">=</span> <span class="st">'OrRd'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">raster.smoke</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m2.raster</span><span class="op">$</span><span class="va">SMOKING</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span><span class="st">'SMOKING'</span>,</span>
<span>            style <span class="op">=</span> <span class="st">'cont'</span>,</span>
<span>            palette <span class="op">=</span> <span class="st">'BuPu'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">raster.phyhlth</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_shape.html">tm_shape</a></span><span class="op">(</span><span class="va">m2.raster</span><span class="op">$</span><span class="va">PHYSHLTH</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tm_raster.html">tm_raster</a></span><span class="op">(</span><span class="st">'PHYSHLTH'</span>,</span>
<span>            style <span class="op">=</span> <span class="st">'cont'</span>,</span>
<span>            palette <span class="op">=</span> <span class="st">'YlGnBu'</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/tmap/man/tmap_arrange.html">tmap_arrange</a></span><span class="op">(</span><span class="va">raster.int</span>, <span class="va">raster.smoke</span>, <span class="va">raster.phyhlth</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="12-spatial-regression-3_files/figure-html/unnamed-chunk-27-1.png" width="672"></div>
<p>What this demonstrates is that a pre-defined spatial grid can recover the same patterns, and in instances where the number of observations is extremely large, the spatial grid could be a more efficient approach. Unfortunately (for reasons I do not understand), standard errors and t-values do not seem to be returned for this spatial grid, so significance testing is not available (as far as I can tell at the time of this writing).</p>

</div>
</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="spatial-regression-ii-spatial-econometric-regression.html"><span class="header-section-number">11</span> Spatial Regression II: Spatial econometric regression</a></div>
<div class="next"><a href="reproducibility-and-projects-in-r.html"><span class="header-section-number">13</span> Reproducibility and Projects in R</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#spatial-regression-iii-geographically-weighted-regression"><span class="header-section-number">12</span> Spatial Regression III: Geographically Weighted Regression</a></li>
<li>
<a class="nav-link" href="#getting-ready-10"><span class="header-section-number">12.1</span> Getting Ready</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#learning-objectives-11"><span class="header-section-number">12.1.1</span> Learning objectives</a></li>
<li><a class="nav-link" href="#important-vocabulary-11"><span class="header-section-number">12.1.2</span> Important Vocabulary</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#spatial-thinking-in-epidemiology-9"><span class="header-section-number">12.2</span> Spatial Thinking in Epidemiology</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#non-stationarity-and-spatially-varying-relationships"><span class="header-section-number">12.2.1</span> Non-stationarity and spatially varying relationships</a></li>
<li><a class="nav-link" href="#introducing-geographically-weighted-regression"><span class="header-section-number">12.2.2</span> Introducing geographically weighted regression</a></li>
<li><a class="nav-link" href="#making-epidemiologic-meaning-of-spatially-varying-coefficients"><span class="header-section-number">12.2.3</span> Making epidemiologic meaning of spatially varying coefficients</a></li>
<li><a class="nav-link" href="#distinguishing-variation-in-prevalence-from-variation-in-correlation"><span class="header-section-number">12.2.4</span> Distinguishing variation in prevalence from variation in correlation</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#spatial-analysis-in-epidemiology-7"><span class="header-section-number">12.3</span> Spatial Analysis in Epidemiology</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#estimating-geogrpahically-weighted-regression-models"><span class="header-section-number">12.3.1</span> Estimating geogrpahically weighted regression models</a></li>
<li><a class="nav-link" href="#preparing-for-using-gwmodel"><span class="header-section-number">12.3.2</span> Preparing for using GWModel</a></li>
<li><a class="nav-link" href="#defining-local-optimizing-kernel-bandwidths"><span class="header-section-number">12.3.3</span> Defining local: optimizing kernel bandwidths</a></li>
<li><a class="nav-link" href="#geographically-weighted-regression"><span class="header-section-number">12.3.4</span> Geographically weighted regression</a></li>
<li><a class="nav-link" href="#checking-local-multi-collinearity"><span class="header-section-number">12.3.5</span> Checking local multi-collinearity</a></li>
<li><a class="nav-link" href="#adjusting-for-multiple-comparisons"><span class="header-section-number">12.3.6</span> Adjusting for multiple comparisons</a></li>
<li><a class="nav-link" href="#visualizing-model-inference"><span class="header-section-number">12.3.7</span> Visualizing model inference</a></li>
<li><a class="nav-link" href="#extensions"><span class="header-section-number">12.3.8</span> Extensions</a></li>
<li><a class="nav-link" href="#data-models"><span class="header-section-number">12.3.9</span> Data models</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/mkram01/EPI563-SpatialEPI/blob/master/12-spatial-regression-3.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/mkram01/EPI563-SpatialEPI/edit/master/12-spatial-regression-3.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>EPI 563: Spatial Epidemiology, Fall 2022</strong>" was written by Michael Kramer. It was last built on Last updated: 2022-09-04.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
