<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 12 Spatial Regression III | EPI 563: Spatial Epidemiology, Fall 2020</title>
  <meta name="description" content="Week 12 Spatial Regression III | EPI 563: Spatial Epidemiology, Fall 2020" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 12 Spatial Regression III | EPI 563: Spatial Epidemiology, Fall 2020" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="mkram01/EPI563-SpatialEPI" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 12 Spatial Regression III | EPI 563: Spatial Epidemiology, Fall 2020" />
  
  
  

<meta name="author" content="Michael Kramer" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatial-regression-ii.html"/>
<link rel="next" href="tips-for-reproducibility-in-r.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">EPI 563: Spatial Epidemiology, Fall 2020</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>How to use this eBook</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#strategy-for-using-this-ebook"><i class="fa fa-check"></i>Strategy for using this eBook</a></li>
</ul></li>
<li class="part"><span><b>I Getting ready…</b></span></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li><a href="software-installation.html#installing-r-on-your-computer">Installing <code>R</code> on your computer</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#installing-rstudio-on-your-computer"><i class="fa fa-check"></i>Installing RStudio on your computer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html"><i class="fa fa-check"></i>Installing packages for this course</a>
<ul>
<li><a href="installing-packages-for-this-course.html#installing-rtools40">Installing <code>Rtools40</code></a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-general-data-science"><i class="fa fa-check"></i>Installing packages used for general data science</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-use-for-geographic-data"><i class="fa fa-check"></i>Installing packages use for geographic data</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-spatial-data-manipulation-visualization"><i class="fa fa-check"></i>Installing packages used for spatial data manipulation &amp; visualization</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-spatial-analysis"><i class="fa fa-check"></i>Installing packages used for spatial analysis</a></li>
</ul></li>
<li class="part"><span><b>II Weekly Modules</b></span></li>
<li class="chapter" data-level="1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html"><i class="fa fa-check"></i><b>1</b> Locating Spatial Epidemiology</a>
<ul>
<li class="chapter" data-level="1.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#getting-ready"><i class="fa fa-check"></i><b>1.1</b> Getting Ready</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#learning-objectives"><i class="fa fa-check"></i><b>1.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#additional-resources"><i class="fa fa-check"></i><b>1.1.2</b> Additional Resources</a></li>
<li class="chapter" data-level="1.1.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#important-vocabulary"><i class="fa fa-check"></i><b>1.1.3</b> Important Vocabulary</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-thinking-in-epidemiology"><i class="fa fa-check"></i><b>1.2</b> Spatial Thinking in Epidemiology</a></li>
<li class="chapter" data-level="1.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-analysis-in-epidemiology"><i class="fa fa-check"></i><b>1.3</b> Spatial Analysis in Epidemiology</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-data-storage-foramts"><i class="fa fa-check"></i><b>1.3.1</b> Spatial data storage foramts</a></li>
<li class="chapter" data-level="1.3.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#representing-spatial-data-in-r"><i class="fa fa-check"></i><b>1.3.2</b> Representing spatial data in <code>R</code></a></li>
<li class="chapter" data-level="1.3.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#benefits-of-sf-data-classes"><i class="fa fa-check"></i><b>1.3.3</b> Benefits of <code>sf</code> data classes</a></li>
<li class="chapter" data-level="1.3.4" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#working-with-spatial-data-in-r"><i class="fa fa-check"></i><b>1.3.4</b> Working with spatial data in <code>R</code></a></li>
<li class="chapter" data-level="1.3.5" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#basic-visual-inspectionplots"><i class="fa fa-check"></i><b>1.3.5</b> Basic visual inspection/plots</a></li>
<li class="chapter" data-level="1.3.6" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#working-with-crs-and-projection"><i class="fa fa-check"></i><b>1.3.6</b> Working with CRS and projection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html"><i class="fa fa-check"></i><b>2</b> Cartography for Epidemiology I</a>
<ul>
<li class="chapter" data-level="2.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#getting-ready"><i class="fa fa-check"></i><b>2.1</b> Getting Ready</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#learning-objectives-w2"><i class="fa fa-check"></i><b>2.1.1</b> Learning objectives, w2</a></li>
<li class="chapter" data-level="2.1.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#additional-resources-w2"><i class="fa fa-check"></i><b>2.1.2</b> Additional Resources, w2</a></li>
<li class="chapter" data-level="2.1.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#important-vocabulary-w2"><i class="fa fa-check"></i><b>2.1.3</b> Important Vocabulary, w2</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#spatial-thinking-in-epidemiology-w2"><i class="fa fa-check"></i><b>2.2</b> Spatial Thinking in Epidemiology, w2</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#color-choices"><i class="fa fa-check"></i><b>2.2.1</b> Color choices</a></li>
<li class="chapter" data-level="2.2.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#choropleth-binning-styles"><i class="fa fa-check"></i><b>2.2.2</b> Choropleth binning styles</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#spatial-analysis-in-epidemiology-w2"><i class="fa fa-check"></i><b>2.3</b> Spatial Analysis in Epidemiology, w2</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-numerator-data"><i class="fa fa-check"></i><b>2.3.1</b> Obtaining and preparing numerator data</a></li>
<li class="chapter" data-level="2.3.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-denominator-or-contextual-data"><i class="fa fa-check"></i><b>2.3.2</b> Obtaining and preparing denominator or contextual data</a></li>
<li class="chapter" data-level="2.3.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-geographic-data"><i class="fa fa-check"></i><b>2.3.3</b> Obtaining and preparing geographic data</a></li>
<li class="chapter" data-level="2.3.4" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#merging-attributes-and-geography"><i class="fa fa-check"></i><b>2.3.4</b> Merging Attributes and Geography</a></li>
<li class="chapter" data-level="2.3.5" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#mapping-mortality-uninsured"><i class="fa fa-check"></i><b>2.3.5</b> Mapping Mortality &amp; Uninsured</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html"><i class="fa fa-check"></i><b>3</b> Cartography for Epidemiology II</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#learning-objectives-w3"><i class="fa fa-check"></i><b>3.1</b> Learning objectives, w3</a></li>
<li class="chapter" data-level="3.2" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#additional-resources-w3"><i class="fa fa-check"></i><b>3.2</b> Additional resources, w3</a></li>
<li class="chapter" data-level="3.3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#important-vocabulary-w3"><i class="fa fa-check"></i><b>3.3</b> Important Vocabulary, w3</a></li>
<li class="chapter" data-level="3.4" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#spatial-thinking-in-epidemiology-w3"><i class="fa fa-check"></i><b>3.4</b> Spatial Thinking in Epidemiology, w3</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risks-of-privacy-breaches-in-collection-of-geospatial-information"><i class="fa fa-check"></i><b>3.4.1</b> Risks of privacy breaches in collection of geospatial information</a></li>
<li class="chapter" data-level="3.4.2" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risk-of-confidentiality-breaches-through-unintentional-de-identification"><i class="fa fa-check"></i><b>3.4.2</b> Risk of confidentiality breaches through unintentional de-identification</a></li>
<li class="chapter" data-level="3.4.3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risk-of-stigmatization-of-place"><i class="fa fa-check"></i><b>3.4.3</b> Risk of stigmatization of place</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html"><i class="fa fa-check"></i><b>4</b> Disease Mapping I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#getting-ready-w4"><i class="fa fa-check"></i><b>4.1</b> Getting ready, w4</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#learning-objectives-w4"><i class="fa fa-check"></i><b>4.1.1</b> Learning objectives, w4</a></li>
<li class="chapter" data-level="4.1.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#additional-resources-w4"><i class="fa fa-check"></i><b>4.1.2</b> Additional Resources, w4</a></li>
<li class="chapter" data-level="4.1.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#important-vocabulary-w4"><i class="fa fa-check"></i><b>4.1.3</b> Important Vocabulary, w4</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#spatial-thinking-in-epidemiology-w4"><i class="fa fa-check"></i><b>4.2</b> Spatial Thinking in Epidemiology, w4</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#why-do-we-need-disease-mapping"><i class="fa fa-check"></i><b>4.2.1</b> Why do we need disease mapping?</a></li>
<li class="chapter" data-level="4.2.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#using-statistics-and-probability-models-to-improve-disease-mapping"><i class="fa fa-check"></i><b>4.2.2</b> Using statistics and probability models to improve disease mapping</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#spatial-analysis-in-epidemiology-w4"><i class="fa fa-check"></i><b>4.3</b> Spatial Analysis in Epidemiology, w4</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-is-there-spatial-heterogeneity"><i class="fa fa-check"></i><b>4.3.1</b> Disease mapping: Is there spatial heterogeneity?</a></li>
<li class="chapter" data-level="4.3.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-how-precise-are-county-estimates"><i class="fa fa-check"></i><b>4.3.2</b> Disease mapping: How precise are county estimates?</a></li>
<li class="chapter" data-level="4.3.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-adjusting-for-covariates"><i class="fa fa-check"></i><b>4.3.3</b> Disease mapping: Adjusting for covariates</a></li>
<li class="chapter" data-level="4.3.4" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-rate-stabilization-with-global-empirical-bayes"><i class="fa fa-check"></i><b>4.3.4</b> Disease mapping: Rate stabilization with global Empirical Bayes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html"><i class="fa fa-check"></i><b>5</b> Disease Mapping II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#getting-ready-w5"><i class="fa fa-check"></i><b>5.1</b> Getting Ready, w5</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#w5-learning-objectives"><i class="fa fa-check"></i><b>5.1.1</b> w5 Learning objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#additional-resources-w5"><i class="fa fa-check"></i><b>5.1.2</b> Additional Resources, w5</a></li>
<li class="chapter" data-level="5.1.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#important-vocabulary-w5"><i class="fa fa-check"></i><b>5.1.3</b> Important Vocabulary, w5</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-thinking-in-epidemiology-w5"><i class="fa fa-check"></i><b>5.2</b> Spatial Thinking in Epidemiology, w5</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#an-argument-for-the-relevance-of-space"><i class="fa fa-check"></i><b>5.2.1</b> An argument for the relevance of space</a></li>
<li class="chapter" data-level="5.2.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#on-making-meaning-from-neighbors"><i class="fa fa-check"></i><b>5.2.2</b> On making meaning from neighbors</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-analysis-in-epidemiology-w5"><i class="fa fa-check"></i><b>5.3</b> Spatial Analysis in Epidemiology, w5</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-contiguity-neighbor-objects"><i class="fa fa-check"></i><b>5.3.1</b> Creating contiguity neighbor objects</a></li>
<li class="chapter" data-level="5.3.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.3.2</b> Creating k-nearest neighbors</a></li>
<li class="chapter" data-level="5.3.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-graph-based-triangle-neighbor-objects"><i class="fa fa-check"></i><b>5.3.3</b> Creating Graph-based triangle neighbor objects</a></li>
<li class="chapter" data-level="5.3.4" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-fixed-distance-neighbors"><i class="fa fa-check"></i><b>5.3.4</b> Creating fixed-distance neighbors</a></li>
<li class="chapter" data-level="5.3.5" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#from-spatial-neighbors-to-spatial-disease-mapping"><i class="fa fa-check"></i><b>5.3.5</b> From spatial neighbors to spatial Disease Mapping</a></li>
<li class="chapter" data-level="5.3.6" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-empirical-bayes"><i class="fa fa-check"></i><b>5.3.6</b> Spatial Empirical Bayes</a></li>
<li class="chapter" data-level="5.3.7" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#final-thoughts-making-choices"><i class="fa fa-check"></i><b>5.3.7</b> Final thoughts: Making choices</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html"><i class="fa fa-check"></i><b>6</b> Disease Mapping III</a>
<ul>
<li class="chapter" data-level="6.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#getting-ready-w6"><i class="fa fa-check"></i><b>6.1</b> Getting Ready, w6</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#learning-objectives-w6"><i class="fa fa-check"></i><b>6.1.1</b> Learning objectives, w6</a></li>
<li class="chapter" data-level="6.1.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#additional-resources-w6"><i class="fa fa-check"></i><b>6.1.2</b> Additional Resources, w6</a></li>
<li class="chapter" data-level="6.1.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#important-vocabulary-w6"><i class="fa fa-check"></i><b>6.1.3</b> Important Vocabulary, w6</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#spatial-thinking-in-epidemiology-w6"><i class="fa fa-check"></i><b>6.2</b> Spatial Thinking in Epidemiology, w6</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#revisiting-spatial-point-processes"><i class="fa fa-check"></i><b>6.2.1</b> Revisiting spatial point processes</a></li>
<li class="chapter" data-level="6.2.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#what-is-a-kernel-density-estimator"><i class="fa fa-check"></i><b>6.2.2</b> What is a kernel density estimator?</a></li>
<li class="chapter" data-level="6.2.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#limitations-in-kernel-density-estimation"><i class="fa fa-check"></i><b>6.2.3</b> Limitations in kernel density estimation</a></li>
<li class="chapter" data-level="6.2.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#uses-for-kernel-density-estimation-kde-in-spatial-epidemiology"><i class="fa fa-check"></i><b>6.2.4</b> Uses for kernel density estimation (KDE) in spatial epidemiology</a></li>
<li class="chapter" data-level="6.2.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#guide-to-the-rest-of-this-section"><i class="fa fa-check"></i><b>6.2.5</b> Guide to the rest of this section…</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#spatial-analysis-in-epidemiology-kernel-estimation-of-point-processes"><i class="fa fa-check"></i><b>6.3</b> Spatial Analysis in Epidemiology: Kernel estimation of point processes</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#preparing-packages-and-data"><i class="fa fa-check"></i><b>6.3.1</b> Preparing packages and data</a></li>
<li class="chapter" data-level="6.3.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#introducing-a-new-spatial-data-class-ppp"><i class="fa fa-check"></i><b>6.3.2</b> Introducing a new spatial data class: <code>ppp</code></a></li>
<li class="chapter" data-level="6.3.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-the-ppp-objects"><i class="fa fa-check"></i><b>6.3.3</b> Creating the <code>ppp</code> objects</a></li>
<li class="chapter" data-level="6.3.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#bandwidth-selection"><i class="fa fa-check"></i><b>6.3.4</b> Bandwidth selection</a></li>
<li class="chapter" data-level="6.3.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#estimating-kernel-density-surfaces"><i class="fa fa-check"></i><b>6.3.5</b> Estimating Kernel Density surfaces</a></li>
<li class="chapter" data-level="6.3.6" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-relative-risk-surface-manually"><i class="fa fa-check"></i><b>6.3.6</b> Creating relative risk surface manually</a></li>
<li class="chapter" data-level="6.3.7" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-relative-risk-surface-with-risk-function"><i class="fa fa-check"></i><b>6.3.7</b> Creating relative risk surface with <code>risk()</code> function</a></li>
<li class="chapter" data-level="6.3.8" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#using-functions-to-map-rr-with-tmap"><i class="fa fa-check"></i><b>6.3.8</b> Using functions to map RR with <code>tmap</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#gwss"><i class="fa fa-check"></i><b>6.4</b> Spatial Analysis in Epidemiology: Kernel estimation of areal data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#packages-and-data"><i class="fa fa-check"></i><b>6.4.1</b> Packages and data</a></li>
<li class="chapter" data-level="6.4.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#what-bandwidth-for-kernel-density-estimates"><i class="fa fa-check"></i><b>6.4.2</b> What bandwidth for kernel density estimates?</a></li>
<li class="chapter" data-level="6.4.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#geographically-weighted-summary-statistics-gwss"><i class="fa fa-check"></i><b>6.4.3</b> Geographically weighted summary statistics: <code>gwss()</code></a></li>
<li class="chapter" data-level="6.4.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#calculating-pseudo-p-values-for-smoothed-estimates"><i class="fa fa-check"></i><b>6.4.4</b> Calculating pseudo p-values for smoothed estimates</a></li>
<li class="chapter" data-level="6.4.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#estimating-geographically-weighted-bivariate-statistics"><i class="fa fa-check"></i><b>6.4.5</b> Estimating geographically-weighted bivariate statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html"><i class="fa fa-check"></i><b>7</b> Disease Mapping IV</a>
<ul>
<li class="chapter" data-level="7.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#getting-ready-w7"><i class="fa fa-check"></i><b>7.1</b> Getting Ready, w7</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#learning-objectives-w7"><i class="fa fa-check"></i><b>7.1.1</b> Learning objectives, w7</a></li>
<li class="chapter" data-level="7.1.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#additional-resources-w7"><i class="fa fa-check"></i><b>7.1.2</b> Additional Resources, w7</a></li>
<li class="chapter" data-level="7.1.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#important-vocabulary-w7"><i class="fa fa-check"></i><b>7.1.3</b> Important Vocabulary, w7</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#spatial-thinking-in-epidemiology-w7"><i class="fa fa-check"></i><b>7.2</b> Spatial Thinking in Epidemiology, w7</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#what-is-bayesian-inference"><i class="fa fa-check"></i><b>7.2.1</b> What is <em>Bayesian Inference</em>?</a></li>
<li class="chapter" data-level="7.2.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#bayesian-inference-in-spatial-epidemiology"><i class="fa fa-check"></i><b>7.2.2</b> Bayesian inference in spatial epidemiology</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#spatial-analysis-in-epidemiology-w7"><i class="fa fa-check"></i><b>7.3</b> Spatial Analysis in Epidemiology, w7</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>7.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#preparing-for-carbayes"><i class="fa fa-check"></i><b>7.3.2</b> Preparing for <code>CARBayes()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#fitting-a-besag-york-mollie-bym-bayesian-model"><i class="fa fa-check"></i><b>7.3.3</b> Fitting a <em>Besag-York-Mollie (BYM)</em> Bayesian model</a></li>
<li class="chapter" data-level="7.3.4" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#summarizing-carbayes-model-output"><i class="fa fa-check"></i><b>7.3.4</b> Summarizing <code>CARBayes</code> model output</a></li>
<li class="chapter" data-level="7.3.5" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#making-inference-from-bayesian-posteriors"><i class="fa fa-check"></i><b>7.3.5</b> Making inference from Bayesian posteriors</a></li>
<li class="chapter" data-level="7.3.6" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#extracting-summaries-for-mapping-or-analysis"><i class="fa fa-check"></i><b>7.3.6</b> Extracting summaries for mapping or analysis</a></li>
<li class="chapter" data-level="7.3.7" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#plot-raw-versus-smoothed"><i class="fa fa-check"></i><b>7.3.7</b> Plot raw versus smoothed</a></li>
<li class="chapter" data-level="7.3.8" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#mapping-rates"><i class="fa fa-check"></i><b>7.3.8</b> Mapping rates</a></li>
<li class="chapter" data-level="7.3.9" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#mapping-exceedance-probability"><i class="fa fa-check"></i><b>7.3.9</b> Mapping exceedance probability</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html"><i class="fa fa-check"></i><b>8</b> Spatial Structure and Clustering I</a>
<ul>
<li class="chapter" data-level="8.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#getting-ready-w8"><i class="fa fa-check"></i><b>8.1</b> Getting Ready, w8</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#learning-objectives-w8"><i class="fa fa-check"></i><b>8.1.1</b> Learning objectives, w8</a></li>
<li class="chapter" data-level="8.1.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#additional-resources-w8"><i class="fa fa-check"></i><b>8.1.2</b> Additional Resources, w8</a></li>
<li class="chapter" data-level="8.1.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#important-vocabulary-w8"><i class="fa fa-check"></i><b>8.1.3</b> Important Vocabulary, w8</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#spatial-thinking-in-epidemiology-w8"><i class="fa fa-check"></i><b>8.2</b> Spatial Thinking in Epidemiology, w8</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#two-big-questions"><i class="fa fa-check"></i><b>8.2.1</b> Two big questions…</a></li>
<li class="chapter" data-level="8.2.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#why-does-structure-or-clustering-matter"><i class="fa fa-check"></i><b>8.2.2</b> Why does structure or clustering matter?</a></li>
<li class="chapter" data-level="8.2.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#making-meaning-of-hypotheses-in-spatial-structure-testing"><i class="fa fa-check"></i><b>8.2.3</b> Making meaning of hypotheses in spatial structure testing</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#spatial-analysis-in-epidemiology-w8"><i class="fa fa-check"></i><b>8.3</b> Spatial Analysis in Epidemiology, w8</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>8.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="8.3.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#global-morans-i"><i class="fa fa-check"></i><b>8.3.2</b> Global Moran’s I</a></li>
<li class="chapter" data-level="8.3.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#local-morans-i"><i class="fa fa-check"></i><b>8.3.3</b> Local Moran’s I</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html"><i class="fa fa-check"></i><b>9</b> Spatial Structure and Clustering II</a>
<ul>
<li class="chapter" data-level="9.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#getting-ready-w9"><i class="fa fa-check"></i><b>9.1</b> Getting Ready, w9</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#learning-objectives-w9"><i class="fa fa-check"></i><b>9.1.1</b> Learning objectives, w9</a></li>
<li class="chapter" data-level="9.1.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#additional-resources-w9"><i class="fa fa-check"></i><b>9.1.2</b> Additional Resources, w9</a></li>
<li class="chapter" data-level="9.1.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#important-vocabulary-w9"><i class="fa fa-check"></i><b>9.1.3</b> Important Vocabulary, w9</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatial-thinking-in-epidemiology-conceptual-tools-for-thinking-about-clusters"><i class="fa fa-check"></i><b>9.2</b> Spatial Thinking in Epidemiology: Conceptual tools for thinking about ‘clusters’</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#the-clustering-conundrum"><i class="fa fa-check"></i><b>9.2.1</b> The clustering conundrum</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatial-scan-statistics"><i class="fa fa-check"></i><b>9.3</b> Spatial Scan Statistics</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>9.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="9.3.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#overview-of-kulldorff-nagarwalla-scan-statistic"><i class="fa fa-check"></i><b>9.3.2</b> Overview of <em>Kulldorff &amp; Nagarwalla</em> scan statistic</a></li>
<li class="chapter" data-level="9.3.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatio-temporal-scan-statistics"><i class="fa fa-check"></i><b>9.3.3</b> Spatio-temporal scan statistics</a></li>
<li class="chapter" data-level="9.3.4" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#estimating-spatial-only-kulldorff-scan-statistics"><i class="fa fa-check"></i><b>9.3.4</b> Estimating <em>spatial-only</em> Kulldorff scan statistics</a></li>
<li class="chapter" data-level="9.3.5" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#estimating-spatio-temporal-kuldorff-scan-statistic"><i class="fa fa-check"></i><b>9.3.5</b> Estimating <em>spatio-temporal</em> Kuldorff scan statistic</a></li>
<li class="chapter" data-level="9.3.6" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#concluding-thoughts"><i class="fa fa-check"></i><b>9.3.6</b> Concluding thoughts</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="spatreg1.html"><a href="spatreg1.html"><i class="fa fa-check"></i><b>10</b> Spatial Regression I</a>
<ul>
<li class="chapter" data-level="10.1" data-path="spatreg1.html"><a href="spatreg1.html#getting-ready-w10"><i class="fa fa-check"></i><b>10.1</b> Getting Ready, w10</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="spatreg1.html"><a href="spatreg1.html#learning-objectives-w10"><i class="fa fa-check"></i><b>10.1.1</b> Learning objectives, w10</a></li>
<li class="chapter" data-level="10.1.2" data-path="spatreg1.html"><a href="spatreg1.html#important-vocabulary-w10"><i class="fa fa-check"></i><b>10.1.2</b> Important Vocabulary, w10</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="spatreg1.html"><a href="spatreg1.html#multivariable-regression-for-exploring-spatial-data"><i class="fa fa-check"></i><b>10.2</b> Multivariable regression for exploring spatial data</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="spatreg1.html"><a href="spatreg1.html#data-generating-process"><i class="fa fa-check"></i><b>10.2.1</b> Data Generating Process</a></li>
<li class="chapter" data-level="10.2.2" data-path="spatreg1.html"><a href="spatreg1.html#model-residuals-are-not-just-mistakes"><i class="fa fa-check"></i><b>10.2.2</b> Model residuals are not just mistakes</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="spatreg1.html"><a href="spatreg1.html#spatializing-aspatial-regression"><i class="fa fa-check"></i><b>10.3</b> Spatializing aspatial regression</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="spatreg1.html"><a href="spatreg1.html#data-packages"><i class="fa fa-check"></i><b>10.3.1</b> Data &amp; Packages</a></li>
<li class="chapter" data-level="10.3.2" data-path="spatreg1.html"><a href="spatreg1.html#fitting-unconditional-empty-model"><i class="fa fa-check"></i><b>10.3.2</b> Fitting unconditional (empty) model</a></li>
<li class="chapter" data-level="10.3.3" data-path="spatreg1.html"><a href="spatreg1.html#fitting-conditional-model"><i class="fa fa-check"></i><b>10.3.3</b> Fitting conditional model</a></li>
<li class="chapter" data-level="10.3.4" data-path="spatreg1.html"><a href="spatreg1.html#mapping-residuals"><i class="fa fa-check"></i><b>10.3.4</b> Mapping residuals</a></li>
<li class="chapter" data-level="10.3.5" data-path="spatreg1.html"><a href="spatreg1.html#morans-i-tests-on-lm-models"><i class="fa fa-check"></i><b>10.3.5</b> Moran’s I tests on <code>lm</code> models</a></li>
<li class="chapter" data-level="10.3.6" data-path="spatreg1.html"><a href="spatreg1.html#morans-i-tests-on-glm-models"><i class="fa fa-check"></i><b>10.3.6</b> Moran’s I tests on <code>glm</code> models</a></li>
<li class="chapter" data-level="10.3.7" data-path="spatreg1.html"><a href="spatreg1.html#mapping-glm-residuals"><i class="fa fa-check"></i><b>10.3.7</b> Mapping <code>glm</code> residuals</a></li>
<li class="chapter" data-level="10.3.8" data-path="spatreg1.html"><a href="spatreg1.html#morans-i-for-glm"><i class="fa fa-check"></i><b>10.3.8</b> Moran’s I for <code>glm</code></a></li>
<li class="chapter" data-level="10.3.9" data-path="spatreg1.html"><a href="spatreg1.html#final-words"><i class="fa fa-check"></i><b>10.3.9</b> Final words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html"><i class="fa fa-check"></i><b>11</b> Spatial Regression II</a>
<ul>
<li class="chapter" data-level="11.1" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#getting-ready-w11"><i class="fa fa-check"></i><b>11.1</b> Getting Ready, w11</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#learning-objectives-w11"><i class="fa fa-check"></i><b>11.1.1</b> Learning objectives, w11</a></li>
<li class="chapter" data-level="11.1.2" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#important-vocabulary-w11"><i class="fa fa-check"></i><b>11.1.2</b> Important Vocabulary, w11</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#spatially-varying-relationships"><i class="fa fa-check"></i><b>11.2</b> Spatially varying relationships</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#non-stationarity-in-context-of-spatial-epidemiology"><i class="fa fa-check"></i><b>11.2.1</b> Non-stationarity in context of spatial epidemiology</a></li>
<li class="chapter" data-level="11.2.2" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#introducing-geographically-weighted-regression"><i class="fa fa-check"></i><b>11.2.2</b> Introducing geographically weighted regression</a></li>
<li class="chapter" data-level="11.2.3" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#making-epidemiologic-meaning-of-spatially-varying-coefficients"><i class="fa fa-check"></i><b>11.2.3</b> Making epidemiologic meaning of spatially varying coefficients</a></li>
<li class="chapter" data-level="11.2.4" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#distinguishing-variation-in-prevalence-from-variation-in-correlation"><i class="fa fa-check"></i><b>11.2.4</b> Distinguishing variation in <strong>prevalence</strong> from variation in <strong>correlation</strong></a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#estimating-geogrpahically-weighted-regression-models"><i class="fa fa-check"></i><b>11.3</b> Estimating geogrpahically weighted regression models</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#packages-and-data"><i class="fa fa-check"></i><b>11.3.1</b> Packages and Data</a></li>
<li class="chapter" data-level="11.3.2" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#preparing-for-using-gwmodel"><i class="fa fa-check"></i><b>11.3.2</b> Preparing for using <code>GWModel</code></a></li>
<li class="chapter" data-level="11.3.3" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#defining-local-optimizing-kernel-bandwidths"><i class="fa fa-check"></i><b>11.3.3</b> Defining local: optimizing kernel bandwidths</a></li>
<li class="chapter" data-level="11.3.4" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#geographically-weighted-regression"><i class="fa fa-check"></i><b>11.3.4</b> Geographically weighted regression</a></li>
<li class="chapter" data-level="11.3.5" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#checking-local-multi-collinearity"><i class="fa fa-check"></i><b>11.3.5</b> Checking local multi-collinearity</a></li>
<li class="chapter" data-level="11.3.6" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#adjusting-for-multiple-comparisons"><i class="fa fa-check"></i><b>11.3.6</b> Adjusting for multiple comparisons</a></li>
<li class="chapter" data-level="11.3.7" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#visualizing-model-inference"><i class="fa fa-check"></i><b>11.3.7</b> Visualizing model inference</a></li>
<li class="chapter" data-level="11.3.8" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#extensions"><i class="fa fa-check"></i><b>11.3.8</b> Extensions</a></li>
<li class="chapter" data-level="11.3.9" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#data-models"><i class="fa fa-check"></i><b>11.3.9</b> Data models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html"><i class="fa fa-check"></i><b>12</b> Spatial Regression III</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#getting-ready-w12"><i class="fa fa-check"></i><b>12.1</b> Getting Ready, w12</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#learning-objectives-w12"><i class="fa fa-check"></i><b>12.1.1</b> Learning objectives, w12</a></li>
<li class="chapter" data-level="12.1.2" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#important-vocabulary-w12"><i class="fa fa-check"></i><b>12.1.2</b> Important Vocabulary, w12</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#spatial-econometric-models-putting-dependence-right-in-the-model"><i class="fa fa-check"></i><b>12.2</b> Spatial econometric models: Putting dependence right in the model</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#comparing-spatial-econometric-models"><i class="fa fa-check"></i><b>12.2.1</b> Comparing spatial econometric models</a></li>
<li class="chapter" data-level="12.2.2" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#comparing-and-selecting-spatial-econometric-models"><i class="fa fa-check"></i><b>12.2.2</b> Comparing and selecting spatial econometric models</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#estimating-spatial-econometrics-models"><i class="fa fa-check"></i><b>12.3</b> Estimating spatial econometrics models</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#package-data"><i class="fa fa-check"></i><b>12.3.1</b> Package &amp; Data</a></li>
<li class="chapter" data-level="12.3.2" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#defining-the-study-question"><i class="fa fa-check"></i><b>12.3.2</b> Defining the study question</a></li>
<li class="chapter" data-level="12.3.3" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#defining-competing-definitions-of-local"><i class="fa fa-check"></i><b>12.3.3</b> Defining competing definitions of <em>local</em></a></li>
<li class="chapter" data-level="12.3.4" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#two-extremes"><i class="fa fa-check"></i><b>12.3.4</b> Two extremes</a></li>
<li class="chapter" data-level="12.3.5" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#fitting-multivariable-regression-models"><i class="fa fa-check"></i><b>12.3.5</b> Fitting multivariable regression models</a></li>
<li class="chapter" data-level="12.3.6" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#spatial-error-model-1"><i class="fa fa-check"></i><b>12.3.6</b> Spatial Error Model</a></li>
<li class="chapter" data-level="12.3.7" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#hausman-test-of-coefficients"><i class="fa fa-check"></i><b>12.3.7</b> Hausman test of coefficients</a></li>
<li class="chapter" data-level="12.3.8" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#spatial-lag-model"><i class="fa fa-check"></i><b>12.3.8</b> Spatial Lag Model</a></li>
<li class="chapter" data-level="12.3.9" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#spatial-durbin-model-1"><i class="fa fa-check"></i><b>12.3.9</b> Spatial Durbin Model</a></li>
<li class="chapter" data-level="12.3.10" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#comparing-models"><i class="fa fa-check"></i><b>12.3.10</b> Comparing Models</a></li>
<li class="chapter" data-level="12.3.11" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#impact-assessments"><i class="fa fa-check"></i><b>12.3.11</b> Impact Assessments</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Appendices</b></span></li>
<li class="chapter" data-level="13" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html"><i class="fa fa-check"></i><b>13</b> Tips for reproducibility in <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#additional-resources"><i class="fa fa-check"></i>Additional Resources</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#workflows-to-enhance-reproducibility"><i class="fa fa-check"></i>Workflows to enhance reproducibility</a>
<ul>
<li><a href="tips-for-reproducibility-in-r.html#using-projects-in-r">Using Projects in <code>R</code></a></li>
</ul></li>
<li><a href="tips-for-reproducibility-in-r.html#understanding-directory-and-file-path-names-in-r">Understanding directory and file path names in <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#specify-a-location-within-the-working-directory"><i class="fa fa-check"></i>Specify a location within the working directory</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#specify-a-relative-location-outside-the-working-directory"><i class="fa fa-check"></i>Specify a relative location outside the working directory</a></li>
</ul></li>
<li><a href="tips-for-reproducibility-in-r.html#why-r-notebooks">Why <code>R Notebooks</code>?</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#what-you-need-to-know"><i class="fa fa-check"></i>What you need to know</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#important-r-notebook-functions"><i class="fa fa-check"></i>Important R Notebook functions</a>
<ul>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#the-yaml"><i class="fa fa-check"></i>The YAML</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#typing-text"><i class="fa fa-check"></i>Typing text</a></li>
<li><a href="tips-for-reproducibility-in-r.html#adding-r-code">Adding <code>R</code> Code</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#making-tables"><i class="fa fa-check"></i>Making tables</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#workflow"><i class="fa fa-check"></i>Workflow</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#optional-functions"><i class="fa fa-check"></i>Optional functions</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#customizing-your-yaml"><i class="fa fa-check"></i>Customizing your YAML</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#simple-formatting-of-your-notebook"><i class="fa fa-check"></i>Simple formatting of your Notebook</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#text-formatting"><i class="fa fa-check"></i>Text formatting</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#final-note"><i class="fa fa-check"></i>Final Note</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sf-overview.html"><a href="sf-overview.html"><i class="fa fa-check"></i><b>14</b> Tips for working with <code>sf</code> data class</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sf-overview.html"><a href="sf-overview.html#st_set_geom"><i class="fa fa-check"></i><b>14.1</b> <code>st_set_geom()</code></a></li>
<li class="chapter" data-level="14.2" data-path="sf-overview.html"><a href="sf-overview.html#st-as-sf"><i class="fa fa-check"></i><b>14.2</b> <code>st_as_sf()</code></a></li>
<li class="chapter" data-level="14.3" data-path="sf-overview.html"><a href="sf-overview.html#st_crs"><i class="fa fa-check"></i><b>14.3</b> <code>st_crs()</code></a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>15</b> Tips for using <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="15.1" data-path="dplyr.html"><a href="dplyr.html#select"><i class="fa fa-check"></i><b>15.1</b> <code>select()</code></a></li>
<li class="chapter" data-level="15.2" data-path="dplyr.html"><a href="dplyr.html#mutate"><i class="fa fa-check"></i><b>15.2</b> <code>mutate()</code></a></li>
<li class="chapter" data-level="15.3" data-path="dplyr.html"><a href="dplyr.html#filter"><i class="fa fa-check"></i><b>15.3</b> <code>filter()</code></a></li>
<li class="chapter" data-level="15.4" data-path="dplyr.html"><a href="dplyr.html#arrange"><i class="fa fa-check"></i><b>15.4</b> <code>arrange()</code></a></li>
<li class="chapter" data-level="15.5" data-path="dplyr.html"><a href="dplyr.html#pipe-operator"><i class="fa fa-check"></i><b>15.5</b> <code>%&gt;%</code> Pipe operator</a></li>
<li class="chapter" data-level="15.6" data-path="dplyr.html"><a href="dplyr.html#group_by-and-summarise"><i class="fa fa-check"></i><b>15.6</b> <code>group_by()</code> and <code>summarise()</code></a></li>
<li class="chapter" data-level="15.7" data-path="dplyr.html"><a href="dplyr.html#join"><i class="fa fa-check"></i><b>15.7</b> <code>join()</code></a></li>
<li class="chapter" data-level="15.8" data-path="dplyr.html"><a href="dplyr.html#pivot_"><i class="fa fa-check"></i><b>15.8</b> Reshaping (transposing) data</a>
<ul>
<li class="chapter" data-level="15.8.1" data-path="dplyr.html"><a href="dplyr.html#pivot_longer-for-going-from-wide-to-long"><i class="fa fa-check"></i><b>15.8.1</b> <code>pivot_longer()</code> for going from wide to long</a></li>
<li class="chapter" data-level="15.8.2" data-path="dplyr.html"><a href="dplyr.html#pivot_wider"><i class="fa fa-check"></i><b>15.8.2</b> <code>pivot_wider()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="intro-tmap.html"><a href="intro-tmap.html"><i class="fa fa-check"></i><b>16</b> Tips for using <code>tmap</code></a>
<ul>
<li class="chapter" data-level="16.1" data-path="intro-tmap.html"><a href="intro-tmap.html#tmap-mode"><i class="fa fa-check"></i><b>16.1</b> <code>tmap</code> mode</a></li>
<li class="chapter" data-level="16.2" data-path="intro-tmap.html"><a href="intro-tmap.html#qtm"><i class="fa fa-check"></i><b>16.2</b> Quick maps: <code>qtm()</code></a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-polygons"><i class="fa fa-check"></i><b>16.2.1</b> Customizing <code>qtm()</code> for polygons</a></li>
<li class="chapter" data-level="16.2.2" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-lines"><i class="fa fa-check"></i><b>16.2.2</b> Customizing <code>qtm()</code> for lines</a></li>
<li class="chapter" data-level="16.2.3" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-points"><i class="fa fa-check"></i><b>16.2.3</b> Customizing <code>qtm()</code> for points</a></li>
<li class="chapter" data-level="16.2.4" data-path="intro-tmap.html"><a href="intro-tmap.html#finding-valid-color-options"><i class="fa fa-check"></i><b>16.2.4</b> Finding valid color options</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="intro-tmap.html"><a href="intro-tmap.html#building-maps-with-tmap"><i class="fa fa-check"></i><b>16.3</b> Building maps with <code>tmap</code></a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="intro-tmap.html"><a href="intro-tmap.html#building-blocks-in-tmap"><i class="fa fa-check"></i><b>16.3.1</b> Building blocks in <code>tmap</code></a></li>
<li class="chapter" data-level="16.3.2" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-text-on-maps"><i class="fa fa-check"></i><b>16.3.2</b> Customizing text on maps</a></li>
<li class="chapter" data-level="16.3.3" data-path="intro-tmap.html"><a href="intro-tmap.html#adding-two-or-more-spatial-objects-in-one-map"><i class="fa fa-check"></i><b>16.3.3</b> Adding two or more spatial objects in one map</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="intro-tmap.html"><a href="intro-tmap.html#controlling-layout-and-map-elements"><i class="fa fa-check"></i><b>16.4</b> Controlling layout and map elements</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="intro-tmap.html"><a href="intro-tmap.html#understanding-the-graphic-space-in-tmap"><i class="fa fa-check"></i><b>16.4.1</b> Understanding the graphic space in <code>tmap</code></a></li>
<li class="chapter" data-level="16.4.2" data-path="intro-tmap.html"><a href="intro-tmap.html#controlling-map-layout"><i class="fa fa-check"></i><b>16.4.2</b> Controlling map layout</a></li>
<li class="chapter" data-level="16.4.3" data-path="intro-tmap.html"><a href="intro-tmap.html#adding-map-elements"><i class="fa fa-check"></i><b>16.4.3</b> Adding map elements</a></li>
<li class="chapter" data-level="16.4.4" data-path="intro-tmap.html"><a href="intro-tmap.html#change-the-global-style-of-a-map"><i class="fa fa-check"></i><b>16.4.4</b> Change the global style of a map</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="intro-tmap.html"><a href="intro-tmap.html#making-small-multiple-maps"><i class="fa fa-check"></i><b>16.5</b> Making small-multiple maps</a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="intro-tmap.html"><a href="intro-tmap.html#small-multiples-as-a-vector-of-variables"><i class="fa fa-check"></i><b>16.5.1</b> Small multiples as a vector of variables</a></li>
<li class="chapter" data-level="16.5.2" data-path="intro-tmap.html"><a href="intro-tmap.html#tmap-facet"><i class="fa fa-check"></i><b>16.5.2</b> Small multiples with facets</a></li>
<li class="chapter" data-level="16.5.3" data-path="intro-tmap.html"><a href="intro-tmap.html#facets-for-time-series"><i class="fa fa-check"></i><b>16.5.3</b> Facets for time-series</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="intro-tmap.html"><a href="intro-tmap.html#small-multiples-with-tmap_arrange"><i class="fa fa-check"></i><b>16.6</b> Small multiples with <code>tmap_arrange()</code></a></li>
<li class="chapter" data-level="16.7" data-path="intro-tmap.html"><a href="intro-tmap.html#summarizing-small-multiples"><i class="fa fa-check"></i><b>16.7</b> Summarizing small multiples</a></li>
<li class="chapter" data-level="16.8" data-path="intro-tmap.html"><a href="intro-tmap.html#saving-maps"><i class="fa fa-check"></i><b>16.8</b> Saving maps</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EPI 563: Spatial Epidemiology, Fall 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatial-regression-iii" class="section level1" number="12">
<h1><span class="header-section-number">Week 12</span> Spatial Regression III</h1>
<div id="getting-ready-w12" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Getting Ready, w12</h2>
<div id="learning-objectives-w12" class="section level3" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Learning objectives, w12</h3>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 100%; margin-left: auto; margin-right: auto;  " id="learning-ob">
<caption style="caption-side: top; text-align: center;"><span id="tab:learning-ob">TABLE 1.1: </span> Learning objectives by weekly module</caption><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(208, 211, 212); font-weight: bold;">After this module you should be able to…</th></tr>
</table>

</div>
<div id="important-vocabulary-w12" class="section level3" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Important Vocabulary, w12</h3>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-316">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-316">TABLE 12.1: </span> Vocabulary for Week 12</caption><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Term</span></th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Definition</span></th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Data generating process</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">The true underlying causal structure that gives rise to (generates) the data from which you sampled. The data generating process is not typically known. We use models to try to emulate or approximate the data generating process.</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial Durbin model</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Spatial econometric model in which sptaially lagged summary of neighbors values of the *covariates* and of the *outcome*. Spatially lagged covariates suggest exposure in neighboring places affects outcome in index location.</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial Econometrics</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">A sub-field of statistics bridging econometrics and spatial analysis, wherein theoretical properties, dependencies, and interactions of spatially referenced data are analyzed in a regression framework.</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial error model</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Spatial econometric model in which unmeasured or unobserved spatially clustered predictors of the outcome produce residual autocorrelation in regression model residuals that is not accounted for by the main effects of measured covariates</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial lag model</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">Spatial econometric model in which a spatially lagged sumary of neighbors values of the dependent (outcome) variable is included on the right-hand side of the model. This pattern theoretically suggests a diffusion or contagion process of the *outcome*</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatially lagged variable</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">The weighted sum or weighted average of the neighboring values for that variable. The variable could be a spatially lagged outcome or spatially lagged covariate/predictor</td></tr>
</table>

</div>
</div>
<div id="spatial-econometric-models-putting-dependence-right-in-the-model" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Spatial econometric models: Putting dependence right in the model</h2>
<p>In <a href="spatreg1.html#spatreg1">Spatial Regression 1</a>, we examined the spatial dependence left-over after (e.g. <em>residual to</em>) conventional <em>aspatial linear regression</em>. The benefits of multivariable regression for answering epidemiologic questions are the ability to summarize relationships conditional on possibly highly-dimensional covariate patterns. The use of Moran’s I statistics to test for presence of spatial auto correlation in the residuals (errors) of multiply-adjusted models is a strategy for <strong>a)</strong> diagnosing violations of model assumptions; and <strong>b)</strong> iteratively improving model specification (variables selection) in an effort to <em>explain</em> measured variables as drivers of clustered outcomes.</p>
<p>However, the mix of <em>aspatial regression</em> with <em>spatial residual diagnostics</em> limits explanatory power for epidemiologically interesting spatial phenomenon. Specifically, the <em>aspatial regression</em> strategy:</p>
<ul>
<li>Assumes that the full effects of <em>exposures</em> on <em>outcomes</em> are contained within the boundaries of the unit of aggregation (e.g. neither ‘<em>spills over</em>’ or ‘<em>spreads to</em>’ neighboring regions affecting their rates)</li>
<li>Will still produce biased estimates of coefficients <em>if residual autocorrelation of the errrors</em> remains. In other words, if you add in all of the predictor variables you have, and the Moran’s I statistic remains meaningfully high, the regression coefficients are likely to be biased.</li>
</ul>
<p>In this module, we extend these <em>aspatial</em> methods by inserting representations of the <em>data generating process</em> that produces or explains auto correlation directly <em>into</em> the regression model. The <em>data generating process</em> is the set of interactions, relationships, and effects among people and their environments that give rise to the actual observed data. Therefore, by articulating a specific and testable <em>data generating process</em>, we are trying to explicitly model the spatial processes at play in order to recover unbiased (or less biased) covariate association estimates, but also to statistically test and quantify for evidence of <em>spatial spillover</em>. <em>Spatial spillover</em> refers to the phenomenon where the experiences in neighboring units (e.g. their outcome rates or their exposure/covariate values) have a direct or indirect influence on the risks or rates in an index region. Spillover therefore approximates the processes of contagion, diffusion, and propagation that could occur with infectious diseases, environmental contaminants, and some social processes including norms, knowledge, attitudes, and behaviors.</p>
<p>The potential evident in this class of spatial models – often termed <em>spatial econometrics models</em> because of their development in economics – comes at the cost of many assumptions, and increased importance of thoughtfulness on the part of the epidemiologic analyst. There are both thorny statistical issues involved, but also the perennial challenge of overlaying statistical issues on the questions and interests of population sciences like epidemiology.</p>
<div id="comparing-spatial-econometric-models" class="section level3" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Comparing spatial econometric models</h3>
<p>There are numerous regression models to quantify spatially correlated data. In this module we introduce just three that have seen more use in economics, sociology, and political science, but that are occasionally used in epidemiology. Unfortunately, these methods are primarily developed for <em>linear regression</em> where the outcomes (or really the errors conditional on all other aspects of the model) are assumed to be normally and independently distributed. We can use these models for spatial analysis of epidemiologic data if the ‘events’ being analyzed are rates, risks, or prevalence that are plausibly normally distributed (note we can still use population weighting of regions to account for heteroskedasticity in variance due to varying population size). For those interested, there are some Bayesian and other extensions to incorporate spatially-lagged predictors into generalized linear regression.</p>
<div id="spatially-lagged-outcome-model" class="section level4" number="12.2.1.1">
<h4><span class="header-section-number">12.2.1.1</span> Spatially Lagged Outcome Model</h4>
<p>The first econometric model to be introduced is sometimes called a ‘<em>spatial lag model</em>’ because it includes the <em>spatially lagged</em> value of the neighbors outcome (e.g. weighted average of the values of the outcome for all spatial neighbors) as a <em>preictor</em> in the model. In other words it suggests that the disease risk, rate, or prevalence in the neighboring regions has a direct influence on the risk, rate, or prevalence inside the index region. The easiest metaphor for this would be contagious infectious disease, where the number of infected neighbors could directly cause your own infection incidence to rise due to contagion. While we have previously talked about <em>social contagion</em> for understanding the spatial spread of disease, that seems more plausible in the next model, where the exposures or predictors are lagged.</p>
<p>The Spatial Lag Model can be represented like this:</p>
<p><span class="math display">\[Y_i=\rho WY_{-i} + \beta X_i + e_i\]</span>
To describe that model in words we have:</p>
<ul>
<li>The health event outcome, <span class="math inline">\(Y_i\)</span> which is the value of a risk, rate, prevalence in the <span class="math inline">\(i^{th}\)</span> region</li>
<li>The spatial correlation coefficient, <span class="math inline">\(\rho\)</span> quantifying the strength or magnitude of correlation between the average outcome in the neighbors with the outcome in the index county, <span class="math inline">\(i\)</span>, conditional on all other variables in the model. The spatial correlation coefficient, <span class="math inline">\(\rho\)</span> is interpreted as other correlation coefficients with a range from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span>. Note that the value <span class="math inline">\(\rho=0\)</span> implies zero correlation (net of other covariates in the model) of the neighbors outcome with the index region outcome; in this setting the term effectively drops from the model because it is zero, resulting in a conventional <em>aspatial linear regression</em> model.</li>
<li>The spatial weights matrix, <span class="math inline">\(W\)</span>, is the same spatial weights construct used in spatial Empirical Bayes and Moran’s I analyses. In other words it is the mathematical summarization of which regions are neighbors with which. Note that we use <em>row-standardized weights</em> to aid in interpretting the spatial regression coefficient.</li>
<li>The <span class="math inline">\(\rho W\)</span> is specific to the values of the outcomes <span class="math inline">\(Y_{-i}\)</span>. In other words this is about the regions that <em>are not <span class="math inline">\(i\)</span></em>, and specifically those who are neighbors, as defined by <span class="math inline">\(W\)</span> (e.g. all non-neighbors have <span class="math inline">\(W=0\)</span> and thus drop out).</li>
<li>The <span class="math inline">\(\beta X_i\)</span> and <span class="math inline">\(e_i\)</span> have the same interpretation as they do in conventional regression. Specifically, <span class="math inline">\(\beta\)</span> is the regression coefficient for the change in the outcome <span class="math inline">\(Y\)</span> for each 1-unit change in <span class="math inline">\(X\)</span>, conditional on the spatially lagged outcome, <span class="math inline">\(\rho WY_{-i}\)</span></li>
</ul>
</div>
<div id="spatial-durbin-model" class="section level4" number="12.2.1.2">
<h4><span class="header-section-number">12.2.1.2</span> Spatial Durbin Model</h4>
<p>A natural extension to the Spatial Lag is a model where not only the <em>outcome</em> or dependent variable are allowed to spillover from one region to another, but the effects of the <em>exposure</em> or other independent covariates are similarly allowed to spillover. Conceptually, this model proxies a <em>data generating process</em> wherein the exposures effect on health is not constrained to fall only within the boundaries of a region and that region’s own outcome, but could also diffuse or spread to influence the outcome in neighboring regions. This is relatively easy to imagine with environmental and service-access predictors whose influence are unlikely to arbitrarily end at boundaries.</p>
<p>The statistical description of the Spatial Durbin model looks much like the Spatial Lag, with one addition:</p>
<p><span class="math display">\[Y_i=\rho WY_{-i} + \beta X_i + \gamma WX_{-i} + e_i\]</span></p>
<p>In this model the added components can be described in words like this:</p>
<ul>
<li>The spatial weights matrix, <span class="math inline">\(W\)</span> is identical in both locations: <span class="math inline">\(\rho WY_{-i}\)</span> and <span class="math inline">\(\gamma WX_{-i}\)</span>. In both instances it simply describes which regions are neighbors (<span class="math inline">\(W&gt;0\)</span>) and which are not neighbors (<span class="math inline">\(W==0\)</span>).</li>
<li>There are two sets of covariates, <span class="math inline">\(X\)</span> in this model. The first reference (<span class="math inline">\(\beta X_i\)</span>) refers to the measured covariates, <span class="math inline">\(X\)</span> in the <span class="math inline">\(i^{th}\)</span> region. In contrast the second reference <span class="math inline">\(\gamma WX_{-i}\)</span>, refers to the values of <span class="math inline">\(X\)</span> that <strong>are not</strong> in the <span class="math inline">\(i^{th}\)</span> region, indicated by the <span class="math inline">\(X_{-i}\)</span> or ‘<em>all regions that are not <span class="math inline">\(i\)</span></em>’. More specifically this is the lagged (averaged) values of the neighbors for all regions not-i but also where <span class="math inline">\(W&gt;0\)</span> (e.g. among neighbors).</li>
<li><span class="math inline">\(\gamma\)</span> is the coefficient quantifying the magnitude and direction of the association between the spatially-lagged covariates and the outcome.</li>
</ul>
</div>
<div id="spatial-error-model" class="section level4" number="12.2.1.3">
<h4><span class="header-section-number">12.2.1.3</span> Spatial Error Model</h4>
<p>This final model is an alternative specification of the underlying reason for the observed data patterns, the data generating process. In this model, the assumption is that the reason for the observed spatial patterns of autocorrelation in outcomes and/or residuals is not one of spillover (contagion) of outcomes from one reason to the next, nor the spillover or diffusion of the effects of exposures from one region on the outcomes of neighbors.</p>
<p>Instead, this model simply states that the reason is because of important <em>missing variables</em> that themselves are spatially clustered. Therefore – until they can be included in the model – the model residuals will also be clustered or auto correlated. In other words this model assertion was the starting point in <a href="spatreg1.html#spatreg1">Spatial Regression I</a>. However, what is different here is that the Spatial Error model articulates a statistical way to estimate <em>valid</em> and <em>unbiased</em> coefficients in spite of (or conditional on) the dependent errors or residuals.</p>
<p>This is done in a manner familiar to those who have worked with correlated data. The strategy is to explicitly model or account for the auto correlation as a nuisance term in order that the other terms in the model can be estimated in an unbiased way. The model form looks like this:</p>
<p><span class="math display">\[Y_i=\beta X_i+ u_i\]</span>
<span class="math display">\[u_i=\lambda Wu_{-i} + e_i\]</span></p>
<p>Essentially what this model does is give a place for the correlation to be modeled (e.g. the residual correlation coefficient, <span class="math inline">\(\lambda\)</span>), in order that the remaining residual, <span class="math inline">\(e_i\)</span> can be assumed to be distributed <span class="math inline">\(N(0, \sigma^2)\)</span>). The quantification of the correlation coefficient <span class="math inline">\(\lambda\)</span> provides a similar interpretation as the spatial lag correlation coefficient, <span class="math inline">\(\rho\)</span>, in that each range from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span>, with zero suggesting no correlation (e.g. all units are spatially independent, conditional on variables in the model).</p>
</div>
</div>
<div id="comparing-and-selecting-spatial-econometric-models" class="section level3" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> Comparing and selecting spatial econometric models</h3>
<p>Given this set of models, how is the spatial epidemiologist to choose? The best strategy is a mix of substantive knowledge and theory that is specific to the scenario or question at hand, with careful and cautious use of statistical testing to compare the model fit of competing models.</p>
<p>First, there are several assertions made by LeSage &amp; Pace (2009) that consider the consequences of a mis-match between whatever the <strong>true</strong> data generating process might be (e.g. what is really happening in the world that gave rise to the data), versus the data generating process approximated by the choice of one of these models.</p>
<ol style="list-style-type: decimal">
<li>If the <em>true</em> data generating process is <em>Spatial Error</em>, any of the three models will produce unbiased estimates of coefficients, although the <em>Durbin</em> and <em>Spatial Lag</em> models may be less statistically efficient at doing so (e.g. produce unnecessarily large standard errors). So the answer will, on average, be valid regardless of model choice, but only if the true reason for the spatial clustering of residuals is because of missing variables.</li>
<li>If the <em>true</em> data generating process is <em>Spatial Lag</em>, but the analyst selects a <em>Spatial Error</em> model, the model coefficients could be biased and misleading. In other words if there is a ‘<em>contagious</em>’ spread of the outcome producing the dependence in the risk or rate of disease, but instead of appropriately fitting a <em>spatial Lag</em> model, a spatial error model is fit instead, the answers may be invalid.</li>
<li>Finally, if the <em>true</em> data generating process concerns direct spatial spread of the outcome and spatial spillover of the exposures or predictors (e.g. as suggested in the <em>Durbin</em> model), either the <em>spatial Error</em> or the <em>Spatial Lag</em> model will be biased. In other words, failing to explicitly model the spatial spillover of covariates can produce biased estimates.</li>
</ol>
<p>The take home message from these assertions is that the <em>Spatial Durbin</em> model is a logical baseline or starting point in the absence of any specific substantive or theoretical reason to prefer the other models. By comparing the spatial Durbin model to the others, it is possible to test whether in fact there is any statistical evidence for the spatial spillover of covariates.</p>
<p>The use of statistical testing to compare models will be reviewed in the next tutorial section. However, briefly, it is possible to use likelihood ratio testing or comparison of AIC of competing model forms to determine whether the model fit is explained better with one strategy or another.</p>
</div>
</div>
<div id="estimating-spatial-econometrics-models" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Estimating spatial econometrics models</h2>
<div id="package-data" class="section level3" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Package &amp; Data</h3>
<p>The packages are largely the usual suspects with one addition, the package <code>spatialreg</code>. This package actually subsumed many functions from <code>spdep</code>. We will still use <code>spdep</code> for neighbor &amp; weights creation, but I will not load the package directly because it has many function conflicts with <code>spatialreg</code>. We will use the <code>spdep::</code> notation to call it out when needed.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="spatial-regression-iii.html#cb321-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb321-2"><a href="spatial-regression-iii.html#cb321-2"></a><span class="kw">library</span>(spatialreg)</span>
<span id="cb321-3"><a href="spatial-regression-iii.html#cb321-3"></a><span class="kw">library</span>(sf)</span>
<span id="cb321-4"><a href="spatial-regression-iii.html#cb321-4"></a><span class="kw">library</span>(tmap)</span></code></pre></div>
<p>Once again, we will use the Atlanta-area BRFSS 500-cities project census-tract-based estimates of self-reported health behaviors and outcomes, merged with some area-based indicators.</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="spatial-regression-iii.html#cb322-1"></a><span class="co"># Read in the dataset and remove tracts with missing values...</span></span>
<span id="cb322-2"><a href="spatial-regression-iii.html#cb322-2"></a>atl &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&#39;BRFSS_Atl.gpkg&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb322-3"><a href="spatial-regression-iii.html#cb322-3"></a><span class="st">  </span><span class="kw">na.omit</span>() </span></code></pre></div>
<p>The <a href="spatial-regression-ii.html#brfss-data">full data dictionary is in the Spatial Regression II</a> section of th eBook. Briefly, here are the variables we will focus on for this tutorial example:</p>
<table>
<colgroup>
<col width="23%" />
<col width="43%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>FIPS</code></td>
<td>Census tract ID</td>
<td></td>
</tr>
<tr class="even">
<td><code>PopulationCount</code></td>
<td>Count of tract pop</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="odd">
<td><code>MENTALHLTH</code></td>
<td>Prevalence poor mental health &gt; 14 days (18+)m</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="even">
<td><code>PHYSHLTH</code></td>
<td>Prevalence poor physical health &gt; 14 days (18+)</td>
<td>500-cities, BRFSS</td>
</tr>
<tr class="odd">
<td><code>ParkProximity_std</code></td>
<td>Distance to nearest park (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="even">
<td><code>Poverty_std</code></td>
<td>Poverty rate (z-score)</td>
<td>Opportunity Index</td>
</tr>
<tr class="odd">
<td><code>InstabilityStress</code></td>
<td>Summed z-score from Foreclosure &amp; Vacancy</td>
<td>Derived from Opportunity Index</td>
</tr>
<tr class="even">
<td><code>geom</code></td>
<td>Census tract polygon geom</td>
<td>US Census bureau</td>
</tr>
</tbody>
</table>
</div>
<div id="defining-the-study-question" class="section level3" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Defining the study question</h3>
<p>What follows is an abbreviated summary of specific questions (statistical and epidemiologic), and their motivation. A more <em>real-world</em> scenario might include additional measures, consideration of other sources of bias include misclassification of exposure or outcome, selection bias, and ecologic bias or confounding related to the modifiable areal-unit problem.</p>
<div id="the-idealized-ovarching-question" class="section level4" number="12.3.2.1">
<h4><span class="header-section-number">12.3.2.1</span> The idealized ovarching question</h4>
<p><em>The idealized overarching question</em> is whether living in place characterized by concentrated poverty and housing instability <em>causes</em> (e.g. increases or decreases) poor mental health. We specifically focus on these variables for their hypothesized contribution to mental health:</p>
<ul>
<li><code>Poverty_std</code> is the standardized poverty rate within each tract. We know that spatial concentration of poverty is associated with numerous contextual processes including services, stigma, and the built environment including walkability, food, and social environment. We therefore might hypothesize that higher poverty is associated with higher prevalence of poor health. Because of the spatial patterning of poverty and its relation to investment in built environment and services, we might also hypothesize this variable could also have a spatial spillover effect on mental health prevalence.</li>
<li><code>InstabilityStress</code> captures the degree to which housing instability (e.g. vacancy and foreclosures) occur in a neighborhood. Increased housing instability could be directly stressful for individuals, but could also produce indirect anxiety and depression in residents in the area.</li>
<li><code>ParkProximity_Std</code> represents relative access to green space and parks. Evidence is mixed as to whether proximity to green space is causally related to mental health, but we might hypothesize that if a relationship exists, it is protective. We also might hypothesize that this is a predictor that could have ‘spatial spillover’</li>
<li><code>PHYSHLTH</code> captures the prevalence of poor physical health and is plausibly a direct cause of poor mental health. We might include this as a possible confounder of the effect.</li>
</ul>
<p>This question is of public health relevance to the extent that spatial concentration of poverty, housing policy, and urban design decisions are reproduced through transportation, zoning, development, and housing policies (which themselves are theoretically quite modifiable), and the identification of place-based determinants of health can imply place-based targeted intervention including mental health screening and mental health services.</p>
</div>
<div id="the-more-realistically-answered-overarching-question" class="section level4" number="12.3.2.2">
<h4><span class="header-section-number">12.3.2.2</span> The (more) realistically answered overarching question</h4>
<p>Generally, we cannot answer such an idealized overarching question with a single study design or modality. Given the use of the BRFSS 500-cities project, our <em>more realistic overarching question</em> might be whether the ecologic census-tract prevalence of self-reported poor mental health is associated with poverty rates in a sub-region of the Atlanta metropolitan region, conditional on ecologically-measured confounders. This more realistic question differs from the idealized version in its de-emphasis on recovering causal effect estimates, acknowledgment of ecologic (and in this case cross-sectional) measurement of exposure, outcome, and covariates, and restriction to a possibly unique sub-section of the metropolitan region.</p>
</div>
<div id="specific-questions" class="section level4" number="12.3.2.3">
<h4><span class="header-section-number">12.3.2.3</span> Specific questions</h4>
<p>Within this framework, we can generate several specific questions for which we anticipate specific answers. This distinction between the <em>overarching question</em> (which may have discrete quantitative answers, or often has qualitative answers), and <em>specific questions</em> is important. The former clearly frames and motivates the latter, but without the latter (specific questions) you may get lost in the sea of statistical results without clarity on what you can and want to know.</p>
<p>Below are just <em>some</em> possible questions that we can answer with these data. I divide them (perhaps too simplistically) into <em>statistical</em> and <em>epidemiologic</em> questions simply to highlight the different emphasis of each field. In reality there is clearly overlap in statistical and epidemiologic questions!</p>
</div>
<div id="statistical-questions" class="section level4" number="12.3.2.4">
<h4><span class="header-section-number">12.3.2.4</span> Statistical questions</h4>
<ol style="list-style-type: decimal">
<li>Which data generating process (spatial error, lagged outcome, or lagged outcome and covariates) best fits the data?</li>
<li>Is there residual auto correlation above and beyond that explained by spatial auto regression terms?</li>
<li>Which spatial weights matrix best fits the data?</li>
</ol>
</div>
<div id="epidemiologic-questions" class="section level4" number="12.3.2.5">
<h4><span class="header-section-number">12.3.2.5</span> Epidemiologic questions</h4>
<ol style="list-style-type: decimal">
<li>Is tract-level poverty or housing instability associated with poor mental health, adjusting for candidate causal confounders detailed above?</li>
<li>Is there evidence of confounding of the target relationships by the candidate confounders using a change-in-estimates approach?</li>
<li>Assuming census tracts are a reasonable definition of local neighborhoods, is spatial clustering of poor mental health primarily a function of missing variables or of spatial contagion or spillover processes?</li>
<li>Does the association (if any) of poverty or housing instability with poor mental health primarily defined by <em>local effects</em> (e.g. within-neighborhood) or does poverty or housing instability in one place affect mental health in neighboring places?</li>
<li>If there are spillover effects of contextual covariates, how important are the <em>direct</em> as compared with <em>indirect</em> effects?</li>
<li>Do the spatial relationships between contextual covariates and poor mental health depend on (vary by) the definition of <em>local</em> and the inter-connectedness of places?</li>
</ol>
</div>
</div>
<div id="defining-competing-definitions-of-local" class="section level3" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Defining competing definitions of <em>local</em></h3>
<p>We have emphasized at several points throughout the semester that one fundamentally important decision in spatial analysis is the specification of the <em>spatial weights matrix</em> which is the mathematical encoding of our belief about spatial relationships between study units of observation. The spatial neighbors are those geographic units believed to share experience or interact with one another, and are differentiated from units unlikely to do so. Whether regional units (or really the inhabitants of those regions) <em>interact</em> depends on the question at hand. For instance the experience of <em>sharing</em> access to a primary health care center likely occurs at relatively small scale (small set of neighborhoods primarily depend on that clinic). In contrast, when looking at access to liver transplantation services, the scope of <em>local</em> is quite different, with a much geographically more far-flung range of places willing to access that health resource.</p>
<p>In our question, the notion of the <em>spatial concentration of poverty and housing instability</em> is core. We could estimate these variables at the scale of a household, or the building, or the census tract, or conglomerations of census tracts, and so forth. Poverty concentrated at larger areas likely looks different in terms of the social and environmental context than micro-pockets of poverty, and therefore may have different impacts on mental health. So what is a reasonable definition of how much census tracts <em>share</em> or <em>interact</em> or <em>spread</em> the experience of poverty and mental health?</p>
</div>
<div id="two-extremes" class="section level3" number="12.3.4">
<h3><span class="header-section-number">12.3.4</span> Two extremes</h3>
<p>The Queen contiguity definition of neighbors probably represents the lower bound of connectedness possible with a given set of geographic boundaries (e.g. we can’t estimate apartment building values because we only have census tracts). But might interactions occur beyond the bounds of the contiguous census tracts? Perhaps. Might interactions be as likely to occur 10 miles away as 1 mile away? Unlikely (but not impossible). <em>K-nearest neighbors</em> is a definition that lets us flexibly scale up the size of the spatial connection network.</p>
<p>As a quick review, let’s create several competing spatial weights matrices under competing definitions of spatial neighbors. As mentioned above, the package we will use for spatial regression (<code>spatialreg</code>) has several conflicts with the package containing functions for creating neighbors (<code>spdep</code>). For that reason we did not load the package <code>spdep</code> above, but instead call it explicitly here using the double-colon notation below.</p>
<p>Queen contiguity weights:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="spatial-regression-iii.html#cb323-1"></a><span class="co"># Create a Queen Contiguity weights objects</span></span>
<span id="cb323-2"><a href="spatial-regression-iii.html#cb323-2"></a>queen &lt;-<span class="st"> </span>atl <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># start with sf object</span></span>
<span id="cb323-3"><a href="spatial-regression-iii.html#cb323-3"></a><span class="st">  </span>spdep<span class="op">::</span><span class="kw">poly2nb</span>() <span class="op">%&gt;%</span><span class="st">      </span><span class="co"># convert polygons to neighbor object</span></span>
<span id="cb323-4"><a href="spatial-regression-iii.html#cb323-4"></a><span class="st">  </span>spdep<span class="op">::</span><span class="kw">nb2listw</span>()         <span class="co"># convert nb object to spatial weights</span></span>
<span id="cb323-5"><a href="spatial-regression-iii.html#cb323-5"></a></span>
<span id="cb323-6"><a href="spatial-regression-iii.html#cb323-6"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: nb2listw() creates row-standardized weighted by default</span></span>
<span id="cb323-7"><a href="spatial-regression-iii.html#cb323-7"></a><span class="co"># That is what we want for spatial regression</span></span></code></pre></div>
<p>As a somewhat extreme alternative, here I create a <em>k-nearest neighbor</em> spatial weights assuming that interaction occurs between each tract and their <strong>25 nearest neighbors</strong>!</p>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="spatial-regression-iii.html#cb324-1"></a><span class="co"># Create a 15 tract k-nearest neighbor weights object</span></span>
<span id="cb324-2"><a href="spatial-regression-iii.html#cb324-2"></a>knn15 &lt;-<span class="st"> </span>atl <span class="op">%&gt;%</span><span class="st">               </span><span class="co"># start with sf object</span></span>
<span id="cb324-3"><a href="spatial-regression-iii.html#cb324-3"></a><span class="st">  </span><span class="kw">st_centroid</span>() <span class="op">%&gt;%</span><span class="st">            </span><span class="co"># get the centroid of each tract</span></span>
<span id="cb324-4"><a href="spatial-regression-iii.html#cb324-4"></a><span class="st">  </span><span class="kw">st_coordinates</span>() <span class="op">%&gt;%</span><span class="st">         </span><span class="co"># create matrix of x,y coordinates for that centroid</span></span>
<span id="cb324-5"><a href="spatial-regression-iii.html#cb324-5"></a><span class="st">  </span>spdep<span class="op">::</span><span class="kw">knearneigh</span>(<span class="dt">k=</span><span class="dv">15</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># use spdep to find 15 nearest neighbors</span></span>
<span id="cb324-6"><a href="spatial-regression-iii.html#cb324-6"></a><span class="st">  </span>spdep<span class="op">::</span><span class="kw">knn2nb</span>() <span class="op">%&gt;%</span><span class="st">          </span><span class="co"># convert that into a formal nb object</span></span>
<span id="cb324-7"><a href="spatial-regression-iii.html#cb324-7"></a><span class="st">  </span>spdep<span class="op">::</span><span class="kw">nb2listw</span>()            <span class="co"># and finally convert the nb into a spatial weights object</span></span></code></pre></div>
<p>Now, let’s plot the two versions to visualize the range of connectivity being hypothesized:</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="spatial-regression-iii.html#cb325-1"></a><span class="co"># Create centroids object</span></span>
<span id="cb325-2"><a href="spatial-regression-iii.html#cb325-2"></a>atl.cent &lt;-<span class="st"> </span><span class="kw">st_centroid</span>(<span class="kw">st_geometry</span>(atl))</span>
<span id="cb325-3"><a href="spatial-regression-iii.html#cb325-3"></a></span>
<span id="cb325-4"><a href="spatial-regression-iii.html#cb325-4"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb325-5"><a href="spatial-regression-iii.html#cb325-5"></a><span class="kw">plot</span>(<span class="kw">st_geometry</span>(atl), <span class="dt">main =</span> <span class="st">&#39;Queen&#39;</span>, <span class="dt">border =</span> <span class="st">&#39;grey&#39;</span>)</span>
<span id="cb325-6"><a href="spatial-regression-iii.html#cb325-6"></a><span class="kw">plot</span>(queen, <span class="dt">coords =</span> atl.cent, <span class="dt">add =</span> T)</span>
<span id="cb325-7"><a href="spatial-regression-iii.html#cb325-7"></a><span class="kw">plot</span>(<span class="kw">st_geometry</span>(atl), <span class="dt">main =</span> <span class="st">&#39;KNN 15&#39;</span>, <span class="dt">border =</span> <span class="st">&#39;grey&#39;</span>)</span>
<span id="cb325-8"><a href="spatial-regression-iii.html#cb325-8"></a><span class="kw">plot</span>(knn15, <span class="dt">coords =</span> atl.cent, <span class="dt">add =</span> T)</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-322-1.png" width="672" /></p>
<p>Clearly the <em>k-nearest neighbors</em> provides a denser connectivity matrix with more neighbors than does the Queen contiguity.</p>
</div>
<div id="fitting-multivariable-regression-models" class="section level3" number="12.3.5">
<h3><span class="header-section-number">12.3.5</span> Fitting multivariable regression models</h3>
<div id="spatial-or-aspatial" class="section level4" number="12.3.5.1">
<h4><span class="header-section-number">12.3.5.1</span> Spatial or aspatial?</h4>
<p>Because this is a different model from previous weeks, we should not assume that the aspatial model is necessarily a poor choice. Fitting and summarizing the results – including assessment of spatial auto correlation of residuals– should always be a starting point before moving on to spatial econometric regression.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="spatial-regression-iii.html#cb326-1"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(MENTALHLTH <span class="op">~</span><span class="st"> </span>Poverty_std <span class="op">+</span><span class="st"> </span>InstabilityStress <span class="op">+</span><span class="st"> </span>ParkProximity_std  <span class="op">+</span><span class="st"> </span>PHYSHLTH,</span>
<span id="cb326-2"><a href="spatial-regression-iii.html#cb326-2"></a>         <span class="dt">data =</span> atl)</span>
<span id="cb326-3"><a href="spatial-regression-iii.html#cb326-3"></a><span class="kw">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = MENTALHLTH ~ Poverty_std + InstabilityStress + ParkProximity_std + 
##     PHYSHLTH, data = atl)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7934 -0.7675 -0.1878  0.6420  3.9312 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        5.57191    0.33031  16.869   &lt;2e-16 ***
## Poverty_std        1.12808    0.10492  10.752   &lt;2e-16 ***
## InstabilityStress -0.05725    0.05310  -1.078   0.2824    
## ParkProximity_std  0.53791    0.25446   2.114   0.0359 *  
## PHYSHLTH           0.46897    0.02883  16.269   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.198 on 180 degrees of freedom
## Multiple R-squared:  0.9004,	Adjusted R-squared:  0.8982 
## F-statistic: 406.8 on 4 and 180 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Review the results above and take note of the magnitude and direction of associations. Remember our primary question focuses on poverty and housing instability. Also note the model fit as indicated by the <span class="math inline">\(R^2=0.9\)</span>. That is extremely high and may suggest over fitting. This could be related to the way in which the BRFSS 500-cities small area data are created: it is a small area modeling process in its own right, and the included variables may <em>overly explain</em> one another when jointly considered. <em>We will ignore that fact for the purposes of this exercise, but I point it out to suggest some caution with such optimistic looking fit statistics!</em></p>
<p>To diagnose spatial auto correlation in the model residuals we repeat procedures from two weeks ago. I try the procedure for both the Queen contiguity weights and the 25-nearest neighbors. You can extend this to other intermediate specifications.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="spatial-regression-iii.html#cb328-1"></a>spdep<span class="op">::</span><span class="kw">lm.morantest</span>(m1, <span class="dt">listw =</span> queen)</span>
<span id="cb328-2"><a href="spatial-regression-iii.html#cb328-2"></a>spdep<span class="op">::</span><span class="kw">lm.morantest</span>(m1, <span class="dt">listw =</span> knn15)</span></code></pre></div>
<p>It appears that the model parameters do a reasonably good job of removing the spatial auto correlation, but there is still a significant positive Moran’s I under each spatial weights definition, warranting transition to spatial regression.</p>
</div>
</div>
<div id="spatial-error-model-1" class="section level3" number="12.3.6">
<h3><span class="header-section-number">12.3.6</span> Spatial Error Model</h3>
<p>The Spatial Error Model (SEM) posits that the measured covariates relate to (act on) the outcome within each region independently (e.g. they <strong>don’t</strong> spillover or act across boundaries). However, the model allows that <em>something unmeasured</em> (and within the county) predicts the outcome and is itself spatially patterned (not spatially random). The result is that the spatial auto correlation is a nuisance dependency arising from that missing covariate. By <em>modeling the error</em> (e.g. by specifying and/or estimating the form of the dependency as part of the model fitting process), we can achieve two objectives: <strong>i)</strong> quantify estimates of the residual dependency in the form of the correlation coefficient <span class="math inline">\(\lambda\)</span> (lambda); and <strong>ii)</strong> estimate regression coefficients for the <em>measured</em> covariates that are no longer biased by the spatial dependence.</p>
<p>Remember, the assumed data generating process under the Spatial Error Model is as follows:</p>
<p><span class="math display">\[Y_i=\beta X_i+u_i\]</span></p>
<p><span class="math display">\[u_i=\lambda Wu_{-i}+e_i\]</span></p>
<p>Where <span class="math inline">\(Y\)</span> is the vector of outcomes (prevalence of poor mental health in our case for the <span class="math inline">\(i^{th}\)</span> census tract); <span class="math inline">\(X\)</span> is a matrix of covariates (e.g. n = 185 census tracts x k = 1 intercept + 4 predictors); <span class="math inline">\(\beta\)</span> is a vector of coefficients, with <span class="math inline">\(\beta_0\)</span> being the intercept; and <span class="math inline">\(u\)</span> is the error term.</p>
<p>In the SEM, the error term, <span class="math inline">\(u\)</span>, is composed of two components: the one is the spatially independent portion, <span class="math inline">\(e_i\)</span>; and the other part is the spatially auto correlated portion induced by the spatially patterned missing variable(s). It is expressed as the strength of the correlation, <span class="math inline">\(\lambda\)</span> with the spatially-lagged measures of <span class="math inline">\(u\)</span> as indicated through the spatial weights matrix <span class="math inline">\(Wu\)</span>.</p>
<div id="fitting-the-spatial-error-model" class="section level4" number="12.3.6.1">
<h4><span class="header-section-number">12.3.6.1</span> Fitting the Spatial Error Model</h4>
<p>Here is code for fitting the SEM model using the Queen contiguity weights. You can re-fit the model with alternative spatial weights matrices. The function, <code>errorsarlm()</code> stands for <em>spatial autoregressive (SAR) linear model</em>, and it requires a formula defining the model, the dataset, and then the definition of the spatial neighbors object.</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="spatial-regression-iii.html#cb329-1"></a>sem &lt;-<span class="st"> </span><span class="kw">errorsarlm</span>(MENTALHLTH <span class="op">~</span><span class="st"> </span>Poverty_std <span class="op">+</span><span class="st"> </span>InstabilityStress <span class="op">+</span><span class="st"> </span>ParkProximity_std  <span class="op">+</span><span class="st"> </span>PHYSHLTH,</span>
<span id="cb329-2"><a href="spatial-regression-iii.html#cb329-2"></a>                  <span class="dt">data =</span> atl,</span>
<span id="cb329-3"><a href="spatial-regression-iii.html#cb329-3"></a>                  <span class="dt">listw =</span> queen)</span>
<span id="cb329-4"><a href="spatial-regression-iii.html#cb329-4"></a></span>
<span id="cb329-5"><a href="spatial-regression-iii.html#cb329-5"></a><span class="kw">summary</span>(sem)</span></code></pre></div>
<pre><code>## 
## Call:errorsarlm(formula = MENTALHLTH ~ Poverty_std + InstabilityStress + 
##     ParkProximity_std + PHYSHLTH, data = atl, listw = queen)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.72726 -0.76110 -0.12242  0.69509  4.21695 
## 
## Type: error 
## Coefficients: (asymptotic standard errors) 
##                    Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)        5.315774   0.386667 13.7477   &lt;2e-16
## Poverty_std        0.970541   0.106880  9.0807   &lt;2e-16
## InstabilityStress -0.026098   0.055274 -0.4722   0.6368
## ParkProximity_std  0.429410   0.273470  1.5702   0.1164
## PHYSHLTH           0.499118   0.033517 14.8913   &lt;2e-16
## 
## Lambda: 0.41473, LR test value: 13.904, p-value: 0.00019236
## Asymptotic standard error: 0.093931
##     z-value: 4.4152, p-value: 1.0092e-05
## Wald statistic: 19.494, p-value: 1.0092e-05
## 
## Log likelihood: -286.4547 for error model
## ML residual variance (sigma squared): 1.2512, (sigma: 1.1186)
## Number of observations: 185 
## Number of parameters estimated: 7 
## AIC: 586.91, (AIC for lm: 598.81)</code></pre>
</div>
<div id="interpreting-sem-output" class="section level4" number="12.3.6.2">
<h4><span class="header-section-number">12.3.6.2</span> Interpreting SEM output</h4>
<p>There are several bits of information one can glean from the output. Here is a summary of some of the points:</p>
<ol style="list-style-type: decimal">
<li>The regression coefficients suggest that <code>Poverty_std</code> and <code>PHYSHLTH</code> are significantly and positively associated with prevalence of poor mental health. <code>ParkProximity_std</code> has a relatively large magnitude of association but is not statistically significant, and <code>InstabilityStress</code> is not associated.</li>
<li>To interpret, the coefficient <code>Poverty_std</code> is significantly positively associated with the outcome. For each 1-standard deviation increase in tract poverty rate, there is a 1% increase in prevalence of poor mental health.</li>
<li>There is moderately strong (and statistically significant) spatial auto correlation in the errors, as evidenced by an estimated <span class="math inline">\(\lambda=0.41, p &lt; 0.001\)</span>.</li>
<li>The log-Likelihood and AIC are reported, and the comparison of the AIC from the Spatial Error Model (<span class="math inline">\(AIC=587\)</span>) as compared to the aspatial linear model (<span class="math inline">\(AIC=599\)</span>) suggest better fit for the SEM (e.g. <em>smaller</em> AIC is better fit).</li>
</ol>
</div>
</div>
<div id="hausman-test-of-coefficients" class="section level3" number="12.3.7">
<h3><span class="header-section-number">12.3.7</span> Hausman test of coefficients</h3>
<p>One statistical test specific to the use of the Spatial Error Model is the <em>Hausman Test</em>. Recall that one concern with naively using aspatial regression in the presence of underlying spatial auto correlation is that the regression coefficients from the aspatial regression may be biased. The <em>Hausman Test</em> is a test of the consistency of the regression coefficients in a Spatial Error Model compared to the aspatial version. <strong>It does not test for spatial autocorrelation; instead it tests for whether the coefficients are consistent</strong>.</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="spatial-regression-iii.html#cb331-1"></a><span class="kw">Hausman.test</span>(sem)</span></code></pre></div>
<pre><code>## 
## 	Spatial Hausman test (asymptotic)
## 
## data:  NULL
## Hausman test = 14.781, df = 5, p-value = 0.01134</code></pre>
<p>The significant test suggests that the regression coefficients from the SEM are likely inconsistent with the coefficients from the aspatial model; in other words there <em>is evidence</em> that the aspatial model coefficients are biased as compared to the spatial error model.</p>
</div>
<div id="spatial-lag-model" class="section level3" number="12.3.8">
<h3><span class="header-section-number">12.3.8</span> Spatial Lag Model</h3>
<p>The spatial lag model shifts the source of spatial auto correlation from the error term to the mean portion of the model. In particular, the Spatial Lag Model posits that a reason for spatial auto correlation is the dependency between the <em>outcome</em> in one region and the average outcome in all of the <em>neighboring</em> regions. This dependency implies some form of <em>spread</em> of the outcome, as would be expected in infectious or contagious processes (my influenza affects your risk of influenza), but could be imagined in terms of social contagion (e.g. if smoking were a behavioral outcome and my smoking affects your sense of normalcy around smoking).</p>
<p>However it is not clear whether a spatially-lagged prevalence of poor mental health should be contagious. Perhaps being in a place where everyone is depressed affects your own depression? While this statistical estimation cannot guarantee that <em>contagion</em> is at play in the real world, the notion of <em>spatially-lagged outcomes</em> is interesting and compelling from epidemiologic and public health perspective, as it suggests something about the spread or diffusion of the outcome, and may imply intervention is needed not only to change environmental risk factors, but to break the propagation from one person (or unit) to another.</p>
<p>Remember, the data generating process for the SLM is as follows:</p>
<p><span class="math inline">\(Y_i=\rho WY_{-i}+\beta X_i+e_i\)</span></p>
<p>where <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\beta\)</span> are the same as in the SEM above, and <span class="math inline">\(e_i\)</span> is a spatially-<em>independent</em> residual error term. The new coefficient in this model is <span class="math inline">\(\rho\)</span>, which is the correlation coefficient estimating the degree to which the mean outcomes of one’s neighbors (as captured spatially via the spatial weights matrix as <span class="math inline">\(WY_{-i}\)</span>) is itself a predictor of the local outcome. Assuming the spatial weights matrix, <span class="math inline">\(W\)</span> is row-standardized, then <span class="math inline">\(-1&lt;\rho&lt;+1\)</span> with <span class="math inline">\(\rho=0\)</span> meaning no spatial auto correlation between outcomes.</p>
<p>The function <code>lagsarlm()</code> in the package <code>spatialreg</code> fits both the Spatial Lag Model as well as the Spatial Durbin Model (below). The use of <code>Durbin = FALSE</code> distinguishes the SLM, which only has spatially-lagged outcomes, but not covariates.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="spatial-regression-iii.html#cb333-1"></a>slm &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(MENTALHLTH <span class="op">~</span><span class="st"> </span>Poverty_std <span class="op">+</span><span class="st"> </span>InstabilityStress <span class="op">+</span><span class="st"> </span>ParkProximity_std  <span class="op">+</span><span class="st"> </span>PHYSHLTH,</span>
<span id="cb333-2"><a href="spatial-regression-iii.html#cb333-2"></a>                <span class="dt">data =</span> atl,</span>
<span id="cb333-3"><a href="spatial-regression-iii.html#cb333-3"></a>                <span class="dt">listw =</span> queen,</span>
<span id="cb333-4"><a href="spatial-regression-iii.html#cb333-4"></a>                <span class="dt">Durbin =</span> F)</span>
<span id="cb333-5"><a href="spatial-regression-iii.html#cb333-5"></a></span>
<span id="cb333-6"><a href="spatial-regression-iii.html#cb333-6"></a><span class="kw">summary</span>(slm)</span></code></pre></div>
<pre><code>## 
## Call:lagsarlm(formula = MENTALHLTH ~ Poverty_std + InstabilityStress + 
##     ParkProximity_std + PHYSHLTH, data = atl, listw = queen,     Durbin = F)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.95397 -0.77812 -0.14108  0.68593  3.41057 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##                    Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)        4.595551   0.507521  9.0549  &lt; 2e-16
## Poverty_std        1.056327   0.103725 10.1839  &lt; 2e-16
## InstabilityStress -0.102273   0.055872 -1.8305  0.06718
## ParkProximity_std  0.430945   0.249558  1.7268  0.08420
## PHYSHLTH           0.419326   0.036375 11.5280  &lt; 2e-16
## 
## Rho: 0.14362, LR test value: 5.6967, p-value: 0.016996
## Asymptotic standard error: 0.060921
##     z-value: 2.3574, p-value: 0.018403
## Wald statistic: 5.5574, p-value: 0.018403
## 
## Log likelihood: -290.5585 for lag model
## ML residual variance (sigma squared): 1.3492, (sigma: 1.1616)
## Number of observations: 185 
## Number of parameters estimated: 7 
## AIC: 595.12, (AIC for lm: 598.81)
## LM test for residual autocorrelation
## test value: 6.9746, p-value: 0.0082677</code></pre>
<div id="interpreting-slm-output" class="section level4" number="12.3.8.1">
<h4><span class="header-section-number">12.3.8.1</span> Interpreting SLM Output</h4>
<p>There are some similarities and some differences in the output of the spatial lag as compared with spatial error models:</p>
<ol style="list-style-type: decimal">
<li>The regression coefficients do not appear substantially different in magnitude or sign from the SEM, with the possible exception of housing instability which appears to have a larger coefficient and smaller (albeit still non-significant) p-value.</li>
<li>Instead of the <span class="math inline">\(\lambda\)</span> coefficient, this model now reports the spatial lag term, <span class="math inline">\(\rho=0.14, p = 0.017\)</span>. This suggests that there is close only modest spatial dependence in the outcome (small, statistically significant <span class="math inline">\(\rho\)</span>).</li>
<li>The AIC for the SLM is smaller than the AIC for the aspatial linear model, suggesting some improvement in fit by including the spatial auto correlation.</li>
<li>There is significant, residual spatial auto correlation in the errors (e.g. <span class="math inline">\(p=0.008\)</span>), conditional on the covariates in the model and the spatially-lagged <span class="math inline">\(\rho\)</span> coefficient.</li>
</ol>
</div>
<div id="model-fit-statistics" class="section level4" number="12.3.8.2">
<h4><span class="header-section-number">12.3.8.2</span> Model fit statistics</h4>
<p>We can use Likelihood Ratio Tests to compare the fit of pairs of models. Here we can formally test two questions:</p>
<ol style="list-style-type: decimal">
<li>Does the spatial lag model fit better than the aspatial regression model?</li>
</ol>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="spatial-regression-iii.html#cb335-1"></a><span class="kw">LR.sarlm</span>(m1, slm)</span></code></pre></div>
<pre><code>## 
## 	Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = -5.6967, df = 1, p-value = 0.017
## sample estimates:
##  Log likelihood of m1 Log likelihood of slm 
##             -293.4069             -290.5585</code></pre>
<p><strong>ANSWER</strong>: Yes. (p-value for difference in fit = 0.017)</p>
<ol start="2" style="list-style-type: decimal">
<li>Does the spatial lag model fit better than the spatial error model?</li>
</ol>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="spatial-regression-iii.html#cb337-1"></a><span class="co"># instead we can compare AIC for each model</span></span>
<span id="cb337-2"><a href="spatial-regression-iii.html#cb337-2"></a><span class="kw">AIC</span>(sem, slm)</span></code></pre></div>
<p><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-329">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-329">TABLE 12.2: </span> </caption><col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">df</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">AIC</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">7</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">587</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">7</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">595</td></tr>
</table>

<strong>ANSWER</strong>: The <em>spatial error model</em> appears to have a slightly smaller AIC than the <em>spatial lag model</em> suggesting it (the spatial error model) fits better.</p>
</div>
</div>
<div id="spatial-durbin-model-1" class="section level3" number="12.3.9">
<h3><span class="header-section-number">12.3.9</span> Spatial Durbin Model</h3>
<p>The Spatial Durbin Model extends the Spatial Lag Model by allowing not only the <em>outcome</em>, but also the <em>covariates</em> to <em>spillover</em> from one region to the next. While the notion of spatial lag suggests <em>contagion</em> because it is about <em>outcomes</em> causing <em>outcomes</em>, the spillover effect of covariates is more broadly applicable. The implication of external effects of covariates is simply that their impact is felt beyond the (possibly arbitrary) boundaries of geographic regions. This could occur from environmental drift (e.g. via air or water), or through spatial mobility of individual from their home location to nearby locations.</p>
<p>Remember, the mathematical form of this data generating process extends the SLM by adding spatially-lagged <span class="math inline">\(X\)</span> as well as <span class="math inline">\(Y\)</span> variables:</p>
<p><span class="math display">\[Y_i=\rho WY_{-i}+\beta X_i + \gamma WX_{-i} + e_i\]</span></p>
<p>where <span class="math inline">\(\beta X_i\)</span> models the within-region effects of covariate <span class="math inline">\(X\)</span>, and <span class="math inline">\(\gamma WX_{-i}\)</span> models the spillover or spatially-lagged effects of <span class="math inline">\(X_{-i}\)</span> (e.g. spatially lagged average of the <span class="math inline">\(X\)</span> values that are <em>not in region <span class="math inline">\(i\)</span></em>) on the spatial neighbors indicated by <span class="math inline">\(W\)</span>.</p>
<div id="fitting-the-spatial-durbin-model" class="section level4" number="12.3.9.1">
<h4><span class="header-section-number">12.3.9.1</span> Fitting the Spatial Durbin Model</h4>
<p>The code for fitting the Spatial Durbin Model only differs from the SLM code by changing the model to <code>Durbin = TRUE</code>.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="spatial-regression-iii.html#cb338-1"></a>sdm &lt;-<span class="st"> </span><span class="kw">lagsarlm</span>(MENTALHLTH <span class="op">~</span><span class="st"> </span>Poverty_std <span class="op">+</span><span class="st"> </span>InstabilityStress <span class="op">+</span><span class="st"> </span>ParkProximity_std  <span class="op">+</span><span class="st"> </span>PHYSHLTH,</span>
<span id="cb338-2"><a href="spatial-regression-iii.html#cb338-2"></a>                <span class="dt">data =</span> atl,</span>
<span id="cb338-3"><a href="spatial-regression-iii.html#cb338-3"></a>                <span class="dt">listw =</span> queen,</span>
<span id="cb338-4"><a href="spatial-regression-iii.html#cb338-4"></a>                <span class="dt">Durbin =</span> T)</span>
<span id="cb338-5"><a href="spatial-regression-iii.html#cb338-5"></a></span>
<span id="cb338-6"><a href="spatial-regression-iii.html#cb338-6"></a><span class="kw">summary</span>(sdm)</span></code></pre></div>
<pre><code>## 
## Call:lagsarlm(formula = MENTALHLTH ~ Poverty_std + InstabilityStress + 
##     ParkProximity_std + PHYSHLTH, data = atl, listw = queen,     Durbin = T)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -3.065250 -0.702557 -0.077417  0.528628  4.017753 
## 
## Type: mixed 
## Coefficients: (asymptotic standard errors) 
##                        Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)            4.369455   0.787175  5.5508 2.844e-08
## Poverty_std            0.909306   0.113223  8.0311 8.882e-16
## InstabilityStress     -0.023942   0.063633 -0.3763   0.70673
## ParkProximity_std      0.275745   0.310209  0.8889   0.37406
## PHYSHLTH               0.542647   0.043181 12.5667 &lt; 2.2e-16
## lag.Poverty_std        0.430300   0.262114  1.6417   0.10066
## lag.InstabilityStress -0.227807   0.117749 -1.9347   0.05303
## lag.ParkProximity_std -0.096726   0.563610 -0.1716   0.86374
## lag.PHYSHLTH          -0.294494   0.071865 -4.0979 4.169e-05
## 
## Rho: 0.34143, LR test value: 10.337, p-value: 0.0013041
## Asymptotic standard error: 0.098766
##     z-value: 3.457, p-value: 0.00054623
## Wald statistic: 11.951, p-value: 0.00054623
## 
## Log likelihood: -280.3087 for mixed model
## ML residual variance (sigma squared): 1.1849, (sigma: 1.0885)
## Number of observations: 185 
## Number of parameters estimated: 11 
## AIC: 582.62, (AIC for lm: 590.95)
## LM test for residual autocorrelation
## test value: 0.19933, p-value: 0.65526</code></pre>
</div>
<div id="interpreting-sdm-output" class="section level4" number="12.3.9.2">
<h4><span class="header-section-number">12.3.9.2</span> Interpreting SDM output</h4>
<p>Again, there are similarities and differences in the output.</p>
<ol style="list-style-type: decimal">
<li>The coefficient table includes the same <em>within-region</em> effects as before; these are the <span class="math inline">\(\beta X_i\)</span> values from the data generating process above.</li>
<li>The coefficient table now also includes the spatially-lagged versions of each covariate, representing the <span class="math inline">\(\gamma WX_{-i}\)</span>. These are the associations between spatially lagged and averaged <em>neighboring units</em> <span class="math inline">\(X\)</span> covariates on own-unit outcomes. In the results above these are indicated by the prefix <code>lag.xxx</code>.</li>
<li>The same <span class="math inline">\(\rho\)</span> coefficient is estimated in this model, but now the value is <span class="math inline">\(\rho = 0.34, p=0.001\)</span>, suggesting that, conditional on the spatially-lagged covariates, there is now stronger correlation between outcomes in neighboring regions and own-region outcomes.</li>
<li>The AIC of 583 for the SDM is smaller than the AIC of 591 for the aspatial regression (and also smaller than the SLM and SEM models)</li>
<li>There is no significant residual auto correlation (e.g. <span class="math inline">\(p=0.65\)</span>)</li>
</ol>
<p>In more qualitative terms, here are two example interpretations:</p>
<ul>
<li>Poverty has both a direct and a spillover effect, in each case associated with higher prevalence of poor mental health</li>
<li>Prevalence of poor physical health is positively correlated with poor mental health <em>within the census tract</em>, but that is somewhat offset by an inverse association between neighboring tracts prevalence of poor physical health.</li>
</ul>
</div>
<div id="model-fit-statistics-1" class="section level4" number="12.3.9.3">
<h4><span class="header-section-number">12.3.9.3</span> Model fit statistics</h4>
<p>Once again, we can check Likelihood Ratio Tests to assess model fit.</p>
<ol style="list-style-type: decimal">
<li>Does the Durbin model fit better than aspatial regression?</li>
</ol>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="spatial-regression-iii.html#cb340-1"></a><span class="kw">LR.sarlm</span>(m1,sdm)</span></code></pre></div>
<pre><code>## 
## 	Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = -26.196, df = 5, p-value = 8.174e-05
## sample estimates:
##  Log likelihood of m1 Log likelihood of sdm 
##             -293.4069             -280.3087</code></pre>
<p><strong>ANSWER</strong>: Yes. The spatial Durbin model fits better.</p>
<ol start="2" style="list-style-type: decimal">
<li>Does the Durbin model fit better than the SEM?</li>
</ol>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="spatial-regression-iii.html#cb342-1"></a><span class="kw">LR.sarlm</span>(sdm, sem)</span></code></pre></div>
<pre><code>## 
## 	Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = 12.292, df = 4, p-value = 0.01531
## sample estimates:
## Log likelihood of sdm Log likelihood of sem 
##             -280.3087             -286.4547</code></pre>
<p><strong>ANSWER</strong>: Yes. The Spatial Durbin model fits at least somewhat better than the SEM.</p>
<ol start="3" style="list-style-type: decimal">
<li>Does the Durbin model fit better than the SLM?</li>
</ol>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="spatial-regression-iii.html#cb344-1"></a><span class="kw">LR.sarlm</span>(sdm, slm)</span></code></pre></div>
<pre><code>## 
## 	Likelihood ratio for spatial linear models
## 
## data:  
## Likelihood ratio = 20.5, df = 4, p-value = 0.0003978
## sample estimates:
## Log likelihood of sdm Log likelihood of slm 
##             -280.3087             -290.5585</code></pre>
<p><strong>ANSWER</strong>: Yes. The spatial Durbin model appears to fit best of all of the models.</p>

<div class="rmdwarning">
NOTE: In this particular case the Spatial Durbin model appears to be the best fitting. This fact, combined with the fact that we anticipate that a Durbin model provides the best opportunity to return statistically unbiased coefficient estimates is meaningful. However, note this is only a function of the particular variables. In alternate model specifications of these same data, the Durbin model <em>does not fit best</em>. Do not assume that Durbin is always the best fitting model.
</div>
</div>
</div>
<div id="comparing-models" class="section level3" number="12.3.10">
<h3><span class="header-section-number">12.3.10</span> Comparing Models</h3>
<p>There are many things to hold in mind at once when comparing models:</p>
<ol style="list-style-type: decimal">
<li>If one model better represents the question of interest or the process in play, that is noteworthy. For example, many epidemiologists argue for selecting covariates based on plausible role as contributing to bias from confounding (e.g. as determined from prior knowledge, DAG), rather than by using model fit statistics.</li>
<li>If the underlying data generating process is not clear, the best chance for unbiased estimates of the regression coefficients comes from the Spatial Durbin Model.</li>
<li>The model fit statistics provide information about how well different specifications of the data generating process fit the observed data. These fit statistics may be all you have to go on, and are important sources of information. However, you should note that fit statistics are specific the inputs provided, including the specification of model covariates, and the choice of spatial weights. Thus, a single comparison of fit statistics does not necessarily settle the issue.</li>
</ol>
</div>
<div id="impact-assessments" class="section level3" number="12.3.11">
<h3><span class="header-section-number">12.3.11</span> Impact Assessments</h3>
<p>In the setting in which either the Spatial Lag Model or the Spatial Durbin Model were of interest, it is important to note that the coefficients cannot be interpreted in the conventional manner to which we are accustomed in regression. The reason is that the presence of <em>spatial spillover</em> represented by either the <span class="math inline">\(\rho\)</span> coefficient for spillover of the outcome, or the <span class="math inline">\(\gamma\)</span> coefficients for spillover of the covariates, means that any change in an <span class="math inline">\(X\)</span> variable does not only affect the <span class="math inline">\(Y\)</span> within that single region. Instead it has direct and indirect impacts that spread (or propagate or ripple) through the system defined by the spatial weights matrix.</p>
<p>To quantify the effects in the context of this echo or feedback, formal definitions of statistical <em>impacts</em> have been defined to capture the reverberations of effects transmitted through the system as a function of the strength of the correlation coefficients.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="spatial-regression-iii.html#cb346-1"></a><span class="kw">impacts</span>(sdm, <span class="dt">listw =</span> queen)</span></code></pre></div>
<pre><code>## Impact measures (mixed, exact):
##                        Direct     Indirect      Total
## Poverty_std        0.96236964  1.071752764  2.0341224
## InstabilityStress -0.04084631 -0.341421083 -0.3822674
## ParkProximity_std  0.27556056 -0.003729526  0.2718310
## PHYSHLTH           0.53482319 -0.158016271  0.3768069</code></pre>
<p>The results decompose the impact of changes in each <span class="math inline">\(X\)</span> covariate into the the <em>Direct</em> and <em>Indirect</em> component.</p>
<ol style="list-style-type: decimal">
<li>The average <em>Direct Impact</em> is the effect, averaged across all regions, of a change in a predictor covariate (e.g. exposure) in <span class="math inline">\(region_i\)</span> on the outcome in <span class="math inline">\(region_i\)</span>, accounting for the fact that changing local exposure might spillover to change neighbors outcomes, which might echo back and affect local outcomes.</li>
<li>The average <em>Indirect Impact</em> is the effect, averaged across all regions, of a change in a neighbors (e.g. <span class="math inline">\(region_j\)</span>) predictor covariate on the local outcome in <span class="math inline">\(region_i\)</span>.</li>
<li>The <em>Total Impact</em> is the sum of the direct and indirect impacts.</li>
</ol>
<p>From the results above, we can see that the <em>Total Impact</em> of <code>Poverty_std</code> is 2, with a direct impact of 0.96 (higher poverty in my tract predicts higher prevalence of poor mental health), and an indirect impact of 1.07 (higher poverty in my neighbors tracts predicts additional <em>higher</em> prevalence of poor mental health).</p>
<p>But is this <em>impact</em> significant? We can use Bayesian Markov Chain Monte Carlo simulations to quantify the bounds of these impacts. To do so, we must simulate the <code>impacts()</code> a large number of times (I actually only run a medium number of times, <code>R=199</code>, for efficiency; you could increase this number for more prediction):</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="spatial-regression-iii.html#cb348-1"></a>sdm.impact &lt;-<span class="st"> </span><span class="kw">impacts</span>(sdm, <span class="dt">listw =</span> queen, <span class="dt">R =</span> <span class="dv">199</span>)</span>
<span id="cb348-2"><a href="spatial-regression-iii.html#cb348-2"></a><span class="kw">summary</span>(sdm.impact)</span></code></pre></div>
<pre><code>## Impact measures (mixed, exact):
##                        Direct     Indirect      Total
## Poverty_std        0.96236964  1.071752764  2.0341224
## InstabilityStress -0.04084631 -0.341421083 -0.3822674
## ParkProximity_std  0.27556056 -0.003729526  0.2718310
## PHYSHLTH           0.53482319 -0.158016271  0.3768069
## ========================================================
## Simulation results (asymptotic variance matrix):
## Direct:
## 
## Iterations = 1:199
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 199 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                       Mean      SD Naive SE Time-series SE
## Poverty_std        0.96261 0.11664 0.008269       0.008269
## InstabilityStress -0.04704 0.06480 0.004593       0.005170
## ParkProximity_std  0.24957 0.31087 0.022037       0.019964
## PHYSHLTH           0.53651 0.04123 0.002923       0.002923
## 
## 2. Quantiles for each variable:
## 
##                      2.5%      25%      50%       75%   97.5%
## Poverty_std        0.7302  0.89315  0.96796  1.030832 1.18681
## InstabilityStress -0.1722 -0.08805 -0.05189 -0.008109 0.08082
## ParkProximity_std -0.2937  0.03479  0.26520  0.478664 0.79011
## PHYSHLTH           0.4526  0.50936  0.53660  0.564467 0.61561
## 
## ========================================================
## Indirect:
## 
## Iterations = 1:199
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 199 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                       Mean      SD Naive SE Time-series SE
## Poverty_std        1.07090 0.33911 0.024039       0.024039
## InstabilityStress -0.33471 0.16790 0.011902       0.013842
## ParkProximity_std -0.03132 0.74243 0.052630       0.052630
## PHYSHLTH          -0.16047 0.07017 0.004974       0.004974
## 
## 2. Quantiles for each variable:
## 
##                      2.5%     25%      50%     75%    97.5%
## Poverty_std        0.4329  0.8336  1.03820  1.2702  1.78813
## InstabilityStress -0.7001 -0.4258 -0.33200 -0.2300  0.02429
## ParkProximity_std -1.4859 -0.4829 -0.01516  0.3788  1.47414
## PHYSHLTH          -0.3233 -0.2004 -0.15827 -0.1058 -0.04275
## 
## ========================================================
## Total:
## 
## Iterations = 1:199
## Thinning interval = 1 
## Number of chains = 1 
## Sample size per chain = 199 
## 
## 1. Empirical mean and standard deviation for each variable,
##    plus standard error of the mean:
## 
##                      Mean      SD Naive SE Time-series SE
## Poverty_std        2.0335 0.35585 0.025226       0.025226
## InstabilityStress -0.3818 0.17074 0.012103       0.012035
## ParkProximity_std  0.2183 0.68755 0.048739       0.048739
## PHYSHLTH           0.3760 0.05912 0.004191       0.004191
## 
## 2. Quantiles for each variable:
## 
##                      2.5%     25%     50%     75%    97.5%
## Poverty_std        1.3281  1.8388  2.0025  2.2454  2.85652
## InstabilityStress -0.7528 -0.4726 -0.3761 -0.2725 -0.05927
## ParkProximity_std -1.0689 -0.1831  0.1970  0.6234  1.44780
## PHYSHLTH           0.2520  0.3340  0.3825  0.4201  0.47406</code></pre>
<p>From this we can see that the both the <em>direct</em> and the <em>indirect</em> impacts of <code>Poverty_std</code> and <code>PHYSHLTH</code> appear significantly different from zero (at least when I ran it…the specific numbers depend on the random seed and the number of samples drawn). Furthermore, the <em>indirect</em> effect of <code>InstabilityStress</code> appears to be significantly different from zero based on the 95% confidence intervals not overlapping zero.</p>

</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="spatial-regression-ii.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tips-for-reproducibility-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/mkram01/EPI563-SpatialEPI/edit/master/12-spatial-regression-3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["EPI563-SpatialEPI.pdf"],
"toc": {
"collapse": "section",
"toc_depth": 2,
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
