<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 9 Spatial Structure and Clustering II | EPI 563: Spatial Epidemiology, Fall 2020</title>
  <meta name="description" content="Week 9 Spatial Structure and Clustering II | EPI 563: Spatial Epidemiology, Fall 2020" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 9 Spatial Structure and Clustering II | EPI 563: Spatial Epidemiology, Fall 2020" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="mkram01/EPI563-SpatialEPI" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 9 Spatial Structure and Clustering II | EPI 563: Spatial Epidemiology, Fall 2020" />
  
  
  

<meta name="author" content="Michael Kramer" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatial-structure-and-clustering-i.html"/>
<link rel="next" href="spatial-regression-i.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">EPI 563: Spatial Epidemiology, Fall 2020</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>How to use this eBook</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#strategy-for-using-this-ebook"><i class="fa fa-check"></i>Strategy for using this eBook</a></li>
</ul></li>
<li class="part"><span><b>I Getting ready…</b></span></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li><a href="software-installation.html#installing-r-on-your-computer">Installing <code>R</code> on your computer</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#installing-rstudio-on-your-computer"><i class="fa fa-check"></i>Installing RStudio on your computer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html"><i class="fa fa-check"></i>Installing packages for this course</a>
<ul>
<li><a href="installing-packages-for-this-course.html#installing-rtools40">Installing <code>Rtools40</code></a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-general-data-science"><i class="fa fa-check"></i>Installing packages used for general data science</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-use-for-geographic-data"><i class="fa fa-check"></i>Installing packages use for geographic data</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-spatial-data-manipulation-visualization"><i class="fa fa-check"></i>Installing packages used for spatial data manipulation &amp; visualization</a></li>
<li class="chapter" data-level="" data-path="installing-packages-for-this-course.html"><a href="installing-packages-for-this-course.html#installing-packages-used-for-spatial-analysis"><i class="fa fa-check"></i>Installing packages used for spatial analysis</a></li>
</ul></li>
<li class="part"><span><b>II Weekly Modules</b></span></li>
<li class="chapter" data-level="1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html"><i class="fa fa-check"></i><b>1</b> Locating Spatial Epidemiology</a>
<ul>
<li class="chapter" data-level="1.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#getting-ready"><i class="fa fa-check"></i><b>1.1</b> Getting Ready</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#learning-objectives"><i class="fa fa-check"></i><b>1.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#additional-resources"><i class="fa fa-check"></i><b>1.1.2</b> Additional Resources</a></li>
<li class="chapter" data-level="1.1.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#important-vocabulary"><i class="fa fa-check"></i><b>1.1.3</b> Important Vocabulary</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-thinking-in-epidemiology"><i class="fa fa-check"></i><b>1.2</b> Spatial Thinking in Epidemiology</a></li>
<li class="chapter" data-level="1.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-analysis-in-epidemiology"><i class="fa fa-check"></i><b>1.3</b> Spatial Analysis in Epidemiology</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#spatial-data-storage-foramts"><i class="fa fa-check"></i><b>1.3.1</b> Spatial data storage foramts</a></li>
<li class="chapter" data-level="1.3.2" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#representing-spatial-data-in-r"><i class="fa fa-check"></i><b>1.3.2</b> Representing spatial data in <code>R</code></a></li>
<li class="chapter" data-level="1.3.3" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#benefits-of-sf-data-classes"><i class="fa fa-check"></i><b>1.3.3</b> Benefits of <code>sf</code> data classes</a></li>
<li class="chapter" data-level="1.3.4" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#working-with-spatial-data-in-r"><i class="fa fa-check"></i><b>1.3.4</b> Working with spatial data in <code>R</code></a></li>
<li class="chapter" data-level="1.3.5" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#basic-visual-inspectionplots"><i class="fa fa-check"></i><b>1.3.5</b> Basic visual inspection/plots</a></li>
<li class="chapter" data-level="1.3.6" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#working-with-crs-and-projection"><i class="fa fa-check"></i><b>1.3.6</b> Working with CRS and projection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html"><i class="fa fa-check"></i><b>2</b> Cartography for Epidemiology I</a>
<ul>
<li class="chapter" data-level="2.1" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#getting-ready"><i class="fa fa-check"></i><b>2.1</b> Getting Ready</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#learning-objectives-w2"><i class="fa fa-check"></i><b>2.1.1</b> Learning objectives, w2</a></li>
<li class="chapter" data-level="2.1.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#additional-resources-w2"><i class="fa fa-check"></i><b>2.1.2</b> Additional Resources, w2</a></li>
<li class="chapter" data-level="2.1.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#important-vocabulary-w2"><i class="fa fa-check"></i><b>2.1.3</b> Important Vocabulary, w2</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#spatial-thinking-in-epidemiology-w2"><i class="fa fa-check"></i><b>2.2</b> Spatial Thinking in Epidemiology, w2</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#color-choices"><i class="fa fa-check"></i><b>2.2.1</b> Color choices</a></li>
<li class="chapter" data-level="2.2.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#choropleth-binning-styles"><i class="fa fa-check"></i><b>2.2.2</b> Choropleth binning styles</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#spatial-analysis-in-epidemiology-w2"><i class="fa fa-check"></i><b>2.3</b> Spatial Analysis in Epidemiology, w2</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-numerator-data"><i class="fa fa-check"></i><b>2.3.1</b> Obtaining and preparing numerator data</a></li>
<li class="chapter" data-level="2.3.2" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-denominator-or-contextual-data"><i class="fa fa-check"></i><b>2.3.2</b> Obtaining and preparing denominator or contextual data</a></li>
<li class="chapter" data-level="2.3.3" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#obtaining-and-preparing-geographic-data"><i class="fa fa-check"></i><b>2.3.3</b> Obtaining and preparing geographic data</a></li>
<li class="chapter" data-level="2.3.4" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#merging-attributes-and-geography"><i class="fa fa-check"></i><b>2.3.4</b> Merging Attributes and Geography</a></li>
<li class="chapter" data-level="2.3.5" data-path="cartography-for-epidemiology-i.html"><a href="cartography-for-epidemiology-i.html#mapping-mortality-uninsured"><i class="fa fa-check"></i><b>2.3.5</b> Mapping Mortality &amp; Uninsured</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html"><i class="fa fa-check"></i><b>3</b> Cartography for Epidemiology II</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#learning-objectives-w3"><i class="fa fa-check"></i><b>3.1</b> Learning objectives, w3</a></li>
<li class="chapter" data-level="3.2" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#additional-resources-w3"><i class="fa fa-check"></i><b>3.2</b> Additional resources, w3</a></li>
<li class="chapter" data-level="3.3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#important-vocabulary-w3"><i class="fa fa-check"></i><b>3.3</b> Important Vocabulary, w3</a></li>
<li class="chapter" data-level="3.4" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#spatial-thinking-in-epidemiology-w3"><i class="fa fa-check"></i><b>3.4</b> Spatial Thinking in Epidemiology, w3</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risks-of-privacy-breaches-in-collection-of-geospatial-information"><i class="fa fa-check"></i><b>3.4.1</b> Risks of privacy breaches in collection of geospatial information</a></li>
<li class="chapter" data-level="3.4.2" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risk-of-confidentiality-breaches-through-unintentional-de-identification"><i class="fa fa-check"></i><b>3.4.2</b> Risk of confidentiality breaches through unintentional de-identification</a></li>
<li class="chapter" data-level="3.4.3" data-path="cartography-for-epidemiology-ii.html"><a href="cartography-for-epidemiology-ii.html#risk-of-stigmatization-of-place"><i class="fa fa-check"></i><b>3.4.3</b> Risk of stigmatization of place</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html"><i class="fa fa-check"></i><b>4</b> Disease Mapping I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#getting-ready-w4"><i class="fa fa-check"></i><b>4.1</b> Getting ready, w4</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#learning-objectives-w4"><i class="fa fa-check"></i><b>4.1.1</b> Learning objectives, w4</a></li>
<li class="chapter" data-level="4.1.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#additional-resources-w4"><i class="fa fa-check"></i><b>4.1.2</b> Additional Resources, w4</a></li>
<li class="chapter" data-level="4.1.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#important-vocabulary-w4"><i class="fa fa-check"></i><b>4.1.3</b> Important Vocabulary, w4</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#spatial-thinking-in-epidemiology-w4"><i class="fa fa-check"></i><b>4.2</b> Spatial Thinking in Epidemiology, w4</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#why-do-we-need-disease-mapping"><i class="fa fa-check"></i><b>4.2.1</b> Why do we need disease mapping?</a></li>
<li class="chapter" data-level="4.2.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#using-statistics-and-probability-models-to-improve-disease-mapping"><i class="fa fa-check"></i><b>4.2.2</b> Using statistics and probability models to improve disease mapping</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#spatial-analysis-in-epidemiology-w4"><i class="fa fa-check"></i><b>4.3</b> Spatial Analysis in Epidemiology, w4</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-is-there-spatial-heterogeneity"><i class="fa fa-check"></i><b>4.3.1</b> Disease mapping: Is there spatial heterogeneity?</a></li>
<li class="chapter" data-level="4.3.2" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-how-precise-are-county-estimates"><i class="fa fa-check"></i><b>4.3.2</b> Disease mapping: How precise are county estimates?</a></li>
<li class="chapter" data-level="4.3.3" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-adjusting-for-covariates"><i class="fa fa-check"></i><b>4.3.3</b> Disease mapping: Adjusting for covariates</a></li>
<li class="chapter" data-level="4.3.4" data-path="disease-mapping-i.html"><a href="disease-mapping-i.html#disease-mapping-rate-stabilization-with-global-empirical-bayes"><i class="fa fa-check"></i><b>4.3.4</b> Disease mapping: Rate stabilization with global Empirical Bayes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html"><i class="fa fa-check"></i><b>5</b> Disease Mapping II</a>
<ul>
<li class="chapter" data-level="5.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#getting-ready-w5"><i class="fa fa-check"></i><b>5.1</b> Getting Ready, w5</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#w5-learning-objectives"><i class="fa fa-check"></i><b>5.1.1</b> w5 Learning objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#additional-resources-w5"><i class="fa fa-check"></i><b>5.1.2</b> Additional Resources, w5</a></li>
<li class="chapter" data-level="5.1.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#important-vocabulary-w5"><i class="fa fa-check"></i><b>5.1.3</b> Important Vocabulary, w5</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-thinking-in-epidemiology-w5"><i class="fa fa-check"></i><b>5.2</b> Spatial Thinking in Epidemiology, w5</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#an-argument-for-the-relevance-of-space"><i class="fa fa-check"></i><b>5.2.1</b> An argument for the relevance of space</a></li>
<li class="chapter" data-level="5.2.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#on-making-meaning-from-neighbors"><i class="fa fa-check"></i><b>5.2.2</b> On making meaning from neighbors</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-analysis-in-epidemiology-w5"><i class="fa fa-check"></i><b>5.3</b> Spatial Analysis in Epidemiology, w5</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-contiguity-neighbor-objects"><i class="fa fa-check"></i><b>5.3.1</b> Creating contiguity neighbor objects</a></li>
<li class="chapter" data-level="5.3.2" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-k-nearest-neighbors"><i class="fa fa-check"></i><b>5.3.2</b> Creating k-nearest neighbors</a></li>
<li class="chapter" data-level="5.3.3" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-graph-based-triangle-neighbor-objects"><i class="fa fa-check"></i><b>5.3.3</b> Creating Graph-based triangle neighbor objects</a></li>
<li class="chapter" data-level="5.3.4" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#creating-fixed-distance-neighbors"><i class="fa fa-check"></i><b>5.3.4</b> Creating fixed-distance neighbors</a></li>
<li class="chapter" data-level="5.3.5" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#from-spatial-neighbors-to-spatial-disease-mapping"><i class="fa fa-check"></i><b>5.3.5</b> From spatial neighbors to spatial Disease Mapping</a></li>
<li class="chapter" data-level="5.3.6" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#spatial-empirical-bayes"><i class="fa fa-check"></i><b>5.3.6</b> Spatial Empirical Bayes</a></li>
<li class="chapter" data-level="5.3.7" data-path="disease-mapping-ii.html"><a href="disease-mapping-ii.html#final-thoughts-making-choices"><i class="fa fa-check"></i><b>5.3.7</b> Final thoughts: Making choices</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html"><i class="fa fa-check"></i><b>6</b> Disease Mapping III</a>
<ul>
<li class="chapter" data-level="6.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#getting-ready-w6"><i class="fa fa-check"></i><b>6.1</b> Getting Ready, w6</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#learning-objectives-w6"><i class="fa fa-check"></i><b>6.1.1</b> Learning objectives, w6</a></li>
<li class="chapter" data-level="6.1.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#additional-resources-w6"><i class="fa fa-check"></i><b>6.1.2</b> Additional Resources, w6</a></li>
<li class="chapter" data-level="6.1.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#important-vocabulary-w6"><i class="fa fa-check"></i><b>6.1.3</b> Important Vocabulary, w6</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#spatial-thinking-in-epidemiology-w6"><i class="fa fa-check"></i><b>6.2</b> Spatial Thinking in Epidemiology, w6</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#revisiting-spatial-point-processes"><i class="fa fa-check"></i><b>6.2.1</b> Revisiting spatial point processes</a></li>
<li class="chapter" data-level="6.2.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#what-is-a-kernel-density-estimator"><i class="fa fa-check"></i><b>6.2.2</b> What is a kernel density estimator?</a></li>
<li class="chapter" data-level="6.2.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#limitations-in-kernel-density-estimation"><i class="fa fa-check"></i><b>6.2.3</b> Limitations in kernel density estimation</a></li>
<li class="chapter" data-level="6.2.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#uses-for-kernel-density-estimation-kde-in-spatial-epidemiology"><i class="fa fa-check"></i><b>6.2.4</b> Uses for kernel density estimation (KDE) in spatial epidemiology</a></li>
<li class="chapter" data-level="6.2.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#guide-to-the-rest-of-this-section"><i class="fa fa-check"></i><b>6.2.5</b> Guide to the rest of this section…</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#spatial-analysis-in-epidemiology-kernel-estimation-of-point-processes"><i class="fa fa-check"></i><b>6.3</b> Spatial Analysis in Epidemiology: Kernel estimation of point processes</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#preparing-packages-and-data"><i class="fa fa-check"></i><b>6.3.1</b> Preparing packages and data</a></li>
<li class="chapter" data-level="6.3.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#introducing-a-new-spatial-data-class-ppp"><i class="fa fa-check"></i><b>6.3.2</b> Introducing a new spatial data class: <code>ppp</code></a></li>
<li class="chapter" data-level="6.3.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-the-ppp-objects"><i class="fa fa-check"></i><b>6.3.3</b> Creating the <code>ppp</code> objects</a></li>
<li class="chapter" data-level="6.3.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#bandwidth-selection"><i class="fa fa-check"></i><b>6.3.4</b> Bandwidth selection</a></li>
<li class="chapter" data-level="6.3.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#estimating-kernel-density-surfaces"><i class="fa fa-check"></i><b>6.3.5</b> Estimating Kernel Density surfaces</a></li>
<li class="chapter" data-level="6.3.6" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-relative-risk-surface-manually"><i class="fa fa-check"></i><b>6.3.6</b> Creating relative risk surface manually</a></li>
<li class="chapter" data-level="6.3.7" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#creating-relative-risk-surface-with-risk-function"><i class="fa fa-check"></i><b>6.3.7</b> Creating relative risk surface with <code>risk()</code> function</a></li>
<li class="chapter" data-level="6.3.8" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#using-functions-to-map-rr-with-tmap"><i class="fa fa-check"></i><b>6.3.8</b> Using functions to map RR with <code>tmap</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#spatial-analysis-in-epidemiology-kernel-estimation-of-areal-data"><i class="fa fa-check"></i><b>6.4</b> Spatial Analysis in Epidemiology: Kernel estimation of areal data</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#packages-and-data"><i class="fa fa-check"></i><b>6.4.1</b> Packages and data</a></li>
<li class="chapter" data-level="6.4.2" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#what-bandwidth-for-kernel-density-estimates"><i class="fa fa-check"></i><b>6.4.2</b> What bandwidth for kernel density estimates?</a></li>
<li class="chapter" data-level="6.4.3" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#geographically-weighted-summary-statistics-gwss"><i class="fa fa-check"></i><b>6.4.3</b> Geographically weighted summary statistics: <code>gwss()</code></a></li>
<li class="chapter" data-level="6.4.4" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#calculating-pseudo-p-values-for-smoothed-estimates"><i class="fa fa-check"></i><b>6.4.4</b> Calculating pseudo p-values for smoothed estimates</a></li>
<li class="chapter" data-level="6.4.5" data-path="disease-mapping-iii.html"><a href="disease-mapping-iii.html#estimating-geographically-weighted-bivariate-statistics"><i class="fa fa-check"></i><b>6.4.5</b> Estimating geographically-weighted bivariate statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html"><i class="fa fa-check"></i><b>7</b> Disease Mapping IV</a>
<ul>
<li class="chapter" data-level="7.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#getting-ready-w7"><i class="fa fa-check"></i><b>7.1</b> Getting Ready, w7</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#learning-objectives-w7"><i class="fa fa-check"></i><b>7.1.1</b> Learning objectives, w7</a></li>
<li class="chapter" data-level="7.1.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#additional-resources-w7"><i class="fa fa-check"></i><b>7.1.2</b> Additional Resources, w7</a></li>
<li class="chapter" data-level="7.1.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#important-vocabulary-w7"><i class="fa fa-check"></i><b>7.1.3</b> Important Vocabulary, w7</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#spatial-thinking-in-epidemiology-w7"><i class="fa fa-check"></i><b>7.2</b> Spatial Thinking in Epidemiology, w7</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#what-is-bayesian-inference"><i class="fa fa-check"></i><b>7.2.1</b> What is <em>Bayesian Inference</em>?</a></li>
<li class="chapter" data-level="7.2.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#bayesian-inference-in-spatial-epidemiology"><i class="fa fa-check"></i><b>7.2.2</b> Bayesian inference in spatial epidemiology</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#spatial-analysis-in-epidemiology-w7"><i class="fa fa-check"></i><b>7.3</b> Spatial Analysis in Epidemiology, w7</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>7.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#preparing-for-carbayes"><i class="fa fa-check"></i><b>7.3.2</b> Preparing for <code>CARBayes()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#fitting-a-besag-york-mollie-bym-bayesian-model"><i class="fa fa-check"></i><b>7.3.3</b> Fitting a <em>Besag-York-Mollie (BYM)</em> Bayesian model</a></li>
<li class="chapter" data-level="7.3.4" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#summarizing-carbayes-model-output"><i class="fa fa-check"></i><b>7.3.4</b> Summarizing <code>CARBayes</code> model output</a></li>
<li class="chapter" data-level="7.3.5" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#making-inference-from-bayesian-posteriors"><i class="fa fa-check"></i><b>7.3.5</b> Making inference from Bayesian posteriors</a></li>
<li class="chapter" data-level="7.3.6" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#extracting-summaries-for-mapping-or-analysis"><i class="fa fa-check"></i><b>7.3.6</b> Extracting summaries for mapping or analysis</a></li>
<li class="chapter" data-level="7.3.7" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#plot-raw-versus-smoothed"><i class="fa fa-check"></i><b>7.3.7</b> Plot raw versus smoothed</a></li>
<li class="chapter" data-level="7.3.8" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#mapping-rates"><i class="fa fa-check"></i><b>7.3.8</b> Mapping rates</a></li>
<li class="chapter" data-level="7.3.9" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#mapping-exceedance-probability"><i class="fa fa-check"></i><b>7.3.9</b> Mapping exceedance probability</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html"><i class="fa fa-check"></i><b>8</b> Spatial Structure and Clustering I</a>
<ul>
<li class="chapter" data-level="8.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#getting-ready-w8"><i class="fa fa-check"></i><b>8.1</b> Getting Ready, w8</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#learning-objectives-w8"><i class="fa fa-check"></i><b>8.1.1</b> Learning objectives, w8</a></li>
<li class="chapter" data-level="8.1.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#additional-resources-w8"><i class="fa fa-check"></i><b>8.1.2</b> Additional Resources, w8</a></li>
<li class="chapter" data-level="8.1.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#important-vocabulary-w8"><i class="fa fa-check"></i><b>8.1.3</b> Important Vocabulary, w8</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#spatial-thinking-in-epidemiology-w8"><i class="fa fa-check"></i><b>8.2</b> Spatial Thinking in Epidemiology, w8</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#two-big-questions"><i class="fa fa-check"></i><b>8.2.1</b> Two big questions…</a></li>
<li class="chapter" data-level="8.2.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#why-does-structure-or-clustering-matter"><i class="fa fa-check"></i><b>8.2.2</b> Why does structure or clustering matter?</a></li>
<li class="chapter" data-level="8.2.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#making-meaning-of-hypotheses-in-spatial-structure-testing"><i class="fa fa-check"></i><b>8.2.3</b> Making meaning of hypotheses in spatial structure testing</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#spatial-analysis-in-epidemiology-w8"><i class="fa fa-check"></i><b>8.3</b> Spatial Analysis in Epidemiology, w8</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>8.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="8.3.2" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#global-morans-i"><i class="fa fa-check"></i><b>8.3.2</b> Global Moran’s I</a></li>
<li class="chapter" data-level="8.3.3" data-path="spatial-structure-and-clustering-i.html"><a href="spatial-structure-and-clustering-i.html#local-morans-i"><i class="fa fa-check"></i><b>8.3.3</b> Local Moran’s I</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html"><i class="fa fa-check"></i><b>9</b> Spatial Structure and Clustering II</a>
<ul>
<li class="chapter" data-level="9.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#getting-ready-w9"><i class="fa fa-check"></i><b>9.1</b> Getting Ready, w9</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#learning-objectives-w9"><i class="fa fa-check"></i><b>9.1.1</b> Learning objectives, w9</a></li>
<li class="chapter" data-level="9.1.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#additional-resources-w9"><i class="fa fa-check"></i><b>9.1.2</b> Additional Resources, w9</a></li>
<li class="chapter" data-level="9.1.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#important-vocabulary-w9"><i class="fa fa-check"></i><b>9.1.3</b> Important Vocabulary, w9</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatial-thinking-in-epidemiology-conceptual-tools-for-thinking-about-clusters"><i class="fa fa-check"></i><b>9.2</b> Spatial Thinking in Epidemiology: Conceptual tools for thinking about ‘clusters’</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#the-clustering-conundrum"><i class="fa fa-check"></i><b>9.2.1</b> The clustering conundrum</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatial-scan-statistics"><i class="fa fa-check"></i><b>9.3</b> Spatial Scan Statistics</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="disease-mapping-iv.html"><a href="disease-mapping-iv.html#packages-data"><i class="fa fa-check"></i><b>9.3.1</b> Packages &amp; Data</a></li>
<li class="chapter" data-level="9.3.2" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#overview-of-kulldorff-nagarwalla-scan-statistic"><i class="fa fa-check"></i><b>9.3.2</b> Overview of <em>Kulldorff &amp; Nagarwalla</em> scan statistic</a></li>
<li class="chapter" data-level="9.3.3" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#spatio-temporal-scan-statistics"><i class="fa fa-check"></i><b>9.3.3</b> Spatio-temporal scan statistics</a></li>
<li class="chapter" data-level="9.3.4" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#estimating-spatial-only-kulldorff-scan-statistics"><i class="fa fa-check"></i><b>9.3.4</b> Estimating <em>spatial-only</em> Kulldorff scan statistics</a></li>
<li class="chapter" data-level="9.3.5" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#estimating-spatio-temporal-kuldorff-scan-statistic"><i class="fa fa-check"></i><b>9.3.5</b> Estimating <em>spatio-temporal</em> Kuldorff scan statistic</a></li>
<li class="chapter" data-level="9.3.6" data-path="spatial-structure-and-clustering-ii.html"><a href="spatial-structure-and-clustering-ii.html#concluding-thoughts"><i class="fa fa-check"></i><b>9.3.6</b> Concluding thoughts</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html"><i class="fa fa-check"></i><b>10</b> Spatial Regression I</a>
<ul>
<li class="chapter" data-level="10.1" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#getting-ready-w10"><i class="fa fa-check"></i><b>10.1</b> Getting Ready, w10</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#learning-objectives-w10"><i class="fa fa-check"></i><b>10.1.1</b> Learning objectives, w10</a></li>
<li class="chapter" data-level="10.1.2" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#additional-resources-w10"><i class="fa fa-check"></i><b>10.1.2</b> Additional Resources, w10</a></li>
<li class="chapter" data-level="10.1.3" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#important-vocabulary-w10"><i class="fa fa-check"></i><b>10.1.3</b> Important Vocabulary, w10</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#multivariable-regression-for-exploring-spatial-data"><i class="fa fa-check"></i><b>10.2</b> Multivariable regression for exploring spatial data</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#data-generating-process"><i class="fa fa-check"></i><b>10.2.1</b> Data Generating Process</a></li>
<li class="chapter" data-level="10.2.2" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#model-residuals-are-not-just-mistakes"><i class="fa fa-check"></i><b>10.2.2</b> Model residuals are not just mistakes</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#spatializing-aspatial-regression"><i class="fa fa-check"></i><b>10.3</b> Spatializing aspatial regression</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#data-packages"><i class="fa fa-check"></i><b>10.3.1</b> Data &amp; Packages</a></li>
<li class="chapter" data-level="10.3.2" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#fitting-unconditional-empty-model"><i class="fa fa-check"></i><b>10.3.2</b> Fitting unconditional (empty) model</a></li>
<li class="chapter" data-level="10.3.3" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#fitting-conditional-model"><i class="fa fa-check"></i><b>10.3.3</b> Fitting conditional model</a></li>
<li class="chapter" data-level="10.3.4" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#mapping-residuals"><i class="fa fa-check"></i><b>10.3.4</b> Mapping residuals</a></li>
<li class="chapter" data-level="10.3.5" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#morans-i-tests-on-lm-models"><i class="fa fa-check"></i><b>10.3.5</b> Moran’s I tests on <code>lm</code> models</a></li>
<li class="chapter" data-level="10.3.6" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#morans-i-tests-on-glm-models"><i class="fa fa-check"></i><b>10.3.6</b> Moran’s I tests on <code>glm</code> models</a></li>
<li class="chapter" data-level="10.3.7" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#mapping-glm-residuals"><i class="fa fa-check"></i><b>10.3.7</b> Mapping <code>glm</code> residuals</a></li>
<li class="chapter" data-level="10.3.8" data-path="spatial-regression-i.html"><a href="spatial-regression-i.html#final-words"><i class="fa fa-check"></i><b>10.3.8</b> Final words</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html"><i class="fa fa-check"></i><b>11</b> Spatial Regression II</a>
<ul>
<li class="chapter" data-level="11.1" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#w11-learning-objectives"><i class="fa fa-check"></i><b>11.1</b> w11 Learning objectives</a></li>
<li class="chapter" data-level="11.2" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#w11-additional-resources"><i class="fa fa-check"></i><b>11.2</b> w11 Additional Resources</a></li>
<li class="chapter" data-level="11.3" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#w11-spatial-thinking-in-epidemiology"><i class="fa fa-check"></i><b>11.3</b> w11 Spatial Thinking in Epidemiology</a></li>
<li class="chapter" data-level="11.4" data-path="spatial-regression-ii.html"><a href="spatial-regression-ii.html#w11-spatial-analysis-in-epidemiology"><i class="fa fa-check"></i><b>11.4</b> w11 Spatial Analysis in Epidemiology</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html"><i class="fa fa-check"></i><b>12</b> Spatial Regression III</a>
<ul>
<li class="chapter" data-level="12.1" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#w12-learning-objectives"><i class="fa fa-check"></i><b>12.1</b> w12 Learning objectives</a></li>
<li class="chapter" data-level="12.2" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#w12-additional-resources"><i class="fa fa-check"></i><b>12.2</b> w12 Additional Resources</a></li>
<li class="chapter" data-level="12.3" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#w12-spatial-thinking-in-epidemiology"><i class="fa fa-check"></i><b>12.3</b> w12 Spatial Thinking in Epidemiology</a></li>
<li class="chapter" data-level="12.4" data-path="spatial-regression-iii.html"><a href="spatial-regression-iii.html#w12-spatial-analysis-in-epidemiology"><i class="fa fa-check"></i><b>12.4</b> w12 Spatial Analysis in Epidemiology</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="wrap-up-project.html"><a href="wrap-up-project.html"><i class="fa fa-check"></i><b>13</b> Wrap-up &amp; Project</a>
<ul>
<li class="chapter" data-level="13.1" data-path="wrap-up-project.html"><a href="wrap-up-project.html#w13-learning-objectives"><i class="fa fa-check"></i><b>13.1</b> w13 Learning objectives</a></li>
<li class="chapter" data-level="13.2" data-path="wrap-up-project.html"><a href="wrap-up-project.html#w13-additional-resources"><i class="fa fa-check"></i><b>13.2</b> w13 Additional Resources</a></li>
<li class="chapter" data-level="13.3" data-path="wrap-up-project.html"><a href="wrap-up-project.html#w13-spatial-thinking-in-epidemiology"><i class="fa fa-check"></i><b>13.3</b> w13 Spatial Thinking in Epidemiology</a></li>
<li class="chapter" data-level="13.4" data-path="wrap-up-project.html"><a href="wrap-up-project.html#w13-spatial-analysis-in-epidemiology"><i class="fa fa-check"></i><b>13.4</b> w13 Spatial Analysis in Epidemiology</a></li>
</ul></li>
<li class="part"><span><b>III Appendices</b></span></li>
<li class="chapter" data-level="14" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html"><i class="fa fa-check"></i><b>14</b> Tips for reproducibility in <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="locating-spatial-epidemiology.html"><a href="locating-spatial-epidemiology.html#additional-resources"><i class="fa fa-check"></i>Additional Resources</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#workflows-to-enhance-reproducibility"><i class="fa fa-check"></i>Workflows to enhance reproducibility</a>
<ul>
<li><a href="tips-for-reproducibility-in-r.html#using-projects-in-r">Using Projects in <code>R</code></a></li>
</ul></li>
<li><a href="tips-for-reproducibility-in-r.html#understanding-directory-and-file-path-names-in-r">Understanding directory and file path names in <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#specify-a-location-within-the-working-directory"><i class="fa fa-check"></i>Specify a location within the working directory</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#specify-a-relative-location-outside-the-working-directory"><i class="fa fa-check"></i>Specify a relative location outside the working directory</a></li>
</ul></li>
<li><a href="tips-for-reproducibility-in-r.html#why-r-notebooks">Why <code>R Notebooks</code>?</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#what-you-need-to-know"><i class="fa fa-check"></i>What you need to know</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#important-r-notebook-functions"><i class="fa fa-check"></i>Important R Notebook functions</a>
<ul>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#the-yaml"><i class="fa fa-check"></i>The YAML</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#typing-text"><i class="fa fa-check"></i>Typing text</a></li>
<li><a href="tips-for-reproducibility-in-r.html#adding-r-code">Adding <code>R</code> Code</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#making-tables"><i class="fa fa-check"></i>Making tables</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#workflow"><i class="fa fa-check"></i>Workflow</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#optional-functions"><i class="fa fa-check"></i>Optional functions</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#customizing-your-yaml"><i class="fa fa-check"></i>Customizing your YAML</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#simple-formatting-of-your-notebook"><i class="fa fa-check"></i>Simple formatting of your Notebook</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#text-formatting"><i class="fa fa-check"></i>Text formatting</a></li>
<li class="chapter" data-level="" data-path="tips-for-reproducibility-in-r.html"><a href="tips-for-reproducibility-in-r.html#final-note"><i class="fa fa-check"></i>Final Note</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="sf-overview.html"><a href="sf-overview.html"><i class="fa fa-check"></i><b>15</b> Tips for working with <code>sf</code> data class</a>
<ul>
<li class="chapter" data-level="15.1" data-path="sf-overview.html"><a href="sf-overview.html#st_set_geom"><i class="fa fa-check"></i><b>15.1</b> <code>st_set_geom()</code></a></li>
<li class="chapter" data-level="15.2" data-path="sf-overview.html"><a href="sf-overview.html#st-as-sf"><i class="fa fa-check"></i><b>15.2</b> <code>st_as_sf()</code></a></li>
<li class="chapter" data-level="15.3" data-path="sf-overview.html"><a href="sf-overview.html#st_crs"><i class="fa fa-check"></i><b>15.3</b> <code>st_crs()</code></a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>16</b> Tips for using <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="16.1" data-path="dplyr.html"><a href="dplyr.html#select"><i class="fa fa-check"></i><b>16.1</b> <code>select()</code></a></li>
<li class="chapter" data-level="16.2" data-path="dplyr.html"><a href="dplyr.html#mutate"><i class="fa fa-check"></i><b>16.2</b> <code>mutate()</code></a></li>
<li class="chapter" data-level="16.3" data-path="dplyr.html"><a href="dplyr.html#filter"><i class="fa fa-check"></i><b>16.3</b> <code>filter()</code></a></li>
<li class="chapter" data-level="16.4" data-path="dplyr.html"><a href="dplyr.html#arrange"><i class="fa fa-check"></i><b>16.4</b> <code>arrange()</code></a></li>
<li class="chapter" data-level="16.5" data-path="dplyr.html"><a href="dplyr.html#pipe-operator"><i class="fa fa-check"></i><b>16.5</b> <code>%&gt;%</code> Pipe operator</a></li>
<li class="chapter" data-level="16.6" data-path="dplyr.html"><a href="dplyr.html#group_by-and-summarise"><i class="fa fa-check"></i><b>16.6</b> <code>group_by()</code> and <code>summarise()</code></a></li>
<li class="chapter" data-level="16.7" data-path="dplyr.html"><a href="dplyr.html#join"><i class="fa fa-check"></i><b>16.7</b> <code>join()</code></a></li>
<li class="chapter" data-level="16.8" data-path="dplyr.html"><a href="dplyr.html#pivot_"><i class="fa fa-check"></i><b>16.8</b> Reshaping (transposing) data</a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="dplyr.html"><a href="dplyr.html#pivot_longer-for-going-from-wide-to-long"><i class="fa fa-check"></i><b>16.8.1</b> <code>pivot_longer()</code> for going from wide to long</a></li>
<li class="chapter" data-level="16.8.2" data-path="dplyr.html"><a href="dplyr.html#pivot_wider"><i class="fa fa-check"></i><b>16.8.2</b> <code>pivot_wider()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="intro-tmap.html"><a href="intro-tmap.html"><i class="fa fa-check"></i><b>17</b> Tips for using <code>tmap</code></a>
<ul>
<li class="chapter" data-level="17.1" data-path="intro-tmap.html"><a href="intro-tmap.html#tmap-mode"><i class="fa fa-check"></i><b>17.1</b> <code>tmap</code> mode</a></li>
<li class="chapter" data-level="17.2" data-path="intro-tmap.html"><a href="intro-tmap.html#qtm"><i class="fa fa-check"></i><b>17.2</b> Quick maps: <code>qtm()</code></a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-polygons"><i class="fa fa-check"></i><b>17.2.1</b> Customizing <code>qtm()</code> for polygons</a></li>
<li class="chapter" data-level="17.2.2" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-lines"><i class="fa fa-check"></i><b>17.2.2</b> Customizing <code>qtm()</code> for lines</a></li>
<li class="chapter" data-level="17.2.3" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-qtm-for-points"><i class="fa fa-check"></i><b>17.2.3</b> Customizing <code>qtm()</code> for points</a></li>
<li class="chapter" data-level="17.2.4" data-path="intro-tmap.html"><a href="intro-tmap.html#finding-valid-color-options"><i class="fa fa-check"></i><b>17.2.4</b> Finding valid color options</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="intro-tmap.html"><a href="intro-tmap.html#building-maps-with-tmap"><i class="fa fa-check"></i><b>17.3</b> Building maps with <code>tmap</code></a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="intro-tmap.html"><a href="intro-tmap.html#building-blocks-in-tmap"><i class="fa fa-check"></i><b>17.3.1</b> Building blocks in <code>tmap</code></a></li>
<li class="chapter" data-level="17.3.2" data-path="intro-tmap.html"><a href="intro-tmap.html#customizing-text-on-maps"><i class="fa fa-check"></i><b>17.3.2</b> Customizing text on maps</a></li>
<li class="chapter" data-level="17.3.3" data-path="intro-tmap.html"><a href="intro-tmap.html#adding-two-or-more-spatial-objects-in-one-map"><i class="fa fa-check"></i><b>17.3.3</b> Adding two or more spatial objects in one map</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="intro-tmap.html"><a href="intro-tmap.html#controlling-layout-and-map-elements"><i class="fa fa-check"></i><b>17.4</b> Controlling layout and map elements</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="intro-tmap.html"><a href="intro-tmap.html#understanding-the-graphic-space-in-tmap"><i class="fa fa-check"></i><b>17.4.1</b> Understanding the graphic space in <code>tmap</code></a></li>
<li class="chapter" data-level="17.4.2" data-path="intro-tmap.html"><a href="intro-tmap.html#controlling-map-layout"><i class="fa fa-check"></i><b>17.4.2</b> Controlling map layout</a></li>
<li class="chapter" data-level="17.4.3" data-path="intro-tmap.html"><a href="intro-tmap.html#adding-map-elements"><i class="fa fa-check"></i><b>17.4.3</b> Adding map elements</a></li>
<li class="chapter" data-level="17.4.4" data-path="intro-tmap.html"><a href="intro-tmap.html#change-the-global-style-of-a-map"><i class="fa fa-check"></i><b>17.4.4</b> Change the global style of a map</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="intro-tmap.html"><a href="intro-tmap.html#making-small-multiple-maps"><i class="fa fa-check"></i><b>17.5</b> Making small-multiple maps</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="intro-tmap.html"><a href="intro-tmap.html#small-multiples-as-a-vector-of-variables"><i class="fa fa-check"></i><b>17.5.1</b> Small multiples as a vector of variables</a></li>
<li class="chapter" data-level="17.5.2" data-path="intro-tmap.html"><a href="intro-tmap.html#tmap-facet"><i class="fa fa-check"></i><b>17.5.2</b> Small multiples with facets</a></li>
<li class="chapter" data-level="17.5.3" data-path="intro-tmap.html"><a href="intro-tmap.html#facets-for-time-series"><i class="fa fa-check"></i><b>17.5.3</b> Facets for time-series</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="intro-tmap.html"><a href="intro-tmap.html#small-multiples-with-tmap_arrange"><i class="fa fa-check"></i><b>17.6</b> Small multiples with <code>tmap_arrange()</code></a></li>
<li class="chapter" data-level="17.7" data-path="intro-tmap.html"><a href="intro-tmap.html#summarizing-small-multiples"><i class="fa fa-check"></i><b>17.7</b> Summarizing small multiples</a></li>
<li class="chapter" data-level="17.8" data-path="intro-tmap.html"><a href="intro-tmap.html#saving-maps"><i class="fa fa-check"></i><b>17.8</b> Saving maps</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EPI 563: Spatial Epidemiology, Fall 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatial-structure-and-clustering-ii" class="section level1" number="9">
<h1><span class="header-section-number">Week 9</span> Spatial Structure and Clustering II</h1>
<div id="getting-ready-w9" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Getting Ready, w9</h2>
<div id="learning-objectives-w9" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Learning objectives, w9</h3>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 100%; margin-left: auto; margin-right: auto;  " id="learning-ob">
<caption style="caption-side: top; text-align: center;"><span id="tab:learning-ob">TABLE 1.1: </span> Learning objectives by weekly module</caption><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(208, 211, 212); font-weight: bold;">After this module you should be able to…</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(250, 229, 211); font-weight: normal;">Evaluate statistical estimation of spatial clustering in population health to generate epidemiologic hypotheses</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 6pt; background-color: rgb(245, 203, 167); font-weight: normal;">Apply spatial scan statistics to epidemiologic data and interpret results</td></tr>
</table>

</div>
<div id="additional-resources-w9" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Additional Resources, w9</h3>
<ul>
<li><a href="https://github.com/BenjaK/scanstatistics">Vignette for <code>scanstatistics</code> package in R</a></li>
<li><a href="https://www.satscan.org/">SatScan website</a>, supported by National Cancer Institute</li>
</ul>
</div>
<div id="important-vocabulary-w9" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Important Vocabulary, w9</h3>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; width: 90%; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-231">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-231">TABLE 9.1: </span> Vocabulary for Week 9</caption><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Term</span></th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(84, 153, 199); font-weight: bold;"><span style="color: rgb(255, 255, 255);">Definition</span></th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">1st order process</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">Statistical measures where units taken one at a time. Spatial heterogeneity is about how the mean intensity varies for each unit, and is therefore primarily about first order process</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">2nd order process</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">Statistical measures where units considered at least two at a time. Spatial dependence is about correlation or relatedness between units and is therefore about 2nd order processes</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Global vs Local spatial analysis</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">Global analysis evaluates a pattern or trends that characterizes the entire study region; in contrast local analysis characterizes patterns that are unique to each sub-region of the study area</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial dependence</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">When attribute values or statistical parameters are, on avreage, more similar for nearby places than they are for distant places. Spatial dependence is evaluated by looking at pairs or sets of places.</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(212, 230, 241); font-weight: bold;">Spatial heterogeneity</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(212, 230, 241); font-weight: normal;">Attributes or statistical parameters are varied (e.g. not homogenous) across sub-areas in a broader region. In Disease mapping we typically are evaluating whether (and how much) disease intensity (risk, rate, prevalence) varies across places.</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 2pt 2pt 6pt; background-color: rgb(169, 204, 227); font-weight: bold;">Spatial scan statistic</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 1pt 1pt 1pt 1pt; border-top-color: rgb(255, 255, 255);  border-right-color: rgb(255, 255, 255);  border-bottom-color: rgb(255, 255, 255);  border-left-color: rgb(255, 255, 255); padding: 2pt 6pt 2pt 2pt; background-color: rgb(169, 204, 227); font-weight: normal;">A test for extreme or unusual event intensity inside versus outside a varying regional window, in an effort to detect local clusters of disease</td></tr>
</table>

</div>
</div>
<div id="spatial-thinking-in-epidemiology-conceptual-tools-for-thinking-about-clusters" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Spatial Thinking in Epidemiology: Conceptual tools for thinking about ‘clusters’</h2>
<p>Last week we formalized two essential questions in spatial epidemiology:</p>
<ol style="list-style-type: decimal">
<li>Is there <strong>spatial heterogeneity</strong> or variation in the intensity of disease within a study area?</li>
<li>Is there <strong>spatial dependency</strong> or autocorrelation in the disease rate among local sub-regions of the overall study area?</li>
</ol>
<p>These two questions recalled a contrast that we have made in prior weeks between <em>global</em> patterns and <em>local</em> patterns:</p>
<ol style="list-style-type: decimal">
<li><strong>Global</strong>: characterization of patterns of intensity or autocorrelation for an entire study region.</li>
<li><strong>Local</strong>: characterization of specific deviations from expectation in sub-regions of the study area.</li>
</ol>
<p>To combine these two constructs, describing <strong>global heterogeneity</strong> is to ask, “<em>are there any areas that are meaningfully different from the constant risk null hypothesis?</em>” Describing <strong>global autocorrelation</strong> is to ask, “<em>on average do values in each region correlate with values in their neighboring regions?</em>”</p>
<p>And by extension, describing <strong>local heterogeneity</strong> is to detect the existence of a local extreme (e.g. intensity that is significantly and/or meaningfully higher or lower than expected under assumptions of constant risk). Similarly, describing <strong>local autocorrelation</strong> is to detect specific sub-regions that are unusually similar to (or perhaps unusually unlike) their neighbors.</p>
<div id="the-clustering-conundrum" class="section level3" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> The clustering conundrum</h3>
<p>The preceding summary of points covered over the past weeks gives us a starting point for analytically and statistically <em>detecting</em> and <em>describing</em> spatial clustering of disease. As discussed last week, this is of interest statistically (e.g. to rule out bias and error as sources of unusual patterning), epidemiologically (e.g. to characterize the occurrence of disease as part of surveillance or etiologic research), and from a policy and public health perspective (e.g. to inform public health prevention, regulation, or policy). While the constructs above help with the <em>detection</em> of unusual patterns, <em>explaining</em> them (e.g. in terms of causes, processes, and exposures) is often the ultimate goal.</p>
<p>So what exactly is ‘<em>disease clustering</em>’ and what does statistical evidence of global or local heterogeneity or dependency tell us about the generation or causes of clustering? It turns out this notion of explaining ‘<em>clustering</em>’ is a tricky one both conceptually and analytically.</p>
<p><strong>Conceptually</strong>, we might like to distinguish between at least two kinds of processes:</p>
<ol style="list-style-type: decimal">
<li>Factors about the context or the population itself that results in greater or smaller intensity of disease in one place versus another. For example environmental toxicants such as air pollution or arsenic in the water could plausibly affect all who live in the area, resulting in a higher disease prevalence. UV-exposure varies by latitude, and this partly explains differences in skin cancer and Vitamin D deficiency. <em>Spatial variation caused by changes in the underlying property of places or populations are called</em> <strong>1st order effects</strong>.</li>
<li>Processes of spread, contagion, or diffusion suggest that some interaction between people (or between the institutional influence within places) result in a spread or transmission of disease. This is most intuitive for infectious disease, where transmission is a function of proximity. But contagion and diffusion can occur in non-infectious outcomes as well, as seen with behavioral contagion and social norms shared within networks (e.g. acceptability of smoking, expectations about body size, etc). <em>Spatial variation or clustering caused by the interaction between individuals or entities are called</em> <strong>2nd order effects</strong>.</li>
</ol>
<div class="figure"><span id="fig:unnamed-chunk-232"></span>
<img src="images/1st_2nd_order_property.png" alt="Image source: https://mgimond.github.io/Spatial/index.html"  />
<p class="caption">
FIGURE 9.1: Image source: <a href="https://mgimond.github.io/Spatial/index.html" class="uri">https://mgimond.github.io/Spatial/index.html</a>
</p>
</div>
<p>The figure above illustrates 1st and 2nd order spatial effects in the context of ecology. The core concept relevant to epidemiology is that 1st order effects assume patterns are from differences in the <em>mean intensity</em>, whereas 2nd order effects focuses on differences in <em>covariation</em> or <em>correlation</em>. You might recognize, therefore, a parallel with our two essential questions of heterogeneity of the mean intensity versus autocorrelation among pairs of units. You may also note that our analytic strategies have been framed in the context of these distinctions: tests for spatial heterogeneity built on the null hypothesis of constant risk sound like they are evaluating 1st order effects; in contrast tests for spatial autocorrelation comparing pairs of regions sound like they are evaluating 2nd order effects.</p>
<p><strong>Analytically</strong> it would be great to have a test that distinguishes clearly between these competing explanations for how the unusual spatial pattern was generated or produced. But this is the second tricky issue. Both 1st and 2nd order processes can produce patterns of disease that could be detected with either tests for heterogeneity or tests for spatial autocorrelation. Said another way, our tests cannot analytically distinguish <strong>why</strong> an unusual pattern was caused; instead they are complementary ways to describe the <strong>magnitude</strong> and <strong>location</strong> of patterns.</p>
<p>At the end of the day, spatial epidemiologists must design the studies and select the tools that best serve the needs of the question at hand. If detecting and describing clustering is the primary goals (e.g. for surveillance or description), then the combination of disease mapping and cluster detection may be the beginning and the end of the work. However, if characterizing the underlying causes and processes are important – either for scientific understanding or effective public health action – then the tools are just steps on the way. Disease mapping and cluster detection may generate hypotheses, lead to additional investigation, or be used to triangulate with other data to build a fuller picture.</p>
</div>
</div>
<div id="spatial-scan-statistics" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Spatial Scan Statistics</h2>
<p>The family of <em>scan statistics</em> are commonly used for identifying localized spatial clusters of disease. Some of the specific examples of statistical approaches in this broad category have been attributed to <em>Besag &amp; Newell</em>, <em>Openshaw</em> (the <em>Geographical Analysis Machine</em>), and to <em>Kulldorff &amp; Nagarwalla</em>. This discussion focuses primarily on implementation of the latter set of tests. Many users take advantage of stand-alone free software called <em>SaTScan</em> to carry out these tests. The software can be downloaded here: <a href="https://www.satscan.org/download_satscan.html" class="uri">https://www.satscan.org/download_satscan.html</a>. This site also has a rich set of tutorial and technical documentation resources.</p>
<p>In part because of the widespread use of the <em>SaTScan</em> software, there has been less development of scan statistics in <code>R</code>. For that reason, some of the functions used in the examples below do not have as many <em>helper</em> functions or wrappers as we’ve had in some previous examples. As a result tutorial is a mix of spatial analysis and hacking our way through output with <code>R</code> coding.</p>
<div id="packages-data" class="section level3" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Packages &amp; Data</h3>
<p>We will use several familiar, and one new package in this lab: <code>scanstatistics</code></p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="spatial-structure-and-clustering-ii.html#cb223-1"></a><span class="kw">library</span>(sf)        <span class="co"># manage sf class data </span></span>
<span id="cb223-2"><a href="spatial-structure-and-clustering-ii.html#cb223-2"></a><span class="kw">library</span>(dplyr)     <span class="co"># facilitates data processing</span></span>
<span id="cb223-3"><a href="spatial-structure-and-clustering-ii.html#cb223-3"></a><span class="kw">library</span>(tmap)      <span class="co"># for thematic mapping</span></span>
<span id="cb223-4"><a href="spatial-structure-and-clustering-ii.html#cb223-4"></a><span class="kw">library</span>(SpatialEpi) <span class="co"># Functions including the kulldorff()</span></span>
<span id="cb223-5"><a href="spatial-structure-and-clustering-ii.html#cb223-5"></a><span class="co">#install.packages(&#39;scanstatistics&#39;) # install if not already done</span></span>
<span id="cb223-6"><a href="spatial-structure-and-clustering-ii.html#cb223-6"></a><span class="kw">library</span>(scanstatistics) <span class="co"># spatio-temporal scan</span></span>
<span id="cb223-7"><a href="spatial-structure-and-clustering-ii.html#cb223-7"></a><span class="kw">library</span>(ggplot2)  <span class="co"># Create a ggplot visualization</span></span></code></pre></div>
<p>In terms of data, we are using a new dataset for this example. Specifically we have the counts of reported sexually transmitted infections (STIs; includes chlamydia, gonorrhea, chancroid, and syphilis) for each county, along with the population count at risk. These data exist in a <em>cross-sectional</em> version, pooling counts for 2018, with n=159 rows for the 159 counties. However, there is also a <em>spatio-temporal</em> dataset of STIs for each county for each year from 2010-2018. These data are in <em>long format</em> which means that there is a row for every year and county (e.g. repeated rows within counties).</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="spatial-structure-and-clustering-ii.html#cb224-1"></a><span class="co"># cross-sectional STI data</span></span>
<span id="cb224-2"><a href="spatial-structure-and-clustering-ii.html#cb224-2"></a>sti &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&#39;ga-std-2017-18.gpkg&#39;</span>) </span>
<span id="cb224-3"><a href="spatial-structure-and-clustering-ii.html#cb224-3"></a>r &lt;-<span class="st"> </span><span class="kw">sum</span>(sti<span class="op">$</span>STD) <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(sti<span class="op">$</span>POP)</span>
<span id="cb224-4"><a href="spatial-structure-and-clustering-ii.html#cb224-4"></a>sti<span class="op">$</span>expected &lt;-<span class="st"> </span>r<span class="op">*</span>sti<span class="op">$</span>POP</span>
<span id="cb224-5"><a href="spatial-structure-and-clustering-ii.html#cb224-5"></a></span>
<span id="cb224-6"><a href="spatial-structure-and-clustering-ii.html#cb224-6"></a><span class="co"># longitudinal STI data</span></span>
<span id="cb224-7"><a href="spatial-structure-and-clustering-ii.html#cb224-7"></a>sti_long &lt;-<span class="st"> </span><span class="kw">st_read</span>(<span class="st">&#39;ga-std-long.gpkg&#39;</span>)</span></code></pre></div>
<p>Because these are new data, here is a simple map of the STI rate for the 2017-18 years pooled.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="spatial-structure-and-clustering-ii.html#cb225-1"></a>sti <span class="op">%&gt;%</span></span>
<span id="cb225-2"><a href="spatial-structure-and-clustering-ii.html#cb225-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">rate =</span> STD <span class="op">/</span><span class="st"> </span>POP <span class="op">*</span><span class="st"> </span><span class="dv">1000</span>) <span class="op">%&gt;%</span></span>
<span id="cb225-3"><a href="spatial-structure-and-clustering-ii.html#cb225-3"></a><span class="st">  </span><span class="kw">tm_shape</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb225-4"><a href="spatial-structure-and-clustering-ii.html#cb225-4"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&#39;rate&#39;</span>,</span>
<span id="cb225-5"><a href="spatial-structure-and-clustering-ii.html#cb225-5"></a>          <span class="dt">style =</span> <span class="st">&#39;quantile&#39;</span>,</span>
<span id="cb225-6"><a href="spatial-structure-and-clustering-ii.html#cb225-6"></a>          <span class="dt">palette =</span> <span class="st">&#39;YlGnBu&#39;</span>,</span>
<span id="cb225-7"><a href="spatial-structure-and-clustering-ii.html#cb225-7"></a>          <span class="dt">title =</span> <span class="st">&#39;STI per 1000&#39;</span>) <span class="op">+</span></span>
<span id="cb225-8"><a href="spatial-structure-and-clustering-ii.html#cb225-8"></a><span class="st">  </span><span class="kw">tm_borders</span>()</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-236-1.png" width="672" /></p>
</div>
<div id="overview-of-kulldorff-nagarwalla-scan-statistic" class="section level3" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> Overview of <em>Kulldorff &amp; Nagarwalla</em> scan statistic</h3>
<p>Scan statistics get their name because they conceptually cluster identification in a flexible manner by ‘<em>scanning</em>’ the entire study region with many different possible windows of observation. The basic analytic strategy of the Kulldorff scan statistic follows several steps:</p>
<ol style="list-style-type: decimal">
<li>Define a single location (e.g. centroid of a polygon, or at regularly-placed grid points across the region)</li>
<li>At each location, further define the radius of a <em>window</em> defining the area <em>local to</em> the location. The radius typically is varied iteratively from zero (e.g. only the single location included), to something large (perhaps as large as is necessary to include 50% of the population). Scan statistics typically use a <em>circular</em> window, although <em>ellipses</em> and other shapes are possible.</li>
<li>For each location <span class="math inline">\(x\)</span>, and for each window-radius (e.g. the window surrounding each reference point), aggregate the count of events and the population at risk (or alternatively the <em>expected count of events</em> under a constant risk hypothesis) <strong>inside</strong> (e.g. <span class="math inline">\(p\)</span>) and <strong>outside</strong> (e.g. <span class="math inline">\(q\)</span>) the window.</li>
<li>Calculate a <em>likelihood ratio test</em> for whether the rates/risks are equal (<span class="math inline">\(H_0: p=q\)</span>), or the risk inside the window is larger (<span class="math inline">\(H_1: p&gt;q\)</span>).</li>
<li>Repeat the above four steps for <em>every iteration of window-radius</em> and <em>every location</em> in the study region.</li>
</ol>
<p>The first thing that should be apparent, is that the null assumption being tested is the <em>constant risk</em> or <em>spatial homogeneity of risk</em> assumption, rather than the <em>spatial independence</em> assumption. This is clear from the fact that we are not assessing correlation between values, but the magnitude of the risk/rate inside versus outside the region. This illustrates that testing for spatial autocorrelation (e.g. with Moran’s I or LISA) is not the only way to conceive of clusters.</p>
<p>It is also apparent that what results is a large number of test statistics, which raises concern for multiple comparisons and Type I error. Kulldorff’s approach, however, suggests that we are not interested in the set of <em>statistically significant</em> test statistics (of which there could be many by chance alone given the number of tests conducted), but instead that we are interested in identifying a single (or perhaps a few) <em>most-likely cluster(s)</em>. By <em>a priori</em> restricting interest to a most-likely cluster, we eliminate concern for multiple comparison. It is possible that the most-likely cluster is in fact statistically significant, or that it is not (e.g. if there is spatial homogeneity, the <em>most likely</em> is still not that interesting!).</p>
<p>Because all-possible locations <span class="math inline">\(x\)</span> and window-radius were tested, we can also choose to look at secondary clusters, recognizing that the further down the list of <em>unusual</em> test statistics, the greater the risk of Type I error.</p>
<p>The strengths of the Kulldorff scan statistic are its flexibility with respect to defining ‘<em>local</em>’, and the straightforward evaluation of whether there is more risk within a window versus outside. The potential limitations are that some clusters (e.g. along highways producing a linear pattern) may not be readily detected by circular or elliptical search windows.</p>
</div>
<div id="spatio-temporal-scan-statistics" class="section level3" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Spatio-temporal scan statistics</h3>
<p>While the above strategy described a purely <em>spatial</em> scan, it is relatively straightforward to extend the strategy to include <em>spatio-temporal</em> scans. Obviously for this to work, data must be available for every time-period within every region.</p>
<p>For spatio-temporal scans, we simply add another dimension of the defined <em>window</em>. Each window will be centered at a given location (e.g. the centroid of a county), have a given radius, <em>and include a varying-number of time-periods</em>. For instance, two iterations of the test could be centered at the same spatial location, with the same window-size, but one might include a single time-period, and another includes two time-periods. A comparison of the resulting test statistics tells us whether the count of events <em>inside the spatio-temporal window</em> with one time-period is different from that of a <em>spatio-temporal window</em> with two time-periods. Instead of a <em>scanning circle</em> traveling across the map, we might imagine a <em>scanning column</em> or tube with its height varying to define different numbers of time periods.</p>
<p>For example in the illustration below, the conventional cross-sectional scan statistic would simply move a two-dimensional window around the map. But the spatio-temporal window has a third dimension reflecting maps <em>stacked on top of one another</em>.</p>
<div class="figure"><span id="fig:unnamed-chunk-237"></span>
<img src="images/spatio-temporal-window.png" alt="Image source: https://www.mdpi.com/1999-4907/11/4/454/htm"  />
<p class="caption">
FIGURE 9.2: Image source: <a href="https://www.mdpi.com/1999-4907/11/4/454/htm" class="uri">https://www.mdpi.com/1999-4907/11/4/454/htm</a>
</p>
</div>
</div>
<div id="estimating-spatial-only-kulldorff-scan-statistics" class="section level3" number="9.3.4">
<h3><span class="header-section-number">9.3.4</span> Estimating <em>spatial-only</em> Kulldorff scan statistics</h3>
<p>The <code>kulldorff()</code> function in the package, <code>SpatialEpi</code> is a relatively easy way to implement spatial-only scan statistics.</p>
<div id="prepare-data" class="section level4" number="9.3.4.1">
<h4><span class="header-section-number">9.3.4.1</span> Prepare data</h4>
<p>Look at the help documentation for the function. The function is not currently written to directly use a spatial object in <code>R</code>, so instead we must supply a matrix of <span class="math inline">\(x,y\)</span> coordinates representing the centroids of each area region, county in this scenario. The centroids are used in the iterative specification of the study window, determining who is <em>in</em> versus <em>out</em> of the window by whether the county-centroid falls in or out of the circle.</p>
<p>First we need the <span class="math inline">\(x,y\)</span> coordinates of the <em>centroid</em> of each county in a <code>matrix</code> form. The following code achieves that.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="spatial-structure-and-clustering-ii.html#cb226-1"></a>sti_cent &lt;-<span class="st"> </span><span class="kw">st_centroid</span>(sti) <span class="op">%&gt;%</span></span>
<span id="cb226-2"><a href="spatial-structure-and-clustering-ii.html#cb226-2"></a><span class="st">  </span><span class="kw">st_coordinates</span>()</span>
<span id="cb226-3"><a href="spatial-structure-and-clustering-ii.html#cb226-3"></a><span class="kw">head</span>(sti_cent)</span></code></pre></div>
<pre><code>##         X       Y
## 1 1057695 1255760
## 2 1363356 1098009
## 3 1095793 1279833
## 4 1367529 1010385
## 5 1225492 1068308
## 6 1279077 1097468</code></pre>
</div>
<div id="call-kulldorff-function" class="section level4" number="9.3.4.2">
<h4><span class="header-section-number">9.3.4.2</span> Call <code>kulldorff()</code> function</h4>
<p>There are several other decisions to make when using the scan statistic. First, what is the maximum size window you wish to search? This can be specified using contextual knowledge about how large or small clusters are anticipated to be. In the absence of <em>a priori</em> knowledge about size, it is common practice to allow windows to vary from zero to a size large enough to include 50% of the population within the window.</p>
<p>In addition, you must set the number of Monte Carlo simulations of the null hypothesis (e.g. simulations of the distribution of counts under a <em>constant risk hypothesis</em>). As discussed previously, you need an adequately large number of iterations to approximate the distribution of what could happen by chance alone under the null. The precision (number of significant digits) of the resulting p-value is limited by the number of iterations. Below I specify n=499 null iterations, which when added to the single test of the observed data produces n=500 versions of the test. Our inference is based on how unusual the single test from the observed data are in relation to the 499 tests under the null.</p>
<p>Finally, the specification of the <code>alpha.level</code> dictates which (if any) <em>secondary clusters</em> are retained. The most-likely cluster will be reported no matter the significance, but secondary clusters are only retained if they are smaller than the alpha threshold. For the purposes of exploration I set alpha to 0.2.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="spatial-structure-and-clustering-ii.html#cb228-1"></a>k1 &lt;-<span class="st"> </span><span class="kw">kulldorff</span>(sti_cent, </span>
<span id="cb228-2"><a href="spatial-structure-and-clustering-ii.html#cb228-2"></a>                <span class="dt">cases =</span> sti<span class="op">$</span>STD,</span>
<span id="cb228-3"><a href="spatial-structure-and-clustering-ii.html#cb228-3"></a>                <span class="dt">population =</span> sti<span class="op">$</span>POP,</span>
<span id="cb228-4"><a href="spatial-structure-and-clustering-ii.html#cb228-4"></a>                <span class="dt">expected.cases =</span> sti<span class="op">$</span>expected,</span>
<span id="cb228-5"><a href="spatial-structure-and-clustering-ii.html#cb228-5"></a>                <span class="dt">pop.upper.bound =</span> <span class="fl">0.5</span>,</span>
<span id="cb228-6"><a href="spatial-structure-and-clustering-ii.html#cb228-6"></a>                <span class="dt">n.simulations =</span> <span class="dv">499</span>,</span>
<span id="cb228-7"><a href="spatial-structure-and-clustering-ii.html#cb228-7"></a>                <span class="dt">alpha.level =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-239-1.png" width="672" /></p>
<p>The plot produced by default (to suppress plot specify <code>plot = FALSE</code>), shows a histogram of the simulated null distribution for log-likelihood ratios of the contrast of rates <em>inside</em> versus <em>outside</em> assuming the constant risk hypothesis. In other words, the permutation simulation applied the average risk to the actual population assuming simple Poisson distribution. The histogram therefore includes information on the likelihood ratios for <span class="math inline">\(n=499\)</span> simulations of the null, plus <span class="math inline">\(n=1\)</span> actual observed likelihood ratio from the single most significant cluster identified from all-possible scans. In this case the single most significant cluster is indicated with a <em>red line</em>. It is quite evident that this cluster is <em>highly unusual</em> under the null assumption, with empirical <em>p-value = 0.002</em>.</p>
</div>
<div id="summarize-results" class="section level4" number="9.3.4.3">
<h4><span class="header-section-number">9.3.4.3</span> Summarize results</h4>
<p>Unfortunately, there is not a handy function for providing a pretty summary, but much information is contained within this object. By examining specific aspects of the result we can learn a great deal. First, note that the object produced, <code>k1</code> is a <code>list</code> meaning it is composed of several sub-parts.We can see the names of those parts like this:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="spatial-structure-and-clustering-ii.html#cb229-1"></a><span class="co"># See the elements returned by function - explore them!</span></span>
<span id="cb229-2"><a href="spatial-structure-and-clustering-ii.html#cb229-2"></a><span class="kw">names</span>(k1) </span></code></pre></div>
<pre><code>## [1] &quot;most.likely.cluster&quot; &quot;secondary.clusters&quot;  &quot;type&quot;               
## [4] &quot;log.lkhd&quot;            &quot;simulated.log.lkhd&quot;</code></pre>
<p>We will begin by looking at the <code>most.likely.cluster</code> component, which itself has several sub-parts:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="spatial-structure-and-clustering-ii.html#cb231-1"></a><span class="co"># See the row-numbers for the counties in the most-likely cluster</span></span>
<span id="cb231-2"><a href="spatial-structure-and-clustering-ii.html#cb231-2"></a>k1<span class="op">$</span>most.likely.cluster<span class="op">$</span>location.IDs.included</span></code></pre></div>
<pre><code>##  [1] 138 142 111 137 135  76  23   8 159 130  24 123 131  90  85  46 157 136 141
## [20] 129 122  99 145  83  29 104  74 153 152  96  35  95  45  78 100  62  93  88
## [39] 105  69  98  32 128 140  38  49  12   5 158 119 151  34  75 125  53 102  91
## [58] 144 132  18  25  89  81  80  72 124  48  26  19 139 120  52  63 154  97 121
## [77] 117  84   6  36  37  50 134  79 156  59  68  82  66  94 147   1</code></pre>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="spatial-structure-and-clustering-ii.html#cb233-1"></a><span class="co"># See the SMR for the most-likely cluster</span></span>
<span id="cb233-2"><a href="spatial-structure-and-clustering-ii.html#cb233-2"></a>k1<span class="op">$</span>most.likely.cluster<span class="op">$</span>SMR</span></code></pre></div>
<pre><code>## [1] 1.255823</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="spatial-structure-and-clustering-ii.html#cb235-1"></a><span class="co"># See the observed and expected cases inside cluster</span></span>
<span id="cb235-2"><a href="spatial-structure-and-clustering-ii.html#cb235-2"></a>k1<span class="op">$</span>most.likely.cluster<span class="op">$</span>number.of.cases</span></code></pre></div>
<pre><code>## [1] 55699</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="spatial-structure-and-clustering-ii.html#cb237-1"></a>k1<span class="op">$</span>most.likely.cluster<span class="op">$</span>expected.cases</span></code></pre></div>
<pre><code>## [1] 44352.6</code></pre>
<p>You can see that the STI rate inside this cluster is two and a half times higher than the rate outside the cluster (e.g. the SMR contrasting rates <em>inside</em> versus <em>outside</em> is 2.54).</p>
<p>We can also look at similar information for the <em>secondary</em> clusters, which are the clusters with the second-highest log-likelihood ratio.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="spatial-structure-and-clustering-ii.html#cb239-1"></a><span class="co"># see how many additional clusters reported:</span></span>
<span id="cb239-2"><a href="spatial-structure-and-clustering-ii.html#cb239-2"></a><span class="kw">length</span>(k1<span class="op">$</span>secondary.clusters)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>The object <code>secondary.clusters</code> is a list, with each element of the list containing the same information we just reviewed in the <code>most.likely.cluster</code>. In other words we can see the p-value, SMR, and list of counties contributing to each of these secondary clusters. In this code-snippet I use the base-R function <code>sapply()</code> to extract the 5th element (SMR) and 8th element (p.value) from each of the secondary cluster in <code>k1$secondary.clusters</code>. (Alternatively you could have used <code>k1$secondary.clusters[[1]]$p.value</code>, and <code>k1$secondary.clusters[[2]]$p.value</code> to get the values)</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="spatial-structure-and-clustering-ii.html#cb241-1"></a><span class="kw">sapply</span>(k1<span class="op">$</span>secondary.clusters, <span class="st">&#39;[[&#39;</span>, <span class="dv">5</span>) <span class="co"># this gets SMR&#39;s</span></span></code></pre></div>
<pre><code>## [1] 2.247193 1.398893 1.329548 1.269046</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="spatial-structure-and-clustering-ii.html#cb243-1"></a><span class="kw">sapply</span>(k1<span class="op">$</span>secondary.clusters, <span class="st">&#39;[[&#39;</span>, <span class="dv">6</span>) <span class="co"># this gets log-likelihoods</span></span></code></pre></div>
<pre><code>## [1] 1013.01844  245.26646   32.76399   24.50300</code></pre>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="spatial-structure-and-clustering-ii.html#cb245-1"></a><span class="kw">sapply</span>(k1<span class="op">$</span>secondary.clusters, <span class="st">&#39;[[&#39;</span>, <span class="dv">8</span>) <span class="co"># this gets p.values</span></span></code></pre></div>
<pre><code>## [1] 0.002 0.002 0.002 0.002</code></pre>
<p>First, notice that the log-likelihood ratios for these two secondary clusters are substantially smaller than our most-likely cluster (it was nearly 6000!). In addition the SMR’s and p-values vary.</p>
</div>
<div id="plotting-results" class="section level4" number="9.3.4.4">
<h4><span class="header-section-number">9.3.4.4</span> Plotting results</h4>
<p>Just as there isn’t a handy function for summarizing the results, there also isn’t a handy function for plotting results. As a result we have to do a little work to <strong>see</strong> where the clusters are. Here is a step-by-step strategy for creating a variable in our Georgia county STI dataset that indicates whether each county is in or out of a cluster.</p>
<ol style="list-style-type: decimal">
<li>First, initialize a new variable called <code>k1_cluster</code>. To <em>initialize</em> simply means to create it without any values (e.g. all set to <code>NA</code>).</li>
</ol>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="spatial-structure-and-clustering-ii.html#cb247-1"></a>sti<span class="op">$</span>k1_cluster &lt;-<span class="st"> </span><span class="ot">NA</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Now fill in the value for this new variable according to whether each county is <strong>in</strong> a given cluster. Recall that the row-numbers for the counties included in the <em>most-likely cluster</em> are contained as a vector in <code>k1$most.likely.cluster$location.IDs.included</code>. Therefore, we can use those row indices to say which counties should be assigned to <strong>cluster 1</strong> (the most-likely cluster).</li>
</ol>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="spatial-structure-and-clustering-ii.html#cb248-1"></a>sti<span class="op">$</span>k1_cluster[k1<span class="op">$</span>most.likely.cluster<span class="op">$</span>location.IDs.included] &lt;-<span class="st"> &#39;Most likely cluster&#39;</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>The same approach can be used to extract the <code>location.IDs.included</code> for each of the two secondary clusters. Here I simply loop (using <code>for(i in 1:length(x))</code>) across however many <code>secondary.clusters</code> there are and name them.</li>
</ol>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="spatial-structure-and-clustering-ii.html#cb249-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(k1<span class="op">$</span>secondary.clusters)){</span>
<span id="cb249-2"><a href="spatial-structure-and-clustering-ii.html#cb249-2"></a>sti<span class="op">$</span>k1_cluster[k1<span class="op">$</span>secondary.clusters[[i]]<span class="op">$</span>location.IDs.included] &lt;-<span class="st"> </span><span class="kw">paste</span>(</span>
<span id="cb249-3"><a href="spatial-structure-and-clustering-ii.html#cb249-3"></a>  <span class="st">&#39;Secondary cluster &#39;</span>, i, <span class="dt">sep =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb249-4"><a href="spatial-structure-and-clustering-ii.html#cb249-4"></a>}</span></code></pre></div>
<p>The result is a mappable variable:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="spatial-structure-and-clustering-ii.html#cb250-1"></a><span class="kw">tm_shape</span>(sti) <span class="op">+</span></span>
<span id="cb250-2"><a href="spatial-structure-and-clustering-ii.html#cb250-2"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&#39;k1_cluster&#39;</span>,</span>
<span id="cb250-3"><a href="spatial-structure-and-clustering-ii.html#cb250-3"></a>          <span class="dt">style =</span> <span class="st">&#39;cat&#39;</span>,</span>
<span id="cb250-4"><a href="spatial-structure-and-clustering-ii.html#cb250-4"></a>          <span class="dt">textNA =</span> <span class="st">&#39;Not in cluster&#39;</span>,</span>
<span id="cb250-5"><a href="spatial-structure-and-clustering-ii.html#cb250-5"></a>          <span class="dt">palette =</span> <span class="st">&#39;Set1&#39;</span>,</span>
<span id="cb250-6"><a href="spatial-structure-and-clustering-ii.html#cb250-6"></a>          <span class="dt">title =</span> <span class="st">&#39;&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb250-7"><a href="spatial-structure-and-clustering-ii.html#cb250-7"></a><span class="st">  </span><span class="kw">tm_borders</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb250-8"><a href="spatial-structure-and-clustering-ii.html#cb250-8"></a><span class="st">  </span><span class="kw">tm_layout</span>(<span class="dt">legend.outside =</span> T)</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-247-1.png" width="672" /></p>
<p>There are several things apparent from this map. First and foremost, the STI rate in the portion of the state colored red is substantially higher than outside that portion, and the cluster including all of these counties has the largest likelihood ratio. In addition to that huge cluster, there are a handful of secondary clusters that reached our threshold of significance at <span class="math inline">\(\alpha = 0.2\)</span>.</p>
</div>
</div>
<div id="estimating-spatio-temporal-kuldorff-scan-statistic" class="section level3" number="9.3.5">
<h3><span class="header-section-number">9.3.5</span> Estimating <em>spatio-temporal</em> Kuldorff scan statistic</h3>
<p>In <code>R</code>, there is currently only one package that readily permits <em>spatio-temporal</em> scan testing, and that is <code>scanstatistics</code>. It actually implement a somewhat limited version of the <em>temporal</em> component: It assess how cluster duration varies, but at least in its current iteration, all cluster duration go from the <em>last period</em> back. In other words if our data end in 2017, it will consider 2017, then 2017+2016, then 2017+2016+2015. However what it (apparently) will not do is consider intervals of time in the middle of the study period (e.g. 2015+2016 but not including 2017). This is unlike Kulldorff’s implementation in the free software Sat Scan.</p>

<div class="rmdwarning">
The examples below have some relatively complex looking R code. It is provided here for those who might try to adapt the code to their own projects. However please note that I do not expect everyone to ‘learn’ or ‘remember’ all of these code details. The important high level concepts concern the interpretation of scan statistics, and understanding of their general strategy and assumptions.
</div>
<div id="preparing-data" class="section level4" number="9.3.5.1">
<h4><span class="header-section-number">9.3.5.1</span> Preparing data</h4>
<p>If you did not already load in the <code>OD_long</code> dataset in the beginning, go back and do that now. Examine this dataset; notice that instead of only one row for each county, there are now several rows, one for each year. These data are for 2008-2017, so there are 10 rows for every county.</p>
<p>There are several ways to present data to the <code>scanstatistics</code> functions, but the easiest will probably be as an <code>sf</code> data frame. However the variables must follow a specific naming protocol (see help documentation).</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="spatial-structure-and-clustering-ii.html#cb251-1"></a>sti_scan2 &lt;-<span class="st"> </span>sti_long <span class="op">%&gt;%</span></span>
<span id="cb251-2"><a href="spatial-structure-and-clustering-ii.html#cb251-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">count =</span> STD,       <span class="co"># event variable must be labeled &#39;count&#39;</span></span>
<span id="cb251-3"><a href="spatial-structure-and-clustering-ii.html#cb251-3"></a>         <span class="dt">location =</span> GEOID, <span class="co"># region id must be labeled &#39;location&#39;</span></span>
<span id="cb251-4"><a href="spatial-structure-and-clustering-ii.html#cb251-4"></a>         <span class="dt">population =</span> POP, <span class="co"># denominator must be labeled &#39;population</span></span>
<span id="cb251-5"><a href="spatial-structure-and-clustering-ii.html#cb251-5"></a>         <span class="dt">time =</span> <span class="kw">as.integer</span>(YEAR))<span class="op">%&gt;%</span><span class="st">  </span><span class="co"># time-period must be labeled &#39;time&#39;</span></span>
<span id="cb251-6"><a href="spatial-structure-and-clustering-ii.html#cb251-6"></a><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(time, location, count, population) </span></code></pre></div>
</div>
<div id="prepare-geographic-window-zones" class="section level4" number="9.3.5.2">
<h4><span class="header-section-number">9.3.5.2</span> Prepare geographic window <em>zones</em></h4>
<p>This package also has a unique way of defining the areas contained within the varying-sized <em>windows</em>, which are called <em>zones</em> in this context. The approach first defines k-nearest neighbors in order to locate how regions are <em>connected</em> to one another. Then using measures of distance between each region and its k-nearest neighbors, the varying-sized windows are applied. The result is a set of <em>zones</em> which consist of each county plus its neighbors starting at zero-distance (no neighbors) up to the maximum number of neighbors defined.</p>
<p>Although the data are in the <em>long</em> format (e.g. multiple years for every geographic region, county), the zones should be calculated from an object where each region is only represented once.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="spatial-structure-and-clustering-ii.html#cb252-1"></a>zones &lt;-<span class="st"> </span>sti <span class="op">%&gt;%</span></span>
<span id="cb252-2"><a href="spatial-structure-and-clustering-ii.html#cb252-2"></a><span class="st">  </span><span class="kw">st_centroid</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># convert polygons to centroid</span></span>
<span id="cb252-3"><a href="spatial-structure-and-clustering-ii.html#cb252-3"></a><span class="st">  </span><span class="kw">st_coordinates</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="co">#converts sf object to matrix of x, y locations</span></span>
<span id="cb252-4"><a href="spatial-structure-and-clustering-ii.html#cb252-4"></a><span class="st">  </span><span class="kw">spDists</span>(<span class="dt">x =</span> ., <span class="dt">y =</span> ., <span class="dt">longlat =</span> <span class="ot">FALSE</span>) <span class="op">%&gt;%</span></span>
<span id="cb252-5"><a href="spatial-structure-and-clustering-ii.html#cb252-5"></a><span class="st">  </span><span class="kw">dist_to_knn</span>(<span class="dt">k =</span> <span class="dv">50</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># distance up to the 50 nearest neighbors</span></span>
<span id="cb252-6"><a href="spatial-structure-and-clustering-ii.html#cb252-6"></a><span class="st">  </span><span class="kw">knn_zones</span>() <span class="co"># convert into zones needed for scanstatistics based on distances</span></span></code></pre></div>
<p>What exactly did this function do? First try looking at how long the output is:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="spatial-structure-and-clustering-ii.html#cb253-1"></a><span class="kw">length</span>(zones)</span></code></pre></div>
<pre><code>## [1] 7718</code></pre>
<p>It is of class <code>list</code>, so try looking at some of the elements in the list (here I just randomly chose some elements):</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="spatial-structure-and-clustering-ii.html#cb255-1"></a>zones[[<span class="dv">34</span>]]</span></code></pre></div>
<pre><code>##  [1]   1   3   9  26  28  34  44  50  52  65  72  77  79  80  82  89  92  94 101
## [20] 103 106 107 113 115 117 118 124 127 139 147 150 151 156 158</code></pre>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="spatial-structure-and-clustering-ii.html#cb257-1"></a>zones[[<span class="dv">657</span>]]</span></code></pre></div>
<pre><code>##  [1]  2  4 14 17 39 41 56 57 60 67 70 87</code></pre>
<p>Notice that each element in the list called <code>zones</code> is a vector of row-id’s. In other words what <code>zones</code> represents is every iteration of <em>location x window-size</em> calculated from the preceding procedure. This will become important when it comes time to plot the results.</p>
</div>
<div id="estimate-spatio-temporal-scan-statistics" class="section level4" number="9.3.5.3">
<h4><span class="header-section-number">9.3.5.3</span> Estimate spatio-temporal scan statistics</h4>
<p>There are several scan statistic options in this package including reliance on Poisson assumptions versus Negative binomial, and allowing for estimation with population denominators, or with expected counts. Here is an implementation of the population-denominator version of the Poisson scan (<strong>note</strong> this will take a minute to run):</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="spatial-structure-and-clustering-ii.html#cb259-1"></a>k2 &lt;-<span class="st"> </span><span class="kw">scan_pb_poisson</span>(sti_scan2, </span>
<span id="cb259-2"><a href="spatial-structure-and-clustering-ii.html#cb259-2"></a>                      <span class="dt">zones =</span> zones,</span>
<span id="cb259-3"><a href="spatial-structure-and-clustering-ii.html#cb259-3"></a>                      <span class="dt">n_mcsim =</span> <span class="dv">499</span>)</span>
<span id="cb259-4"><a href="spatial-structure-and-clustering-ii.html#cb259-4"></a><span class="kw">print</span>(k2)</span></code></pre></div>
<pre><code>## Data distribution:                Poisson
## Type of scan statistic:           population-based
## Setting:                          univariate
## Number of locations considered:   159
## Maximum duration considered:      9
## Number of spatial zones:          7718
## Number of Monte Carlo replicates: 499
## Monte Carlo P-value:              0.002
## Gumbel P-value:                   0
## Most likely event duration:       9
## ID of locations in MLC:           4, 47, 60, 71</code></pre>
<p>The basic summary information tells us the row-ID’s for the most likely spatio-temporal cluster, and that of the 9 year period, the most-likely duration of this cluster is in fact 9-years (e.g. 2010-2018). In other words the cluster of STI’s is quite persistent over time!</p>
</div>
<div id="visualizing-most-likely-clusters" class="section level4" number="9.3.5.4">
<h4><span class="header-section-number">9.3.5.4</span> Visualizing most-likely clusters</h4>
<p>The package <code>scanstatistics</code> has a function for extracting the most-likely clusters, and from this we can visualize their location, and explore the duration and intensity of each.</p>
<p>First, we use the function <code>top_clusters()</code> to extract the information. In this case we are asking for the <strong>top 5</strong> clusters, specifying that we want them to be non-overlapping.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="spatial-structure-and-clustering-ii.html#cb261-1"></a>top5 &lt;-<span class="st"> </span><span class="kw">top_clusters</span>(k2, zones, <span class="dt">k =</span> <span class="dv">5</span>, <span class="dt">overlapping =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<p>To see what <code>top_clusters()</code> produced, look at the object:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="spatial-structure-and-clustering-ii.html#cb262-1"></a>top5</span></code></pre></div>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:unnamed-chunk-255">
<caption style="caption-side: top; text-align: center;"><span id="tab:unnamed-chunk-255">TABLE 9.2: </span> </caption><col><col><col><col><col><col><tr>
<th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">zone</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">duration</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">score</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">relrisk_in</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">relrisk_out</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Gumbel_pvalue</th></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">154&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">9</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">1.19e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">1.57</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.929</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">155&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">9</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.16e+04</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.56</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.929</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">4.6e+03&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">9</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">8.9e+03&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">1.42</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.931</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">6.96e+03</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">9</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">5.33e+03</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.54</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.966</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">501&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">8</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">2.66e+03</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">1.85</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.988</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
</table>

<p>As expected there are 5 rows in the object, and each row tells us something about the clusters. The first thing it tells us is what <em>spatial</em> zone is involved. Remember how each element in the object <code>zones</code> was a vector of neighbors? This zone number refers to a particular neighbor set with the highest likelihoods of containing clustered deaths. In addition the object <code>top5</code> tells us the most likely duration or <em>temporal</em> dimension of the cluster. So the single most likely <em>spatio-temporal</em> cluster is described by zone 154, and it is 9 years in duration; the fifth most likely cluster is described spatially by zones 501, and temporally was 8-years in duration.</p>
<p>To get the information about zones into our <code>sf</code> object for mapping we can use functions from the package <code>purrr</code> which is an efficient way to process vectors contained in lists. What it is doing is looking at the zones defined in <code>top5$zone</code>, and using that number, extracting the vector of row-ids from our original <code>zones</code> object. This produces a list of involved counties.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="spatial-structure-and-clustering-ii.html#cb263-1"></a><span class="co"># First, get vector of county names</span></span>
<span id="cb263-2"><a href="spatial-structure-and-clustering-ii.html#cb263-2"></a>county &lt;-<span class="st"> </span><span class="kw">as.vector</span>(sti<span class="op">$</span>NAME)</span>
<span id="cb263-3"><a href="spatial-structure-and-clustering-ii.html#cb263-3"></a></span>
<span id="cb263-4"><a href="spatial-structure-and-clustering-ii.html#cb263-4"></a><span class="co"># Find the counties corresponding to the spatial zones of the 5 clusters.</span></span>
<span id="cb263-5"><a href="spatial-structure-and-clustering-ii.html#cb263-5"></a>top5_counties &lt;-<span class="st"> </span>top5<span class="op">$</span>zone <span class="op">%&gt;%</span></span>
<span id="cb263-6"><a href="spatial-structure-and-clustering-ii.html#cb263-6"></a><span class="st">  </span>purrr<span class="op">::</span><span class="kw">map</span>(get_zone, <span class="dt">zones =</span> zones) <span class="op">%&gt;%</span></span>
<span id="cb263-7"><a href="spatial-structure-and-clustering-ii.html#cb263-7"></a><span class="st">  </span>purrr<span class="op">::</span><span class="kw">map</span>(<span class="cf">function</span>(x) county[x])</span></code></pre></div>
<p>The new object, <code>top5_counties</code> is a list of length 5, and each element of the list is a vector of county names.</p>
<p>Now we can use this list of names to populate a new variable in our <code>sf</code> dataset. We’ll do that by iterating through the elements in the list, <code>top5_counties</code>, and apply a cluster ID, cluster duration, and cluster score, which is related to the log-likelihood.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="spatial-structure-and-clustering-ii.html#cb264-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(top5_counties)){</span>
<span id="cb264-2"><a href="spatial-structure-and-clustering-ii.html#cb264-2"></a>  cluster &lt;-<span class="st"> </span>top5_counties[[i]]</span>
<span id="cb264-3"><a href="spatial-structure-and-clustering-ii.html#cb264-3"></a>  sti<span class="op">$</span>cluster[sti<span class="op">$</span>NAME <span class="op">%in%</span><span class="st"> </span>cluster] &lt;-<span class="st"> </span>i</span>
<span id="cb264-4"><a href="spatial-structure-and-clustering-ii.html#cb264-4"></a>  sti<span class="op">$</span>c_score[sti<span class="op">$</span>NAME <span class="op">%in%</span><span class="st"> </span>cluster] &lt;-<span class="st"> </span>top5<span class="op">$</span>score[i]</span>
<span id="cb264-5"><a href="spatial-structure-and-clustering-ii.html#cb264-5"></a>  sti<span class="op">$</span>c_duration[sti<span class="op">$</span>NAME <span class="op">%in%</span><span class="st"> </span>cluster] &lt;-<span class="st"> </span>top5<span class="op">$</span>duration[i]</span>
<span id="cb264-6"><a href="spatial-structure-and-clustering-ii.html#cb264-6"></a>}</span></code></pre></div>
</div>
<div id="mapping-top-5-clusters" class="section level4" number="9.3.5.5">
<h4><span class="header-section-number">9.3.5.5</span> Mapping top-5 clusters</h4>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="spatial-structure-and-clustering-ii.html#cb265-1"></a><span class="kw">tm_shape</span>(sti) <span class="op">+</span><span class="st"> </span></span>
<span id="cb265-2"><a href="spatial-structure-and-clustering-ii.html#cb265-2"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&#39;cluster&#39;</span>,</span>
<span id="cb265-3"><a href="spatial-structure-and-clustering-ii.html#cb265-3"></a>          <span class="dt">style =</span> <span class="st">&#39;cat&#39;</span>) <span class="op">+</span></span>
<span id="cb265-4"><a href="spatial-structure-and-clustering-ii.html#cb265-4"></a><span class="st">  </span><span class="kw">tm_borders</span>()</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-258-1.png" width="672" /></p>
<p>So why are there only 4 clusters when we asked for 5? After some investigation it is clear that the most likely cluster and the second most-likely fully overlap (despite the option to disallow overlapping clusters!).</p>
<p>You may also note that the cluster locations look quite different from the cross-sectional analysis of 2018 data! This is because the search for spatio-temporal clustering can turn up distinct patterns from what would be observed in a single year. These clusters rise to the top because there is the strongest evidence for them being significantly unusual.</p>
<p>If you wanted to also produce a visualization of the time-span of each of these clusters, you could use <code>ggplot2</code> to do so. First we create a variable for the start and end time (all end times are assumed to be the last year, 2017).</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="spatial-structure-and-clustering-ii.html#cb266-1"></a><span class="co"># Assign a cluster number called &#39;order&#39;</span></span>
<span id="cb266-2"><a href="spatial-structure-and-clustering-ii.html#cb266-2"></a>top5<span class="op">$</span>order &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(top5)</span>
<span id="cb266-3"><a href="spatial-structure-and-clustering-ii.html#cb266-3"></a><span class="co"># Calculate start/end years from cluster duration</span></span>
<span id="cb266-4"><a href="spatial-structure-and-clustering-ii.html#cb266-4"></a>top5<span class="op">$</span>end &lt;-<span class="st"> </span><span class="dv">2018</span></span>
<span id="cb266-5"><a href="spatial-structure-and-clustering-ii.html#cb266-5"></a>top5<span class="op">$</span>start &lt;-<span class="st"> </span><span class="dv">2018</span> <span class="op">-</span><span class="st"> </span>top5<span class="op">$</span>duration</span>
<span id="cb266-6"><a href="spatial-structure-and-clustering-ii.html#cb266-6"></a></span>
<span id="cb266-7"><a href="spatial-structure-and-clustering-ii.html#cb266-7"></a><span class="co"># Create ggplot</span></span>
<span id="cb266-8"><a href="spatial-structure-and-clustering-ii.html#cb266-8"></a>g &lt;-<span class="st"> </span><span class="kw">ggplot</span>(top5, <span class="kw">aes</span>(<span class="dt">x =</span> start, <span class="dt">y =</span> order, <span class="dt">col =</span> <span class="kw">as.factor</span>(order)))</span>
<span id="cb266-9"><a href="spatial-structure-and-clustering-ii.html#cb266-9"></a>g <span class="op">+</span><span class="st"> </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">yend =</span> order), <span class="dt">xend =</span> <span class="dv">2019</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb266-10"><a href="spatial-structure-and-clustering-ii.html#cb266-10"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb266-11"><a href="spatial-structure-and-clustering-ii.html#cb266-11"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Cluster timing&#39;</span>,</span>
<span id="cb266-12"><a href="spatial-structure-and-clustering-ii.html#cb266-12"></a>       <span class="dt">y =</span> <span class="st">&#39;Cluster number&#39;</span>,</span>
<span id="cb266-13"><a href="spatial-structure-and-clustering-ii.html#cb266-13"></a>       <span class="dt">col =</span> <span class="st">&#39;Cluster&#39;</span>) </span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-259-1.png" width="672" /></p>
<p>Because most of the clusters represent persistently high levels over the entire 9-year period, there is not much distinction in this example. However, Cluster 5 does stand out in that it was only apparent in the beginning of the study period.</p>
</div>
<div id="mapping-relative-scores" class="section level4" number="9.3.5.6">
<h4><span class="header-section-number">9.3.5.6</span> Mapping relative scores</h4>
<p>Each county has a varying probability of being <em>in</em> versus <em>out</em> of a cluster. There is a function (<em>which takes a long time to run!</em>) that calculates, the average of the statistic for each space-time window that the location is included. In other words, it averages the statistic over both the zones and the maximum duration. The reason for doing this, is to quantify (and visualize) the relative likelihood that each location is a part of the cluster.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="spatial-structure-and-clustering-ii.html#cb267-1"></a><span class="co"># Note: This step takes awhile...about 4-5 minutes on my computer</span></span>
<span id="cb267-2"><a href="spatial-structure-and-clustering-ii.html#cb267-2"></a>county_scores &lt;-<span class="st"> </span><span class="kw">score_locations</span>(k2, zones)</span></code></pre></div>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="spatial-structure-and-clustering-ii.html#cb268-1"></a><span class="co"># This part goes quicker - first just rename some stuff for merging</span></span>
<span id="cb268-2"><a href="spatial-structure-and-clustering-ii.html#cb268-2"></a>sti_scan3 &lt;-<span class="st"> </span>county_scores <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb268-3"><a href="spatial-structure-and-clustering-ii.html#cb268-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">NAME =</span> county) <span class="op">%&gt;%</span></span>
<span id="cb268-4"><a href="spatial-structure-and-clustering-ii.html#cb268-4"></a><span class="st">  </span><span class="kw">left_join</span>(sti, <span class="dt">by =</span><span class="st">&#39;NAME&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb268-5"><a href="spatial-structure-and-clustering-ii.html#cb268-5"></a><span class="st">  </span><span class="kw">st_as_sf</span>() <span class="co"># this just converts the new object back to &#39;sf&#39;</span></span></code></pre></div>
<p>Now you can map the <em>relative score</em>, interpreting it as the relative likelihood of each county being a member of the cluster:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="spatial-structure-and-clustering-ii.html#cb269-1"></a><span class="kw">tm_shape</span>(sti_scan3) <span class="op">+</span></span>
<span id="cb269-2"><a href="spatial-structure-and-clustering-ii.html#cb269-2"></a><span class="st">  </span><span class="kw">tm_fill</span>(<span class="st">&#39;relative_score&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb269-3"><a href="spatial-structure-and-clustering-ii.html#cb269-3"></a><span class="st">  </span><span class="kw">tm_borders</span>()</span></code></pre></div>
<p><img src="EPI563-SpatialEPI_files/figure-html/unnamed-chunk-262-1.png" width="672" /></p>
<p>This shows that, using the 9-year time series, there is variation in the likelihood of counties being a part of a true cluster, with highest probability around the most likely cluster. It is once again notable that the patterns of spatio-temporal clustering are relatively distinct from the patterns of point-in-time cross-sectional clustering using 2018 data only.</p>
</div>
</div>
<div id="concluding-thoughts" class="section level3" number="9.3.6">
<h3><span class="header-section-number">9.3.6</span> Concluding thoughts</h3>
<p>The scan statistics represent one more tool useful for investigating for the existence and location of spatial clusters of disease events. In the case of the scan statistics, the <em>clustering</em> is specifically local <em>excess risk</em> in violation of the assumption of <em>spatial homogeneity</em> or constant risk. It is therefore distinct from the measures of <em>spatial auto correlation</em> such as the Moran’s I statistic.</p>
<p>Scan statistics are useful for finding a statistically significant most-likely cluster, and for exploring secondary clusters. Their extension to spatio-temporal setting is another feature. This information can compliment what is learned from tests of spatial auto correlation, and from the global and local test discussed last week.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatial-structure-and-clustering-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="spatial-regression-i.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/mkram01/EPI563-SpatialEPI/edit/master/09-spatial-cluster-2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"toc_depth": 2,
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
